load("//src/libraries:defs.bzl", "netcoreapp_ref_assembly", "netcoreapp_impl_assembly", "ref_impl_pair")

exports_files([
    "ref/System.Linq.AsyncEnumerable.cs",
    "ref/SystemLinq.AsyncEnumerable.netcore.cs",
])

netcoreapp_ref_assembly(
    name = "ref_System.Linq.AsyncEnumerable",
    srcs = [
        "ref/System.Linq.AsyncEnumerable.cs",
        "ref/SystemLinq.AsyncEnumerable.netcore.cs",
    ],
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Collections:ref_System.Collections",
        "//src/libraries/System.Linq:ref_System.Linq",
    ],
)

netcoreapp_impl_assembly(
    name = "impl_System.Linq.AsyncEnumerable",
    srcs = [
        "src/System/Linq/AggregateAsync.cs",
        "src/System/Linq/AggregateBy.cs",
        "src/System/Linq/AllAsync.cs",
        "src/System/Linq/AnyAsync.cs",
        "src/System/Linq/Append.cs",
        "src/System/Linq/AsyncEnumerable.cs",
        "src/System/Linq/AverageAsync.cs",
        "src/System/Linq/Cast.cs",
        "src/System/Linq/Chunk.cs",
        "src/System/Linq/Concat.cs",
        "src/System/Linq/ContainsAsync.cs",
        "src/System/Linq/CountAsync.cs",
        "src/System/Linq/CountBy.cs",
        "src/System/Linq/DefaultIfEmpty.cs",
        "src/System/Linq/Distinct.cs",
        "src/System/Linq/DistinctBy.cs",
        "src/System/Linq/ElementAtAsync.cs",
        "src/System/Linq/Empty.cs",
        "src/System/Linq/Except.cs",
        "src/System/Linq/ExceptBy.cs",
        "src/System/Linq/FirstAsync.cs",
        "src/System/Linq/GroupBy.cs",
        "src/System/Linq/GroupJoin.cs",
        "src/System/Linq/Index.cs",
        "src/System/Linq/InfiniteSequence.cs",
        "src/System/Linq/Intersect.cs",
        "src/System/Linq/IntersectBy.cs",
        "src/System/Linq/Join.cs",
        "src/System/Linq/LastAsync.cs",
        "src/System/Linq/LeftJoin.cs",
        "src/System/Linq/MaxAsync.cs",
        "src/System/Linq/MaxByAsync.cs",
        "src/System/Linq/MinAsync.cs",
        "src/System/Linq/MinByAsync.cs",
        "src/System/Linq/OfType.cs",
        "src/System/Linq/OrderBy.cs",
        "src/System/Linq/Prepend.cs",
        "src/System/Linq/Range.cs",
        "src/System/Linq/Repeat.cs",
        "src/System/Linq/Reverse.cs",
        "src/System/Linq/RightJoin.cs",
        "src/System/Linq/Select.cs",
        "src/System/Linq/SelectMany.cs",
        "src/System/Linq/Sequence.cs",
        "src/System/Linq/SequenceEqualAsync.cs",
        "src/System/Linq/Shuffle.cs",
        "src/System/Linq/SingleAsync.cs",
        "src/System/Linq/Skip.cs",
        "src/System/Linq/SkipLast.cs",
        "src/System/Linq/SkipWhile.cs",
        "src/System/Linq/SumAsync.cs",
        "src/System/Linq/Take.cs",
        "src/System/Linq/TakeLast.cs",
        "src/System/Linq/TakeWhile.cs",
        "src/System/Linq/ThrowHelper.cs",
        "src/System/Linq/ToArrayAsync.cs",
        "src/System/Linq/ToAsyncEnumerable.cs",
        "src/System/Linq/ToDictionaryAsync.cs",
        "src/System/Linq/ToHashSetAsync.cs",
        "src/System/Linq/ToListAsync.cs",
        "src/System/Linq/ToLookupAsync.cs",
        "src/System/Linq/Union.cs",
        "src/System/Linq/UnionBy.cs",
        "src/System/Linq/Where.cs",
        "src/System/Linq/Zip.cs",
    ],
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Collections:ref_System.Collections",
        "//src/libraries/System.Linq:ref_System.Linq",
        "//src/libraries/System.Memory:ref_System.Memory",
        "//src/libraries/System.Runtime.InteropServices:ref_System.Runtime.InteropServices",
    ],
    nowarn = ["CS1998", "CA2007"],
    resx_file = "src/Resources/Strings.resx",
)

ref_impl_pair(
    name = "live_System.Linq.AsyncEnumerable",
    ref = ":ref_System.Linq.AsyncEnumerable",
    lib = ":impl_System.Linq.AsyncEnumerable",
    visibility = ["//visibility:public"],
)
