load("//src/tests:live_test.bzl", "coreclr_test")

coreclr_test(
    name = "Runtime_53549",
    srcs = ["Runtime_53549.cs"],
    optimize = True,
    deps = [
        "//src/libraries/System.Threading.Thread:ref_System.Threading.Thread",
        "//src/libraries/System.Threading:ref_System.Threading",
    ],
)

coreclr_test(
    name = "Runtime_53549_1",
    srcs = ["Runtime_53549_1.cs"],
    optimize = True,
    deps = [
        "//src/libraries/System.Threading.Thread:ref_System.Threading.Thread",
        "//src/libraries/System.Threading:ref_System.Threading",
    ],
)
