load("//src/tests:live_test.bzl", "il_coreclr_test")

il_coreclr_test(
    name = "basetestclassesil",
    srcs = ["basetestclassesil.il"],
    tags = ["manual"],  # Needs additional deps not yet available
)

il_coreclr_test(
    name = "testclassesil",
    srcs = ["testclassesil.il"],
    tags = ["manual"],  # Needs additional deps not yet available
)
