load("//src/tests:live_test.bzl", "coreclr_test")

coreclr_test(
    name = "Crc32.Arm_r",
    srcs = [
        "Program.Crc32.cs",
        "//src/tests/JIT/HardwareIntrinsics/Arm/Shared:Helpers.cs",
        "//src/tests/JIT/HardwareIntrinsics/Arm/Shared:Program.cs",
    ],
    tags = ["manual"],  # Needs additional deps not yet available
)

coreclr_test(
    name = "Crc32.Arm_ro",
    srcs = [
        "Program.Crc32.cs",
        "//src/tests/JIT/HardwareIntrinsics/Arm/Shared:Helpers.cs",
        "//src/tests/JIT/HardwareIntrinsics/Arm/Shared:Program.cs",
    ],
    optimize = True,
    tags = ["manual"],  # Needs additional deps not yet available
)
