load("//src/tests:live_test.bzl", "coreclr_test")

coreclr_test(
    name = "ConditionalSelectConstants",
    srcs = ["ConditionalSelectConstants.cs"],
    optimize = True,
    compiler_options = ["/nowarn:SYSLIB5003"],
)

coreclr_test(
    name = "PredicateInstructions",
    srcs = ["PredicateInstructions.cs"],
    optimize = True,
    allow_unsafe_blocks = True,
    compiler_options = ["/nowarn:SYSLIB5003"],
)

coreclr_test(
    name = "EmbeddedLoads",
    srcs = ["EmbeddedLoads.cs"],
    optimize = True,
    allow_unsafe_blocks = True,
    compiler_options = ["/nowarn:SYSLIB5003"],
)

coreclr_test(
    name = "ChangeMaskUse",
    srcs = ["ChangeMaskUse.cs"],
    optimize = True,
    deps = [
        "//src/libraries/System.Threading.Thread:ref_System.Threading.Thread",
        "//src/libraries/System.Threading:ref_System.Threading",
    ],
    compiler_options = ["/nowarn:SYSLIB5003"],
)

coreclr_test(
    name = "ConstantVectors",
    srcs = ["ConstantVectors.cs"],
    optimize = True,
    compiler_options = ["/nowarn:SYSLIB5003"],
)

coreclr_test(
    name = "ConstantMasksOp2Fixed",
    srcs = ["ConstantMasksOp2Fixed.cs"],
    optimize = True,
    compiler_options = ["/nowarn:SYSLIB5003"],
)

coreclr_test(
    name = "ConstantMasks",
    srcs = ["ConstantMasks.cs"],
    optimize = True,
    compiler_options = ["/nowarn:SYSLIB5003"],
)

coreclr_test(
    name = "MaskUse",
    srcs = ["MaskUse.cs"],
    optimize = True,
    deps = [
        "//src/libraries/System.Threading.Thread:ref_System.Threading.Thread",
        "//src/libraries/System.Threading:ref_System.Threading",
    ],
    compiler_options = ["/nowarn:SYSLIB5003"],
)
