load("//src/libraries:defs.bzl", "netcoreapp_impl_assembly")

netcoreapp_impl_assembly(
    name = "impl_System.Reflection.Extensions",
    skip_locals_init = False,
    srcs = ["src/System.Reflection.Extensions.cs"],
    deps = [
        "//src/libraries:ref_System.Runtime",
    ],
    os_targeted = True,
    exclude_sr = True,
    generate_documentation_file = False,
    library_import_generator = False,
)
