load("//src/libraries:defs.bzl", "netcoreapp_ref_assembly", "netcoreapp_impl_assembly")

exports_files(["src/ILLink/ILLink.Descriptors.LibraryBuild.xml"])

netcoreapp_ref_assembly(
    name = "ref_System.Security.Principal.Windows",
    srcs = [
        "ref/System.Security.Principal.Windows.cs",
    ],
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Security.Claims:ref_System.Security.Claims",
    ],
)

netcoreapp_impl_assembly(
    name = "impl_System.Security.Principal.Windows",
    com_interface_generator = True,
    nowarn = ["CS1591"],
    pnse = True,
    srcs = [
        "System.Security.Principal.Windows.notsupported.cs",
    ],
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Runtime.InteropServices:ref_System.Runtime.InteropServices",
        "//src/libraries/System.Security.Claims:ref_System.Security.Claims",
            "//src/libraries:ref_Microsoft.Win32.Primitives",
        "//src/libraries/System.Collections:ref_System.Collections",
        "//src/libraries/System.Memory:ref_System.Memory",
        "//src/libraries/System.Threading:ref_System.Threading",
],
    resx_file = "src/Resources/Strings.resx",
    supported_os_platforms_short = ["windows"],
    include_dll_safe_search_path = True,
    nullable = "annotations",
    include_editorconfig = False,
)
