load("//src/libraries:defs.bzl", "netcoreapp_impl_assembly")

netcoreapp_impl_assembly(
    name = "impl_System.Numerics",
    skip_cs1591 = True,
    srcs = ["src/System.Numerics.cs"],
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Runtime.Numerics:ref_System.Runtime.Numerics",
        "//src/libraries/System.Numerics.Vectors:ref_System.Numerics.Vectors",
    ],
    os_targeted = True,
    exclude_sr = True,
    assembly_version = "4.0.0.0",
)
