load("//src/tests:live_test.bzl", "coreclr_test")

coreclr_test(
    name = "Vector64_r",
    srcs = [
        "Program.Vector64.cs",
        "//src/tests/JIT/HardwareIntrinsics/General/Shared:Program.cs",
    ],
)

coreclr_test(
    name = "Vector64_ro",
    srcs = [
        "Program.Vector64.cs",
        "//src/tests/JIT/HardwareIntrinsics/General/Shared:Program.cs",
    ],
    optimize = True,
)
