load("//src/tests:live_test.bzl", "library_test")
load("//src/libraries:defs.bzl", "MULTITARGET_NOWARN")
load("//:defs.bzl", "OPEN_SNK")

library_test(
    name = "System.Security.Cryptography.Pkcs.Tests",
    srcs = glob(
        ["**/*.cs"],
        exclude = [
            # Windows CNG key persistence tests
            "EnvelopedCms/DecryptTests.KeyPersistence.cs",
        ],
    ) + [
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/MLDsa/MLDsaTestsData.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/MLDsa/MLDsaTestsData.Ietf.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/SlhDsa/SlhDsaTestData.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/SlhDsa/SlhDsaTestData.GeneratedCertificates.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/ByteUtils.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/PlatformSupport.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/CngKeyWrapper.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/SignatureSupport.cs",
    ],
    deps = [
        "//src/libraries/System.Security.Cryptography.Pkcs:ref_System.Security.Cryptography.Pkcs",
        "//src/libraries/System.Security.Cryptography:ref_System.Security.Cryptography",
        "//src/libraries/System.Xml.ReaderWriter:ref_System.Xml.ReaderWriter",
        "//src/libraries/System.Formats.Asn1:ref_System.Formats.Asn1",
        "//src/libraries/System.Collections.Immutable:ref_System.Collections.Immutable",
        "//src/libraries/System.Collections.Concurrent:ref_System.Collections.Concurrent",
        "//src/libraries/System.Runtime.Numerics:ref_System.Runtime.Numerics",
        "//src/libraries:ref_System.Threading.Tasks",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/Common/tests:TestUtilities",
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//microsoft.dotnet.xunitextensions",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    allow_unsafe_blocks = True,
    nowarn = MULTITARGET_NOWARN + ["SYSLIB0057", "SYSLIB5006"],
    size = "large",
    keyfile = OPEN_SNK,
)
