load("//src/libraries:defs.bzl", "netcoreapp_impl_assembly")

# PNSE/stub assembly — placeholder for the runtime pack.
# On Linux, this library is either PlatformNotSupported or platform-specific.
netcoreapp_impl_assembly(
    name = "impl_System.Runtime.InteropServices.JavaScript",
    pnse = True,
    srcs = ["//src/libraries/shims:System.Void.cs"],
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Runtime.InteropServices:ref_System.Runtime.InteropServices",
    ],
    exclude_sr = True,
    include_dll_safe_search_path = True,
)
