load("//src/libraries:defs.bzl", "netcoreapp_ref_assembly", "netcoreapp_impl_assembly")

netcoreapp_ref_assembly(
    name = "ref_mscorlib",
    srcs = [ "ref/mscorlib.cs" ],
    deps = [
        "//src/libraries/Microsoft.Win32.Registry:ref_Microsoft.Win32.Registry",
        "//src/libraries/System.Collections.Concurrent:ref_System.Collections.Concurrent",
        "//src/libraries/System.Collections.NonGeneric:ref_System.Collections.NonGeneric",
        "//src/libraries/System.Collections:ref_System.Collections",
        "//src/libraries/System.ComponentModel:ref_System.ComponentModel",
        "//src/libraries/System.Console:ref_System.Console",
        "//src/libraries/System.Diagnostics.Contracts:ref_System.Diagnostics.Contracts",
        "//src/libraries/System.Diagnostics.StackTrace:ref_System.Diagnostics.StackTrace",
        "//src/libraries/System.Diagnostics.Tracing:ref_System.Diagnostics.Tracing",
        "//src/libraries/System.IO.FileSystem.AccessControl:ref_System.IO.FileSystem.AccessControl",
        "//src/libraries/System.IO.FileSystem.DriveInfo:ref_System.IO.FileSystem.DriveInfo",
        "//src/libraries/System.IO.IsolatedStorage:ref_System.IO.IsolatedStorage",
        "//src/libraries/System.ObjectModel:ref_System.ObjectModel",
        "//src/libraries/System.Reflection.Emit.ILGeneration:ref_System.Reflection.Emit.ILGeneration",
        "//src/libraries/System.Reflection.Emit.Lightweight:ref_System.Reflection.Emit.Lightweight",
        "//src/libraries/System.Reflection.Emit:ref_System.Reflection.Emit",
        "//src/libraries/System.Reflection.Primitives:ref_System.Reflection.Primitives",
        "//src/libraries/System.Resources.Writer:ref_System.Resources.Writer",
        "//src/libraries/System.Runtime.CompilerServices.VisualC:ref_System.Runtime.CompilerServices.VisualC",
        "//src/libraries/System.Runtime.InteropServices:ref_System.Runtime.InteropServices",
        "//src/libraries/System.Runtime.Serialization.Formatters:ref_System.Runtime.Serialization.Formatters",
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Security.AccessControl:ref_System.Security.AccessControl",
        "//src/libraries/System.Security.Claims:ref_System.Security.Claims",
        "//src/libraries/System.Security.Cryptography:ref_System.Security.Cryptography",
        "//src/libraries/System.Security.Principal.Windows:ref_System.Security.Principal.Windows",
        "//src/libraries/System.Text.Encoding.Extensions:ref_System.Text.Encoding.Extensions",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/System.Threading.Overlapped:ref_System.Threading.Overlapped",
        "//src/libraries/System.Threading.Tasks.Parallel:ref_System.Threading.Tasks.Parallel",
        "//src/libraries/System.Threading.ThreadPool:ref_System.Threading.ThreadPool",
        "//src/libraries/System.Threading.Thread:ref_System.Threading.Thread",
        "//src/libraries/shims/stubs:ref_System.Security.Permissions",
        "//src/libraries/shims/stubs:ref_System.Threading.AccessControl",
    ],
    keyfile = "@nuget.microsoft.dotnet.arcade.sdk.v10.0.0-beta.26102.102//:tools/snk/ECMA.snk"
)

netcoreapp_impl_assembly(
    name = "impl_mscorlib",
    skip_cs1591 = True,
    srcs = [
        "ref/mscorlib.cs",
        "src/mscorlib.cs",
        "//src/libraries/shims:System.Void.cs",
    ],
    assembly_version = "4.0.0.0",
    deps = [
        "//src/libraries:ref_System.Private.CoreLib",
        "//src/libraries/Microsoft.Win32.Registry:impl_Microsoft.Win32.Registry",
        "//src/libraries/System.Collections:impl_System.Collections",
        "//src/libraries/System.Collections.Concurrent:impl_System.Collections.Concurrent",
        "//src/libraries/System.Collections.NonGeneric:impl_System.Collections.NonGeneric",
        "//src/libraries/System.ComponentModel:impl_System.ComponentModel",
        "//src/libraries/System.Console:impl_System.Console",
        "//src/libraries/System.Diagnostics.StackTrace:impl_System.Diagnostics.StackTrace",
        "//src/libraries/System.IO.FileSystem.AccessControl:impl_System.IO.FileSystem.AccessControl",
        "//src/libraries/System.IO.FileSystem.DriveInfo:impl_System.IO.FileSystem.DriveInfo",
        "//src/libraries/System.IO.IsolatedStorage:impl_System.IO.IsolatedStorage",
        "//src/libraries/System.Reflection.TypeExtensions:ref_System.Reflection.TypeExtensions",
        "//src/libraries/System.Memory:impl_System.Memory",
        "//src/libraries/System.ObjectModel:impl_System.ObjectModel",
    #<ProjectReference Include="$(LibrariesProjectRoot)System.Reflection.TypeExtensions\src\System.Reflection.TypeExtensions.csproj" />
        "//src/libraries/System.Resources.Writer:impl_System.Resources.Writer",
        "//src/libraries/System.Runtime.CompilerServices.VisualC:impl_System.Runtime.CompilerServices.VisualC",
        "//src/libraries/System.Runtime.InteropServices:impl_System.Runtime.InteropServices",
        "//src/libraries/System.Runtime.Serialization.Formatters:impl_System.Runtime.Serialization.Formatters",
        "//src/libraries:impl_System.Runtime",
        "//src/libraries/System.Security.AccessControl:impl_System.Security.AccessControl",
        "//src/libraries/System.Security.Claims:impl_System.Security.Claims",
        "//src/libraries/System.Security.Cryptography:impl_System.Security.Cryptography",
        "//src/libraries/System.Security.Principal.Windows:impl_System.Security.Principal.Windows",
        "//src/libraries/System.Threading:impl_System.Threading",
        "//src/libraries/System.Threading.Tasks.Parallel:impl_System.Threading.Tasks.Parallel",
        "//src/libraries/shims/stubs:ref_System.Security.Permissions",
        "//src/libraries/shims/stubs:ref_System.Threading.AccessControl",
    ],
    os_targeted = True,
    exclude_sr = True,
    keyfile = "@nuget.microsoft.dotnet.arcade.sdk.v10.0.0-beta.26102.102//:tools/snk/ECMA.snk",
)