load("//src/libraries:defs.bzl", "netcoreapp_impl_assembly")

netcoreapp_impl_assembly(
    name = "impl_System.Security.Cryptography.Encoding",
    srcs = ["src/System.Security.Cryptography.Encoding.cs"],
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Security.Cryptography:ref_System.Security.Cryptography",
    ],
    exclude_sr = True,
)
