load("//src/libraries:defs.bzl", "netcoreapp_ref_assembly", "netcoreapp_impl_assembly", "ref_impl_pair")

exports_files([
    "ref/System.Formats.Cbor.cs",
    "ref/System.Formats.Cbor.netcoreapp.cs",
])

netcoreapp_ref_assembly(
    name = "ref_System.Formats.Cbor",
    srcs = [
        "ref/System.Formats.Cbor.cs",
        "ref/System.Formats.Cbor.netcoreapp.cs",
    ],
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Memory:ref_System.Memory",
        "//src/libraries/System.Runtime.Numerics:ref_System.Runtime.Numerics",
    ],
)

netcoreapp_impl_assembly(
    name = "impl_System.Formats.Cbor",
    srcs = [
        "//src/libraries/Common:src/System/Memory/PointerMemoryManager.cs",
        "//src/libraries/Common:src/System/Obsoletions.cs",

        "src/System/Formats/Cbor/CborConformanceLevel.cs",
        "src/System/Formats/Cbor/CborContentException.cs",
        "src/System/Formats/Cbor/CborHelpers.netcoreapp.cs",
        "src/System/Formats/Cbor/CborInitialByte.cs",
        "src/System/Formats/Cbor/CborTag.cs",
        "src/System/Formats/Cbor/HalfHelpers.netcoreapp.cs",
        "src/System/Formats/Cbor/Reader/CborReader.Array.cs",
        "src/System/Formats/Cbor/Reader/CborReader.Integer.cs",
        "src/System/Formats/Cbor/Reader/CborReader.Map.cs",
        "src/System/Formats/Cbor/Reader/CborReader.PeekState.cs",
        "src/System/Formats/Cbor/Reader/CborReader.Simple.cs",
        "src/System/Formats/Cbor/Reader/CborReader.Simple.netcoreapp.cs",
        "src/System/Formats/Cbor/Reader/CborReader.SkipValue.cs",
        "src/System/Formats/Cbor/Reader/CborReader.String.cs",
        "src/System/Formats/Cbor/Reader/CborReader.Tag.cs",
        "src/System/Formats/Cbor/Reader/CborReader.cs",
        "src/System/Formats/Cbor/Reader/CborReaderState.cs",
        "src/System/Formats/Cbor/Writer/CborWriter.Array.cs",
        "src/System/Formats/Cbor/Writer/CborWriter.Integer.cs",
        "src/System/Formats/Cbor/Writer/CborWriter.Map.cs",
        "src/System/Formats/Cbor/Writer/CborWriter.Simple.cs",
        "src/System/Formats/Cbor/Writer/CborWriter.Simple.netcoreapp.cs",
        "src/System/Formats/Cbor/Writer/CborWriter.String.cs",
        "src/System/Formats/Cbor/Writer/CborWriter.Tag.cs",
        "src/System/Formats/Cbor/Writer/CborWriter.cs",
    ],
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Collections:ref_System.Collections",
        "//src/libraries/System.Memory:ref_System.Memory",
        "//src/libraries/System.Runtime.Numerics:ref_System.Runtime.Numerics",
        "//src/libraries/System.Text.Encoding.Extensions:ref_System.Text.Encoding.Extensions",
        "//src/libraries/System.Threading:ref_System.Threading",
    ],
    resx_file = "src/Resources/Strings.resx",
)

ref_impl_pair(
    name = "live_System.Formats.Cbor",
    ref = ":ref_System.Formats.Cbor",
    lib = ":impl_System.Formats.Cbor",
    visibility = ["//visibility:public"],
)
