load("//src/libraries:defs.bzl", "netcoreapp_ref_assembly", "netcoreapp_impl_assembly")
load("//:defs.bzl", "OPEN_SNK")

exports_files([
    "ref/System.Net.Mail.Mime.cs",
    "src/Resources/Strings.resx",
    "src/System/Net/Base64Stream.cs",
    "src/System/Net/BufferBuilder.cs",
    "src/System/Net/CloseableStream.cs",
    "src/System/Net/DelegatedStream.cs",
    "src/System/Net/TrackingStringDictionary.cs",
    "src/System/Net/TrackingValidationObjectDictionary.cs",
    "src/System/Net/Mail/DomainLiteralReader.cs",
    "src/System/Net/Mail/DotAtomReader.cs",
    "src/System/Net/Mail/ISmtpAuthenticationModule.cs",
    "src/System/Net/Mail/MailAddress.cs",
    "src/System/Net/Mail/MailAddressCollection.cs",
    "src/System/Net/Mail/MailAddressParser.cs",
    "src/System/Net/Mail/MailBnfHelper.cs",
    "src/System/Net/Mail/MailHeaderID.cs",
    "src/System/Net/Mail/MailHeaderInfo.cs",
    "src/System/Net/Mail/MailPriority.cs",
    "src/System/Net/Mail/NetEventSource.Mail.cs",
    "src/System/Net/Mail/QuotedPairReader.cs",
    "src/System/Net/Mail/QuotedStringFormatReader.cs",
    "src/System/Net/Mail/SmtpConnection.Auth.cs",
    "src/System/Net/Mail/SmtpException.cs",
    "src/System/Net/Mail/SmtpLoginAuthenticationModule.cs",
    "src/System/Net/Mail/SmtpNegotiateAuthenticationModule.cs",
    "src/System/Net/Mail/SmtpNtlmAuthenticationModule.cs",
    "src/System/Net/Mail/SmtpStatusCode.cs",
    "src/System/Net/Mail/WhitespaceReader.cs",
    "src/System/Net/Mime/Base64Encoder.cs",
    "src/System/Net/Mime/Base64WriteStateInfo.cs",
    "src/System/Net/Mime/BaseWriter.cs",
    "src/System/Net/Mime/ByteEncoder.cs",
    "src/System/Net/Mime/ContentDisposition.cs",
    "src/System/Net/Mime/ContentType.cs",
    "src/System/Net/Mime/DispositionTypeNames.cs",
    "src/System/Net/Mime/EightBitStream.cs",
    "src/System/Net/Mime/EncodedStreamFactory.cs",
    "src/System/Net/Mime/HeaderCollection.cs",
    "src/System/Net/Mime/IByteEncoder.cs",
    "src/System/Net/Mime/IEncodableStream.cs",
    "src/System/Net/Mime/MediaTypeNames.cs",
    "src/System/Net/Mime/MimeBasePart.cs",
    "src/System/Net/Mime/MimePart.cs",
    "src/System/Net/Mime/QEncoder.cs",
    "src/System/Net/Mime/QEncodedStream.cs",
    "src/System/Net/Mime/QuotedPrintableStream.cs",
    "src/System/Net/Mime/SmtpDateTime.cs",
    "src/System/Net/Mime/TransferEncoding.cs",
    "src/System/Net/Mime/WriteStateInfoBase.cs",
])

netcoreapp_ref_assembly(
    name = "ref_System.Net.Mail",
    srcs = [
        "ref/System.Net.Mail.cs",
    ],
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Collections.Specialized:ref_System.Collections.Specialized",
        "//src/libraries/System.ComponentModel.EventBasedAsync:ref_System.ComponentModel.EventBasedAsync",
        "//src/libraries/System.Net.Primitives:ref_System.Net.Primitives",
        "//src/libraries/System.Net.Requests:ref_System.Net.Requests",
        "//src/libraries/System.Security.Cryptography:ref_System.Security.Cryptography",
    ],
)

netcoreapp_impl_assembly(
    name = "impl_System.Net.Mail",
    keyfile = OPEN_SNK,
    com_interface_generator = True,
    nowarn = ["CS1591"],
    os_targeted = "unix",
    srcs = glob(
        ["src/System/**/*.cs"],
        exclude = [
            # Browser/WASI only
            "src/System/Net/Mail/SmtpClient.Wasm.cs",
            # Not in csproj
            "src/System/Net/Mime/MultiAsyncResult.cs",
        ],
    ) + [
        # Common sources (TargetPlatformIdentifier != '')
        "//src/libraries/Common:src/System/Net/ReadWriteAdapter.cs",
        "//src/libraries/Common:src/System/Text/ValueStringBuilder.cs",
        "//src/libraries/Common:src/DisableRuntimeMarshalling.cs",
        "//src/libraries/Common:src/System/Net/Logging/NetEventSource.Common.cs",
        "//src/libraries/Common:src/System/Net/Logging/NetEventSource.Common.Associate.cs",
        "//src/libraries/Common:src/System/HexConverter.cs",
        "//src/libraries/Common:src/System/Obsoletions.cs",
        # Non-browser/non-wasi Common sources
        "//src/libraries/Common:src/System/NotImplemented.cs",
    ],
    resx_file = "src/Resources/Strings.resx",
    allow_unsafe_blocks = True,
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Collections:ref_System.Collections",
        "//src/libraries/System.Collections.Specialized:ref_System.Collections.Specialized",
        "//src/libraries/System.ComponentModel.EventBasedAsync:ref_System.ComponentModel.EventBasedAsync",
        "//src/libraries/System.Diagnostics.Tracing:ref_System.Diagnostics.Tracing",
        "//src/libraries/System.Memory:ref_System.Memory",
        "//src/libraries/System.Net.NetworkInformation:ref_System.Net.NetworkInformation",
        "//src/libraries/System.Net.Primitives:ref_System.Net.Primitives",
        "//src/libraries/System.Net.Requests:ref_System.Net.Requests",
        "//src/libraries/System.Net.Security:ref_System.Net.Security",
        "//src/libraries/System.Net.Sockets:ref_System.Net.Sockets",
        "//src/libraries/System.Runtime.InteropServices:ref_System.Runtime.InteropServices",
        "//src/libraries/System.Security.Cryptography:ref_System.Security.Cryptography",
        "//src/libraries/System.Threading:ref_System.Threading",
    ],
    supported_os_platforms = ["unix"],
)
