load("//src/tests:live_test.bzl", "coreclr_merged_test")

coreclr_merged_test(
    name = "JIT.Generics",
    deps = [
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    test_deps = [
        "//src/tests/JIT/Generics/Arrays/ConstructedTypes/Jagged:Struct01",
        "//src/tests/JIT/Generics/Arrays/ConstructedTypes/Jagged:Struct01_instance_Jagged",
        "//src/tests/JIT/Generics/Arrays/ConstructedTypes/Jagged:class01_ConstructedTypes_Jagged",
        "//src/tests/JIT/Generics/Arrays/ConstructedTypes/Jagged:class01_instance_Jagged",
        "//src/tests/JIT/Generics/Arrays/ConstructedTypes/Jagged:class01_static_Jagged",
        "//src/tests/JIT/Generics/Arrays/ConstructedTypes/Jagged:class02_Jagged",
        "//src/tests/JIT/Generics/Arrays/ConstructedTypes/Jagged:class03_Jagged",
        "//src/tests/JIT/Generics/Arrays/ConstructedTypes/Jagged:class04_Jagged",
        "//src/tests/JIT/Generics/Arrays/ConstructedTypes/Jagged:class05_Jagged",
        "//src/tests/JIT/Generics/Arrays/ConstructedTypes/Jagged:class06",
        "//src/tests/JIT/Generics/Arrays/ConstructedTypes/Jagged:class07",
        "//src/tests/JIT/Generics/Arrays/ConstructedTypes/Jagged:struc01",
        "//src/tests/JIT/Generics/Arrays/ConstructedTypes/Jagged:struct01_static_Jagged",
        "//src/tests/JIT/Generics/Arrays/ConstructedTypes/Jagged:struct02_Jagged",
        "//src/tests/JIT/Generics/Arrays/ConstructedTypes/Jagged:struct03_Jagged",
        "//src/tests/JIT/Generics/Arrays/ConstructedTypes/Jagged:struct04_Jagged",
        "//src/tests/JIT/Generics/Arrays/ConstructedTypes/Jagged:struct05_Jagged",
        "//src/tests/JIT/Generics/Arrays/ConstructedTypes/Jagged:struct06",
        "//src/tests/JIT/Generics/Arrays/ConstructedTypes/Jagged:struct07",
        "//src/tests/JIT/Generics/Arrays/ConstructedTypes/MultiDim:class01_ConstructedTypes_MultiDim",
        "//src/tests/JIT/Generics/Arrays/ConstructedTypes/MultiDim:class01_instance_MultiDim",
        "//src/tests/JIT/Generics/Arrays/ConstructedTypes/MultiDim:class01_static_MultiDim",
        "//src/tests/JIT/Generics/Arrays/ConstructedTypes/MultiDim:struct01_ConstructedTypes",
        "//src/tests/JIT/Generics/Arrays/ConstructedTypes/MultiDim:struct01_instance_MultiDim",
        "//src/tests/JIT/Generics/Arrays/ConstructedTypes/MultiDim:struct01_static_MultiDim",
        "//src/tests/JIT/Generics/Arrays/TypeParameters/Jagged:class01_TypeParameters_Jagged",
        "//src/tests/JIT/Generics/Arrays/TypeParameters/Jagged:struct01_Jagged",
        "//src/tests/JIT/Generics/Arrays/TypeParameters/MultiDim:class01_TypeParameters_MultiDim",
        "//src/tests/JIT/Generics/Arrays/TypeParameters/MultiDim:struct01_struct01.csproj",
        "//src/tests/JIT/Generics/ConstrainedCall:class1_cs_d",
        "//src/tests/JIT/Generics/ConstrainedCall:class1_cs_do",
        "//src/tests/JIT/Generics/ConstrainedCall:class1_cs_r",
        "//src/tests/JIT/Generics/ConstrainedCall:class1_cs_ro",
        "//src/tests/JIT/Generics/ConstrainedCall:class2_cs_d",
        "//src/tests/JIT/Generics/ConstrainedCall:class2_cs_do",
        "//src/tests/JIT/Generics/ConstrainedCall:class2_cs_r",
        "//src/tests/JIT/Generics/ConstrainedCall:class2_cs_ro",
        "//src/tests/JIT/Generics/ConstrainedCall:vt1_cs_d",
        "//src/tests/JIT/Generics/ConstrainedCall:vt1_cs_do",
        "//src/tests/JIT/Generics/ConstrainedCall:vt1_cs_r",
        "//src/tests/JIT/Generics/ConstrainedCall:vt1_cs_ro",
        "//src/tests/JIT/Generics/ConstrainedCall:vt2_cs_d",
        "//src/tests/JIT/Generics/ConstrainedCall:vt2_cs_do",
        "//src/tests/JIT/Generics/ConstrainedCall:vt2_cs_r",
        "//src/tests/JIT/Generics/ConstrainedCall:vt2_cs_ro",
        "//src/tests/JIT/Generics/ConstrainedCall:vt3_cs_d",
        "//src/tests/JIT/Generics/ConstrainedCall:vt3_cs_do",
        "//src/tests/JIT/Generics/ConstrainedCall:vt3_cs_r",
        "//src/tests/JIT/Generics/ConstrainedCall:vt3_cs_ro",
        "//src/tests/JIT/Generics/ConstrainedCall:vt4_cs_d",
        "//src/tests/JIT/Generics/ConstrainedCall:vt4_cs_do",
        "//src/tests/JIT/Generics/ConstrainedCall:vt4_cs_r",
        "//src/tests/JIT/Generics/ConstrainedCall:vt4_cs_ro",
        "//src/tests/JIT/Generics/Constraints:Call_instance01_d",
        "//src/tests/JIT/Generics/Constraints:Call_instance01_do",
        "//src/tests/JIT/Generics/Constraints:Call_instance01_r",
        "//src/tests/JIT/Generics/Constraints:Call_instance01_ro",
        "//src/tests/JIT/Generics/Constraints:call_instance01",
        "//src/tests/JIT/Generics/Constraints:call_static01",
        "//src/tests/JIT/Generics/Constraints:convert_instance01",
        "//src/tests/JIT/Generics/Constraints:convert_static01",
        "//src/tests/JIT/Generics/Constraints:transitive_instance01",
        "//src/tests/JIT/Generics/Constraints:transitive_static01",
        "//src/tests/JIT/Generics/Conversions/Boxing:box_isinst_br_nullable",
        "//src/tests/JIT/Generics/Conversions/Boxing:box_isinst_unbox",
        "//src/tests/JIT/Generics/Conversions/Boxing:box_unbox01",
        "//src/tests/JIT/Generics/Conversions/Reference:gentogen01",
        "//src/tests/JIT/Generics/Conversions/Reference:gentogen02",
        "//src/tests/JIT/Generics/Conversions/Reference:gentogen03",
        "//src/tests/JIT/Generics/Conversions/Reference:gentonongen01",
        "//src/tests/JIT/Generics/Conversions/Reference:gentonongen02",
        "//src/tests/JIT/Generics/Conversions/Reference:gentonongen03",
        "//src/tests/JIT/Generics/Conversions/Reference:nongentogen01",
        "//src/tests/JIT/Generics/Conversions/Reference:nongentogen02",
        "//src/tests/JIT/Generics/Conversions/Reference:nongentogen03",
        "//src/tests/JIT/Generics/Coverage:chaos55915408cs",
        "//src/tests/JIT/Generics/Coverage:chaos55915408cs_o",
        "//src/tests/JIT/Generics/Coverage:chaos56200037cs",
        "//src/tests/JIT/Generics/Coverage:chaos56200037cs_o",
        "//src/tests/JIT/Generics/Coverage:chaos65204782cs",
        "//src/tests/JIT/Generics/Coverage:chaos65204782cs_o",
        "//src/tests/JIT/Generics/Exceptions:general_class_instance01",
        "//src/tests/JIT/Generics/Exceptions:general_class_static01",
        "//src/tests/JIT/Generics/Exceptions:general_struct_instance01",
        "//src/tests/JIT/Generics/Exceptions:general_struct_static01",
        "//src/tests/JIT/Generics/Exceptions:specific_class_instance01",
        "//src/tests/JIT/Generics/Exceptions:specific_class_instance02",
        "//src/tests/JIT/Generics/Exceptions:specific_class_static01",
        "//src/tests/JIT/Generics/Exceptions:specific_class_static02",
        "//src/tests/JIT/Generics/Exceptions:specific_struct_instance01",
        "//src/tests/JIT/Generics/Exceptions:specific_struct_instance02",
        "//src/tests/JIT/Generics/Exceptions:specific_struct_static01",
        "//src/tests/JIT/Generics/Exceptions:specific_struct_static02",
        "//src/tests/JIT/Generics/Fields:instance_assignment_class01_Fields",
        "//src/tests/JIT/Generics/Fields:instance_assignment_struct01_Fields",
        "//src/tests/JIT/Generics/Fields:instance_equalnull_class01_Fields",
        "//src/tests/JIT/Generics/Fields:instance_equalnull_struct01_Fields",
        "//src/tests/JIT/Generics/Fields:instance_passing_class01_Fields",
        "//src/tests/JIT/Generics/Fields:instance_passing_struct01_Fields",
        "//src/tests/JIT/Generics/Fields:static_assignment_class01_Fields",
        "//src/tests/JIT/Generics/Fields:static_assignment_struct01_Fields",
        "//src/tests/JIT/Generics/Fields:static_equalnull_class01_Fields",
        "//src/tests/JIT/Generics/Fields:static_equalnull_struct01_Fields",
        "//src/tests/JIT/Generics/Fields:static_passing_class01_Fields",
        "//src/tests/JIT/Generics/Fields:static_passing_struct01_Fields",
        "//src/tests/JIT/Generics/Instantiation/Classes:baseclass01",
        "//src/tests/JIT/Generics/Instantiation/Classes:baseclass02",
        "//src/tests/JIT/Generics/Instantiation/Classes:baseclass03",
        "//src/tests/JIT/Generics/Instantiation/Classes:baseclass04",
        "//src/tests/JIT/Generics/Instantiation/Classes:baseclass05",
        "//src/tests/JIT/Generics/Instantiation/Classes:class01_Classes",
        "//src/tests/JIT/Generics/Instantiation/Classes:class02_Classes",
        "//src/tests/JIT/Generics/Instantiation/Classes:class03_Classes",
        "//src/tests/JIT/Generics/Instantiation/Interfaces:class01_Interfaces",
        "//src/tests/JIT/Generics/Instantiation/Interfaces:class02_Interfaces",
        "//src/tests/JIT/Generics/Instantiation/Interfaces:class03_Interfaces",
        "//src/tests/JIT/Generics/Instantiation/Interfaces:class04_Interfaces",
        "//src/tests/JIT/Generics/Instantiation/Interfaces:class05_Interfaces",
        "//src/tests/JIT/Generics/Instantiation/Interfaces:struct01_Interfaces",
        "//src/tests/JIT/Generics/Instantiation/Interfaces:struct02_Interfaces",
        "//src/tests/JIT/Generics/Instantiation/Interfaces:struct03_Interfaces",
        "//src/tests/JIT/Generics/Instantiation/Interfaces:struct04_Interfaces",
        "//src/tests/JIT/Generics/Instantiation/Interfaces:struct05_Interfaces",
        "//src/tests/JIT/Generics/Instantiation/Structs:struct01_Structs",
        "//src/tests/JIT/Generics/Instantiation/Structs:struct02_Structs",
        "//src/tests/JIT/Generics/Instantiation/Structs:struct03_Structs",
        "//src/tests/JIT/Generics/Instantiation/delegates:Delegate001",
        "//src/tests/JIT/Generics/Instantiation/delegates:Delegate002",
        "//src/tests/JIT/Generics/Instantiation/delegates:Delegate003",
        "//src/tests/JIT/Generics/Instantiation/delegates:Delegate004",
        "//src/tests/JIT/Generics/Instantiation/delegates:Delegate005",
        "//src/tests/JIT/Generics/Instantiation/delegates:Delegate006",
        "//src/tests/JIT/Generics/Instantiation/delegates:Delegate007",
        "//src/tests/JIT/Generics/Instantiation/delegates:Delegate008",
        "//src/tests/JIT/Generics/Instantiation/delegates:Delegate009",
        "//src/tests/JIT/Generics/Instantiation/delegates:Delegate010",
        "//src/tests/JIT/Generics/Instantiation/delegates:Delegate011",
        "//src/tests/JIT/Generics/Instantiation/delegates:Delegate012",
        "//src/tests/JIT/Generics/Instantiation/delegates:Delegate013",
        "//src/tests/JIT/Generics/Instantiation/delegates:Delegate014",
        "//src/tests/JIT/Generics/Instantiation/delegates:Delegate015",
        "//src/tests/JIT/Generics/Instantiation/delegates:Delegate016",
        "//src/tests/JIT/Generics/Instantiation/delegates:Delegate017",
        "//src/tests/JIT/Generics/Instantiation/delegates:Delegate018",
        "//src/tests/JIT/Generics/Instantiation/delegates:Delegate019",
        "//src/tests/JIT/Generics/Instantiation/delegates:Delegate020",
        "//src/tests/JIT/Generics/Instantiation/delegates:Delegate021",
        "//src/tests/JIT/Generics/Instantiation/delegates:Delegate022",
        "//src/tests/JIT/Generics/Instantiation/delegates:Delegate023",
        "//src/tests/JIT/Generics/Instantiation/delegates:Delegate024",
        "//src/tests/JIT/Generics/Instantiation/delegates:Delegate025",
        "//src/tests/JIT/Generics/Instantiation/delegates:Delegate026",
        "//src/tests/JIT/Generics/Instantiation/delegates:Delegate027",
        "//src/tests/JIT/Generics/Instantiation/delegates:Delegate028",
        "//src/tests/JIT/Generics/Instantiation/delegates:Delegate029",
        "//src/tests/JIT/Generics/Instantiation/delegates:Delegate030",
        "//src/tests/JIT/Generics/Instantiation/delegates:Delegate031",
        "//src/tests/JIT/Generics/Instantiation/delegates:Delegate032",
        "//src/tests/JIT/Generics/Locals:instance_assignment_class01_Locals",
        "//src/tests/JIT/Generics/Locals:instance_assignment_struct01_Locals",
        "//src/tests/JIT/Generics/Locals:instance_equalnull_class01_Locals",
        "//src/tests/JIT/Generics/Locals:instance_equalnull_struct01_Locals",
        "//src/tests/JIT/Generics/Locals:instance_passing_class01_Locals",
        "//src/tests/JIT/Generics/Locals:instance_passing_struct01_Locals",
        "//src/tests/JIT/Generics/Locals:static_assignment_class01_Locals",
        "//src/tests/JIT/Generics/Locals:static_assignment_struct01_Locals",
        "//src/tests/JIT/Generics/Locals:static_equalnull_class01_Locals",
        "//src/tests/JIT/Generics/Locals:static_equalnull_struct01_Locals",
        "//src/tests/JIT/Generics/Locals:static_passing_class01_Locals",
        "//src/tests/JIT/Generics/Locals:static_passing_struct01_Locals",
        "//src/tests/JIT/Generics/MemberAccess:class_instance01",
        "//src/tests/JIT/Generics/MemberAccess:class_static01",
        "//src/tests/JIT/Generics/MemberAccess:interface_class01",
        "//src/tests/JIT/Generics/MemberAccess:interface_class02",
        "//src/tests/JIT/Generics/MemberAccess:interface_struct01",
        "//src/tests/JIT/Generics/MemberAccess:interface_struct02",
        "//src/tests/JIT/Generics/MemberAccess:struct_instance01",
        "//src/tests/JIT/Generics/MemberAccess:struct_static01",
        "//src/tests/JIT/Generics/Parameters:instance_assignment_class01_Parameters",
        "//src/tests/JIT/Generics/Parameters:instance_assignment_struct01_Parameters",
        "//src/tests/JIT/Generics/Parameters:instance_equalnull_class01_Parameters",
        "//src/tests/JIT/Generics/Parameters:instance_equalnull_struct01_Parameters",
        "//src/tests/JIT/Generics/Parameters:instance_passing_class01_Parameters",
        "//src/tests/JIT/Generics/Parameters:instance_passing_struct01_Parameters",
        "//src/tests/JIT/Generics/Parameters:static_assignment_class01_Parameters",
        "//src/tests/JIT/Generics/Parameters:static_assignment_struct01_Parameters",
        "//src/tests/JIT/Generics/Parameters:static_equalnull_class01_Parameters",
        "//src/tests/JIT/Generics/Parameters:static_equalnull_struct01_Parameters",
        "//src/tests/JIT/Generics/Parameters:static_passing_class01_Parameters",
        "//src/tests/JIT/Generics/Parameters:static_passing_struct01_Parameters",
        "//src/tests/JIT/Generics/TypeParameters:default_class01",
        "//src/tests/JIT/Generics/TypeParameters:default_struct01",
        "//src/tests/JIT/Generics/Typeof:class01_Typeof",
        "//src/tests/JIT/Generics/Typeof:class02_Typeof",
        "//src/tests/JIT/Generics/Typeof:class03_Typeof",
        "//src/tests/JIT/Generics/Typeof:dynamicTypes",
        "//src/tests/JIT/Generics/Typeof:objectBoxing",
        "//src/tests/JIT/Generics/Typeof:refTypesdynamic",
        "//src/tests/JIT/Generics/Typeof:struct01_Typeof",
        "//src/tests/JIT/Generics/Typeof:struct02_Typeof",
        "//src/tests/JIT/Generics/Typeof:struct03_Typeof",
        "//src/tests/JIT/Generics/Typeof:valueTypeBoxing",
    ],
)
