load("//:defs.bzl", "csharp_binary", "gen_assembly_info", "gen_target_framework_attrs")

gen_assembly_info(
    name = "assemblyinfo_ilc",
    out = "ILCompiler_inbuild.AssemblyInfo.cs",
    assembly_name = "ilc",
    cls_compliant = False,
    is_aot_compatible = False,
    include_serviceable = False,
    include_description = False,
    assembly_configuration = "Release",
    include_dll_safe_search_path = 0,
)

gen_target_framework_attrs(
    name = "tfmattrs_ilc",
    out = ".NETCoreApp,Version=v10.0.AssemblyAttributes.cs",
)

csharp_binary(
    name = "ilc",
    interceptors_namespaces = ";Microsoft.AspNetCore.Http.Generated;Microsoft.Extensions.Configuration.Binder.SourceGeneration;Microsoft.Extensions.Validation.Generated",
    nowarn = ["1701", "1702", "8002", "IL2121", "NU1701", "NU5105"],
    srcs = glob(
        ["**/*.cs"],
        exclude = ["repro/**"],
    ) + [
        "//src/coreclr/tools/Common:CommandLineHelpers.cs",
        "//src/coreclr/tools/Common:InstructionSetHelpers.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/HelperExtensions.cs",
        ":assemblyinfo_ilc",
        ":tfmattrs_ilc",
    ],
    compiler_options = ["/unsafe", "/warnaserror+:NU1605"],
    deps = [
        "//src/coreclr/tools/aot/ILCompiler.Compiler",
        "//src/coreclr/tools/aot/ILCompiler.DependencyAnalysisFramework",
        "//src/coreclr/tools/aot/ILCompiler.MetadataTransform",
        "//src/coreclr/tools/aot/ILCompiler.RyuJit",
        "//src/coreclr/tools/aot/ILCompiler.TypeSystem",
        "@paket.main//microsoft.diasymreader",
        "@paket.main//system.commandline",
    ],
    target_frameworks = ["net10.0"],
    visibility = ["//visibility:public"],
    analyzers = [
        "//:source_build_analyzers",
        "//src/tools/illink/src/ILLink.RoslynAnalyzer",
    ],
    msbuild_analyzer_config = "source",
    include_library_nowarn = False,
    editorconfig_name = "ILCompiler_inbuild",
)
