load("//src/tests:live_test.bzl", "coreclr_test")

coreclr_test(
    name = "Sse1_handwritten_ro",
    srcs = [
        "HandwrittenProgram.cs",
        "ConvertToInt32WithTruncation.cs",
        "ConvertToInt32.cs",
        "LoadAlignedVector128.cs",
        "LoadHigh.cs",
        "LoadLow.cs",
        "MoveHighToLow.cs",
        "MoveLowToHigh.cs",
        "MoveMask.cs",
        "MoveScalar.cs",
        "Prefetch.cs",
        "ReciprocalScalar.cs",
        "ReciprocalSqrtScalar.cs",
        "ReciprocalSqrt.cs",
        "Reciprocal.cs",
        "Shuffle.cs",
        "SqrtScalar.cs",
        "Sqrt.cs",
        "StoreAlignedNonTemporal.cs",
        "StoreAligned.cs",
        "StoreFence.cs",
        "StoreHigh.cs",
        "StoreLow.cs",
        "StoreScalar.cs",
        "Store.cs",
        "UnpackHigh.cs",
        "UnpackLow.cs",
    ],
    optimize = True,
    allow_unsafe_blocks = True,
    deps = [
        "//src/tests/Common:TestLibrary",
    
        "@paket.main//microsoft.dotnet.xunitextensions",
    ],
)

coreclr_test(
    name = "Sse1_handwritten_r",
    srcs = [
        "HandwrittenProgram.cs",
        "ConvertToInt32WithTruncation.cs",
        "ConvertToInt32.cs",
        "LoadAlignedVector128.cs",
        "LoadHigh.cs",
        "LoadLow.cs",
        "MoveHighToLow.cs",
        "MoveLowToHigh.cs",
        "MoveMask.cs",
        "MoveScalar.cs",
        "Prefetch.cs",
        "ReciprocalScalar.cs",
        "ReciprocalSqrtScalar.cs",
        "ReciprocalSqrt.cs",
        "Reciprocal.cs",
        "Shuffle.cs",
        "SqrtScalar.cs",
        "Sqrt.cs",
        "StoreAlignedNonTemporal.cs",
        "StoreAligned.cs",
        "StoreFence.cs",
        "StoreHigh.cs",
        "StoreLow.cs",
        "StoreScalar.cs",
        "Store.cs",
        "UnpackHigh.cs",
        "UnpackLow.cs",
    ],
    allow_unsafe_blocks = True,
    deps = [
        "//src/tests/Common:TestLibrary",
    
        "@paket.main//microsoft.dotnet.xunitextensions",
    ],
)
