load("//src/libraries:defs.bzl", "COMMON_GENERATOR_ANALYZERS", "MULTITARGET_NOWARN", "impl_assembly")

impl_assembly(
    name = "impl_System.Composition.AttributedModel",
    include_runtime_async = False,
    event_source_generator = False,
    srcs = [
        "src/System/Composition/Convention/AttributedModelProvider.cs",
        "src/System/Composition/ExportAttribute.cs",
        "src/System/Composition/ExportMetadataAttribute.cs",
        "src/System/Composition/ImportAttribute.cs",
        "src/System/Composition/ImportingConstructorAttribute.cs",
        "src/System/Composition/ImportManyAttribute.cs",
        "src/System/Composition/ImportMetadataConstraintAttribute.cs",
        "src/System/Composition/MetadataAttributeAttribute.cs",
        "src/System/Composition/OnImportsSatisfiedAttribute.cs",
        "src/System/Composition/PartMetadataAttribute.cs",
        "src/System/Composition/PartNotDiscoverableAttribute.cs",
        "src/System/Composition/SharedAttribute.cs",
        "src/System/Composition/SharingBoundaryAttribute.cs",
    ],
    deps = [
        "//src/libraries:ref_System.Runtime",
    ],
    nullable = "disable",
    analyzers = COMMON_GENERATOR_ANALYZERS,
    nowarn = MULTITARGET_NOWARN + ["CP0003", "nullable", "CS1591"],
    exclude_sr = True,
)
