load("//src/tests:live_test.bzl", "library_test")
load("//src/libraries:defs.bzl", "MULTITARGET_NOWARN")
load("//:defs.bzl", "ASPNETCORE_SNK")

library_test(
    name = "Microsoft.Extensions.Diagnostics.Abstractions.Tests",
    nowarn = MULTITARGET_NOWARN,
    srcs = glob(["**/*.cs"]),
    deps = [
        "//src/libraries/Microsoft.Extensions.Diagnostics.Abstractions:ref_Microsoft.Extensions.Diagnostics.Abstractions",
        "//src/libraries/Microsoft.Extensions.DependencyInjection:ref_Microsoft.Extensions.DependencyInjection",
        "//src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions:ref_Microsoft.Extensions.DependencyInjection.Abstractions",
        "//src/libraries/Microsoft.Extensions.Options:ref_Microsoft.Extensions.Options",
        "//src/libraries/Microsoft.Extensions.Primitives:ref_Microsoft.Extensions.Primitives",
        "//src/libraries/System.Diagnostics.DiagnosticSource:ref_System.Diagnostics.DiagnosticSource",
        "//src/libraries/Common/tests:TestUtilities",
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//microsoft.dotnet.xunitextensions",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    keyfile = ASPNETCORE_SNK,
)
