load("//src/libraries:defs.bzl", "COMMON_GENERATOR_ANALYZERS", "MULTITARGET_NOWARN", "netcoreapp_ref_assembly", "impl_assembly", "ref_impl_pair")

exports_files([
    "ref/Microsoft.Extensions.Logging.cs",
    "ref/Microsoft.Extensions.Logging.Forwards.cs",
])

netcoreapp_ref_assembly(
    name = "ref_Microsoft.Extensions.Logging",
    srcs = [
        "ref/Microsoft.Extensions.Logging.cs",
        "ref/Microsoft.Extensions.Logging.Forwards.cs",
    ],
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/Microsoft.Extensions.DependencyInjection:ref_Microsoft.Extensions.DependencyInjection",
        "//src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions:ref_Microsoft.Extensions.DependencyInjection.Abstractions",
        "//src/libraries/Microsoft.Extensions.Logging.Abstractions:ref_Microsoft.Extensions.Logging.Abstractions",
        "//src/libraries/Microsoft.Extensions.Options:ref_Microsoft.Extensions.Options",
    ],
)

impl_assembly(
    name = "impl_Microsoft.Extensions.Logging",
    include_runtime_async = False,
    event_source_generator = False,
    analyzers = COMMON_GENERATOR_ANALYZERS,
    nowarn = MULTITARGET_NOWARN + ["CP0003"],
    srcs = glob(["src/**/*.cs"]) + [
        "//src/libraries/Common:src/Extensions/ProviderAliasUtilities/ProviderAliasUtilities.cs",
        "//src/libraries/Common:src/Extensions/Logging/NullExternalScopeProvider.cs",
        "//src/libraries/Common:src/Extensions/Logging/NullScope.cs",
        "//src/libraries/Common:src/Extensions/Logging/DebuggerDisplayFormatting.cs",
    ],
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/Microsoft.Extensions.DependencyInjection:ref_Microsoft.Extensions.DependencyInjection",
        "//src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions:ref_Microsoft.Extensions.DependencyInjection.Abstractions",
        "//src/libraries/Microsoft.Extensions.Logging.Abstractions:ref_Microsoft.Extensions.Logging.Abstractions",
        "//src/libraries/Microsoft.Extensions.Options:ref_Microsoft.Extensions.Options",
        "//src/libraries/System.Collections:ref_System.Collections",
        "//src/libraries/System.Collections.Concurrent:ref_System.Collections.Concurrent",
        "//src/libraries/System.ComponentModel:ref_System.ComponentModel",
        "//src/libraries/System.Diagnostics.DiagnosticSource:ref_System.Diagnostics.DiagnosticSource",
        "//src/libraries/System.Linq:ref_System.Linq",
        "//src/libraries/System.Memory:ref_System.Memory",
        "//src/libraries/System.Threading:ref_System.Threading",
    ],
    resx_file = "src/Resources/Strings.resx",
)

ref_impl_pair(
    name = "live_Microsoft.Extensions.Logging",
    ref = ":ref_Microsoft.Extensions.Logging",
    lib = ":impl_Microsoft.Extensions.Logging",
    visibility = ["//visibility:public"],
)
