load("//src/tests:live_test.bzl", "coreclr_test", "il_coreclr_test")

coreclr_test(
    name = "Inline_DetectChanges",
    srcs = ["Inline_DetectChanges.cs"],
    optimize = True,
)

coreclr_test(
    name = "Inline_RecursiveMethod21",
    srcs = ["Inline_RecursiveMethod21.cs"],
    pri = 1,
    optimize = True,
    size = "medium",
)

coreclr_test(
    name = "struct_opcodes",
    srcs = ["struct_opcodes.cs"],
    pri = 1,
    optimize = True,
    size = "medium",
)

coreclr_test(
    name = "GenericStructs",
    srcs = ["GenericStructs.cs"],
    pri = 1,
    optimize = True,
    size = "medium",
)

coreclr_test(
    name = "DelegStaticFtn",
    srcs = ["DelegStaticFtn.cs"],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "ifelse",
    srcs = ["ifelse.cs"],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "size",
    srcs = ["size.cs"],
    pri = 1,
)

coreclr_test(
    name = "ReturnStruct_Method",
    srcs = ["ReturnStruct_Method.cs"],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "interfaceproperty",
    srcs = ["interfaceProperty.cs"],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "Inline_NormalizeStack",
    srcs = ["Inline_NormalizeStack.cs"],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "StructInClass",
    srcs = ["StructInClass.cs"],
    pri = 1,
    optimize = True,
    size = "medium",
)

coreclr_test(
    name = "throwtest",
    srcs = ["throwTest.cs"],
    pri = 1,
    optimize = True,
    size = "medium",
)

coreclr_test(
    name = "args3",
    srcs = ["args3.cs"],
    pri = 1,
    optimize = True,
    size = "medium",
)

coreclr_test(
    name = "mthdimpl",
    srcs = ["mthdimpl.cs"],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "LotsOfInlines",
    srcs = ["LotsOfInlines.cs"],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "array",
    srcs = ["array.cs"],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "Inline_Vars",
    srcs = ["Inline_Vars.cs"],
)

coreclr_test(
    name = "Inline_Many",
    srcs = ["Inline_Many.cs"],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "args1",
    srcs = ["args1.cs"],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "debug",
    srcs = ["debug.cs"],
    pri = 1,
    debug_type = "full",
    size = "medium",
)

coreclr_test(
    name = "Inline_MultipleReturn",
    srcs = ["Inline_MultipleReturn.cs"],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "property",
    srcs = ["property.cs"],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "Inline_RecursiveMethod",
    srcs = ["Inline_RecursiveMethod.cs"],
    pri = 1,
    optimize = True,
    size = "medium",
)

coreclr_test(
    name = "DelegInstanceFtn",
    srcs = ["DelegInstanceFtn.cs"],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "Inline_Recursion",
    srcs = ["Inline_Recursion.cs"],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "Inline_STARG",
    srcs = ["Inline_STARG.cs"],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "deepcall",
    srcs = ["deepcall.cs"],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "indexer",
    srcs = ["indexer.cs"],
    pri = 1,
    optimize = True,
    size = "medium",
)

coreclr_test(
    name = "Inline_SideAffects",
    srcs = ["Inline_SideAffects.cs"],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "interfaceCall",
    srcs = ["interfaceCall.cs"],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "trycatch",
    srcs = ["trycatch.cs"],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "fact",
    srcs = ["fact.cs"],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "Inline_handler",
    srcs = ["Inline_handler.cs"],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "Inline_DelegateStruct",
    srcs = ["Inline_DelegateStruct.cs"],
    pri = 1,
    optimize = True,
    size = "medium",
)

coreclr_test(
    name = "Inline_GenericMethods",
    srcs = ["Inline_GenericMethods.cs"],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "InlineThrow",
    srcs = ["Inlinethrow.cs"],
)

coreclr_test(
    name = "args2",
    srcs = ["args2.cs"],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "UnsafeBlockCopy",
    srcs = ["UnsafeBlockCopy.cs"],
    pri = 1,
    debug_type = "pdbonly",
    optimize = True,
    allow_unsafe_blocks = True,
    size = "medium",
)

coreclr_test(
    name = "StructAsParam_Method",
    srcs = ["StructAsParam_Method.cs"],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "Inline",
    srcs = ["Inline.cs"],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "mathfunc",
    srcs = ["mathfunc.cs"],
)

il_coreclr_test(
    name = "calli",
    srcs = ["calli.il"],
    debug_type = "pdbonly",
)

coreclr_test(
    name = "ArrayOfStructs",
    srcs = ["ArrayOfStructs.cs"],
    pri = 1,
    optimize = True,
    size = "medium",
)

coreclr_test(
    name = "Inline_NewObj",
    srcs = ["Inline_NewObj.cs"],
    pri = 1,
    size = "medium",
)
