load("//:defs.bzl", "FILE_VERSION", "NETCOREAPP_MINIMUM", "NETCOREAPP_TOOL_CURRENT", "csharp_library")

genrule(
    name = "AssemblyInfo",
    outs = ["AssemblyInfo.g.cs"],
    cmd = "echo '[assembly: System.Reflection.AssemblyFileVersion(\"" + FILE_VERSION + "\")]' > $@",
)

csharp_library(
    name = "ILCompiler.MetadataTransform",
    include_runtime_async = False,
    nowarn = ["1591"],
    msbuild_analyzer_config = "source",
    interceptors_namespaces = ";Microsoft.Extensions.Validation.Generated",
    compiler_options = ["/warnaserror+:NU1605"],
    srcs = [
        ":AssemblyInfo",
        "ILCompiler/Metadata/EntityMap.cs",
        "ILCompiler/Metadata/IMetadataPolicy.cs",
        "ILCompiler/Metadata/MetadataTransform.cs",
        "ILCompiler/Metadata/MetadataTransformResult.cs",
        "ILCompiler/Metadata/Transform.Constant.cs",
        "ILCompiler/Metadata/Transform.CustomAttribute.cs",
        "ILCompiler/Metadata/Transform.Event.cs",
        "ILCompiler/Metadata/Transform.Field.cs",
        "ILCompiler/Metadata/Transform.Method.cs",
        "ILCompiler/Metadata/Transform.Namespace.cs",
        "ILCompiler/Metadata/Transform.Parameter.cs",
        "ILCompiler/Metadata/Transform.Property.cs",
        "ILCompiler/Metadata/Transform.Scope.cs",
        "ILCompiler/Metadata/Transform.String.cs",
        "ILCompiler/Metadata/Transform.Type.cs",
        "ILCompiler/Metadata/Transform.TypeForwarders.cs",
        "ILCompiler/Metadata/Transform.cs",
        "Internal/Metadata/NativeFormat/Writer/ConstantValues.cs",
        "Internal/Metadata/NativeFormat/Writer/MdBinaryWriter.cs",
        "Internal/Metadata/NativeFormat/Writer/MdBinaryWriterGen.cs",
        "Internal/Metadata/NativeFormat/Writer/NativeFormatWriterGen.cs",
        "Internal/Metadata/NativeFormat/Writer/NativeMetadataWriter.cs",
    ] + [
        "//src/coreclr/tools/Common:Internal/LowLevelLinq/LowLevelEnumerable.cs",
        "//src/coreclr/tools/Common:Internal/Metadata/NativeFormat/MdBinaryReader.cs",
        "//src/coreclr/tools/Common:Internal/Metadata/NativeFormat/MdBinaryReaderGen.cs",
        "//src/coreclr/tools/Common:Internal/Metadata/NativeFormat/NativeFormatReaderCommonGen.cs",
        "//src/coreclr/tools/Common:Internal/Metadata/NativeFormat/NativeFormatReaderGen.cs",
        "//src/coreclr/tools/Common:Internal/Metadata/NativeFormat/NativeMetadataReader.cs",
        "//src/coreclr/tools/Common:Internal/NativeFormat/NativeFormat.cs",
        "//src/coreclr/tools/Common:Internal/NativeFormat/NativeFormatReader.Primitives.cs",
        "//src/coreclr/tools/Common:Internal/NativeFormat/NativeFormatReader.String.cs",
        "//src/coreclr/tools/Common:Internal/NativeFormat/NativeFormatReader.cs",
        "//src/coreclr/tools/Common:Internal/NativeFormat/NativeFormatWriter.Primitives.cs",
        "//src/coreclr/tools/Common:Internal/NativeFormat/NativeFormatWriter.cs",
        "//src/coreclr/tools/Common:Internal/NativeFormat/NativeFormatWriterExtensions.cs",
    ],
    defines = ["NATIVEFORMAT_PUBLICWRITER"],
    allow_unsafe_blocks = True,
    analyzers = [
        "//:source_build_analyzers",
        "//src/tools/illink/src/ILLink.RoslynAnalyzer",
    ],
    deps = [
        "//src/coreclr/tools/aot/ILCompiler.TypeSystem",
        "@paket.main//microsoft.diasymreader",
    ],
    target_frameworks = [NETCOREAPP_MINIMUM, NETCOREAPP_TOOL_CURRENT],
    visibility = ["//visibility:public"],
)
