load("//:defs.bzl", "csharp_library", "gen_assembly_info", "gen_target_framework_attrs")

gen_assembly_info(
    name = "assemblyinfo_ILCompiler.MetadataTransform",
    out = "ILCompiler.MetadataTransform.AssemblyInfo.cs",
    assembly_name = "ILCompiler.MetadataTransform",
    cls_compliant = False,
    is_aot_compatible = False,
    include_serviceable = False,
    include_description = False,
    assembly_configuration = "Release",
    include_dll_safe_search_path = 0,
)

gen_target_framework_attrs(
    name = "tfmattrs_ILCompiler.MetadataTransform",
    out = ".NETCoreApp,Version=v10.0.AssemblyAttributes.cs",
)

csharp_library(
    name = "ILCompiler.MetadataTransform",
    nowarn = ["1591"],
    msbuild_analyzer_config = "source",
    interceptors_namespaces = ";Microsoft.Extensions.Validation.Generated",
    compiler_options = ["/warnaserror+:NU1605"],
    srcs = [
        ":assemblyinfo_ILCompiler.MetadataTransform",
        ":tfmattrs_ILCompiler.MetadataTransform",
        "ILCompiler/Metadata/EntityMap.cs",
        "ILCompiler/Metadata/IMetadataPolicy.cs",
        "ILCompiler/Metadata/MetadataTransform.cs",
        "ILCompiler/Metadata/MetadataTransformResult.cs",
        "ILCompiler/Metadata/Transform.Constant.cs",
        "ILCompiler/Metadata/Transform.CustomAttribute.cs",
        "ILCompiler/Metadata/Transform.Event.cs",
        "ILCompiler/Metadata/Transform.Field.cs",
        "ILCompiler/Metadata/Transform.Method.cs",
        "ILCompiler/Metadata/Transform.Namespace.cs",
        "ILCompiler/Metadata/Transform.Parameter.cs",
        "ILCompiler/Metadata/Transform.Property.cs",
        "ILCompiler/Metadata/Transform.Scope.cs",
        "ILCompiler/Metadata/Transform.String.cs",
        "ILCompiler/Metadata/Transform.Type.cs",
        "ILCompiler/Metadata/Transform.TypeForwarders.cs",
        "ILCompiler/Metadata/Transform.cs",
        "Internal/Metadata/NativeFormat/Writer/ConstantValues.cs",
        "Internal/Metadata/NativeFormat/Writer/MdBinaryWriter.cs",
        "Internal/Metadata/NativeFormat/Writer/MdBinaryWriterGen.cs",
        "Internal/Metadata/NativeFormat/Writer/NativeFormatWriterGen.cs",
        "Internal/Metadata/NativeFormat/Writer/NativeMetadataWriter.cs",
    ] + [
        "//src/coreclr/tools/Common:Internal/LowLevelLinq/LowLevelEnumerable.cs",
        "//src/coreclr/tools/Common:Internal/Metadata/NativeFormat/MdBinaryReader.cs",
        "//src/coreclr/tools/Common:Internal/Metadata/NativeFormat/MdBinaryReaderGen.cs",
        "//src/coreclr/tools/Common:Internal/Metadata/NativeFormat/NativeFormatReaderCommonGen.cs",
        "//src/coreclr/tools/Common:Internal/Metadata/NativeFormat/NativeFormatReaderGen.cs",
        "//src/coreclr/tools/Common:Internal/Metadata/NativeFormat/NativeMetadataReader.cs",
        "//src/coreclr/tools/Common:Internal/NativeFormat/NativeFormat.cs",
        "//src/coreclr/tools/Common:Internal/NativeFormat/NativeFormatReader.Primitives.cs",
        "//src/coreclr/tools/Common:Internal/NativeFormat/NativeFormatReader.String.cs",
        "//src/coreclr/tools/Common:Internal/NativeFormat/NativeFormatReader.cs",
        "//src/coreclr/tools/Common:Internal/NativeFormat/NativeFormatWriter.Primitives.cs",
        "//src/coreclr/tools/Common:Internal/NativeFormat/NativeFormatWriter.cs",
        "//src/coreclr/tools/Common:Internal/NativeFormat/NativeFormatWriterExtensions.cs",
    ],
    defines = ["NATIVEFORMAT_PUBLICWRITER"],
    allow_unsafe_blocks = True,
    analyzers = [
        "//:source_build_analyzers",
        "//src/tools/illink/src/ILLink.RoslynAnalyzer",
    ],
    deps = [
        "//src/coreclr/tools/aot/ILCompiler.TypeSystem",
        "@paket.main//microsoft.diasymreader",
    ],
    target_frameworks = ["net10.0"],
    visibility = ["//visibility:public"],
)
