load("//src/tests:live_test.bzl", "library_test")
load("//:defs.bzl", "OPEN_SNK")

library_test(
    name = "System.Security.Cryptography.Csp.Tests",
    srcs = glob(
        ["**/*.cs"],
        exclude = [
            "TrimmingTests/**",
            # Not in csproj explicit compile list (EnableDefaultItems=false)
            "TestData.cs",
        ],
    ) + [
        "//src/libraries/Common/tests:System/Security/Cryptography/SignatureSupport.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/ByteUtils.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/CryptoUtils.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/PlatformSupport.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/CngKeyWrapper.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AsymmetricSignatureFormatter.cs",
        "//src/libraries/Common/tests:System/IO/PositionValueStream.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/RSA/EncryptDecrypt.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/RSA/ImportExport.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/RSA/KeyGeneration.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/RSA/RSAFactory.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/RSA/RSAFactoryTests.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/RSA/RSATestHelpers.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/RSA/SignVerify.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/RSA/TestData.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/RSA/EncryptDecrypt.netcoreapp.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/RSA/RSAKeyExchangeFormatter.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/RSA/RSASignatureFormatter.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/RSA/RSAXml.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/RSA/RSAKeyFileTests.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/RSA/RSAKeyPemTests.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/RSA/SignVerify.netcoreapp.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/DES/DESCipherTests.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/DES/DESFactory.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/DES/DesTests.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/DSA/DSAFactory.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/DSA/DSAFactoryTests.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/DSA/DsaFamilySignatureFormatTests.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/DSA/DSAImportExport.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/DSA/DSAKeyFileTests.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/DSA/DSAKeyPemTests.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/DSA/DSAKeyGeneration.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/DSA/DSASignatureFormatter.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/DSA/DSASignatureFormatTests.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/DSA/DSASignVerify.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/DSA/DSATestData.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/DSA/DSAXml.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/RC2/RC2CipherTests.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/RC2/RC2Factory.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/RC2/RC2Tests.cs",
    ],
    deps = [
        "//src/libraries/System.Security.Cryptography:ref_System.Security.Cryptography",
        "//src/libraries/System.Runtime.Numerics:ref_System.Runtime.Numerics",
        "//src/libraries/System.Xml.ReaderWriter:ref_System.Xml.ReaderWriter",
        "//src/libraries/System.Xml.XDocument:ref_System.Xml.XDocument",
        "//src/libraries/System.Formats.Asn1:ref_System.Formats.Asn1",
        "//src/libraries/System.Collections.Concurrent:ref_System.Collections.Concurrent",
        "//src/libraries/System.Collections.Immutable:ref_System.Collections.Immutable",
        "//src/libraries/System.Text.Encoding.Extensions:ref_System.Text.Encoding.Extensions",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/Common/tests:TestUtilities",
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//microsoft.dotnet.xunitextensions",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    nowarn = ["SYSLIB0021"],
    os_targeted = "unix",
    keyfile = OPEN_SNK,
    size = "large",
)
