load("//src/tests:live_test.bzl", "library_test")
load("//:defs.bzl", "OPEN_SNK")

library_test(
    name = "System.Xml.Linq.Streaming.Tests",
    srcs = glob(["*.cs"]),
    deps = [
        "//src/libraries/System.Xml.XDocument:ref_System.Xml.XDocument",
        "//src/libraries/System.Xml.ReaderWriter:ref_System.Xml.ReaderWriter",
        "//src/libraries/Common/tests:XmlCoreTest",
        "//src/libraries/Common/tests:XmlDiff",
        "//src/libraries/System.Private.Xml.Linq/tests:XDocument.Common",
        "//src/libraries/shims/netstandard:impl_netstandard",
        "//src/libraries/Common/tests:TestUtilities",
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//microsoft.dotnet.xunitextensions",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    keyfile = OPEN_SNK,
)
