load("@rules_dotnet//dotnet:defs.bzl", "csharp_library")
load("//src/roslyn:defs.bzl", "ROSLYN_KEYFILE", "ROSLYN_PUBLIC_KEY", "roslyn_assembly_info")

roslyn_assembly_info(name = "assembly_info")

csharp_library(
    name = "Roslyn.Test.PdbUtilities",
    srcs = glob(["**/*.cs"]) + [":assembly_info"],
    out = "Roslyn.Test.PdbUtilities",
    deps = [
        "//src/roslyn/src/Compilers/Core/Portable:Microsoft.CodeAnalysis",
        "//src/roslyn/src/Compilers/Test/Core:Microsoft.CodeAnalysis.Test.Utilities",
        "@paket.main//microsoft.diasymreader",
        "@paket.main//microsoft.diasymreader.portablepdb",
        "@paket.main//microsoft.diasymreader.converter",
        "@paket.main//microsoft.diasymreader.converter.xml",
        "@paket.main//microsoft.metadata.visualizer",
        "@paket.main//xunit.assert",
    ],
    allow_unsafe_blocks = True,
    nullable = "enable",
    langversion = "preview",
    keyfile = ROSLYN_KEYFILE,
    compiler_options = ["/publicsign"],
    target_frameworks = ["net10.0"],
    internals_visible_to = [
        "Microsoft.CodeAnalysis.CSharp.Test.Utilities, PublicKey=" + ROSLYN_PUBLIC_KEY,
        "Microsoft.CodeAnalysis.CSharp.Syntax.UnitTests, PublicKey=" + ROSLYN_PUBLIC_KEY,
        "Microsoft.CodeAnalysis.CSharp.Symbol.UnitTests, PublicKey=" + ROSLYN_PUBLIC_KEY,
        "Microsoft.CodeAnalysis.CSharp.Semantic.UnitTests, PublicKey=" + ROSLYN_PUBLIC_KEY,
        "Microsoft.CodeAnalysis.CSharp.Emit.UnitTests, PublicKey=" + ROSLYN_PUBLIC_KEY,
        "Microsoft.CodeAnalysis.CSharp.Emit2.UnitTests, PublicKey=" + ROSLYN_PUBLIC_KEY,
        "Microsoft.CodeAnalysis.CSharp.Emit3.UnitTests, PublicKey=" + ROSLYN_PUBLIC_KEY,
        "Microsoft.CodeAnalysis.CSharp.CommandLine.UnitTests, PublicKey=" + ROSLYN_PUBLIC_KEY,
        "Microsoft.CodeAnalysis.CSharp.EndToEnd.UnitTests, PublicKey=" + ROSLYN_PUBLIC_KEY,
        "Microsoft.CodeAnalysis.CSharp.WinRT.UnitTests, PublicKey=" + ROSLYN_PUBLIC_KEY,
        "Microsoft.CodeAnalysis.UnitTests, PublicKey=" + ROSLYN_PUBLIC_KEY,
    ],
    visibility = ["//src/roslyn:__subpackages__"],
)
