load("//src/tests:live_test.bzl", "coreclr_test")

coreclr_test(
    name = "Avx10v1_Vector128_handwritten_r",
    srcs = [
        "//src/tests/JIT/HardwareIntrinsics/X86/Shared:SimpleUnOpTest_DataTable.cs",
        "Avx10v1AbsTest.cs",
    ],
)

coreclr_test(
    name = "Avx10v1_Vector128_handwritten_ro",
    srcs = [
        "//src/tests/JIT/HardwareIntrinsics/X86/Shared:SimpleUnOpTest_DataTable.cs",
        "Avx10v1AbsTest.cs",
    ],
    optimize = True,
)

coreclr_test(
    name = "Avx10v1_Vector128_r",
    srcs = [
        "Program.Avx10v1_Vector128.cs",
        "//src/tests/JIT/HardwareIntrinsics/X86/Shared:Program.cs",
    ],
)

coreclr_test(
    name = "Avx10v1_Vector128_ro",
    srcs = [
        "Program.Avx10v1_Vector128.cs",
        "//src/tests/JIT/HardwareIntrinsics/X86/Shared:Program.cs",
    ],
    optimize = True,
)
