load("//src/libraries:defs.bzl", "netcoreapp_impl_assembly")

netcoreapp_impl_assembly(
    name = "impl_System.Runtime.Serialization",
    skip_cs1591 = True,
    srcs = [
        "src/System.Runtime.Serialization.cs",
    ],
    deps = [
        "//src/libraries/System.Runtime.Serialization.Json:ref_System.Runtime.Serialization.Json",
        "//src/libraries/System.Runtime.Serialization.Primitives:ref_System.Runtime.Serialization.Primitives",
        "//src/libraries/System.Runtime.Serialization.Xml:ref_System.Runtime.Serialization.Xml",
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/shims/stubs:ref_System.Runtime.Serialization.Schema",
    ],
    os_targeted = True,
    exclude_sr = True,
    assembly_version = "4.0.0.0",
)
