load("//src/tests:live_test.bzl", "coreclr_test")

coreclr_test(
    name = "Sse41.X64_r",
    srcs = [
        "Program.Sse41.X64.cs",
        "//src/tests/JIT/HardwareIntrinsics/X86/Shared:Program.cs",
    ],
    tags = ["manual"],  # Needs additional deps not yet available
)

coreclr_test(
    name = "Sse41.X64_ro",
    srcs = [
        "Program.Sse41.X64.cs",
        "//src/tests/JIT/HardwareIntrinsics/X86/Shared:Program.cs",
    ],
    optimize = True,
    tags = ["manual"],  # Needs additional deps not yet available
)
