load("//src/tests:live_test.bzl", "il_coreclr_test")

il_coreclr_test(
    name = "b14067b",
    srcs = ["b14067b.il"],
    pri = 1,
    debug_type = "pdbonly",
    optimize = True,
)

il_coreclr_test(
    name = "b14067a",
    srcs = ["b14067a.il"],
    pri = 1,
    debug_type = "pdbonly",
    optimize = True,
)
