load("//src/libraries:defs.bzl", "netcoreapp_impl_assembly")
load("//:defs.bzl", "SHAREDLIB1024_SNK")

netcoreapp_impl_assembly(
    name = "impl_WindowsBase",
    library_import_generator = False,
    skip_locals_init = False,
    srcs = [
        "src/WindowsBase.cs",
    ],
    deps = [
        "//src/libraries/System.ObjectModel:ref_System.ObjectModel",
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/shims/stubs:ref_System.IO.Packaging",
        "//src/libraries/shims/stubs:ref_System.Security.Permissions",
    ],
    keyfile = SHAREDLIB1024_SNK,
    generate_documentation_file = False,
    os_targeted = True,
    exclude_sr = True,
    assembly_version = "4.0.0.0",
)
