load("//src/tests:live_test.bzl", "coreclr_merged_test")

coreclr_merged_test(
    name = "JIT.performance",
    deps = [
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    test_deps = [
        "//src/tests/JIT/Performance/CodeQuality/BenchmarksGame/binarytrees:binarytrees-2",
        "//src/tests/JIT/Performance/CodeQuality/BenchmarksGame/binarytrees:binarytrees-5",
        "//src/tests/JIT/Performance/CodeQuality/BenchmarksGame/binarytrees:binarytrees-6",
        "//src/tests/JIT/Performance/CodeQuality/BenchmarksGame/fannkuch-redux:fannkuch-redux-2",
        "//src/tests/JIT/Performance/CodeQuality/BenchmarksGame/fannkuch-redux:fannkuch-redux-5",
        "//src/tests/JIT/Performance/CodeQuality/BenchmarksGame/fannkuch-redux:fannkuch-redux-9",
        "//src/tests/JIT/Performance/CodeQuality/BenchmarksGame/fasta:fasta-1",
        "//src/tests/JIT/Performance/CodeQuality/BenchmarksGame/fasta:fasta-2",
        "//src/tests/JIT/Performance/CodeQuality/BenchmarksGame/mandelbrot:mandelbrot-2",
        "//src/tests/JIT/Performance/CodeQuality/BenchmarksGame/mandelbrot:mandelbrot-7",
        "//src/tests/JIT/Performance/CodeQuality/BenchmarksGame/n-body:n-body-3",
        "//src/tests/JIT/Performance/CodeQuality/BenchmarksGame/pidigits:pidigits-3",
        "//src/tests/JIT/Performance/CodeQuality/BenchmarksGame/spectralnorm:spectralnorm-1",
        "//src/tests/JIT/Performance/CodeQuality/BenchmarksGame/spectralnorm:spectralnorm-3",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/BenchF/Adams:Adams",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/BenchF/BenchMk2:BenchMk2",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/BenchF/BenchMrk:BenchMrk",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/BenchF/Bisect:Bisect",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/BenchF/DMath:DMath",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/BenchF/FFT:FFT",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/BenchF/InProd:InProd",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/BenchF/InvMt:InvMt",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/BenchF/LLoops:LLoops",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/BenchF/Lorenz:Lorenz",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/BenchF/MatInv4:MatInv4",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/BenchF/NewtE:NewtE",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/BenchF/NewtR:NewtR",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/BenchF/Regula:Regula",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/BenchF/Romber:Romber",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/BenchF/Secant:Secant",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/BenchF/Simpsn:Simpsn",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/BenchF/SqMtx:SqMtx",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/BenchF/Trap:Trap",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/BenchF/Whetsto:Whetsto",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/BenchI/8Queens:8Queens",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/BenchI/Ackermann:Ackermann",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/BenchI/AddArray:AddArray",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/BenchI/AddArray2:AddArray2",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/BenchI/Array1:Array1",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/BenchI/Array2:Array2",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/BenchI/BenchE:BenchE",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/BenchI/BubbleSort:BubbleSort",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/BenchI/BubbleSort2:BubbleSort2",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/BenchI/CSieve:CSieve",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/BenchI/Fib:Fib",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/BenchI/HeapSort:HeapSort",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/BenchI/IniArray:IniArray",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/BenchI/LogicArray:LogicArray",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/BenchI/Midpoint:Midpoint",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/BenchI/MulMatrix:MulMatrix",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/BenchI/NDhrystone:NDhrystone",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/BenchI/Permutate:Permutate",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/BenchI/Pi:Pi",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/BenchI/Puzzle:Puzzle",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/BenchI/QuickSort:QuickSort",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/BenchI/TreeInsert:TreeInsert",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/BenchI/TreeSort:TreeSort",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/BenchI/XposMatrix:XposMatrix",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/MDBenchF/MDInProd:MDInProd",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/MDBenchF/MDInvMt:MDInvMt",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/MDBenchF/MDLLoops:MDLLoops",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/MDBenchF/MDRomber:MDRomber",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/MDBenchF/MDSqMtx:MDSqMtx",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/MDBenchI/MDAddArray2:MDAddArray2",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/MDBenchI/MDArray2:MDArray2",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/MDBenchI/MDLogicArray:MDLogicArray",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/MDBenchI/MDMidpoint:MDMidpoint",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/MDBenchI/MDMulMatrix:MDMulMatrix",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/MDBenchI/MDNDhrystone:MDNDhrystone",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/MDBenchI/MDPuzzle:MDPuzzle",
        "//src/tests/JIT/Performance/CodeQuality/Benchstones/MDBenchI/MDXposMatrix:MDXposMatrix",
        "//src/tests/JIT/Performance/CodeQuality/BilinearInterpol:BilinearInterpol",
        "//src/tests/JIT/Performance/CodeQuality/Burgers:Burgers",
        "//src/tests/JIT/Performance/CodeQuality/Bytemark:Bytemark",
        "//src/tests/JIT/Performance/CodeQuality/Devirtualization:DefaultEqualityComparerPerf",
        "//src/tests/JIT/Performance/CodeQuality/FractalPerf:FractalPerf",
        "//src/tests/JIT/Performance/CodeQuality/HWIntrinsic/X86/PacketTracer:PacketTracer",
        "//src/tests/JIT/Performance/CodeQuality/Inlining:InlineGCStruct",
        "//src/tests/JIT/Performance/CodeQuality/Inlining:NoThrowInline",
        "//src/tests/JIT/Performance/CodeQuality/Layout:SearchLoops",
        "//src/tests/JIT/Performance/CodeQuality/Linq:Linq",
        "//src/tests/JIT/Performance/CodeQuality/Math/Functions:Functions",
        "//src/tests/JIT/Performance/CodeQuality/SIMD/ConsoleMandel:ConsoleMandel",
        "//src/tests/JIT/Performance/CodeQuality/SIMD/RayTracer:RayTracer",
        "//src/tests/JIT/Performance/CodeQuality/SIMD/SeekUnroll:SeekUnroll",
        "//src/tests/JIT/Performance/CodeQuality/SciMark:SciMark",
        "//src/tests/JIT/Performance/CodeQuality/Span:Indexer",
        "//src/tests/JIT/Performance/CodeQuality/Span:SpanBench",
        "//src/tests/JIT/Performance/CodeQuality/V8/Crypto:Crypto",
        "//src/tests/JIT/Performance/CodeQuality/V8/Richards:Richards",
    ],
)
