load("//src/tests:live_test.bzl", "coreclr_merged_test")

coreclr_merged_test(
    name = "jit64_2",
    deps = [
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    test_deps = [
    ],
)

coreclr_merged_test(
    name = "jit64_5",
    deps = [
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    test_deps = [
        "//src/tests/JIT/jit64/ebvts/cs/generics/generics:repro52",
        "//src/tests/JIT/jit64/eh/basics:loopEH",
        "//src/tests/JIT/jit64/gc/misc:148343",
        "//src/tests/JIT/jit64/gc/misc:9_and_alloca2",
        "//src/tests/JIT/jit64/gc/misc:9param",
        "//src/tests/JIT/jit64/gc/misc:alloca3",
        "//src/tests/JIT/jit64/gc/misc:eh1",
        "//src/tests/JIT/jit64/gc/misc:fgtest1",
        "//src/tests/JIT/jit64/gc/misc:fgtest2",
        "//src/tests/JIT/jit64/gc/misc:gc-pinned-code-motion",
        "//src/tests/JIT/jit64/gc/misc:gcparaminreg",
        "//src/tests/JIT/jit64/gc/misc:ret_struct_test1",
        "//src/tests/JIT/jit64/gc/misc:ret_struct_test4",
        "//src/tests/JIT/jit64/gc/misc:simple1",
        "//src/tests/JIT/jit64/gc/misc:struct1",
        "//src/tests/JIT/jit64/gc/misc:struct1_2",
        "//src/tests/JIT/jit64/gc/misc:struct1_4",
        "//src/tests/JIT/jit64/gc/misc:struct1_5",
        "//src/tests/JIT/jit64/gc/misc:struct2",
        "//src/tests/JIT/jit64/gc/misc:struct2_2",
        "//src/tests/JIT/jit64/gc/misc:struct2_4",
        "//src/tests/JIT/jit64/gc/misc:struct2_5",
        "//src/tests/JIT/jit64/gc/misc:struct2_5_2",
        "//src/tests/JIT/jit64/gc/misc:struct3",
        "//src/tests/JIT/jit64/gc/misc:struct3_2",
        "//src/tests/JIT/jit64/gc/misc:struct3_4",
        "//src/tests/JIT/jit64/gc/misc:struct3_5",
        "//src/tests/JIT/jit64/gc/misc:struct4",
        "//src/tests/JIT/jit64/gc/misc:struct4_2",
        "//src/tests/JIT/jit64/gc/misc:struct4_4",
        "//src/tests/JIT/jit64/gc/misc:struct4_5",
        "//src/tests/JIT/jit64/gc/misc:struct5",
        "//src/tests/JIT/jit64/gc/misc:struct5_2",
        "//src/tests/JIT/jit64/gc/misc:struct5_4",
        "//src/tests/JIT/jit64/gc/misc:struct5_5",
        "//src/tests/JIT/jit64/gc/misc:struct6",
        "//src/tests/JIT/jit64/gc/misc:struct6_2",
        "//src/tests/JIT/jit64/gc/misc:struct6_4",
        "//src/tests/JIT/jit64/gc/misc:struct6_5",
        "//src/tests/JIT/jit64/gc/misc:struct7_1",
        "//src/tests/JIT/jit64/gc/misc:struct8",
        "//src/tests/JIT/jit64/gc/misc:struct9",
        "//src/tests/JIT/jit64/gc/misc:struct9_2",
        "//src/tests/JIT/jit64/gc/misc:structfp1_1",
        "//src/tests/JIT/jit64/gc/misc:structfp1_2",
        "//src/tests/JIT/jit64/gc/misc:structfp1_3",
        "//src/tests/JIT/jit64/gc/misc:structfp1_4",
        "//src/tests/JIT/jit64/gc/misc:structfp1_5",
        "//src/tests/JIT/jit64/gc/misc:structfp1_6",
        "//src/tests/JIT/jit64/gc/misc:structfp2_1",
        "//src/tests/JIT/jit64/gc/misc:structfp2_2",
        "//src/tests/JIT/jit64/gc/misc:structfp2_3",
        "//src/tests/JIT/jit64/gc/misc:structfp2_4",
        "//src/tests/JIT/jit64/gc/misc:structfp3_1",
        "//src/tests/JIT/jit64/gc/misc:structfp4_1",
        "//src/tests/JIT/jit64/gc/misc:structfp5_1",
        "//src/tests/JIT/jit64/gc/misc:structfp6_1",
        "//src/tests/JIT/jit64/gc/misc:structfpseh5_1",
        "//src/tests/JIT/jit64/gc/misc:structfpseh6_1",
        "//src/tests/JIT/jit64/gc/misc:structref1_1",
        "//src/tests/JIT/jit64/gc/misc:structret1_1",
        "//src/tests/JIT/jit64/gc/misc:structret1_2",
        "//src/tests/JIT/jit64/gc/misc:structret1_3",
        "//src/tests/JIT/jit64/gc/misc:structret2_1",
        "//src/tests/JIT/jit64/gc/misc:structret2_2",
        "//src/tests/JIT/jit64/gc/misc:structret2_3",
        "//src/tests/JIT/jit64/gc/misc:structret3_1",
        "//src/tests/JIT/jit64/gc/misc:structret3_2",
        "//src/tests/JIT/jit64/gc/misc:structret3_3",
        "//src/tests/JIT/jit64/gc/misc:structret4_1",
        "//src/tests/JIT/jit64/gc/misc:structret4_2",
        "//src/tests/JIT/jit64/gc/misc:structret4_3",
        "//src/tests/JIT/jit64/gc/misc:structret5_1",
        "//src/tests/JIT/jit64/gc/misc:structret5_2",
        "//src/tests/JIT/jit64/gc/misc:structret5_3",
        "//src/tests/JIT/jit64/gc/misc:structret6_1",
        "//src/tests/JIT/jit64/gc/misc:structret6_2",
        "//src/tests/JIT/jit64/gc/misc:structret6_3",
        "//src/tests/JIT/jit64/gc/misc:structva1_1",
        "//src/tests/JIT/jit64/gc/misc:test1_misc",
        "//src/tests/JIT/jit64/gc/misc:test2_misc",
        "//src/tests/JIT/jit64/gc/misc:test3",
        "//src/tests/JIT/jit64/gc/misc:test_noalloca",
        "//src/tests/JIT/jit64/gc/misc:vbil",
        "//src/tests/JIT/jit64/gc/regress/vswhidbey:143837",
        "//src/tests/JIT/jit64/gc/regress/vswhidbey:339415",
        "//src/tests/JIT/jit64/regress/asurt/143616:foo",
        "//src/tests/JIT/jit64/regress/ddb/103087:103087",
        "//src/tests/JIT/jit64/regress/ddb/113574:113574",
        "//src/tests/JIT/jit64/regress/ddb/132977:132977",
        "//src/tests/JIT/jit64/regress/ddb/87766:ddb87766",
        "//src/tests/JIT/jit64/regress/ndpw/14888:objectusedonlyinhandler",
        "//src/tests/JIT/jit64/regress/ndpw/160545:simple",
        "//src/tests/JIT/jit64/regress/ndpw/21015:interior_pointer",
        "//src/tests/JIT/jit64/regress/vsw/102964:test_102964",
        "//src/tests/JIT/jit64/regress/vsw/329169:test_329169",
        "//src/tests/JIT/jit64/regress/vsw/373472:test_373472",
        "//src/tests/JIT/jit64/regress/vsw/471729:test_471729",
        "//src/tests/JIT/jit64/regress/vsw/517867:test_517867",
        "//src/tests/JIT/jit64/regress/vsw/524070:test1_524070",
        "//src/tests/JIT/jit64/regress/vsw/524070:test2_524070",
        "//src/tests/JIT/jit64/regress/vsw/528315:simple-repro",
        "//src/tests/JIT/jit64/regress/vsw/538615:test1_538615",
        "//src/tests/JIT/jit64/regress/vsw/539509:test1_539509",
        "//src/tests/JIT/jit64/regress/vsw/541067:test1_541067",
        "//src/tests/JIT/jit64/regress/vsw/543229:test_543229",
        "//src/tests/JIT/jit64/regress/vsw/549880:test_549880",
        "//src/tests/JIT/jit64/regress/vsw/560402:opadd",
        "//src/tests/JIT/jit64/regress/vsw/560402:opmul",
        "//src/tests/JIT/jit64/regress/vsw/560402:opsub",
        "//src/tests/JIT/jit64/regress/vsw/601425:stret",
        "//src/tests/JIT/jit64/regress/vsw/610378:vsw610378",
        "//src/tests/JIT/jit64/rtchecks/overflow:overflow01_add",
        "//src/tests/JIT/jit64/rtchecks/overflow:overflow01_div",
        "//src/tests/JIT/jit64/rtchecks/overflow:overflow01_mul",
        "//src/tests/JIT/jit64/rtchecks/overflow:overflow01_sub",
        "//src/tests/JIT/jit64/rtchecks/overflow:overflow02_add",
        "//src/tests/JIT/jit64/rtchecks/overflow:overflow02_div",
        "//src/tests/JIT/jit64/rtchecks/overflow:overflow02_mul",
        "//src/tests/JIT/jit64/rtchecks/overflow:overflow02_sub",
        "//src/tests/JIT/jit64/rtchecks/overflow:overflow03_add",
        "//src/tests/JIT/jit64/rtchecks/overflow:overflow03_div",
        "//src/tests/JIT/jit64/rtchecks/overflow:overflow03_mul",
        "//src/tests/JIT/jit64/rtchecks/overflow:overflow03_sub",
        "//src/tests/JIT/jit64/rtchecks/overflow:overflow04_add",
        "//src/tests/JIT/jit64/rtchecks/overflow:overflow04_div",
        "//src/tests/JIT/jit64/rtchecks/overflow:overflow04_mul",
        "//src/tests/JIT/jit64/rtchecks/overflow:overflow04_sub",
    ],
)

coreclr_merged_test(
    name = "jit64_1",
    deps = [
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    test_deps = [
    ],
)

coreclr_merged_test(
    name = "jit64_3",
    deps = [
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    test_deps = [
        "//src/tests/JIT/jit64/opt/cg/CGRecurse:CGRecurseAAA_d",
        "//src/tests/JIT/jit64/opt/cg/CGRecurse:CGRecurseAAA_do",
        "//src/tests/JIT/jit64/opt/cg/CGRecurse:CGRecurseAAA_r",
        "//src/tests/JIT/jit64/opt/cg/CGRecurse:CGRecurseAAA_ro",
        "//src/tests/JIT/jit64/opt/cg/CGRecurse:CGRecurseAAC_d",
        "//src/tests/JIT/jit64/opt/cg/CGRecurse:CGRecurseAAC_do",
        "//src/tests/JIT/jit64/opt/cg/CGRecurse:CGRecurseAAC_r",
        "//src/tests/JIT/jit64/opt/cg/CGRecurse:CGRecurseAAC_ro",
        "//src/tests/JIT/jit64/opt/cg/CGRecurse:CGRecurseACA_d",
        "//src/tests/JIT/jit64/opt/cg/CGRecurse:CGRecurseACA_do",
        "//src/tests/JIT/jit64/opt/cg/CGRecurse:CGRecurseACA_r",
        "//src/tests/JIT/jit64/opt/cg/CGRecurse:CGRecurseACA_ro",
        "//src/tests/JIT/jit64/opt/cg/CGRecurse:CGRecurseACC_d",
        "//src/tests/JIT/jit64/opt/cg/CGRecurse:CGRecurseACC_do",
        "//src/tests/JIT/jit64/opt/cg/CGRecurse:CGRecurseACC_r",
        "//src/tests/JIT/jit64/opt/cg/CGRecurse:CGRecurseACC_ro",
        "//src/tests/JIT/jit64/opt/cg/cgstress:CgStress1_d",
        "//src/tests/JIT/jit64/opt/cg/cgstress:CgStress1_do",
        "//src/tests/JIT/jit64/opt/cg/cgstress:CgStress1_r",
        "//src/tests/JIT/jit64/opt/cg/cgstress:CgStress1_ro",
        "//src/tests/JIT/jit64/opt/cg/cgstress:CgStress2_d",
        "//src/tests/JIT/jit64/opt/cg/cgstress:CgStress2_do",
        "//src/tests/JIT/jit64/opt/cg/cgstress:CgStress2_r",
        "//src/tests/JIT/jit64/opt/cg/cgstress:CgStress2_ro",
        "//src/tests/JIT/jit64/opt/cg/cgstress:CgStress3_d",
        "//src/tests/JIT/jit64/opt/cg/cgstress:CgStress3_do",
        "//src/tests/JIT/jit64/opt/cg/cgstress:CgStress3_r",
        "//src/tests/JIT/jit64/opt/cg/cgstress:CgStress3_ro",
        "//src/tests/JIT/jit64/opt/cprop:cprop001_d",
        "//src/tests/JIT/jit64/opt/cprop:cprop001_do",
        "//src/tests/JIT/jit64/opt/cprop:cprop001_r",
        "//src/tests/JIT/jit64/opt/cprop:cprop001_ro",
        "//src/tests/JIT/jit64/opt/cprop:implicitDownConv",
        "//src/tests/JIT/jit64/opt/cse:HugeArray",
        "//src/tests/JIT/jit64/opt/cse:HugeArray1",
        "//src/tests/JIT/jit64/opt/cse:HugeField1",
        "//src/tests/JIT/jit64/opt/cse:HugeField2",
        "//src/tests/JIT/jit64/opt/cse:VolatileTest_op_add",
        "//src/tests/JIT/jit64/opt/cse:VolatileTest_op_and",
        "//src/tests/JIT/jit64/opt/cse:VolatileTest_op_div",
        "//src/tests/JIT/jit64/opt/cse:VolatileTest_op_mod",
        "//src/tests/JIT/jit64/opt/cse:VolatileTest_op_mul",
        "//src/tests/JIT/jit64/opt/cse:VolatileTest_op_or",
        "//src/tests/JIT/jit64/opt/cse:VolatileTest_op_shr",
        "//src/tests/JIT/jit64/opt/cse:VolatileTest_op_sub",
        "//src/tests/JIT/jit64/opt/cse:VolatileTest_op_xor",
        "//src/tests/JIT/jit64/opt/cse:arrayexpr1",
        "//src/tests/JIT/jit64/opt/cse:arrayexpr2_d_loop_try",
        "//src/tests/JIT/jit64/opt/cse:arrayexpr2_r",
        "//src/tests/JIT/jit64/opt/cse:arrayexpr2_r_loop",
        "//src/tests/JIT/jit64/opt/cse:arrayexpr2_r_loop_try",
        "//src/tests/JIT/jit64/opt/cse:arrayexpr2_r_try",
        "//src/tests/JIT/jit64/opt/cse:arrayexpr2_ro_loop",
        "//src/tests/JIT/jit64/opt/cse:fieldExprUnchecked1",
        "//src/tests/JIT/jit64/opt/cse:fieldexpr1",
        "//src/tests/JIT/jit64/opt/cse:fieldexpr1_1",
        "//src/tests/JIT/jit64/opt/cse:fieldexpr2",
        "//src/tests/JIT/jit64/opt/cse:hugeSimpleExpr1",
        "//src/tests/JIT/jit64/opt/cse:hugeexpr1",
        "//src/tests/JIT/jit64/opt/cse:mixedexpr1_d_loop_try",
        "//src/tests/JIT/jit64/opt/cse:mixedexpr1_r",
        "//src/tests/JIT/jit64/opt/cse:mixedexpr1_r_loop",
        "//src/tests/JIT/jit64/opt/cse:mixedexpr1_r_loop_try",
        "//src/tests/JIT/jit64/opt/cse:mixedexpr1_r_try",
        "//src/tests/JIT/jit64/opt/cse:mixedexpr1_ro_loop",
        "//src/tests/JIT/jit64/opt/cse:pointerexpr1",
        "//src/tests/JIT/jit64/opt/cse:pointerexpr1_1",
        "//src/tests/JIT/jit64/opt/cse:simpleexpr1",
        "//src/tests/JIT/jit64/opt/cse:simpleexpr1_1",
        "//src/tests/JIT/jit64/opt/cse:simpleexpr2",
        "//src/tests/JIT/jit64/opt/cse:simpleexpr3",
        "//src/tests/JIT/jit64/opt/cse:simpleexpr4_d_loop_try",
        "//src/tests/JIT/jit64/opt/cse:simpleexpr4_r",
        "//src/tests/JIT/jit64/opt/cse:simpleexpr4_r_loop",
        "//src/tests/JIT/jit64/opt/cse:simpleexpr4_r_loop_try",
        "//src/tests/JIT/jit64/opt/cse:simpleexpr4_r_try",
        "//src/tests/JIT/jit64/opt/cse:simpleexpr4_ro_loop",
        "//src/tests/JIT/jit64/opt/cse:staticFieldExpr1_1",
        "//src/tests/JIT/jit64/opt/cse:staticFieldExpr1_d_loop_try",
        "//src/tests/JIT/jit64/opt/cse:staticFieldExpr1_r",
        "//src/tests/JIT/jit64/opt/cse:staticFieldExpr1_r_loop",
        "//src/tests/JIT/jit64/opt/cse:staticFieldExpr1_r_loop_try",
        "//src/tests/JIT/jit64/opt/cse:staticFieldExpr1_r_try",
        "//src/tests/JIT/jit64/opt/cse:staticFieldExpr1_ro_loop",
        "//src/tests/JIT/jit64/opt/cse:staticFieldExprUnchecked1_d_loop_try",
        "//src/tests/JIT/jit64/opt/cse:staticFieldExprUnchecked1_r",
        "//src/tests/JIT/jit64/opt/cse:staticFieldExprUnchecked1_r_loop",
        "//src/tests/JIT/jit64/opt/cse:staticFieldExprUnchecked1_r_loop_try",
        "//src/tests/JIT/jit64/opt/cse:staticFieldExprUnchecked1_r_try",
        "//src/tests/JIT/jit64/opt/cse:staticFieldExprUnchecked1_ro_loop",
        "//src/tests/JIT/jit64/opt/cse:volatilefield",
        "//src/tests/JIT/jit64/opt/cse:volatilestaticfield",
        "//src/tests/JIT/jit64/opt/inl:caninline_d",
        "//src/tests/JIT/jit64/opt/inl:caninline_do",
        "//src/tests/JIT/jit64/opt/inl:caninline_r",
        "//src/tests/JIT/jit64/opt/inl:caninline_ro",
        "//src/tests/JIT/jit64/opt/lim:lim_002",
        "//src/tests/JIT/jit64/opt/lur:lur_02",
        "//src/tests/JIT/jit64/opt/osr:osr001",
        "//src/tests/JIT/jit64/opt/regress/vswhidbey/193825:193825_udo",
        "//src/tests/JIT/jit64/opt/regress/vswhidbey/193825:193825_uro",
        "//src/tests/JIT/jit64/opt/rngchk:ArrayBound_o",
        "//src/tests/JIT/jit64/opt/rngchk:ArrayWith2Loops_o",
        "//src/tests/JIT/jit64/opt/rngchk:ArrayWithFunc_o",
        "//src/tests/JIT/jit64/opt/rngchk:ArrayWithThread_o",
        "//src/tests/JIT/jit64/opt/rngchk:BadMatrixMul_o",
        "//src/tests/JIT/jit64/opt/rngchk:JaggedArray_o",
        "//src/tests/JIT/jit64/opt/rngchk:MatrixMul_o",
        "//src/tests/JIT/jit64/opt/rngchk:RngchkStress1_o",
        "//src/tests/JIT/jit64/opt/rngchk:RngchkStress2_o",
        "//src/tests/JIT/jit64/opt/rngchk:RngchkStress3",
        "//src/tests/JIT/jit64/opt/rngchk:SimpleArray_01_o",
    ],
)

coreclr_merged_test(
    name = "jit64_4",
    deps = [
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    test_deps = [
    ],
)
