load("//src/tests:live_test.bzl", "coreclr_test")

coreclr_test(
    name = "DevDiv_876169_d",
    srcs = ["DevDiv_876169.cs"],
    pri = 1,
    debug_type = "full",
    optimize = False,
    size = "medium",
)

coreclr_test(
    name = "DevDiv_876169_r",
    srcs = ["DevDiv_876169.cs"],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "DevDiv_876169_do",
    srcs = ["DevDiv_876169.cs"],
    pri = 1,
    debug_type = "full",
    optimize = True,
    size = "medium",
)

coreclr_test(
    name = "DevDiv_876169_ro",
    srcs = ["DevDiv_876169.cs"],
    pri = 1,
    optimize = True,
    size = "medium",
)
