load("//src/tests:live_test.bzl", "coreclr_test")

coreclr_test(
    name = "DevDiv_911875_r",
    srcs = ["DevDiv_911875.cs"],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "DevDiv_911875_ro",
    srcs = ["DevDiv_911875.cs"],
    pri = 1,
    optimize = True,
    size = "medium",
)

coreclr_test(
    name = "DevDiv_911875_do",
    srcs = ["DevDiv_911875.cs"],
    pri = 1,
    debug_type = "full",
    optimize = True,
    size = "medium",
)

coreclr_test(
    name = "DevDiv_911875_d",
    srcs = ["DevDiv_911875.cs"],
    pri = 1,
    debug_type = "full",
    optimize = False,
    size = "medium",
)
