load("//src/libraries:defs.bzl", "netcoreapp_impl_assembly")

netcoreapp_impl_assembly(
    name = "impl_System.ComponentModel.DataAnnotations",
    srcs = [
        "src/System.ComponentModel.DataAnnotations.cs",
    ],
    deps = [
        "//src/libraries/System.ComponentModel.Annotations:ref_System.ComponentModel.Annotations",
        "//src/libraries:ref_System.Runtime",
    ],
    exclude_sr = True,
)
