load("//src/libraries:defs.bzl", "netcoreapp_ref_assembly", "netcoreapp_impl_assembly")

exports_files(glob(["src/**/*.cs"]))

netcoreapp_ref_assembly(
    name = "ref_System.Net.NetworkInformation",
    srcs = [
        "ref/System.Net.NetworkInformation.cs",
    ],
    deps = [
        "//src/libraries:ref_Microsoft.Win32.Primitives",
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Net.Primitives:ref_System.Net.Primitives",
    ],
)

netcoreapp_impl_assembly(
    name = "impl_System.Net.NetworkInformation",
    os_targeted = True,
    analyzers = [
        "//src/libraries/System.Runtime.InteropServices:LibraryImportGenerator",
        "//src/libraries/System.Runtime.InteropServices:Microsoft.Interop.SourceGeneration",
    ],
    srcs = glob(
        ["src/System/**/*.cs"],
        exclude = [
            # Windows
            "src/System/Net/NetworkInformation/IPGlobalPropertiesPal.Windows.cs",
            "src/System/Net/NetworkInformation/NetworkAddressChange.Windows.cs",
            "src/System/Net/NetworkInformation/NetworkInterfacePal.Windows.cs",
            "src/System/Net/NetworkInformation/SafeCancelMibChangeNotify.cs",
            "src/System/Net/NetworkInformation/SafeFreeMibTable.cs",
            "src/System/Net/NetworkInformation/SystemGatewayIPAddressInformation.cs",
            "src/System/Net/NetworkInformation/SystemIcmpV4Statistics.cs",
            "src/System/Net/NetworkInformation/SystemIcmpV6Statistics.cs",
            "src/System/Net/NetworkInformation/SystemIPAddressInformation.cs",
            "src/System/Net/NetworkInformation/SystemIPGlobalProperties.cs",
            "src/System/Net/NetworkInformation/SystemIPGlobalStatistics.cs",
            "src/System/Net/NetworkInformation/SystemIPInterfaceProperties.cs",
            "src/System/Net/NetworkInformation/SystemIPInterfaceStatistics.cs",
            "src/System/Net/NetworkInformation/SystemIPv4InterfaceProperties.cs",
            "src/System/Net/NetworkInformation/SystemIPv4InterfaceStatistics.cs",
            "src/System/Net/NetworkInformation/SystemIPv6InterfaceProperties.cs",
            "src/System/Net/NetworkInformation/SystemMulticastIPAddressInformation.cs",
            "src/System/Net/NetworkInformation/SystemNetworkInterface.cs",
            "src/System/Net/NetworkInformation/SystemTcpConnection.cs",
            "src/System/Net/NetworkInformation/SystemTcpStatistics.cs",
            "src/System/Net/NetworkInformation/SystemUdpStatistics.cs",
            "src/System/Net/NetworkInformation/SystemUnicastIPAddressInformation.cs",
            "src/System/Net/NetworkInformation/TeredoHelper.cs",
            # Unix
            "src/System/Net/NetworkInformation/IPAddressUtil.cs",
            "src/System/Net/NetworkInformation/NetworkFiles.cs",
            "src/System/Net/NetworkInformation/SimpleGatewayIPAddressInformation.Unix.cs",
            "src/System/Net/NetworkInformation/SimpleTcpConnectionInformation.Unix.cs",
            "src/System/Net/NetworkInformation/StringParsingHelpers.Dns.cs",
            "src/System/Net/NetworkInformation/UnixIPGlobalProperties.cs",
            "src/System/Net/NetworkInformation/UnixIPInterfaceProperties.cs",
            "src/System/Net/NetworkInformation/UnixIPv4InterfaceProperties.cs",
            "src/System/Net/NetworkInformation/UnixIPv6InterfaceProperties.cs",
            "src/System/Net/NetworkInformation/UnixMulticastIPAddressInformation.cs",
            "src/System/Net/NetworkInformation/UnixNetworkInterface.cs",
            "src/System/Net/NetworkInformation/UnixUnicastIPAddressInformation.cs",
            # Linux
            "src/System/Net/NetworkInformation/ExceptionHelper.Linux.cs",
            "src/System/Net/NetworkInformation/IPGlobalPropertiesPal.Linux.cs",
            "src/System/Net/NetworkInformation/LinuxIcmpV4Statistics.cs",
            "src/System/Net/NetworkInformation/LinuxIcmpV6Statistics.cs",
            "src/System/Net/NetworkInformation/LinuxIPAddressInformation.cs",
            "src/System/Net/NetworkInformation/LinuxIPGlobalProperties.cs",
            "src/System/Net/NetworkInformation/LinuxIPGlobalStatistics.cs",
            "src/System/Net/NetworkInformation/LinuxIPInterfaceProperties.cs",
            "src/System/Net/NetworkInformation/LinuxIPInterfaceStatistics.cs",
            "src/System/Net/NetworkInformation/LinuxIPv4InterfaceProperties.cs",
            "src/System/Net/NetworkInformation/LinuxIPv4InterfaceStatistics.cs",
            "src/System/Net/NetworkInformation/LinuxIPv6InterfaceProperties.cs",
            "src/System/Net/NetworkInformation/LinuxNetworkInterface.cs",
            "src/System/Net/NetworkInformation/LinuxTcpStatistics.cs",
            "src/System/Net/NetworkInformation/LinuxUdpStatistics.cs",
            "src/System/Net/NetworkInformation/NetworkInterfacePal.Linux.cs",
            "src/System/Net/NetworkInformation/StringParsingHelpers.Addresses.cs",
            "src/System/Net/NetworkInformation/StringParsingHelpers.Connections.cs",
            "src/System/Net/NetworkInformation/StringParsingHelpers.Misc.cs",
            "src/System/Net/NetworkInformation/StringParsingHelpers.Statistics.cs",
            # Linux + FreeBSD
            "src/System/Net/NetworkInformation/NetworkAddressChange.Unix.cs",
            # Android
            "src/System/Net/NetworkInformation/AndroidIPGlobalProperties.cs",
            "src/System/Net/NetworkInformation/AndroidIPGlobalStatistics.cs",
            "src/System/Net/NetworkInformation/AndroidIPInterfaceProperties.cs",
            "src/System/Net/NetworkInformation/AndroidIPv4InterfaceProperties.cs",
            "src/System/Net/NetworkInformation/AndroidIPv6InterfaceProperties.cs",
            "src/System/Net/NetworkInformation/AndroidNetworkInterface.cs",
            "src/System/Net/NetworkInformation/IPGlobalPropertiesPal.Android.cs",
            "src/System/Net/NetworkInformation/NetworkAddressChange.Android.cs",
            "src/System/Net/NetworkInformation/NetworkInterfacePal.Android.cs",
            # BSD
            "src/System/Net/NetworkInformation/BsdIcmpV4Statistics.cs",
            "src/System/Net/NetworkInformation/BsdIcmpV6Statistics.cs",
            "src/System/Net/NetworkInformation/BsdIPGlobalProperties.cs",
            "src/System/Net/NetworkInformation/BsdIPv4GlobalStatistics.cs",
            "src/System/Net/NetworkInformation/BsdIPv4InterfaceProperties.cs",
            "src/System/Net/NetworkInformation/BsdIPv4InterfaceStatistics.cs",
            "src/System/Net/NetworkInformation/BsdIPv6InterfaceProperties.cs",
            "src/System/Net/NetworkInformation/BsdIpInterfaceProperties.cs",
            "src/System/Net/NetworkInformation/BsdIpInterfaceStatistics.cs",
            "src/System/Net/NetworkInformation/BsdNetworkInterface.cs",
            "src/System/Net/NetworkInformation/BsdTcpStatistics.cs",
            "src/System/Net/NetworkInformation/BsdUdpStatistics.cs",
            "src/System/Net/NetworkInformation/IPGlobalPropertiesPal.Bsd.cs",
            "src/System/Net/NetworkInformation/NetworkInterfacePal.Bsd.cs",
            # OSX
            "src/System/Net/NetworkInformation/NetworkAddressChange.OSX.cs",
            # Unknown Unix
            "src/System/Net/NetworkInformation/IPGlobalPropertiesPal.UnknownUnix.cs",
            "src/System/Net/NetworkInformation/NetworkAddressChange.UnknownUnix.cs",
            "src/System/Net/NetworkInformation/NetworkInterfacePal.UnknownUnix.cs",
            # Not in any csproj compile group
            "src/System/Net/StartIPOptions.cs",
        ],
    ) + [
        # Common sources
        "//src/libraries/Common:src/DisableRuntimeMarshalling.cs",
        "//src/libraries/Common:src/System/NotImplemented.cs",
        "//src/libraries/Common:src/System/Net/NetworkInformation/HostInformation.cs",
        "//src/libraries/Common:src/System/Net/NetworkInformation/NetworkInformationException.cs",
        "//src/libraries/Common:src/System/HexConverter.cs",
        "//src/libraries/Common:src/System/Obsoletions.cs",
    ] + select({
        "@platforms//os:linux": [
            # Unix src files
            "src/System/Net/NetworkInformation/IPAddressUtil.cs",
            "src/System/Net/NetworkInformation/NetworkFiles.cs",
            "src/System/Net/NetworkInformation/SimpleGatewayIPAddressInformation.Unix.cs",
            "src/System/Net/NetworkInformation/SimpleTcpConnectionInformation.Unix.cs",
            "src/System/Net/NetworkInformation/StringParsingHelpers.Dns.cs",
            "src/System/Net/NetworkInformation/UnixIPGlobalProperties.cs",
            "src/System/Net/NetworkInformation/UnixIPInterfaceProperties.cs",
            "src/System/Net/NetworkInformation/UnixIPv4InterfaceProperties.cs",
            "src/System/Net/NetworkInformation/UnixIPv6InterfaceProperties.cs",
            "src/System/Net/NetworkInformation/UnixMulticastIPAddressInformation.cs",
            "src/System/Net/NetworkInformation/UnixNetworkInterface.cs",
            "src/System/Net/NetworkInformation/UnixUnicastIPAddressInformation.cs",
            # Linux src files
            "src/System/Net/NetworkInformation/ExceptionHelper.Linux.cs",
            "src/System/Net/NetworkInformation/IPGlobalPropertiesPal.Linux.cs",
            "src/System/Net/NetworkInformation/LinuxIcmpV4Statistics.cs",
            "src/System/Net/NetworkInformation/LinuxIcmpV6Statistics.cs",
            "src/System/Net/NetworkInformation/LinuxIPAddressInformation.cs",
            "src/System/Net/NetworkInformation/LinuxIPGlobalProperties.cs",
            "src/System/Net/NetworkInformation/LinuxIPGlobalStatistics.cs",
            "src/System/Net/NetworkInformation/LinuxIPInterfaceProperties.cs",
            "src/System/Net/NetworkInformation/LinuxIPInterfaceStatistics.cs",
            "src/System/Net/NetworkInformation/LinuxIPv4InterfaceProperties.cs",
            "src/System/Net/NetworkInformation/LinuxIPv4InterfaceStatistics.cs",
            "src/System/Net/NetworkInformation/LinuxIPv6InterfaceProperties.cs",
            "src/System/Net/NetworkInformation/LinuxNetworkInterface.cs",
            "src/System/Net/NetworkInformation/LinuxTcpStatistics.cs",
            "src/System/Net/NetworkInformation/LinuxUdpStatistics.cs",
            "src/System/Net/NetworkInformation/NetworkInterfacePal.Linux.cs",
            "src/System/Net/NetworkInformation/StringParsingHelpers.Addresses.cs",
            "src/System/Net/NetworkInformation/StringParsingHelpers.Connections.cs",
            "src/System/Net/NetworkInformation/StringParsingHelpers.Misc.cs",
            "src/System/Net/NetworkInformation/StringParsingHelpers.Statistics.cs",
            # Linux + FreeBSD src files
            "src/System/Net/NetworkInformation/NetworkAddressChange.Unix.cs",
            # Unix Common files
            "//src/libraries/Common:src/Interop/Unix/Interop.Libraries.cs",
            "//src/libraries/Common:src/Interop/Unix/Interop.Errors.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.EnumerateInterfaceAddresses.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.GetDomainName.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.GetHostName.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.MapTcpState.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.NetworkChange.cs",
            "//src/libraries/Common:src/System/Net/NetworkInformation/HostInformationPal.Unix.cs",
            "//src/libraries/Common:src/System/IO/RowConfigReader.cs",
            # Linux Common files
            "//src/libraries/Common:src/System/IO/StringParser.cs",
            "//src/libraries/Common:src/Interop/Linux/Interop.LinuxNetDeviceFlags.cs",
        ],
        "@platforms//os:macos": [
            # Unix src files (shared with Linux)
            "src/System/Net/NetworkInformation/IPAddressUtil.cs",
            "src/System/Net/NetworkInformation/NetworkFiles.cs",
            "src/System/Net/NetworkInformation/SimpleGatewayIPAddressInformation.Unix.cs",
            "src/System/Net/NetworkInformation/SimpleTcpConnectionInformation.Unix.cs",
            "src/System/Net/NetworkInformation/StringParsingHelpers.Dns.cs",
            "src/System/Net/NetworkInformation/UnixIPGlobalProperties.cs",
            "src/System/Net/NetworkInformation/UnixIPInterfaceProperties.cs",
            "src/System/Net/NetworkInformation/UnixIPv4InterfaceProperties.cs",
            "src/System/Net/NetworkInformation/UnixIPv6InterfaceProperties.cs",
            "src/System/Net/NetworkInformation/UnixMulticastIPAddressInformation.cs",
            "src/System/Net/NetworkInformation/UnixNetworkInterface.cs",
            "src/System/Net/NetworkInformation/UnixUnicastIPAddressInformation.cs",
            # BSD/OSX src files
            "src/System/Net/NetworkInformation/IPGlobalPropertiesPal.Bsd.cs",
            "src/System/Net/NetworkInformation/NetworkInterfacePal.Bsd.cs",
            "src/System/Net/NetworkInformation/BsdIcmpV4Statistics.cs",
            "src/System/Net/NetworkInformation/BsdIcmpV6Statistics.cs",
            "src/System/Net/NetworkInformation/BsdIPGlobalProperties.cs",
            "src/System/Net/NetworkInformation/BsdIPv4GlobalStatistics.cs",
            "src/System/Net/NetworkInformation/BsdIpInterfaceStatistics.cs",
            "src/System/Net/NetworkInformation/BsdIPv4InterfaceProperties.cs",
            "src/System/Net/NetworkInformation/BsdIPv4InterfaceStatistics.cs",
            "src/System/Net/NetworkInformation/BsdIPv6InterfaceProperties.cs",
            "src/System/Net/NetworkInformation/BsdIpInterfaceProperties.cs",
            "src/System/Net/NetworkInformation/BsdNetworkInterface.cs",
            "src/System/Net/NetworkInformation/BsdTcpStatistics.cs",
            "src/System/Net/NetworkInformation/BsdUdpStatistics.cs",
            # OSX-specific src files
            "src/System/Net/NetworkInformation/NetworkAddressChange.OSX.cs",
            # Unix Common files
            "//src/libraries/Common:src/Interop/Unix/Interop.Libraries.cs",
            "//src/libraries/Common:src/Interop/Unix/Interop.Errors.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.EnumerateInterfaceAddresses.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.GetDomainName.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.GetHostName.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.MapTcpState.cs",
            "//src/libraries/Common:src/System/Net/NetworkInformation/HostInformationPal.Unix.cs",
            "//src/libraries/Common:src/System/IO/RowConfigReader.cs",
            # BSD Common files
            "//src/libraries/Common:src/Interop/BSD/System.Native/Interop.ProtocolStatistics.cs",
            "//src/libraries/Common:src/Interop/BSD/System.Native/Interop.TcpConnectionInfo.cs",
            # OSX Common files
            "//src/libraries/Common:src/Interop/OSX/Interop.CoreFoundation.cs",
            "//src/libraries/Common:src/Interop/OSX/Interop.Libraries.cs",
            "//src/libraries/Common:src/Interop/OSX/Interop.RunLoop.cs",
            "//src/libraries/Common:src/Interop/OSX/Interop.SystemConfiguration.cs",
            "//src/libraries/Common:src/Microsoft/Win32/SafeHandles/SafeCreateHandle.OSX.cs",
        ],
    }),
    resx_file = "src/Resources/Strings.resx",
    allow_unsafe_blocks = True,
    deps = [
        "//src/libraries:ref_Microsoft.Win32.Primitives",
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Collections:ref_System.Collections",
        "//src/libraries/System.Diagnostics.Tracing:ref_System.Diagnostics.Tracing",
        "//src/libraries/System.Memory:ref_System.Memory",
        "//src/libraries/System.Net.Primitives:ref_System.Net.Primitives",
        "//src/libraries/System.Net.Sockets:ref_System.Net.Sockets",
        "//src/libraries/System.Runtime.InteropServices:ref_System.Runtime.InteropServices",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/System.Threading.Overlapped:ref_System.Threading.Overlapped",
        "//src/libraries/System.Threading.Thread:ref_System.Threading.Thread",
        "//src/libraries/System.Threading.ThreadPool:ref_System.Threading.ThreadPool",
    ],
    supported_os_platforms = ["linux"],
)
