load("//src/tests:live_test.bzl", "coreclr_test")

coreclr_test(
    name = "Vector256_1_r",
    srcs = [
        "Program.Vector256_1.cs",
        "//src/tests/JIT/HardwareIntrinsics/General/Shared:Program.cs",
    ],
)

coreclr_test(
    name = "Vector256_1_ro",
    srcs = [
        "Program.Vector256_1.cs",
        "//src/tests/JIT/HardwareIntrinsics/General/Shared:Program.cs",
    ],
    optimize = True,
)
