load("//:defs.bzl", "NETCOREAPP_MINIMUM", "NETCOREAPP_TOOL_CURRENT", "csharp_library")

csharp_library(
    name = "ILCompiler.DependencyAnalysisFramework",
    include_runtime_async = False,
    nowarn = ["1591"],
    msbuild_analyzer_config = "source",
    interceptors_namespaces = ";Microsoft.Extensions.Validation.Generated",
    compiler_options = ["/warnaserror+:NU1605"],
    srcs = glob(["*.cs"]) + [
        "//src/coreclr/tools/Common:Sorting/ArrayAccessor.cs",
        "//src/coreclr/tools/Common:Sorting/ICompareAsEqualAction.cs",
        "//src/coreclr/tools/Common:Sorting/ISortableDataStructureAccessor.cs",
        "//src/coreclr/tools/Common:Sorting/ListAccessor.cs",
        "//src/coreclr/tools/Common:Sorting/MergeSort.cs",
        "//src/coreclr/tools/Common:Sorting/MergeSortCore.cs",
    ],
    analyzers = [
        "//:source_build_analyzers",
        "//src/tools/illink/src/ILLink.RoslynAnalyzer",
    ],
    target_frameworks = [NETCOREAPP_MINIMUM, NETCOREAPP_TOOL_CURRENT],
    visibility = ["//visibility:public"],
)
