load("//src/libraries:defs.bzl", "netcoreapp_impl_assembly")
load("//:defs.bzl", "OPEN_SNK")

exports_files(["src/ILLink/ILLink.Descriptors.LibraryBuild.xml"])

netcoreapp_impl_assembly(
    name = "impl_System.Private.Xml.Linq",
    nowarn = ["CS1591"],
    srcs = glob(["src/System/**/*.cs"]) + [
        "//src/libraries/Common:src/System/Collections/Generic/EnumerableHelpers.cs",
        "//src/libraries/Common:src/System/Text/StringBuilderCache.cs",
    ],
    resx_file = "src/Resources/Strings.resx",
    deps = [
        "//src/libraries/System.Collections:ref_System.Collections",
        "//src/libraries/System.Linq:ref_System.Linq",
        "//src/libraries/System.Memory:ref_System.Memory",
        "//src/libraries/System.ObjectModel:ref_System.ObjectModel",
        "//src/libraries/System.Private.Xml:impl_System.Private.Xml",
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/System.Threading.Thread:ref_System.Threading.Thread",
    ],
    keyfile = OPEN_SNK,
    library_import_generator = False,
)
