load("//src/tests:live_test.bzl", "library_test")
load("//:defs.bzl", "OPEN_SNK")

exports_files([
    "AllocationHelper.cs",
    "Base64/Base64TestBase.cs",
    "Base64/Base64TestHelper.cs",
    "Base64Url/Base64UrlDecoderUnitTests.cs",
    "Base64Url/Base64UrlEncoderUnitTests.cs",
    "Base64Url/Base64UrlValidationUnitTests.cs",
])

library_test(
    name = "System.Memory.Tests",
    srcs = glob([
        "**/*.cs",
    ]) + [
        "//src/libraries/Common/tests:System/Buffers/NativeMemoryManager.cs",
        "//src/libraries/Common/tests:System/RealFormatterTestsBase.cs",
        "//src/libraries/Common/tests:System/RealParserTestsBase.cs",
    ],
    deps = [
        "//src/libraries/System.Runtime.Numerics:ref_System.Runtime.Numerics",
        "//src/libraries/System.Security.Cryptography:ref_System.Security.Cryptography",
        "//src/libraries/System.Text.Encoding.Extensions:ref_System.Text.Encoding.Extensions",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/System.Threading.Tasks.Parallel:ref_System.Threading.Tasks.Parallel",
        "//src/libraries/Common/tests:TestUtilities",
        "@paket.main//microsoft.dotnet.remoteexecutor",
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//microsoft.dotnet.xunitextensions",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    allow_unsafe_blocks = True,
    size = "large",
    keyfile = OPEN_SNK,
)
