load("//src/tests:live_test.bzl", "coreclr_test")

coreclr_test(
    name = "AssemblyDependencyResolverTests",
    srcs = [
        "AssemblyDependencyResolverTests.cs",
        "NativeDependencyTests.cs",
        "TestBase.cs",
    ],
    deps = [
        "//src/tests/Common:TestLibrary",
        "@paket.main//microsoft.dotnet.xunitextensions",
    ],
    tags = ["manual"],  # Needs writable filesystem
)
