load("//src/libraries:defs.bzl", "netcoreapp_ref_assembly", "netcoreapp_impl_assembly")

netcoreapp_ref_assembly(
    name = "ref_System.Security.AccessControl",
    srcs = [
        "ref/System.Security.AccessControl.cs",
    ],
    deps = [
        "//src/libraries/System.Collections.NonGeneric:ref_System.Collections.NonGeneric",
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Security.Principal.Windows:ref_System.Security.Principal.Windows",
    ],
)

netcoreapp_impl_assembly(
    name = "impl_System.Security.AccessControl",
    com_interface_generator = True,
    nowarn = ["CS1591"],
    pnse = True,
    srcs = [
        "System.Security.AccessControl.notsupported.cs",
    ],
    deps = [
        "//src/libraries:ref_Microsoft.Win32.Primitives",
        "//src/libraries/System.Collections:ref_System.Collections",
        "//src/libraries/System.Collections.NonGeneric:ref_System.Collections.NonGeneric",
        "//src/libraries/System.Memory:ref_System.Memory",
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Runtime.InteropServices:ref_System.Runtime.InteropServices",
        "//src/libraries/System.Security.Principal.Windows:ref_System.Security.Principal.Windows",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/System.Threading.Thread:ref_System.Threading.Thread",
    ],
    resx_file = "src/Resources/Strings.resx",
    nullable = "enable",
    supported_os_platforms_short = ["windows"],
    include_dll_safe_search_path = True,
    include_editorconfig = False,
)
