load("//src/libraries:defs.bzl", "netcoreapp_ref_assembly", "netcoreapp_impl_assembly")

netcoreapp_ref_assembly(
    name = "ref_System.Formats.Asn1",
    srcs = [
        "ref/System.Formats.Asn1.cs",
    ],
    deps = [
        "//src/libraries/System.Collections:ref_System.Collections",
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Runtime.Numerics:ref_System.Runtime.Numerics",
    ],
    defines = [
        "NET9_0_OR_GREATER",
    ]
)

netcoreapp_impl_assembly(
    name = "impl_System.Formats.Asn1",
    multitarget = True,
    skip_cs1591 = True,
    defines = ["CP_NO_ZEROMEMORY"],
    srcs = glob(["src/System/Formats/Asn1/**/*.cs"]) + [
        "//src/libraries/Common:src/System/Security/Cryptography/CryptoPool.cs",
        "//src/libraries/Common:src/System/Obsoletions.cs",
    ],
    resx_file = "src/Resources/Strings.resx",
    deps = [
        "//src/libraries/System.Collections:ref_System.Collections",
        "//src/libraries/System.Memory:ref_System.Memory",
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Runtime.InteropServices:ref_System.Runtime.InteropServices",
        "//src/libraries/System.Runtime.Numerics:ref_System.Runtime.Numerics",
        "//src/libraries/System.Text.Encoding.Extensions:ref_System.Text.Encoding.Extensions",
    ],
    assembly_description = "Provides classes that can read and write the ASN.1 BER, CER, and DER data formats.",
)
