load("//src/libraries:defs.bzl", "netcoreapp_impl_assembly", "netcoreapp_ref_assembly", "ref_impl_pair")

exports_files([
    "ref/System.Security.Cryptography.Xml.cs",
])

netcoreapp_ref_assembly(
    name = "ref_System.Security.Cryptography.Xml",
    srcs = [
        "ref/System.Security.Cryptography.Xml.cs",
    ],
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Security.AccessControl:ref_System.Security.AccessControl",
        "//src/libraries/System.Security.Cryptography:ref_System.Security.Cryptography",
        "//src/libraries/System.Xml.ReaderWriter:ref_System.Xml.ReaderWriter",
    ],
)

netcoreapp_impl_assembly(
    name = "impl_System.Security.Cryptography.Xml",
    srcs = [
        # Common linked files
        "//src/libraries/Common:src/System/HexConverter.cs",
        "//src/libraries/Common:src/System/Obsoletions.cs",
        # Local src files
        "src/System/Security/Cryptography/Xml/AncestralNamespaceContextManager.cs",
        "src/System/Security/Cryptography/Xml/AttributeSortOrder.cs",
        "src/System/Security/Cryptography/Xml/C14NAncestralNamespaceContextManager.cs",
        "src/System/Security/Cryptography/Xml/CanonicalizationDispatcher.cs",
        "src/System/Security/Cryptography/Xml/CanonicalXml.cs",
        "src/System/Security/Cryptography/Xml/CanonicalXmlAttribute.cs",
        "src/System/Security/Cryptography/Xml/CanonicalXmlCDataSection.cs",
        "src/System/Security/Cryptography/Xml/CanonicalXmlComment.cs",
        "src/System/Security/Cryptography/Xml/CanonicalXmlDocument.cs",
        "src/System/Security/Cryptography/Xml/CanonicalXmlElement.cs",
        "src/System/Security/Cryptography/Xml/CanonicalXmlEntityReference.cs",
        "src/System/Security/Cryptography/Xml/CanonicalXmlNodeList.cs",
        "src/System/Security/Cryptography/Xml/CanonicalXmlProcessingInstruction.cs",
        "src/System/Security/Cryptography/Xml/CanonicalXmlSignificantWhitespace.cs",
        "src/System/Security/Cryptography/Xml/CanonicalXmlText.cs",
        "src/System/Security/Cryptography/Xml/CanonicalXmlWhitespace.cs",
        "src/System/Security/Cryptography/Xml/CertUsageType.cs",
        "src/System/Security/Cryptography/Xml/CipherData.cs",
        "src/System/Security/Cryptography/Xml/CipherReference.cs",
        "src/System/Security/Cryptography/Xml/CryptoHelpers.cs",
        "src/System/Security/Cryptography/Xml/CryptoSignedXmlRecursionException.cs",
        "src/System/Security/Cryptography/Xml/DSAKeyValue.cs",
        "src/System/Security/Cryptography/Xml/DSASignatureDescription.cs",
        "src/System/Security/Cryptography/Xml/DataObject.cs",
        "src/System/Security/Cryptography/Xml/DataReference.cs",
        "src/System/Security/Cryptography/Xml/DocPosition.cs",
        "src/System/Security/Cryptography/Xml/EncryptedData.cs",
        "src/System/Security/Cryptography/Xml/EncryptedKey.cs",
        "src/System/Security/Cryptography/Xml/EncryptedReference.cs",
        "src/System/Security/Cryptography/Xml/EncryptedType.cs",
        "src/System/Security/Cryptography/Xml/EncryptedXml.cs",
        "src/System/Security/Cryptography/Xml/EncryptionMethod.cs",
        "src/System/Security/Cryptography/Xml/EncryptionProperty.cs",
        "src/System/Security/Cryptography/Xml/EncryptionPropertyCollection.cs",
        "src/System/Security/Cryptography/Xml/ExcAncestralNamespaceContextManager.cs",
        "src/System/Security/Cryptography/Xml/ExcCanonicalXml.cs",
        "src/System/Security/Cryptography/Xml/ICanonicalizableNode.cs",
        "src/System/Security/Cryptography/Xml/IRelDecryptor.cs",
        "src/System/Security/Cryptography/Xml/KeyInfo.cs",
        "src/System/Security/Cryptography/Xml/KeyInfoClause.cs",
        "src/System/Security/Cryptography/Xml/KeyInfoEncryptedKey.cs",
        "src/System/Security/Cryptography/Xml/KeyInfoName.cs",
        "src/System/Security/Cryptography/Xml/KeyInfoNode.cs",
        "src/System/Security/Cryptography/Xml/KeyInfoRetrievalMethod.cs",
        "src/System/Security/Cryptography/Xml/KeyInfoX509Data.cs",
        "src/System/Security/Cryptography/Xml/KeyReference.cs",
        "src/System/Security/Cryptography/Xml/MyXmlDocument.cs",
        "src/System/Security/Cryptography/Xml/NamespaceFrame.cs",
        "src/System/Security/Cryptography/Xml/NamespaceSortOrder.cs",
        "src/System/Security/Cryptography/Xml/RSAPKCS1SHA1SignatureDescription.cs",
        "src/System/Security/Cryptography/Xml/RSAPKCS1SHA256SignatureDescription.cs",
        "src/System/Security/Cryptography/Xml/RSAPKCS1SHA384SignatureDescription.cs",
        "src/System/Security/Cryptography/Xml/RSAPKCS1SHA512SignatureDescription.cs",
        "src/System/Security/Cryptography/Xml/RSAPKCS1SignatureDescription.cs",
        "src/System/Security/Cryptography/Xml/RSAKeyValue.cs",
        "src/System/Security/Cryptography/Xml/Reference.cs",
        "src/System/Security/Cryptography/Xml/ReferenceList.cs",
        "src/System/Security/Cryptography/Xml/ReferenceTargetType.cs",
        "src/System/Security/Cryptography/Xml/Signature.cs",
        "src/System/Security/Cryptography/Xml/SignedInfo.cs",
        "src/System/Security/Cryptography/Xml/SignedXml.cs",
        "src/System/Security/Cryptography/Xml/SignedXmlDebugLog.cs",
        "src/System/Security/Cryptography/Xml/SymmetricKeyWrap.cs",
        "src/System/Security/Cryptography/Xml/Transform.cs",
        "src/System/Security/Cryptography/Xml/TransformChain.cs",
        "src/System/Security/Cryptography/Xml/Utils.cs",
        "src/System/Security/Cryptography/Xml/XmlDecryptionTransform.cs",
        "src/System/Security/Cryptography/Xml/XmlDsigBase64Transform.cs",
        "src/System/Security/Cryptography/Xml/XmlDsigC14NTransform.cs",
        "src/System/Security/Cryptography/Xml/XmlDsigC14NWithCommentsTransform.cs",
        "src/System/Security/Cryptography/Xml/XmlDsigEnvelopedSignatureTransform.cs",
        "src/System/Security/Cryptography/Xml/XmlDsigExcC14NTransform.cs",
        "src/System/Security/Cryptography/Xml/XmlDsigExcC14NWithCommentsTransform.cs",
        "src/System/Security/Cryptography/Xml/XmlDsigXPathTransform.cs",
        "src/System/Security/Cryptography/Xml/XmlDsigXsltTransform.cs",
        "src/System/Security/Cryptography/Xml/XmlLicenseTransform.cs",
        "src/System/Security/Cryptography/Xml/XmlResolverHelper.cs",
    ],
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Collections:ref_System.Collections",
        "//src/libraries/System.Collections.NonGeneric:ref_System.Collections.NonGeneric",
        "//src/libraries/System.Diagnostics.TraceSource:ref_System.Diagnostics.TraceSource",
        "//src/libraries/System.Memory:ref_System.Memory",
        "//src/libraries/System.Net.Requests:ref_System.Net.Requests",
        "//src/libraries/System.Runtime.Numerics:ref_System.Runtime.Numerics",
        "//src/libraries/System.Security.AccessControl:ref_System.Security.AccessControl",
        "//src/libraries/System.Security.Cryptography:ref_System.Security.Cryptography",
        "//src/libraries/System.Security.Cryptography.Pkcs:ref_System.Security.Cryptography.Pkcs",
        "//src/libraries/System.Xml.ReaderWriter:ref_System.Xml.ReaderWriter",
        "//src/libraries/System.Xml.XPath:ref_System.Xml.XPath",
    ],
    allow_unsafe_blocks = True,
    resx_file = "src/Resources/Strings.resx",
    nowarn = [
        "CA1850",
    ],
)

ref_impl_pair(
    name = "live_System.Security.Cryptography.Xml",
    ref = ":ref_System.Security.Cryptography.Xml",
    lib = ":impl_System.Security.Cryptography.Xml",
    visibility = ["//visibility:public"],
)
