load("//src/tests:live_test.bzl", "coreclr_test", "coreclr_merged_test")

coreclr_test(
    name = "Haar-likeFeaturesGeneric_r",
    srcs = ["Haar-likeFeaturesGeneric.cs"],
)

coreclr_test(
    name = "AbsGeneric_ro",
    srcs = ["AbsGeneric.cs"],
    optimize = True,
)

coreclr_test(
    name = "VectorArray_ro",
    srcs = ["VectorArray.cs", "VectorUtil.cs"],
    optimize = True,
)

coreclr_test(
    name = "MinMax_r",
    srcs = ["MinMax.cs"],
)

coreclr_test(
    name = "StoreElement_r",
    srcs = ["StoreElement.cs"],
    pri = 1,
)

coreclr_test(
    name = "Mul_ro",
    srcs = ["Mul.cs"],
    optimize = True,
)

coreclr_test(
    name = "VectorDiv_ro",
    srcs = ["VectorDiv.cs", "VectorUtil.cs"],
    optimize = True,
)

coreclr_test(
    name = "VectorAbs_ro",
    srcs = ["VectorAbs.cs", "VectorUtil.cs"],
    optimize = True,
)

coreclr_test(
    name = "VectorUnused_r",
    srcs = ["VectorUnused.cs", "VectorUtil.cs"],
)

coreclr_test(
    name = "VectorDot_r",
    srcs = ["VectorDot.cs", "VectorUtil.cs"],
)

coreclr_test(
    name = "Matrix4x4_ro",
    srcs = ["Matrix4x4.cs"],
    optimize = True,
)

coreclr_test(
    name = "CircleInConvex_r",
    srcs = ["CircleInConvex.cs"],
)

coreclr_test(
    name = "VectorArgs_r",
    srcs = ["VectorArgs.cs", "VectorUtil.cs"],
)

coreclr_test(
    name = "CircleInConvex_ro",
    srcs = ["CircleInConvex.cs"],
    optimize = True,
)

coreclr_test(
    name = "SimpleSIMDProgram",
    srcs = ["SimpleSIMDProgram.cs"],
)

coreclr_test(
    name = "Haar-likeFeaturesGeneric_ro",
    srcs = ["Haar-likeFeaturesGeneric.cs"],
    optimize = True,
)

coreclr_test(
    name = "VectorArray_r",
    srcs = ["VectorArray.cs", "VectorUtil.cs"],
)

coreclr_test(
    name = "DivSignedUnsignedTest_ro",
    srcs = ["DivSignedUnsignedTest.cs"],
    optimize = True,
)

coreclr_test(
    name = "AddingSequence_ro",
    srcs = ["AddingSequence.cs"],
    optimize = True,
)

coreclr_test(
    name = "VectorGet_r",
    srcs = ["VectorGet.cs", "VectorUtil.cs"],
)

coreclr_test(
    name = "BugWithAVX_ro",
    srcs = ["BugWithAVX.cs"],
    pri = 1,
    optimize = True,
)

coreclr_test(
    name = "VectorSum_r",
    srcs = ["VectorSum.cs", "VectorUtil.cs"],
)

coreclr_test(
    name = "Ctors_r",
    srcs = ["Ctors.cs", "VectorUtil.cs"],
)

coreclr_test(
    name = "VectorAbs_r",
    srcs = ["VectorAbs.cs", "VectorUtil.cs"],
)

coreclr_test(
    name = "VectorMatrix_r",
    srcs = ["VectorMatrix.cs", "VectorUtil.cs"],
)

coreclr_test(
    name = "VectorMul_r",
    srcs = ["VectorMul.cs", "VectorUtil.cs"],
)

coreclr_test(
    name = "BoxUnbox_r",
    srcs = ["BoxUnbox.cs"],
    pri = 1,
)

coreclr_test(
    name = "VectorRelOp_r",
    srcs = ["VectorRelOp.cs", "VectorUtil.cs"],
)

coreclr_test(
    name = "VectorIntEquals_ro",
    srcs = ["VectorIntEquals.cs", "VectorUtil.cs"],
    optimize = True,
)

coreclr_test(
    name = "CtorFromArray_ro",
    srcs = ["CtorFromArray.cs"],
    optimize = True,
)

coreclr_test(
    name = "VectorHWAccel_ro",
    srcs = ["VectorHWAccel.cs", "VectorUtil.cs"],
    optimize = True,
)

coreclr_test(
    name = "Vector3GetHash_ro",
    srcs = ["Vector3GetHash.cs"],
    pri = 1,
    optimize = True,
)

coreclr_test(
    name = "VectorSub_ro",
    srcs = ["VectorSub.cs", "VectorUtil.cs"],
    optimize = True,
)

coreclr_test(
    name = "VectorSqrt_ro",
    srcs = ["VectorSqrt.cs", "VectorUtil.cs"],
    optimize = True,
)

coreclr_test(
    name = "VectorCeilFloor_r",
    srcs = ["VectorCeilFloor.cs", "VectorUtil.cs"],
    pri = 1,
)

coreclr_test(
    name = "CtorFromArray_r",
    srcs = ["CtorFromArray.cs"],
)

coreclr_test(
    name = "VectorArrayInit_ro",
    srcs = ["VectorArrayInit.cs", "VectorUtil.cs"],
    optimize = True,
)

coreclr_test(
    name = "VectorArgs_ro",
    srcs = ["VectorArgs.cs", "VectorUtil.cs"],
    optimize = True,
)

coreclr_test(
    name = "Vector3GetHash_r",
    srcs = ["Vector3GetHash.cs"],
    pri = 1,
)

coreclr_test(
    name = "VectorCeilFloor_ro",
    srcs = ["VectorCeilFloor.cs", "VectorUtil.cs"],
    optimize = True,
)

coreclr_test(
    name = "VectorHWAccel2_r",
    srcs = ["VectorHWAccel2.cs", "VectorUtil.cs"],
)

coreclr_test(
    name = "CreateGeneric_ro",
    srcs = ["CreateGeneric.cs"],
    optimize = True,
)

coreclr_test(
    name = "VectorSet_ro",
    srcs = ["VectorSet.cs", "VectorUtil.cs"],
    optimize = True,
)

coreclr_test(
    name = "VectorCast_r",
    srcs = ["VectorCast.cs", "VectorUtil.cs"],
)

coreclr_test(
    name = "Vector4_r",
    srcs = ["Vector4.cs"],
)

coreclr_test(
    name = "VectorHWAccel2_ro",
    srcs = ["VectorHWAccel2.cs", "VectorUtil.cs"],
    optimize = True,
)

coreclr_test(
    name = "LdfldGeneric_ro",
    srcs = ["LdfldGeneric.cs"],
    optimize = True,
)

coreclr_test(
    name = "Vector3_ro",
    srcs = ["Vector3.cs"],
    optimize = True,
)

coreclr_test(
    name = "VectorCopyToArray_r",
    srcs = ["VectorCopyToArray.cs", "VectorUtil.cs"],
)

coreclr_test(
    name = "VectorDiv_r",
    srcs = ["VectorDiv.cs", "VectorUtil.cs"],
)

coreclr_test(
    name = "ShiftOperations",
    srcs = ["ShiftOperations.cs"],
    debug_type = "pdbonly",
    optimize = True,
    allow_unsafe_blocks = True,
)

coreclr_test(
    name = "Ldind_r",
    srcs = ["Ldind.cs"],
    pri = 1,
    allow_unsafe_blocks = True,
)

coreclr_test(
    name = "VectorSub_r",
    srcs = ["VectorSub.cs", "VectorUtil.cs"],
)

coreclr_test(
    name = "BugWithAVX_r",
    srcs = ["BugWithAVX.cs"],
    pri = 1,
)

coreclr_test(
    name = "DivSignedUnsignedTest_r",
    srcs = ["DivSignedUnsignedTest.cs"],
)

coreclr_test(
    name = "AbsSqrt_ro",
    srcs = ["AbsSqrt.cs"],
    optimize = True,
)

coreclr_test(
    name = "VectorExp_r",
    srcs = ["VectorExp.cs", "VectorUtil.cs"],
)

coreclr_test(
    name = "CreateGeneric_r",
    srcs = ["CreateGeneric.cs"],
)

coreclr_test(
    name = "VectorHWAccel_r",
    srcs = ["VectorHWAccel.cs", "VectorUtil.cs"],
)

coreclr_test(
    name = "BitwiseOperations_ro",
    srcs = ["BitwiseOperations.cs"],
    optimize = True,
)

coreclr_test(
    name = "Dup_ro",
    srcs = ["Dup.cs"],
    optimize = True,
)

coreclr_test(
    name = "Vector3_r",
    srcs = ["Vector3.cs"],
)

coreclr_test(
    name = "SqrtGeneric_ro",
    srcs = ["SqrtGeneric.cs"],
    optimize = True,
)

coreclr_test(
    name = "VectorSqrt_r",
    srcs = ["VectorSqrt.cs", "VectorUtil.cs"],
    pri = 1,
)

coreclr_test(
    name = "LdfldGeneric_r",
    srcs = ["LdfldGeneric.cs"],
)

coreclr_test(
    name = "VectorMax_ro",
    srcs = ["VectorMax.cs", "VectorUtil.cs"],
    optimize = True,
)

coreclr_test(
    name = "Ldind_ro",
    srcs = ["Ldind.cs"],
    pri = 1,
    optimize = True,
    allow_unsafe_blocks = True,
)

coreclr_test(
    name = "BoxUnbox_ro",
    srcs = ["BoxUnbox.cs"],
    optimize = True,
)

coreclr_test(
    name = "VectorInit_r",
    srcs = ["VectorInit.cs", "VectorUtil.cs"],
)

coreclr_test(
    name = "VectorInit_ro",
    srcs = ["VectorInit.cs", "VectorUtil.cs"],
    optimize = True,
)

coreclr_test(
    name = "VectorMatrix_ro",
    srcs = ["VectorMatrix.cs", "VectorUtil.cs"],
    optimize = True,
)

coreclr_test(
    name = "Dup_r",
    srcs = ["Dup.cs"],
)

coreclr_test(
    name = "AbsSqrt_r",
    srcs = ["AbsSqrt.cs"],
)

coreclr_test(
    name = "VectorExp_ro",
    srcs = ["VectorExp.cs", "VectorUtil.cs"],
    optimize = True,
)

coreclr_test(
    name = "Vector4_ro",
    srcs = ["Vector4.cs"],
    optimize = True,
)

coreclr_test(
    name = "Mul_r",
    srcs = ["Mul.cs"],
    pri = 1,
)

coreclr_test(
    name = "VectorInitN_r",
    srcs = ["VectorInitN.cs", "VectorUtil.cs"],
)

coreclr_test(
    name = "Matrix4x4_r",
    srcs = ["Matrix4x4.cs"],
)

coreclr_test(
    name = "VectorSet_r",
    srcs = ["VectorSet.cs", "VectorUtil.cs"],
)

coreclr_test(
    name = "Ctors_ro",
    srcs = ["Ctors.cs", "VectorUtil.cs"],
    optimize = True,
)

coreclr_test(
    name = "MinMax_ro",
    srcs = ["MinMax.cs"],
    optimize = True,
)

coreclr_test(
    name = "VectorMax_r",
    srcs = ["VectorMax.cs", "VectorUtil.cs"],
)

coreclr_test(
    name = "Plane_r",
    srcs = ["Plane.cs"],
)

coreclr_test(
    name = "VectorReturn_ro",
    srcs = ["VectorReturn.cs", "VectorUtil.cs"],
    optimize = True,
)

coreclr_test(
    name = "BitwiseOperations_r",
    srcs = ["BitwiseOperations.cs"],
)

coreclr_test(
    name = "VectorArrayInit_r",
    srcs = ["VectorArrayInit.cs", "VectorUtil.cs"],
)

coreclr_test(
    name = "VectorDot_ro",
    srcs = ["VectorDot.cs", "VectorUtil.cs"],
    optimize = True,
)

coreclr_test(
    name = "VectorReturn_r",
    srcs = ["VectorReturn.cs", "VectorUtil.cs"],
)

coreclr_test(
    name = "VectorMul_ro",
    srcs = ["VectorMul.cs", "VectorUtil.cs"],
    optimize = True,
)

coreclr_test(
    name = "VectorCopyToArray_ro",
    srcs = ["VectorCopyToArray.cs", "VectorUtil.cs"],
    optimize = True,
)

coreclr_test(
    name = "VectorAdd_ro",
    srcs = ["VectorAdd.cs", "VectorUtil.cs"],
    optimize = True,
)

coreclr_test(
    name = "Ldfld_r",
    srcs = ["Ldfld.cs"],
)

coreclr_test(
    name = "VectorCast_ro",
    srcs = ["VectorCast.cs", "VectorUtil.cs"],
    optimize = True,
)

coreclr_test(
    name = "AbsGeneric_r",
    srcs = ["AbsGeneric.cs"],
)

coreclr_test(
    name = "VectorInitN_ro",
    srcs = ["VectorInitN.cs", "VectorUtil.cs"],
    optimize = True,
)

coreclr_test(
    name = "VectorUnused_ro",
    srcs = ["VectorUnused.cs", "VectorUtil.cs"],
    optimize = True,
)

coreclr_test(
    name = "Sums_r",
    srcs = ["Sums.cs"],
)

coreclr_test(
    name = "StoreElement_ro",
    srcs = ["StoreElement.cs"],
    optimize = True,
)

coreclr_test(
    name = "Sums_ro",
    srcs = ["Sums.cs"],
    optimize = True,
)

coreclr_test(
    name = "Ldfld_ro",
    srcs = ["Ldfld.cs"],
    optimize = True,
)

coreclr_test(
    name = "VectorGet_ro",
    srcs = ["VectorGet.cs", "VectorUtil.cs"],
    optimize = True,
)

coreclr_test(
    name = "VectorMin_r",
    srcs = ["VectorMin.cs", "VectorUtil.cs"],
)

coreclr_test(
    name = "VectorRelOp_ro",
    srcs = ["VectorRelOp.cs", "VectorUtil.cs"],
    optimize = True,
)

coreclr_test(
    name = "VectorMin_ro",
    srcs = ["VectorMin.cs", "VectorUtil.cs"],
    optimize = True,
)

coreclr_test(
    name = "VectorIntEquals_r",
    srcs = ["VectorIntEquals.cs", "VectorUtil.cs"],
    pri = 1,
)

coreclr_test(
    name = "VectorSum_ro",
    srcs = ["VectorSum.cs", "VectorUtil.cs"],
    optimize = True,
)

coreclr_test(
    name = "AddingSequence_r",
    srcs = ["AddingSequence.cs"],
)

coreclr_test(
    name = "Plane_ro",
    srcs = ["Plane.cs"],
    optimize = True,
)

coreclr_test(
    name = "SqrtGeneric_r",
    srcs = ["SqrtGeneric.cs"],
)

coreclr_test(
    name = "VectorAdd_r",
    srcs = ["VectorAdd.cs", "VectorUtil.cs"],
)

coreclr_merged_test(
    name = "JIT.SIMD",
    deps = [
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    test_deps = [
        "//src/tests/JIT/SIMD:AbsGeneric_r",
        "//src/tests/JIT/SIMD:AbsGeneric_ro",
        "//src/tests/JIT/SIMD:AbsSqrt_r",
        "//src/tests/JIT/SIMD:AbsSqrt_ro",
        "//src/tests/JIT/SIMD:AddingSequence_r",
        "//src/tests/JIT/SIMD:AddingSequence_ro",
        "//src/tests/JIT/SIMD:BitwiseOperations_r",
        "//src/tests/JIT/SIMD:BitwiseOperations_ro",
        "//src/tests/JIT/SIMD:BoxUnbox_r",
        "//src/tests/JIT/SIMD:BoxUnbox_ro",
        "//src/tests/JIT/SIMD:BugWithAVX_r",
        "//src/tests/JIT/SIMD:BugWithAVX_ro",
        "//src/tests/JIT/SIMD:CircleInConvex_r",
        "//src/tests/JIT/SIMD:CircleInConvex_ro",
        "//src/tests/JIT/SIMD:CreateGeneric_r",
        "//src/tests/JIT/SIMD:CreateGeneric_ro",
        "//src/tests/JIT/SIMD:CtorFromArray_r",
        "//src/tests/JIT/SIMD:CtorFromArray_ro",
        "//src/tests/JIT/SIMD:Ctors_r",
        "//src/tests/JIT/SIMD:Ctors_ro",
        "//src/tests/JIT/SIMD:DivSignedUnsignedTest_r",
        "//src/tests/JIT/SIMD:DivSignedUnsignedTest_ro",
        "//src/tests/JIT/SIMD:Dup_r",
        "//src/tests/JIT/SIMD:Dup_ro",
        "//src/tests/JIT/SIMD:Haar-likeFeaturesGeneric_r",
        "//src/tests/JIT/SIMD:Haar-likeFeaturesGeneric_ro",
        "//src/tests/JIT/SIMD:LdfldGeneric_r",
        "//src/tests/JIT/SIMD:LdfldGeneric_ro",
        "//src/tests/JIT/SIMD:Ldfld_r",
        "//src/tests/JIT/SIMD:Ldfld_ro",
        "//src/tests/JIT/SIMD:Ldind_r",
        "//src/tests/JIT/SIMD:Ldind_ro",
        "//src/tests/JIT/SIMD:Matrix4x4_r",
        "//src/tests/JIT/SIMD:Matrix4x4_ro",
        "//src/tests/JIT/SIMD:MinMax_r",
        "//src/tests/JIT/SIMD:MinMax_ro",
        "//src/tests/JIT/SIMD:Mul_r",
        "//src/tests/JIT/SIMD:Mul_ro",
        "//src/tests/JIT/SIMD:Plane_r",
        "//src/tests/JIT/SIMD:Plane_ro",
        "//src/tests/JIT/SIMD:ShiftOperations",
        "//src/tests/JIT/SIMD:SimpleSIMDProgram",
        "//src/tests/JIT/SIMD:SqrtGeneric_r",
        "//src/tests/JIT/SIMD:SqrtGeneric_ro",
        "//src/tests/JIT/SIMD:StoreElement_r",
        "//src/tests/JIT/SIMD:StoreElement_ro",
        "//src/tests/JIT/SIMD:Sums_r",
        "//src/tests/JIT/SIMD:Sums_ro",
        "//src/tests/JIT/SIMD:Vector3GetHash_r",
        "//src/tests/JIT/SIMD:Vector3GetHash_ro",
        "//src/tests/JIT/SIMD:Vector3_r",
        "//src/tests/JIT/SIMD:Vector3_ro",
        "//src/tests/JIT/SIMD:Vector4_r",
        "//src/tests/JIT/SIMD:Vector4_ro",
        "//src/tests/JIT/SIMD:VectorAbs_r",
        "//src/tests/JIT/SIMD:VectorAbs_ro",
        "//src/tests/JIT/SIMD:VectorAdd_r",
        "//src/tests/JIT/SIMD:VectorAdd_ro",
        "//src/tests/JIT/SIMD:VectorArgs_r",
        "//src/tests/JIT/SIMD:VectorArgs_ro",
        "//src/tests/JIT/SIMD:VectorArrayInit_r",
        "//src/tests/JIT/SIMD:VectorArrayInit_ro",
        "//src/tests/JIT/SIMD:VectorArray_r",
        "//src/tests/JIT/SIMD:VectorArray_ro",
        "//src/tests/JIT/SIMD:VectorCast_r",
        "//src/tests/JIT/SIMD:VectorCast_ro",
        "//src/tests/JIT/SIMD:VectorCeilFloor_r",
        "//src/tests/JIT/SIMD:VectorCeilFloor_ro",
        "//src/tests/JIT/SIMD:VectorCopyToArray_r",
        "//src/tests/JIT/SIMD:VectorCopyToArray_ro",
        "//src/tests/JIT/SIMD:VectorDiv_r",
        "//src/tests/JIT/SIMD:VectorDiv_ro",
        "//src/tests/JIT/SIMD:VectorDot_r",
        "//src/tests/JIT/SIMD:VectorDot_ro",
        "//src/tests/JIT/SIMD:VectorExp_r",
        "//src/tests/JIT/SIMD:VectorExp_ro",
        "//src/tests/JIT/SIMD:VectorGet_r",
        "//src/tests/JIT/SIMD:VectorGet_ro",
        "//src/tests/JIT/SIMD:VectorHWAccel2_r",
        "//src/tests/JIT/SIMD:VectorHWAccel2_ro",
        "//src/tests/JIT/SIMD:VectorHWAccel_r",
        "//src/tests/JIT/SIMD:VectorHWAccel_ro",
        "//src/tests/JIT/SIMD:VectorInitN_r",
        "//src/tests/JIT/SIMD:VectorInitN_ro",
        "//src/tests/JIT/SIMD:VectorInit_r",
        "//src/tests/JIT/SIMD:VectorInit_ro",
        "//src/tests/JIT/SIMD:VectorIntEquals_r",
        "//src/tests/JIT/SIMD:VectorIntEquals_ro",
        "//src/tests/JIT/SIMD:VectorMatrix_r",
        "//src/tests/JIT/SIMD:VectorMatrix_ro",
        "//src/tests/JIT/SIMD:VectorMax_r",
        "//src/tests/JIT/SIMD:VectorMax_ro",
        "//src/tests/JIT/SIMD:VectorMin_r",
        "//src/tests/JIT/SIMD:VectorMin_ro",
        "//src/tests/JIT/SIMD:VectorMul_r",
        "//src/tests/JIT/SIMD:VectorMul_ro",
        "//src/tests/JIT/SIMD:VectorRelOp_r",
        "//src/tests/JIT/SIMD:VectorRelOp_ro",
        "//src/tests/JIT/SIMD:VectorReturn_r",
        "//src/tests/JIT/SIMD:VectorReturn_ro",
        "//src/tests/JIT/SIMD:VectorSet_r",
        "//src/tests/JIT/SIMD:VectorSet_ro",
        "//src/tests/JIT/SIMD:VectorSqrt_r",
        "//src/tests/JIT/SIMD:VectorSqrt_ro",
        "//src/tests/JIT/SIMD:VectorSub_r",
        "//src/tests/JIT/SIMD:VectorSub_ro",
        "//src/tests/JIT/SIMD:VectorSum_r",
        "//src/tests/JIT/SIMD:VectorSum_ro",
        "//src/tests/JIT/SIMD:VectorUnused_r",
        "//src/tests/JIT/SIMD:VectorUnused_ro",
    ],
)
