load("//src/libraries:defs.bzl", "COMMON_GENERATOR_ANALYZERS", "MULTITARGET_NOWARN", "netcoreapp_ref_assembly", "impl_assembly", "ref_impl_pair")

exports_files([
    "ref/Microsoft.Extensions.Diagnostics.Abstractions.cs",
])

netcoreapp_ref_assembly(
    name = "ref_Microsoft.Extensions.Diagnostics.Abstractions",
    srcs = [
        "ref/Microsoft.Extensions.Diagnostics.Abstractions.cs",
    ],
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions:ref_Microsoft.Extensions.DependencyInjection.Abstractions",
        "//src/libraries/System.Diagnostics.DiagnosticSource:ref_System.Diagnostics.DiagnosticSource",
    ],
)

impl_assembly(
    name = "impl_Microsoft.Extensions.Diagnostics.Abstractions",
    nowarn = MULTITARGET_NOWARN + ["CP0003"],
    srcs = glob(["src/**/*.cs"]) + [
        "//src/libraries/Common:src/Extensions/TypeNameHelper/TypeNameHelper.cs",
    ],
    analyzers = COMMON_GENERATOR_ANALYZERS,
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions:ref_Microsoft.Extensions.DependencyInjection.Abstractions",
        "//src/libraries/Microsoft.Extensions.Options:ref_Microsoft.Extensions.Options",
        "//src/libraries/System.Collections:ref_System.Collections",
        "//src/libraries/System.ComponentModel:ref_System.ComponentModel",
        "//src/libraries/System.Diagnostics.DiagnosticSource:ref_System.Diagnostics.DiagnosticSource",
    ],
    resx_file = "src/Resources/Strings.resx",
)

ref_impl_pair(
    name = "live_Microsoft.Extensions.Diagnostics.Abstractions",
    ref = ":ref_Microsoft.Extensions.Diagnostics.Abstractions",
    lib = ":impl_Microsoft.Extensions.Diagnostics.Abstractions",
    visibility = ["//visibility:public"],
)
