load("//src/tests:live_test.bzl", "coreclr_test")

coreclr_test(
    name = "k-nucleotide-1",
    tags = ["manual"],  # Needs EmbeddedResource support
    srcs = [
        "k-nucleotide-1.cs",
        "harness-helpers.cs",
    ],
    optimize = True,
)

coreclr_test(
    name = "k-nucleotide-9",
    tags = ["manual"],  # Needs EmbeddedResource support
    srcs = [
        "k-nucleotide-9.cs",
        "harness-helpers.cs",
    ],
    optimize = True,
)
