load("//src/tests:live_test.bzl", "coreclr_test")

coreclr_test(
    name = "MarshalSizeOf1_PSC",
    srcs = ["marshalsizeof1.cs"],
    pri = 1,
    deps = [
        "//src/tests/Common:TestLibrary",
        "@paket.main//microsoft.dotnet.xunitextensions",
    ],
)

coreclr_test(
    name = "MarshalSizeOf2_PSC",
    srcs = ["marshalsizeof2.cs"],
    pri = 1,
    deps = [
        "//src/tests/Common:TestLibrary",
        "@paket.main//microsoft.dotnet.xunitextensions",
    ],
)
