load("//src/tests:live_test.bzl", "coreclr_test")

coreclr_test(
    name = "DevDiv_794115_r",
    srcs = ["DevDiv_794115.cs"],
    pri = 1,
)

coreclr_test(
    name = "DevDiv_794115_do",
    srcs = ["DevDiv_794115.cs"],
    pri = 1,
    debug_type = "full",
    optimize = True,
)

coreclr_test(
    name = "DevDiv_794115_ro",
    srcs = ["DevDiv_794115.cs"],
    pri = 1,
    optimize = True,
)

coreclr_test(
    name = "DevDiv_794115_d",
    srcs = ["DevDiv_794115.cs"],
    pri = 1,
    debug_type = "full",
    optimize = False,
)
