# Headers for the dlls subdirectories.
load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//src/coreclr:__subpackages__"])

exports_files([
    "mscoree/mscoree.cpp",
    "mscoree/exports.cpp",
])

cc_library(
    name = "dlls_headers",
    hdrs = glob(
        [
            "**/*.h",
        ],
        allow_empty = True,
    ) + ["//src/coreclr/dlls/mscorrc:resource.h"],
)
