load("//src/libraries:defs.bzl", "netcoreapp_impl_assembly")

netcoreapp_impl_assembly(
    name = "impl_System.Runtime.InteropServices.RuntimeInformation",
    srcs = ["src/System.Runtime.InteropServices.RuntimeInformation.cs"],
    deps = [
        "//src/libraries:ref_System.Runtime",
    ],
    exclude_sr = True,
)
