load("//src/libraries:defs.bzl", "netcoreapp_ref_assembly", "netcoreapp_impl_assembly")

netcoreapp_ref_assembly(
    name = "ref_System.IO.MemoryMappedFiles",
    srcs = [ "ref/System.IO.MemoryMappedFiles.cs" ],
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Runtime.InteropServices:ref_System.Runtime.InteropServices",
    ]
)

netcoreapp_impl_assembly(
    name = "impl_System.IO.MemoryMappedFiles",
    com_interface_generator = True,
    nowarn = ["CS1591"],
    os_targeted = "unix",
    srcs = [
        "src/Microsoft/Win32/SafeMemoryMappedFileHandle.cs",
        "src/Microsoft/Win32/SafeMemoryMappedViewHandle.cs",
        "src/System/IO/MemoryMappedFiles/MemoryMappedFileOptions.cs",
        "src/System/IO/MemoryMappedFiles/MemoryMappedFileAccess.cs",
        "src/System/IO/MemoryMappedFiles/MemoryMappedFile.cs",
        "src/System/IO/MemoryMappedFiles/MemoryMappedView.cs",
        "src/System/IO/MemoryMappedFiles/MemoryMappedViewAccessor.cs",
        "src/System/IO/MemoryMappedFiles/MemoryMappedViewStream.cs",
        "src/System/IO/MemoryMappedFiles/MemoryMappedFileRights.cs",
        "//src/libraries/Common:src/DisableRuntimeMarshalling.cs",
    ] + select({
        "@platforms//os:linux": [
            "src/Microsoft/Win32/SafeMemoryMappedFileHandle.Unix.cs",
            "src/Microsoft/Win32/SafeMemoryMappedViewHandle.Unix.cs",
            "src/System/IO/MemoryMappedFiles/MemoryMappedFile.Unix.cs",
            "src/System/IO/MemoryMappedFiles/MemoryMappedView.Unix.cs",
            "//src/libraries/Common:src/Interop/Unix/Interop.Libraries.cs",
            "//src/libraries/Common:src/Interop/Unix/Interop.Errors.cs",
            "//src/libraries/Common:src/Interop/Unix/Interop.IOErrors.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Close.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Fcntl.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.MMap.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.MUnmap.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.MSync.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Open.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.OpenFlags.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Stat.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.SysConf.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.FTruncate.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.MAdvise.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.ShmOpen.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.MemfdCreate.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Unlink.cs",
        ],
        "@platforms//os:macos": [
            "src/Microsoft/Win32/SafeMemoryMappedFileHandle.Unix.cs",
            "src/Microsoft/Win32/SafeMemoryMappedViewHandle.Unix.cs",
            "src/System/IO/MemoryMappedFiles/MemoryMappedFile.Unix.cs",
            "src/System/IO/MemoryMappedFiles/MemoryMappedView.Unix.cs",
            "//src/libraries/Common:src/Interop/Unix/Interop.Libraries.cs",
            "//src/libraries/Common:src/Interop/Unix/Interop.Errors.cs",
            "//src/libraries/Common:src/Interop/Unix/Interop.IOErrors.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Close.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Fcntl.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.MMap.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.MUnmap.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.MSync.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Open.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.OpenFlags.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Stat.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.SysConf.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.FTruncate.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.MAdvise.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.ShmOpen.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.MemfdCreate.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Unlink.cs",
        ],
    }),
    resx_file = "src/Resources/Strings.resx",
    allow_unsafe_blocks = True,
    deps = [
        "//src/libraries/System.Memory:ref_System.Memory",
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Runtime.InteropServices:ref_System.Runtime.InteropServices",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/System.Threading.Thread:ref_System.Threading.Thread",
    ],
    supported_os_platforms = ["unix"],
)
