load("//src/tests:live_test.bzl", "coreclr_test")

coreclr_test(
    name = "b99969",
    srcs = ["b99969.cs"],
    debug_type = "pdbonly",
    deps = [
        "//src/libraries/System.Threading.Thread:ref_System.Threading.Thread",
        "//src/libraries/System.Threading:ref_System.Threading",
    ],
)
