load("//:defs.bzl", "csharp_library", "gen_assembly_info", "gen_target_framework_attrs")

exports_files([
    "Compiler/FileLayoutOptimizer.cs",
    "Compiler/PettisHansenSort/CallGraphNode.cs",
    "Compiler/PettisHansenSort/DisjointSetForest.cs",
    "Compiler/PettisHansenSort/PettisHansen.cs",
    "Compiler/ProfileData.cs",
    "IBC/IBCDataModel.cs",
    "IBC/IBCProfileData.cs",
    "IBC/MIbcProfileParser.cs",
])

gen_assembly_info(
    name = "assemblyinfo_ILCompiler.ReadyToRun",
    out = "ILCompiler.ReadyToRun.AssemblyInfo.cs",
    assembly_name = "ILCompiler.ReadyToRun",
    cls_compliant = False,
    is_aot_compatible = False,
    include_serviceable = False,
    include_description = False,
    assembly_configuration = "Release",
    include_dll_safe_search_path = 0,
)

gen_target_framework_attrs(
    name = "tfmattrs_ILCompiler.ReadyToRun",
    out = ".NETCoreApp,Version=v10.0.AssemblyAttributes.cs",
)

csharp_library(
    name = "ILCompiler.ReadyToRun",
    interceptors_namespaces = ";Microsoft.Extensions.Validation.Generated",
    nowarn = ["1591"],
    srcs = [
        ":assemblyinfo_ILCompiler.ReadyToRun",
        ":tfmattrs_ILCompiler.ReadyToRun",
        "CodeGen/ReadyToRunObjectWriter.cs",
        "Compiler/AssemblyExtensions.cs",
        "Compiler/CallChainProfile.cs",
        "Compiler/CompilationModuleGroup.ReadyToRun.cs",
        "Compiler/CompositeImageSettings.cs",
        "Compiler/CryptographicHashProvider.cs",
        "Compiler/DependencyAnalysis/AllMethodsOnTypeNode.cs",
        "Compiler/DependencyAnalysis/ArrayOfEmbeddedDataNode.cs",
        "Compiler/DependencyAnalysis/ArrayOfEmbeddedPointersNode.cs",
        "Compiler/DependencyAnalysis/EmbeddedObjectNode.cs",
        "Compiler/DependencyAnalysis/EmbeddedPointerIndirectionNode.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/ArgIterator.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/AssemblyTableNode.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/AttributePresenceFilterNode.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/ByteArrayComparer.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/CompilerIdentifierNode.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/CopiedCorHeaderNode.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/CopiedFieldRvaNode.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/CopiedManagedResourcesNode.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/CopiedMetadataBlobNode.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/CopiedMethodILNode.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/CopiedStrongNameSignatureNode.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/DebugDirectoryEntryNode.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/DebugDirectoryNode.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/DebugInfoTableNode.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/DeferredTillPhaseNode.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/DelayLoadHelperImport.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/DelayLoadHelperMethodImport.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/DelayLoadMethodCallThunkNodeRange.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/DelayLoadMethodImport.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/DelegateCtorSignature.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/DevirtualizationManager.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/EnclosingTypeMapNode.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/ExceptionInfoLookupTableNode.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/FieldFixupSignature.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/GCRefMapBuilder.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/GCRefMapNode.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/GenericLookupSignature.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/HeaderNode.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/HotColdMapNode.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/ILBodyFixupSignature.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/Import.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/ImportSectionNode.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/ImportSectionsTableNode.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/ImportThunk.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/InliningInfoNode.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/InstanceEntryPointTableNode.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/InstrumentationDataTableNode.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/ManifestAssemblyMvidHeaderNode.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/ManifestMetadataTableNode.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/MethodColdCodeNode.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/MethodEntryPointTableNode.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/MethodFixupSignature.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/MethodGCInfoNode.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/MethodIsGenericMapNode.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/MethodWithGCInfo.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/ModuleToken.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/ModuleTokenResolver.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/NewArrayFixupSignature.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/NewObjectFixupSignature.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/NibbleWriter.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/OwnerCompositeExecutableNode.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/PrecodeHelperImport.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/PrecodeMethodImport.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/ReadyToRunHelperSignature.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/ReadyToRunInstructionSetSupportSignature.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/RuntimeFunctionsGCInfoNode.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/RuntimeFunctionsTableNode.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/Signature.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/SignatureBuilder.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/SignatureContext.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/SignatureEmbeddedPointerIndirectionNode.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/StringImport.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/StringImportSignature.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/Target_ARM/ImportThunk.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/Target_ARM64/ImportThunk.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/Target_LoongArch64/ImportThunk.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/Target_RiscV64/ImportThunk.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/Target_X64/ImportThunk.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/Target_X86/ImportThunk.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/TransitionBlock.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/TypeFixupSignature.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/TypeGenericInfoMapNode.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/TypeValidationChecker.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/TypesTableNode.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/VirtualResolutionFixupSignature.cs",
        "Compiler/DependencyAnalysis/ReadyToRun/Win32ResourcesNode.cs",
        "Compiler/DependencyAnalysis/ReadyToRunCodegenNodeFactory.cs",
        "Compiler/DependencyAnalysis/ReadyToRunSymbolNodeFactory.cs",
        "Compiler/DependencyAnalysis/TypeAndMethod.cs",
        "Compiler/FileLayoutOptimizer.cs",
        "Compiler/IRootingServiceProvider.cs",
        "Compiler/Logger.cs",
        "Compiler/NoMethodsCompilationModuleGroup.cs",
        "Compiler/PerfEventSource.cs",
        "Compiler/PettisHansenSort/CallGraphNode.cs",
        "Compiler/PettisHansenSort/DisjointSetForest.cs",
        "Compiler/PettisHansenSort/PettisHansen.cs",
        "Compiler/ProfileData.cs",
        "Compiler/ProfileDataManager.cs",
        "Compiler/R2RTypeExtensions.cs",
        "Compiler/ReadyToRunCodegenCompilation.cs",
        "Compiler/ReadyToRunCodegenCompilationBuilder.cs",
        "Compiler/ReadyToRunCompilationModuleGroupBase.cs",
        "Compiler/ReadyToRunCompilerContext.cs",
        "Compiler/ReadyToRunLibraryRootProvider.cs",
        "Compiler/ReadyToRunMetadataFieldLayoutAlgorithm.cs",
        "Compiler/ReadyToRunProfilingRootProvider.cs",
        "Compiler/ReadyToRunSingleAssemblyCompilationModuleGroup.cs",
        "Compiler/ReadyToRunStandaloneMethodMetadata.cs",
        "Compiler/ReadyToRunTableManager.cs",
        "Compiler/ReadyToRunVisibilityRootProvider.cs",
        "Compiler/ReadyToRunXmlRootProvider.cs",
        "Compiler/RuntimeDeterminedTypeHelper.cs",
        "Compiler/SingleMethodCompilationModuleGroup.cs",
        "Compiler/SystemObjectFieldLayoutAlgorithm.cs",
        "Compiler/VersionResilientHashCode.ReadyToRun.cs",
        "IBC/IBCDataModel.cs",
        "IBC/IBCDataReader.cs",
        "IBC/IBCProfileData.cs",
        "IBC/IBCProfileParser.cs",
        "IBC/MIbcProfileParser.cs",
        "IBC/ReaderExtensions.cs",
        "IL/ReadyToRunILProvider.cs",
        "IL/Stubs/InstanceCalliHelperIntrinsics.cs",
        "IL/Stubs/PInvokeILEmitter.cs",
        "Interop/IL/Marshaller.ReadyToRun.cs",
        "JitInterface/CorInfoImpl.ReadyToRun.cs",
        "JitInterface/UnboxingMethodDescFactory.cs",
        "ObjectWriter/MapFileBuilder.cs",
        "ObjectWriter/OutputInfoBuilder.cs",
        "ObjectWriter/ProfileFileBuilder.cs",
        "ObjectWriter/R2RPEBuilder.cs",
        "ObjectWriter/RelocationHelper.cs",
        "ObjectWriter/SectionBuilder.cs",
        "ObjectWriter/SymbolFileBuilder.cs",
        "ObjectWriter/TargetExtensions.cs",
        "ObjectWriter/TypeString.cs",
        "TypeSystem/Mutable/MutableModule.Sorting.cs",
        "TypeSystem/Mutable/MutableModule.Symbols.cs",
        "TypeSystem/Mutable/MutableModule.cs",
    ] + [
        "//src/coreclr/tools/Common:Compiler/CodeGenerationFailedException.cs",
        "//src/coreclr/tools/Common:Compiler/CompilationBuilder.cs",
        "//src/coreclr/tools/Common:Compiler/CompilationModuleGroup.cs",
        "//src/coreclr/tools/Common:Compiler/CompilerTypeSystemContext.Validation.cs",
        "//src/coreclr/tools/Common:Compiler/CompilerTypeSystemContext.cs",
        "//src/coreclr/tools/Common:Compiler/Dataflow/DynamicallyAccessedMembersBinder.cs",
        "//src/coreclr/tools/Common:Compiler/Dataflow/EcmaExtensions.cs",
        "//src/coreclr/tools/Common:Compiler/Dataflow/GenericParameterProxy.cs",
        "//src/coreclr/tools/Common:Compiler/Dataflow/MethodProxy.cs",
        "//src/coreclr/tools/Common:Compiler/Dataflow/ParameterProxy.cs",
        "//src/coreclr/tools/Common:Compiler/Dataflow/TypeExtensions.cs",
        "//src/coreclr/tools/Common:Compiler/Dataflow/TypeProxy.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/AssemblyStubNode.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/CompilerComparer.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/EmbeddedDataContainerNode.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/IMethodBodyNode.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/IMethodNode.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/INodeWithCodeInfo.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/INodeWithRuntimeDeterminedDependencies.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/ISortableNode.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/ISymbolNode.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/MethodReadOnlyDataNode.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/ObjectDataBuilder.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/ObjectNode.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/ObjectNodeSection.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/Relocation.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/ShadowConcreteMethodNode.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/SortableDependencyNode.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/Target_ARM/ARMEmitter.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/Target_ARM/Register.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/Target_ARM/TargetRegisterMap.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/Target_ARM64/ARM64Emitter.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/Target_ARM64/AddrMode.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/Target_ARM64/Register.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/Target_ARM64/TargetRegisterMap.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/Target_LoongArch64/AddrMode.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/Target_LoongArch64/LoongArch64Emitter.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/Target_LoongArch64/Register.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/Target_LoongArch64/TargetRegisterMap.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/Target_RiscV64/AddrMode.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/Target_RiscV64/Register.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/Target_RiscV64/RiscV64Emitter.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/Target_RiscV64/TargetRegisterMap.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/Target_X64/AddrMode.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/Target_X64/Register.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/Target_X64/TargetRegisterMap.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/Target_X64/X64Emitter.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/Target_X86/AddrMode.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/Target_X86/Register.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/Target_X86/TargetRegisterMap.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/Target_X86/X86Emitter.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyTrackingLevel.cs",
        "//src/coreclr/tools/Common:Compiler/DevirtualizationManager.cs",
        "//src/coreclr/tools/Common:Compiler/DisplayNameHelpers.cs",
        "//src/coreclr/tools/Common:Compiler/EventPseudoDesc.cs",
        "//src/coreclr/tools/Common:Compiler/FeatureSettings.cs",
        "//src/coreclr/tools/Common:Compiler/HardwareIntrinsicHelpers.cs",
        "//src/coreclr/tools/Common:Compiler/ICompilationRootProvider.cs",
        "//src/coreclr/tools/Common:Compiler/InstructionSetSupport.cs",
        "//src/coreclr/tools/Common:Compiler/Int128FieldLayoutAlgorithm.cs",
        "//src/coreclr/tools/Common:Compiler/InternalCompilerErrorException.cs",
        "//src/coreclr/tools/Common:Compiler/MethodExtensions.cs",
        "//src/coreclr/tools/Common:Compiler/NameMangler.cs",
        "//src/coreclr/tools/Common:Compiler/NativeAotNameMangler.cs",
        "//src/coreclr/tools/Common:Compiler/ProcessLinkerXmlBase.cs",
        "//src/coreclr/tools/Common:Compiler/PropertyPseudoDesc.cs",
        "//src/coreclr/tools/Common:Compiler/PseudoDescExtensions.cs",
        "//src/coreclr/tools/Common:Compiler/SingleMethodRootProvider.cs",
        "//src/coreclr/tools/Common:Compiler/TypeExtensions.cs",
        "//src/coreclr/tools/Common:Compiler/TypePreserve.cs",
        "//src/coreclr/tools/Common:Compiler/VectorFieldLayoutAlgorithm.cs",
        "//src/coreclr/tools/Common:Compiler/Win32Resources/ResourceData.Reader.cs",
        "//src/coreclr/tools/Common:Compiler/Win32Resources/ResourceData.ResourcesDataModel.cs",
        "//src/coreclr/tools/Common:Compiler/Win32Resources/ResourceData.UpdateResourceDataModel.cs",
        "//src/coreclr/tools/Common:Compiler/Win32Resources/ResourceData.Win32Structs.cs",
        "//src/coreclr/tools/Common:Compiler/Win32Resources/ResourceData.cs",
        "//src/coreclr/tools/Common:Internal/NativeFormat/NativeFormat.cs",
        "//src/coreclr/tools/Common:Internal/NativeFormat/NativeFormatWriter.Primitives.cs",
        "//src/coreclr/tools/Common:Internal/NativeFormat/NativeFormatWriter.cs",
        "//src/coreclr/tools/Common:Internal/Runtime/CorConstants.cs",
        "//src/coreclr/tools/Common:Internal/Runtime/ModuleHeaders.cs",
        "//src/coreclr/tools/Common:Internal/Runtime/ReadyToRunConstants.cs",
        "//src/coreclr/tools/Common:Internal/Runtime/ReadyToRunInstructionSet.cs",
        "//src/coreclr/tools/Common:Internal/Runtime/ReadyToRunInstructionSetHelper.cs",
        "//src/coreclr/tools/Common:Internal/Runtime/RiscVLoongArch64FpStruct.cs",
        "//src/coreclr/tools/Common:Internal/Text/Utf8String.cs",
        "//src/coreclr/tools/Common:Internal/Text/Utf8StringBuilder.cs",
        "//src/coreclr/tools/Common:JitInterface/CorInfoHelpFunc.cs",
        "//src/coreclr/tools/Common:JitInterface/CorInfoImpl.cs",
        "//src/coreclr/tools/Common:JitInterface/CorInfoImpl_generated.cs",
        "//src/coreclr/tools/Common:JitInterface/CorInfoInstructionSet.cs",
        "//src/coreclr/tools/Common:JitInterface/CorInfoTypes.VarInfo.cs",
        "//src/coreclr/tools/Common:JitInterface/CorInfoTypes.cs",
        "//src/coreclr/tools/Common:JitInterface/IJitHashableOnly.cs",
        "//src/coreclr/tools/Common:JitInterface/JitConfigProvider.cs",
        "//src/coreclr/tools/Common:JitInterface/JitTypeNameFormatter.cs",
        "//src/coreclr/tools/Common:JitInterface/SwiftPhysicalLowering.cs",
        "//src/coreclr/tools/Common:JitInterface/SystemVStructClassificator.cs",
        "//src/coreclr/tools/Common:JitInterface/UnboxingMethodDesc.cs",
        "//src/coreclr/tools/Common:Pgo/PgoFormat.cs",
        "//src/coreclr/tools/Common:Pgo/TypeSystemEntityOrUnknown.cs",
        "//src/coreclr/tools/Common:System/Collections/Generic/ArrayBuilder.cs",
        "//src/coreclr/tools/Common:System/FormattingHelpers.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/HelperExtensions.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/ILProvider.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/ILReader.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/Stubs/ComparerIntrinsics.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/Stubs/InterlockedIntrinsics.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/Stubs/PInvokeILCodeStreams.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/Stubs/RuntimeHelpersIntrinsics.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/Stubs/UnsafeIntrinsics.cs",
        "//src/coreclr/tools/Common:TypeSystem/Interop/IL/MarshalHelpers.cs",
        "//src/coreclr/tools/Common:TypeSystem/Interop/IL/MarshalUtils.cs",
        "//src/coreclr/tools/Common:TypeSystem/Interop/IL/Marshaller.cs",
        "//src/coreclr/tools/Common:TypeSystem/Interop/IL/MarshallerKind.cs",
        "//src/coreclr/tools/Common:TypeSystem/Interop/InteropTypes.cs",
        "//src/coreclr/tools/Common:TypeSystem/Interop/UnmanagedCallingConventions.cs",
        "//src/coreclr/tools/Common:TypeSystem/MetadataEmitter/TypeSystemMetadataEmitter.cs",
    ] + [
        "//src/coreclr/tools/aot/ILCompiler.Reflection.ReadyToRun:PEReaderExtensions.cs",
        "//src/libraries/Common:src/Internal/VersionResilientHashCode.cs",
        "//src/tools/illink/src/ILLink.Shared:ClosedAttribute.cs",
        "//src/tools/illink/src/ILLink.Shared:DynamicallyAccessedMemberTypesEx.cs",
        "//src/tools/illink/src/ILLink.Shared:ParameterIndex.cs",
        "//src/tools/illink/src/ILLink.Shared:TrimAnalysis/ReferenceKind.cs",
        "//src/tools/illink/src/ILLink.Shared:TypeSystemProxy/GenericParameterProxy.cs",
        "//src/tools/illink/src/ILLink.Shared:TypeSystemProxy/IMemberProxy.cs",
        "//src/tools/illink/src/ILLink.Shared:TypeSystemProxy/MethodProxy.cs",
        "//src/tools/illink/src/ILLink.Shared:TypeSystemProxy/ParameterCollection.cs",
        "//src/tools/illink/src/ILLink.Shared:TypeSystemProxy/ParameterProxy.cs",
        "//src/tools/illink/src/ILLink.Shared:TypeSystemProxy/TypeProxy.cs",
        "//src/tools/illink/src/ILLink.Shared:TypeSystemProxy/WellKnownType.cs",
        "//src/coreclr/tools/Common:Compiler/GenericCycleDetection/Graph.cs",
        "//src/coreclr/tools/Common:Compiler/GenericCycleDetection/Graph.Cycles.cs",
        "//src/coreclr/tools/Common:Compiler/GenericCycleDetection/Graph.Vertex.cs",
        "//src/coreclr/tools/Common:Compiler/GenericCycleDetection/GraphBuilder.cs",
        "//src/coreclr/tools/Common:Compiler/GenericCycleDetection/GraphBuilder.ForEach.cs",
        "//src/coreclr/tools/Common:Compiler/GenericCycleDetection/GraphBuilder.MethodCall.cs",
        "//src/coreclr/tools/Common:Compiler/GenericCycleDetection/ModuleCycleInfo.cs",
    ],
    defines = ["READYTORUN"],
    compiler_options = ["/unsafe", "/warnaserror+:NU1605"],
    deps = [
        "//src/coreclr/tools/aot/ILCompiler.DependencyAnalysisFramework",
        "//src/coreclr/tools/aot/ILCompiler.Diagnostics",
        "//src/coreclr/tools/aot/ILCompiler.TypeSystem",
        "@paket.main//microsoft.diasymreader",
    ],
    target_frameworks = ["net10.0"],
    visibility = ["//visibility:public"],
    analyzers = [
        "//src/tools/illink/src/ILLink.RoslynAnalyzer",
        "//:staticcs_analyzers",
    ],
    msbuild_analyzer_config = "style",
    include_default_ruleset = False,
    skip_analyzers = True,
)
