load("//src/libraries:defs.bzl", "netcoreapp_impl_assembly")

netcoreapp_impl_assembly(
    name = "impl_System.Xml.Linq",
    skip_cs1591 = True,
    srcs = [
        "src/System.Xml.Linq.cs",
    ],
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Xml.XDocument:ref_System.Xml.XDocument",
        "//src/libraries/System.Xml.XPath.XDocument:ref_System.Xml.XPath.XDocument",
    ],
    os_targeted = True,
    exclude_sr = True,
    assembly_version = "4.0.0.0",
)
