load("@bazel_skylib//lib:dicts.bzl", "dicts")
load("@rules_dotnet//dotnet:defs.bzl", "compile_csharp_exe")
load("@rules_dotnet//dotnet/private/transitions:tfm_transition.bzl", "tfm_transition")
load("@rules_dotnet//dotnet/private/rules/common:attrs.bzl", "CSHARP_BINARY_COMMON_ATTRS")
load(
    "@rules_dotnet//dotnet/private:providers.bzl",
    "DotnetApphostPackInfo",
    "DotnetBinaryInfo",
    "DotnetRuntimePackInfo",
    "DotnetAssemblyCompileInfo",
    "DotnetAssemblyRuntimeInfo",
)
load("@rules_dotnet//dotnet/private/transitions:default_transition.bzl", "default_transition")
load(
    "@rules_dotnet//dotnet/private:common.bzl",
    "collect_transitive_runfiles",
    "generate_depsjson",
    "generate_runtimeconfig",
    "is_core_framework",
    "is_standard_framework",
    "to_rlocation_path",
)
load("@rules_dotnet//dotnet/private/macros:register_tfms.bzl", "get_tfm_value")
load("@rules_dotnet//dotnet/private/sdk/targeting_packs:targeting_pack_transition.bzl", "targeting_pack_transition")
load("//:defs.bzl", "csharp_library")
load("//src/libraries:defs.bzl", "LIVE_REFPACK_DEPS")

# Label for the Roslyn compiler server persistent worker binary.
_SHARED_COMPILATION_WORKER = "@rules_dotnet//dotnet/private/tools/compiler_worker"

COMMON_ATTRS = {
    "deps": attr.label_list(
        doc = "Other libraries, binaries, or imported DLLs",
        providers = [DotnetAssemblyCompileInfo, DotnetAssemblyRuntimeInfo],
        cfg = tfm_transition,
    ),
    "data": attr.label_list(
        doc = "Runtime files. It is recommended to use the @rules_dotnet//tools/runfiles library to read the runtime files.",
        allow_files = True,
        default = [],
        allow_empty = True,
        # We transition to the default configuration because the end user might have dotnet binaries
        # in their data and we want the TFM graphs to be disconnected
        cfg = default_transition,
    ),
    "compile_data": attr.label_list(
        doc = "Additional compile time files.",
        allow_files = True,
        default = [],
        allow_empty = True,
        # We transition to the default configuration because the end user might have dotnet binaries
        # in their compile_data and we want the TFM graphs to be disconnected
        cfg = default_transition,
    ),
    "appsetting_files": attr.label_list(
        doc = "A list of appsettings files to include in the output directory.",
        allow_files = True,
        default = [],
        allow_empty = True,
        # We transition to the default configuration because the end user might have dotnet binaries
        # in their appsetting_files and we want the TFM graphs to be disconnected
        cfg = default_transition,
    ),
    "srcs": attr.label_list(
        doc = "The source files used in the compilation.",
        allow_files = [".cs"],
        # We transition to the default configuration because the end user might have srcs
        # that is generated by a dotnet binary
        cfg = default_transition,
    ),
    "out": attr.string(
        doc = "File name, without extension, of the built assembly.",
    ),
    "project_sdk": attr.string(
        doc = "The project SDK that is being targeted. " +
            "See https://learn.microsoft.com/en-us/dotnet/core/project-sdk/overview",
        default = "default",
        values = ["default", "web"],
    ),
    "generate_documentation_file": attr.bool(
        doc = "Whether or not to generate a documentation file.",
        default = True,
    ),
    "defines": attr.string_list(
        doc = "A list of preprocessor directive symbols to define.",
        default = [],
        allow_empty = True,
    ),
    "internals_visible_to": attr.string_list(
        doc = "Other libraries that can see the assembly's internal symbols. Using this rather than the InternalsVisibleTo assembly attribute will improve build caching.",
    ),
    "assembly_version": attr.string(
        doc = "The assembly version.",
    ),
    "cls_compliant": attr.bool(
        doc = "Whether the assembly is CLS compliant.",
        default = False,
    ),
    "keyfile": attr.label(
        doc = "The key file used to sign the assembly with a strong name.",
        allow_single_file = True,
        # We transition to the default configuration because the end user might have a keyfile
        # that is generated by a dotnet binary
        cfg = default_transition,
    ),
    "langversion": attr.string(
        doc = "The version string for the language.",
    ),
    "resources": attr.label_list(
        doc = "A list of files to embed in the DLL as resources.",
        allow_files = True,
        # We transition to the default configuration because the end user might have resources
        # that is generated by a dotnet binary
        cfg = default_transition,
    ),
    "resource_logical_names": attr.string_dict(
        doc = "A mapping of resource file basenames to their explicit manifest resource names.",
    ),
    "additionalfiles": attr.label_list(
        doc = "Extra files to configure analyzers.",
        allow_files = True,
        # We transition to the default configuration because the end user might have additional files
        # that is generated by a dotnet binary
        cfg = default_transition,
    ),
    "analyzers": attr.label_list(
        doc = "Additional analyzer assemblies.",
        providers = [DotnetAssemblyCompileInfo, DotnetAssemblyRuntimeInfo],
    ),
    "analyzer_configs": attr.label_list(
        doc = "A list of analyzer configuration files.",
        allow_files = True,
        allow_empty = True,
        cfg = default_transition,
    ),
    "treat_warnings_as_errors": attr.bool(
        doc = "Treat all compiler warnings as errors. Note that this attribute can not be used in conjunction with warnings_as_errors.",
        mandatory = False,
        default = False,
    ),
    "target_frameworks": attr.string_list(
        doc = "A list of target framework monikers to build" +
            "See https://docs.microsoft.com/en-us/dotnet/standard/frameworks",
        mandatory = True,
        allow_empty = False,
    ),
    "disable_implicit_framework_refs": attr.bool(
        doc = "Disable implicit framework references. This is useful when you want to control the framework references yourself.",
        default = True,
    ),
    "warnings_as_errors": attr.string_list(
        doc = "List of compiler warning codes that should be considered as errors. Note that this attribute can not be used in conjunction with treat_warning_as_errors.",
        mandatory = False,
        default = [],
    ),
    "warnings_not_as_errors": attr.string_list(
        doc = "List of compiler warning codes that should not be considered as errors. Note that this attribute can only be used in conjunction with treat_warning_as_errors.",
        mandatory = False,
        default = [],
    ),
    "warning_level": attr.int(
        doc = "The warning level that should be used by the compiler.",
        mandatory = False,
        values = [0, 1, 2, 3, 4, 5],
        default = 3,
    ),
    "nowarn": attr.string_list(
        doc = "List of warnings that should be ignored",
        mandatory = False,
        default = ["CS1701", "CS1702"],
    ),
    "allow_unsafe_blocks": attr.bool(
        doc = "Allow compiling unsafe code. It true, /unsafe is passed to the compiler.",
        mandatory = False,
        default = False,
    ),
    "nullable": attr.string(
        doc = "Enable nullable context, or nullable warnings.",
        mandatory = False,
        default = "disable",
        values = ["disable", "enable", "warnings", "annotations"],
    ),
    "run_analyzers": attr.bool(
        doc = "Controls whether analyzers run at build time.",
        mandatory = False,
        default = True,
    ),
    "compiler_options": attr.string_list(
        doc = "Additional options to pass to the compiler. This attribute should only be used if the compiler flag has not already been exposed as an attribute.",
        mandatory = False,
        default = [],
    ),
    "use_shared_compilation": attr.bool(
        doc = "When True, uses the Roslyn compiler server via a Bazel persistent worker.",
        default = True,
    ),
    "shared_compilation_worker": attr.label(
        doc = "Internal: the persistent worker binary for shared compilation.",
        default = None,
        executable = True,
        cfg = default_transition,
    ),
    "roll_forward_behavior": attr.string(
        doc = "The roll forward behavior that should be used: https://learn.microsoft.com/en-us/dotnet/core/versions/selection#control-roll-forward-behavior",
        default = "Major",
        values = ["Minor", "Major", "LatestPatch", "LatestMinor", "LatestMajor", "Disable"],
    ),
    "_target_framework": attr.label(
        default = "@rules_dotnet//dotnet:target_framework",
    ),
    "_windows_constraint": attr.label(default = "@platforms//os:windows"),
    "_compiler_wrapper_sh": attr.label(
        default = "@rules_dotnet//dotnet/private:compiler_wrapper.sh",
        executable = True,
        cfg = "exec",
        allow_single_file = True,
    ),
    "_compiler_wrapper_bat": attr.label(
        default = "@rules_dotnet//dotnet/private:compiler_wrapper.bat",
        executable = True,
        cfg = "exec",
        allow_single_file = True,
    ),
    "_bash_runfiles": attr.label(
        default = "@bazel_tools//tools/bash/runfiles",
        allow_files = True,
    ),
    "_targeting_pack": attr.label(
        default = "@rules_dotnet//dotnet/private/sdk/targeting_packs:targeting_pack",
        cfg = targeting_pack_transition,
    ),
    "_core_root": attr.label(
        doc = "The host binary to use for the launcher",
        default = "//:Core_Root",
        allow_single_file = True,
    ),
    "include_host_model_dll": attr.bool(
        doc = "Whether to include Microsoft.NET.HostModel from the toolchain. This is only required to build tha apphost shimmer.",
        default = False,
    ),
    "is_aot_compatible": attr.bool(
        doc = "Whether this binary is compatible with Native AOT compilation.",
        default = False,
    ),
    "_illink_analyzers_net8": attr.label(
        default = "@nuget.microsoft.net.illink.tasks.v8.0.22//:analyzers_csharp",
        allow_files = True,
    ),
    "_illink_analyzers_net9": attr.label(
        default = "@nuget.microsoft.net.illink.tasks.v9.0.11//:analyzers_csharp",
        allow_files = True,
    ),
    "_illink_analyzers_net10": attr.label(
        default = "@nuget.microsoft.net.illink.tasks.v10.0.0//:analyzers_csharp",
        allow_files = True,
    ),
}

def _live_csharp_binary_impl(ctx):
    result = build_binary(ctx, compile_csharp_exe)
    return result

_live_csharp_binary_rule = rule(
    _live_csharp_binary_impl,
    doc = """Compile a C# exe for the live framework""",
    attrs = dicts.add(COMMON_ATTRS, {
        "_launcher_sh": attr.label(
            doc = "A template file for the launcher on Linux/MacOS",
            default = "//eng:run_binary.sh.tpl",
            allow_single_file = True,
        )}),
    executable = True,
    toolchains = [
        "@rules_dotnet//dotnet:toolchain_type",
    ],
    cfg = tfm_transition,
)

def live_csharp_binary(
    name,
    deps = [],
    use_shared_compilation = True,
    **kwargs
):
    deps = deps + LIVE_REFPACK_DEPS
    _live_csharp_binary_rule(
        name = name,
        deps = deps,
        use_shared_compilation = use_shared_compilation,
        shared_compilation_worker = _SHARED_COMPILATION_WORKER if use_shared_compilation else None,
        **kwargs
    )

def create_launcher(ctx, runfiles, entry_dll):
    windows_constraint = ctx.attr._windows_constraint[platform_common.ConstraintValueInfo]

    launcher = ctx.actions.declare_file("{}.{}".format(entry_dll.basename, "bat" if ctx.target_platform_has_constraint(windows_constraint) else "sh"), sibling = entry_dll)

    ctx.actions.expand_template(
        template = ctx.file._launcher_sh,
        output = launcher,
        substitutions = {
            "TEMPLATED_core_root": to_rlocation_path(ctx, ctx.file._core_root),
            "TEMPLATED_entry_dll": to_rlocation_path(ctx, entry_dll),
        },
        is_executable = True,
    )
    runfiles.append(ctx.file._core_root)
    runfiles.extend(ctx.files._bash_runfiles)

    return launcher

# Hints for Bazel spawn strategy
COPY_EXECUTION_REQUIREMENTS = {
    # ----------------+-----------------------------------------------------------------------------
    # no-remote       | Prevents the action or test from being executed remotely or cached remotely.
    #                 | This is equivalent to using both `no-remote-cache` and `no-remote-exec`.
    # ----------------+-----------------------------------------------------------------------------
    # no-cache        | Results in the action or test never being cached (remotely or locally)
    # ----------------+-----------------------------------------------------------------------------
    # See https://bazel.build/reference/be/common-definitions#common-attributes
    #
    # Copying file & directories is entirely IO-bound and there is no point doing this work
    # remotely.
    #
    # Also, remote-execution does not allow source directory inputs, see
    # https://github.com/bazelbuild/bazel/commit/c64421bc35214f0414e4f4226cc953e8c55fa0d2 So we must
    # not attempt to execute remotely in that case.
    #
    # There is also no point pulling the output file or directory from the remote cache since the
    # bytes to copy are already available locally. Conversely, no point in writing to the cache if
    # no one has any reason to check it for this action.
    #
    # Read and writing to disk cache is disabled as well primarily to reduce disk usage on the local
    # machine. A disk cache hit of a directory copy could be slghtly faster than a copy since the
    # disk cache stores the directory artifact as a single entry, but the slight performance bump
    # comes at the cost of heavy disk cache usage, which is an unmanaged directory that grow beyond
    # the bounds of the physical disk.
    "no-remote": "1",
    "no-cache": "1",
}

def build_binary(ctx, compile_action):
    """Builds a .Net binary from a compilation action

    Args:
        ctx: Bazel build ctx.
        compile_action: A compilation function
            Args:
                ctx: Bazel build ctx.
                tfm: Target framework string
            Returns:
                An DotnetAssemblyInfo provider
    Returns:
        A collection of the references, runfiles and native dlls.
    """
    tfm = get_tfm_value(ctx.attr._target_framework)

    if is_standard_framework(tfm):
        fail("It doesn't make sense to build an executable for " + tfm)

    (compile_provider, runtime_provider) = compile_action(ctx, tfm)
    dll = runtime_provider.libs[0]
    default_info_files = [dll] + runtime_provider.xml_docs + runtime_provider.appsetting_files.to_list()
    additional_runfiles = []

    launcher = create_launcher(ctx, additional_runfiles, dll)

    runtimeconfig = None
    depsjson = None
    transitive_runtime_deps = runtime_provider.deps.to_list()

    if is_core_framework(tfm):
        # Create the runtimeconfig.json for the binary
        runtimeconfig = ctx.actions.declare_file("%s/%s/%s.runtimeconfig.json" % (ctx.label.name, tfm, ctx.attr.out or ctx.attr.name))
        runtimeconfig_struct = generate_runtimeconfig(
            target_framework = tfm,
            project_sdk = ctx.attr.project_sdk,
            is_self_contained = False,
            roll_forward_behavior = ctx.attr.roll_forward_behavior,
        )

        ctx.actions.write(
            output = runtimeconfig,
            content = json.encode_indent(runtimeconfig_struct),
        )

        depsjson = ctx.actions.declare_file("%s/%s/%s.deps.json" % (ctx.label.name, tfm, ctx.attr.out or ctx.attr.name))
        depsjson_struct = generate_depsjson(
            ctx,
            target_framework = tfm,
            is_self_contained = False,
            target_assembly_runtime_info = runtime_provider,
            transitive_runtime_deps = transitive_runtime_deps,
            use_relative_paths = True,
        )

        ctx.actions.write(
            output = depsjson,
            content = json.encode_indent(depsjson_struct),
        )

    if runtimeconfig != None:
        additional_runfiles.append(runtimeconfig)

    if depsjson != None:
        additional_runfiles.append(depsjson)

    for dep in transitive_runtime_deps:
        for lib in dep.libs:
            if lib.extension == "dll":
                src = lib
                dst = ctx.actions.declare_file("%s/%s/%s" % (ctx.label.name, tfm, lib.basename))
                ctx.actions.run_shell(
                    inputs = [src],
                    outputs = [dst],
                    command = "cp -f \"$1\" \"$2\"",
                    arguments = [src.path, dst.path],
                    mnemonic = "CopyFile",
                    progress_message = "Copying files",
                    use_default_shell_env = True,
                    execution_requirements = COPY_EXECUTION_REQUIREMENTS,
                )
                additional_runfiles.append(dst)

    default_info = DefaultInfo(
        executable = launcher,
        runfiles = collect_transitive_runfiles(ctx, runtime_provider, ctx.attr.deps).merge(ctx.runfiles(files = additional_runfiles)).merge(ctx.attr._bash_runfiles[DefaultInfo].default_runfiles),
        files = depset(default_info_files),
    )

    return [default_info, compile_provider, runtime_provider]
