load("//src/libraries:defs.bzl", "MULTITARGET_NOWARN", "netcoreapp_ref_assembly", "impl_assembly", "ref_impl_pair")

exports_files([
    "ref/System.Management.cs",
    "ref/System.Management.manual.cs",
])

netcoreapp_ref_assembly(
    name = "ref_System.Management",
    srcs = [
        "ref/System.Management.cs",
        "ref/System.Management.manual.cs",
    ],
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries:ref_System.ComponentModel.Primitives",
        "//src/libraries/System.CodeDom:ref_System.CodeDom",
        "//src/libraries/System.Collections.Specialized:ref_System.Collections.Specialized",
        "//src/libraries/System.ComponentModel.TypeConverter:ref_System.ComponentModel.TypeConverter",
        "//src/libraries/System.ObjectModel:ref_System.ObjectModel",
        "//src/libraries/System.Runtime.InteropServices:ref_System.Runtime.InteropServices",
    ],
)

impl_assembly(
    name = "impl_System.Management",
    include_runtime_async = False,
    event_source_generator = False,
    include_editorconfig = False,
    pnse = True,
    pnse_message = "SR.PlatformNotSupported_SystemManagement",
    pnse_ref_srcs = [
        "ref/System.Management.cs",
        "ref/System.Management.manual.cs",
    ],
    srcs = [],
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries:ref_System.ComponentModel.Primitives",
        "//src/libraries/System.CodeDom:ref_System.CodeDom",
        "//src/libraries/System.Collections.Specialized:ref_System.Collections.Specialized",
        "//src/libraries/System.ComponentModel.TypeConverter:ref_System.ComponentModel.TypeConverter",
        "//src/libraries/System.ObjectModel:ref_System.ObjectModel",
        "//src/libraries/System.Runtime.InteropServices:ref_System.Runtime.InteropServices",
    ],
    resx_file = "src/Resources/Strings.resx",
    analyzers = [
        "//src/libraries/System.Text.Json:JsonSourceGenerator",
        "//src/libraries/System.Text.RegularExpressions:RegexGenerator",
    ],
    com_interface_generator = True,
    supported_os_platforms_short = ["windows"],
    nullable = "disable",
    nowarn = MULTITARGET_NOWARN + ["CP0003", "CS0618", "CA1822", "IDE0059", "NU5128", "CS1591"],
    allow_unsafe_blocks = True,
)

ref_impl_pair(
    name = "live_System.Management",
    ref = ":ref_System.Management",
    lib = ":impl_System.Management",
    visibility = ["//visibility:public"],
)
