load("//:defs.bzl", "ECMA_SNK")
load("//src/libraries:defs.bzl", "netcoreapp_impl_assembly")

netcoreapp_impl_assembly(
    name = "impl_System.Data.DataSetExtensions",
    keyfile = ECMA_SNK,
    generate_documentation_file = False,
    library_import_generator = False,
    skip_locals_init = False,
    srcs = ["src/System.Data.DataSetExtensions.cs"],
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Data.Common:ref_System.Data.Common",
    ],
    os_targeted = True,
    exclude_sr = True,
)
