
load("//src/tests:live_test.bzl", "coreclr_merged_test")

coreclr_merged_test(
    name = "merged_3",
    deps = [
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    test_deps = [
        "//src/tests/JIT/Directed/Arrays:nintindexoutofrange",
        "//src/tests/JIT/Directed/physicalpromotion:addressinterference",
        "//src/tests/JIT/Directed/physicalpromotion:fuzzlyn1",
        "//src/tests/JIT/Directed/physicalpromotion:fuzzlyn2",
        "//src/tests/JIT/Directed/physicalpromotion:mixedpromotion",
        "//src/tests/JIT/Directed/physicalpromotion:physicalpromotion",
        "//src/tests/JIT/Directed/physicalpromotion:readbackbeforeqmark",
    ],
)

#JIT/Directed/StructPromote/Unsafe/AccessInvalidFieldOffset/AccessInvalidFieldOffset.dll
#JIT/Directed/debugging/debuginfo/attribute/attribute.dll
#JIT/Directed/zeroinit/Dev10_863995/Dev10_863995.dll
#JIT/Directed/ExcepFilters/excepobj/excepobj/excepobj.dll
#JIT/Directed/ExcepFilters/fault/fault/fault.dll
#JIT/Directed/throwbox/fault_throwbox/fault_throwbox.dll
#JIT/Directed/StructABI/FieldListByteNodeTypeMismatchX86/FieldListByteNodeTypeMismatchX86.dll
#JIT/Directed/throwbox/filter/filter.dll
#JIT/Directed/throwbox/finally/finally.dll
#JIT/Directed/ConstantFolding/folding_extends_int32_on_64_bit_hosts/folding_extends_int32_on_64_bit_hosts.dll
#JIT/Directed/Misc/gettype/gettypetypeofmatrix_gettype/gettypetypeofmatrix_gettype.dll
#JIT/Directed/gettypetypeof/gettypetypeofmatrix_gettypetypeof/gettypetypeofmatrix_gettypetypeof.dll
#JIT/Directed/ConstantFolding/HandlesInAddrModes/HandlesInAddrModes.dll
#JIT/Directed/zeroinit/init_struct/init_struct.dll
#JIT/Directed/IL/Tailcall/jitTailcall1/jitTailcall1.dll
#JIT/Directed/Convert/ldind_conv/ldind_conv.dll
#JIT/Directed/IL/leave/leave1/leave1.dll
#JIT/Directed/UnrollLoop/loop3_r/loop3_r.dll
#JIT/Directed/UnrollLoop/loop4_cs_do/loop4_cs_do.dll
#JIT/Directed/UnrollLoop/loop4_cs_ro/loop4_cs_ro.dll
#JIT/Directed/StructABI/MisSizedStructs/MisSizedStructs.dll
#JIT/Directed/StructABI/MisSizedStructs_ArmArch/MisSizedStructs_ArmArch.dll
#JIT/Directed/ExcepFilters/mixed3/mixed3/mixed3.dll
#JIT/Directed/IL/mutualrecur-tailcall/MutualRecur-TailCall/MutualRecur-TailCall.dll
#JIT/Directed/Misc/function_pointer/MutualThdRecur-fptr/MutualThdRecur-fptr.dll
#JIT/Directed/forceinlining/NegativeCases/NegativeCases.dll
#JIT/Directed/newarr/newarr/newarr.dll
#JIT/Directed/RVAInit/oddsize/oddsize.dll
#JIT/Directed/debugging/poisoning/poison/poison.dll
#JIT/Directed/StructPromote/Unsafe/ReadDoubleFromIntOffset/ReadDoubleFromIntOffset.dll
#JIT/Directed/StructPromote/Unsafe/ReadStructAsAnotherType/ReadStructAsAnotherType.dll
#JIT/Directed/throwbox/rethrow/rethrow.dll
#JIT/Directed/IL/rethrow/Rethrow1/Rethrow1.dll
#JIT/Directed/IL/rethrow/Rethrow2/Rethrow2.dll
#JIT/Directed/StructABI/SevenByteStruct/SevenByteStruct.dll
#JIT/Directed/Convert/signed_overflow_conversions_are_not_treated_as_unsigned/signed_overflow_conversions_are_not_treated_as_unsigned.dll
#JIT/Directed/StrAccess/straccess1_cs_ro/straccess1_cs_ro.dll
#JIT/Directed/StrAccess/straccess2_cs_do/straccess2_cs_do.dll
#JIT/Directed/StrAccess/straccess2_cs_ro/straccess2_cs_ro.dll
#JIT/Directed/StrAccess/straccess3_cs_d/straccess3_cs_d.dll
#JIT/Directed/StrAccess/straccess3_cs_do/straccess3_cs_do.dll
#JIT/Directed/StrAccess/straccess3_cs_r/straccess3_cs_r.dll
#JIT/Directed/StrAccess/straccess3_cs_ro/straccess3_cs_ro.dll
#JIT/Directed/StructABI/structfieldparam_r/structfieldparam_r.dll
#JIT/Directed/StructABI/structfieldparam_ro/structfieldparam_ro.dll
#JIT/Directed/StructABI/structreturn/structreturn.dll
#JIT/Directed/StructABI/StructWithOverlappingFields/StructWithOverlappingFields.dll
#JIT/Directed/zeroinit/tail_zeroinit/tail_zeroinit.dll
#Common/CoreCLRTestLibrary/CoreCLRTestLibrary/TestLibrary.dll
#JIT/Directed/debugging/debuginfo/tests_d/tests_d.dll
#JIT/Directed/debugging/debuginfo/tests_r/tests_r.dll
#JIT/Directed/StructABI/TypeMismatchedArgs/TypeMismatchedArgs.dll
#JIT/Directed/VectorABI/VectorMgdMgdArray_r/VectorMgdMgdArray_r.dll
#JIT/Directed/VectorABI/VectorMgdMgdArray_ro/VectorMgdMgdArray_ro.dll
#JIT/Directed/VectorABI/VectorMgdMgdStatic_r/VectorMgdMgdStatic_r.dll
#JIT/Directed/VectorABI/VectorMgdMgdStatic_ro/VectorMgdMgdStatic_ro.dll
#JIT/Directed/VectorABI/VectorMgdMgd_r/VectorMgdMgd_r.dll
#Common/XUnitWrapperLibrary/XUnitWrapperLibrary/XUnitWrapperLibrary.dll
#JIT/Directed/array-il/_Arrayscomplex3/_Arrayscomplex3.dll
coreclr_merged_test(
    name = "Directed_2",
    deps = [
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    test_deps = [
        "//src/tests/JIT/Directed/PREFIX/PrimitiveVT:callconv1_PREFIX_cs_d",
        "//src/tests/JIT/Directed/PREFIX/PrimitiveVT:callconv1_PREFIX_cs_do",
        "//src/tests/JIT/Directed/PREFIX/PrimitiveVT:callconv1_PREFIX_cs_r",
        "//src/tests/JIT/Directed/PREFIX/PrimitiveVT:callconv1_PREFIX_cs_ro",
        "//src/tests/JIT/Directed/PREFIX/PrimitiveVT:callconv2_PREFIX_cs_d",
        "//src/tests/JIT/Directed/PREFIX/PrimitiveVT:callconv2_PREFIX_cs_do",
        "//src/tests/JIT/Directed/PREFIX/PrimitiveVT:callconv2_PREFIX_cs_r",
        "//src/tests/JIT/Directed/PREFIX/PrimitiveVT:callconv2_PREFIX_cs_ro",
        "//src/tests/JIT/Directed/cmov:Bool_And_Op_cs_d",
        "//src/tests/JIT/Directed/cmov:Bool_And_Op_cs_do",
        "//src/tests/JIT/Directed/cmov:Bool_And_Op_cs_r",
        "//src/tests/JIT/Directed/cmov:Bool_And_Op_cs_ro",
        "//src/tests/JIT/Directed/cmov:Bool_No_Op_cs_d",
        "//src/tests/JIT/Directed/cmov:Bool_No_Op_cs_do",
        "//src/tests/JIT/Directed/cmov:Bool_No_Op_cs_r",
        "//src/tests/JIT/Directed/cmov:Bool_No_Op_cs_ro",
        "//src/tests/JIT/Directed/cmov:Bool_Or_Op_cs_d",
        "//src/tests/JIT/Directed/cmov:Bool_Or_Op_cs_do",
        "//src/tests/JIT/Directed/cmov:Bool_Or_Op_cs_r",
        "//src/tests/JIT/Directed/cmov:Bool_Or_Op_cs_ro",
        "//src/tests/JIT/Directed/cmov:Bool_Xor_Op_cs_d",
        "//src/tests/JIT/Directed/cmov:Bool_Xor_Op_cs_do",
        "//src/tests/JIT/Directed/cmov:Bool_Xor_Op_cs_r",
        "//src/tests/JIT/Directed/cmov:Bool_Xor_Op_cs_ro",
        "//src/tests/JIT/Directed/cmov:Double_And_Op_cs_d",
        "//src/tests/JIT/Directed/cmov:Double_And_Op_cs_do",
        "//src/tests/JIT/Directed/cmov:Double_And_Op_cs_r",
        "//src/tests/JIT/Directed/cmov:Double_And_Op_cs_ro",
        "//src/tests/JIT/Directed/cmov:Double_No_Op_cs_d",
        "//src/tests/JIT/Directed/cmov:Double_No_Op_cs_do",
        "//src/tests/JIT/Directed/cmov:Double_No_Op_cs_r",
        "//src/tests/JIT/Directed/cmov:Double_No_Op_cs_ro",
        "//src/tests/JIT/Directed/cmov:Double_Or_Op_cs_d",
        "//src/tests/JIT/Directed/cmov:Double_Or_Op_cs_do",
        "//src/tests/JIT/Directed/cmov:Double_Or_Op_cs_r",
        "//src/tests/JIT/Directed/cmov:Double_Or_Op_cs_ro",
        "//src/tests/JIT/Directed/cmov:Double_Xor_Op_cs_d",
        "//src/tests/JIT/Directed/cmov:Double_Xor_Op_cs_do",
        "//src/tests/JIT/Directed/cmov:Double_Xor_Op_cs_r",
        "//src/tests/JIT/Directed/cmov:Double_Xor_Op_cs_ro",
        "//src/tests/JIT/Directed/cmov:Float_And_Op_cs_d",
        "//src/tests/JIT/Directed/cmov:Float_And_Op_cs_do",
        "//src/tests/JIT/Directed/cmov:Float_And_Op_cs_r",
        "//src/tests/JIT/Directed/cmov:Float_And_Op_cs_ro",
        "//src/tests/JIT/Directed/cmov:Float_No_Op_cs_d",
        "//src/tests/JIT/Directed/cmov:Float_No_Op_cs_do",
        "//src/tests/JIT/Directed/cmov:Float_No_Op_cs_r",
        "//src/tests/JIT/Directed/cmov:Float_No_Op_cs_ro",
        "//src/tests/JIT/Directed/cmov:Float_Or_Op_cs_d",
        "//src/tests/JIT/Directed/cmov:Float_Or_Op_cs_do",
        "//src/tests/JIT/Directed/cmov:Float_Or_Op_cs_r",
        "//src/tests/JIT/Directed/cmov:Float_Or_Op_cs_ro",
        "//src/tests/JIT/Directed/cmov:Float_Xor_Op_cs_d",
        "//src/tests/JIT/Directed/cmov:Float_Xor_Op_cs_do",
        "//src/tests/JIT/Directed/cmov:Float_Xor_Op_cs_r",
        "//src/tests/JIT/Directed/cmov:Float_Xor_Op_cs_ro",
        "//src/tests/JIT/Directed/cmov:Int_And_Op_cs_d",
        "//src/tests/JIT/Directed/cmov:Int_And_Op_cs_do",
        "//src/tests/JIT/Directed/cmov:Int_And_Op_cs_r",
        "//src/tests/JIT/Directed/cmov:Int_And_Op_cs_ro",
        "//src/tests/JIT/Directed/cmov:Int_No_Op_cs_d",
        "//src/tests/JIT/Directed/cmov:Int_No_Op_cs_do",
        "//src/tests/JIT/Directed/cmov:Int_No_Op_cs_r",
        "//src/tests/JIT/Directed/cmov:Int_No_Op_cs_ro",
        "//src/tests/JIT/Directed/cmov:Int_Or_Op_cs_d",
        "//src/tests/JIT/Directed/cmov:Int_Or_Op_cs_do",
        "//src/tests/JIT/Directed/cmov:Int_Or_Op_cs_r",
        "//src/tests/JIT/Directed/cmov:Int_Or_Op_cs_ro",
        "//src/tests/JIT/Directed/cmov:Int_Xor_Op_cs_d",
        "//src/tests/JIT/Directed/cmov:Int_Xor_Op_cs_do",
        "//src/tests/JIT/Directed/cmov:Int_Xor_Op_cs_r",
        "//src/tests/JIT/Directed/cmov:Int_Xor_Op_cs_ro",
        "//src/tests/JIT/Directed/compare:cmp_int32_d",
        "//src/tests/JIT/Directed/compare:cmp_int32_do",
        "//src/tests/JIT/Directed/compare:cmp_int32_r",
        "//src/tests/JIT/Directed/compare:cmp_int32_ro",
        "//src/tests/JIT/Directed/perffix/commutativecse:ccse_cs_d",
        "//src/tests/JIT/Directed/perffix/commutativecse:ccse_cs_do",
        "//src/tests/JIT/Directed/perffix/commutativecse:ccse_cs_r",
        "//src/tests/JIT/Directed/perffix/commutativecse:ccse_cs_ro",
        "//src/tests/JIT/Directed/perffix/primitivevt:mixed1_cs_d",
        "//src/tests/JIT/Directed/perffix/primitivevt:mixed1_cs_do",
        "//src/tests/JIT/Directed/perffix/primitivevt:mixed1_cs_r",
        "//src/tests/JIT/Directed/perffix/primitivevt:mixed1_cs_ro",
        "//src/tests/JIT/Directed/perffix/primitivevt:mixed2_cs_d",
        "//src/tests/JIT/Directed/perffix/primitivevt:mixed2_cs_do",
        "//src/tests/JIT/Directed/perffix/primitivevt:mixed2_cs_r",
        "//src/tests/JIT/Directed/perffix/primitivevt:mixed2_cs_ro",
        "//src/tests/JIT/Directed/shift:int16_cs_d",
        "//src/tests/JIT/Directed/shift:int16_cs_do",
        "//src/tests/JIT/Directed/shift:int16_cs_r",
        "//src/tests/JIT/Directed/shift:int16_cs_ro",
        "//src/tests/JIT/Directed/shift:int16_r",
        "//src/tests/JIT/Directed/shift:int16_ro",
        "//src/tests/JIT/Directed/shift:int32_cs_d",
        "//src/tests/JIT/Directed/shift:int32_cs_do",
        "//src/tests/JIT/Directed/shift:int32_cs_r",
        "//src/tests/JIT/Directed/shift:int32_cs_ro",
        "//src/tests/JIT/Directed/shift:int32_r",
        "//src/tests/JIT/Directed/shift:int32_ro",
        "//src/tests/JIT/Directed/shift:int64_d",
        "//src/tests/JIT/Directed/shift:int64_do",
        "//src/tests/JIT/Directed/shift:int64_r",
        "//src/tests/JIT/Directed/shift:int64_ro",
        "//src/tests/JIT/Directed/shift:uint16_cs_d",
        "//src/tests/JIT/Directed/shift:uint16_cs_do",
        "//src/tests/JIT/Directed/shift:uint16_cs_r",
        "//src/tests/JIT/Directed/shift:uint16_cs_ro",
        "//src/tests/JIT/Directed/shift:uint16_r",
        "//src/tests/JIT/Directed/shift:uint16_ro",
        "//src/tests/JIT/Directed/shift:uint32_cs_d",
        "//src/tests/JIT/Directed/shift:uint32_cs_do",
        "//src/tests/JIT/Directed/shift:uint32_cs_r",
        "//src/tests/JIT/Directed/shift:uint32_cs_ro",
        "//src/tests/JIT/Directed/shift:uint32_r",
        "//src/tests/JIT/Directed/shift:uint32_ro",
        "//src/tests/JIT/Directed/shift:uint64Opt_d",
        "//src/tests/JIT/Directed/shift:uint64Opt_do",
        "//src/tests/JIT/Directed/shift:uint64Opt_r",
        "//src/tests/JIT/Directed/shift:uint64Opt_ro",
        "//src/tests/JIT/Directed/shift:uint64_d",
        "//src/tests/JIT/Directed/shift:uint64_do",
        "//src/tests/JIT/Directed/shift:uint64_r",
        "//src/tests/JIT/Directed/shift:uint64_ro",
        "//src/tests/JIT/Directed/shift:uint8_cs_d",
        "//src/tests/JIT/Directed/shift:uint8_cs_do",
        "//src/tests/JIT/Directed/shift:uint8_cs_r",
        "//src/tests/JIT/Directed/shift:uint8_cs_ro",
        "//src/tests/JIT/Directed/shift:uint8_r",
        "//src/tests/JIT/Directed/shift:uint8_ro",
    ],
)

coreclr_merged_test(
    name = "Directed_1",
    deps = [
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    test_deps = [
        "//src/tests/JIT/Directed/coverage/flowgraph:gcpoll",
        "//src/tests/JIT/Directed/coverage/flowgraph:xaddmuly_cs_d",
        "//src/tests/JIT/Directed/coverage/flowgraph:xaddmuly_cs_do",
        "//src/tests/JIT/Directed/coverage/flowgraph:xaddmuly_cs_r",
        "//src/tests/JIT/Directed/coverage/flowgraph:xaddmuly_cs_ro",
        "//src/tests/JIT/Directed/coverage/oldtests:33objref_cs_d",
        "//src/tests/JIT/Directed/coverage/oldtests:33objref_cs_do",
        "//src/tests/JIT/Directed/coverage/oldtests:33objref_cs_r",
        "//src/tests/JIT/Directed/coverage/oldtests:33objref_cs_ro",
        "//src/tests/JIT/Directed/coverage/oldtests:cse1_cs_d",
        "//src/tests/JIT/Directed/coverage/oldtests:cse1_cs_do",
        "//src/tests/JIT/Directed/coverage/oldtests:cse1_cs_r",
        "//src/tests/JIT/Directed/coverage/oldtests:cse1_cs_ro",
        "//src/tests/JIT/Directed/coverage/oldtests:cse2_cs_d",
        "//src/tests/JIT/Directed/coverage/oldtests:cse2_cs_do",
        "//src/tests/JIT/Directed/coverage/oldtests:cse2_cs_r",
        "//src/tests/JIT/Directed/coverage/oldtests:cse2_cs_ro",
        "//src/tests/JIT/Directed/coverage/oldtests:lclfldadd_cs_d",
        "//src/tests/JIT/Directed/coverage/oldtests:lclfldadd_cs_do",
        "//src/tests/JIT/Directed/coverage/oldtests:lclfldadd_cs_r",
        "//src/tests/JIT/Directed/coverage/oldtests:lclfldadd_cs_ro",
        "//src/tests/JIT/Directed/coverage/oldtests:lclflddiv_cs_d",
        "//src/tests/JIT/Directed/coverage/oldtests:lclflddiv_cs_do",
        "//src/tests/JIT/Directed/coverage/oldtests:lclflddiv_cs_r",
        "//src/tests/JIT/Directed/coverage/oldtests:lclflddiv_cs_ro",
        "//src/tests/JIT/Directed/coverage/oldtests:lclfldmul_cs_d",
        "//src/tests/JIT/Directed/coverage/oldtests:lclfldmul_cs_do",
        "//src/tests/JIT/Directed/coverage/oldtests:lclfldmul_cs_r",
        "//src/tests/JIT/Directed/coverage/oldtests:lclfldmul_cs_ro",
        "//src/tests/JIT/Directed/coverage/oldtests:lclfldrem_cs_d",
        "//src/tests/JIT/Directed/coverage/oldtests:lclfldrem_cs_do",
        "//src/tests/JIT/Directed/coverage/oldtests:lclfldrem_cs_r",
        "//src/tests/JIT/Directed/coverage/oldtests:lclfldrem_cs_ro",
        "//src/tests/JIT/Directed/coverage/oldtests:lclfldsub_cs_d",
        "//src/tests/JIT/Directed/coverage/oldtests:lclfldsub_cs_do",
        "//src/tests/JIT/Directed/coverage/oldtests:lclfldsub_cs_r",
        "//src/tests/JIT/Directed/coverage/oldtests:lclfldsub_cs_ro",
        "//src/tests/JIT/Directed/nullabletypes/Desktop:boxunboxvaluetype_do",
        "//src/tests/JIT/Directed/nullabletypes/Desktop:boxunboxvaluetype_r",
        "//src/tests/JIT/Directed/nullabletypes/Desktop:boxunboxvaluetype_ro",
        "//src/tests/JIT/Directed/nullabletypes/Desktop:nullcomparaison_d",
        "//src/tests/JIT/Directed/nullabletypes/Desktop:nullcomparaison_do",
        "//src/tests/JIT/Directed/nullabletypes/Desktop:nullcomparaison_r",
        "//src/tests/JIT/Directed/nullabletypes/Desktop:nullcomparaison_ro",
        "//src/tests/JIT/Directed/nullabletypes:boxunboxenum_d",
        "//src/tests/JIT/Directed/nullabletypes:boxunboxenum_do",
        "//src/tests/JIT/Directed/nullabletypes:boxunboxenum_r",
        "//src/tests/JIT/Directed/nullabletypes:boxunboxenum_ro",
        "//src/tests/JIT/Directed/nullabletypes:boxunboxinterface_d",
        "//src/tests/JIT/Directed/nullabletypes:boxunboxinterface_do",
        "//src/tests/JIT/Directed/nullabletypes:boxunboxinterface_r",
        "//src/tests/JIT/Directed/nullabletypes:boxunboxinterface_ro",
        "//src/tests/JIT/Directed/nullabletypes:castclassenum_d",
        "//src/tests/JIT/Directed/nullabletypes:castclassenum_do",
        "//src/tests/JIT/Directed/nullabletypes:castclassenum_r",
        "//src/tests/JIT/Directed/nullabletypes:castclassenum_ro",
        "//src/tests/JIT/Directed/nullabletypes:castclassinterface_d",
        "//src/tests/JIT/Directed/nullabletypes:castclassinterface_do",
        "//src/tests/JIT/Directed/nullabletypes:castclassinterface_r",
        "//src/tests/JIT/Directed/nullabletypes:castclassinterface_ro",
        "//src/tests/JIT/Directed/nullabletypes:castclassvaluetype_d",
        "//src/tests/JIT/Directed/nullabletypes:castclassvaluetype_do",
        "//src/tests/JIT/Directed/nullabletypes:castclassvaluetype_r",
        "//src/tests/JIT/Directed/nullabletypes:castclassvaluetype_ro",
        "//src/tests/JIT/Directed/nullabletypes:constructor_do",
        "//src/tests/JIT/Directed/nullabletypes:constructor_ro",
        "//src/tests/JIT/Directed/nullabletypes:gettype_d",
        "//src/tests/JIT/Directed/nullabletypes:gettype_do",
        "//src/tests/JIT/Directed/nullabletypes:gettype_r",
        "//src/tests/JIT/Directed/nullabletypes:gettype_ro",
        "//src/tests/JIT/Directed/nullabletypes:hashcode_do",
        "//src/tests/JIT/Directed/nullabletypes:hashcode_ro",
        "//src/tests/JIT/Directed/nullabletypes:hasvalue_do",
        "//src/tests/JIT/Directed/nullabletypes:hasvalue_ro",
        "//src/tests/JIT/Directed/nullabletypes:invocation_do",
        "//src/tests/JIT/Directed/nullabletypes:invocation_ro",
        "//src/tests/JIT/Directed/nullabletypes:isinst2_d",
        "//src/tests/JIT/Directed/nullabletypes:isinst2_do",
        "//src/tests/JIT/Directed/nullabletypes:isinst2_r",
        "//src/tests/JIT/Directed/nullabletypes:isinst2_ro",
        "//src/tests/JIT/Directed/nullabletypes:isinst_d",
        "//src/tests/JIT/Directed/nullabletypes:isinst_do",
        "//src/tests/JIT/Directed/nullabletypes:isinst_r",
        "//src/tests/JIT/Directed/nullabletypes:isinst_ro",
        "//src/tests/JIT/Directed/nullabletypes:isinstboxed_d",
        "//src/tests/JIT/Directed/nullabletypes:isinstboxed_do",
        "//src/tests/JIT/Directed/nullabletypes:isinstboxed_r",
        "//src/tests/JIT/Directed/nullabletypes:isinstboxed_ro",
        "//src/tests/JIT/Directed/nullabletypes:isinstenum_d",
        "//src/tests/JIT/Directed/nullabletypes:isinstenum_do",
        "//src/tests/JIT/Directed/nullabletypes:isinstenum_r",
        "//src/tests/JIT/Directed/nullabletypes:isinstenum_ro",
        "//src/tests/JIT/Directed/nullabletypes:isinstgenerics_d",
        "//src/tests/JIT/Directed/nullabletypes:isinstgenerics_do",
        "//src/tests/JIT/Directed/nullabletypes:isinstgenerics_r",
        "//src/tests/JIT/Directed/nullabletypes:isinstgenerics_ro",
        "//src/tests/JIT/Directed/nullabletypes:isinstinterface_d",
        "//src/tests/JIT/Directed/nullabletypes:isinstinterface_do",
        "//src/tests/JIT/Directed/nullabletypes:isinstinterface_r",
        "//src/tests/JIT/Directed/nullabletypes:isinstinterface_ro",
        "//src/tests/JIT/Directed/nullabletypes:isinstvaluetype_d",
        "//src/tests/JIT/Directed/nullabletypes:isinstvaluetype_do",
        "//src/tests/JIT/Directed/nullabletypes:isinstvaluetype_r",
        "//src/tests/JIT/Directed/nullabletypes:isinstvaluetype_ro",
        "//src/tests/JIT/Directed/nullabletypes:tostring_do",
        "//src/tests/JIT/Directed/nullabletypes:tostring_ro",
        "//src/tests/JIT/Directed/nullabletypes:unboxnullable_d",
        "//src/tests/JIT/Directed/nullabletypes:unboxnullable_do",
        "//src/tests/JIT/Directed/nullabletypes:unboxnullable_r",
        "//src/tests/JIT/Directed/nullabletypes:unboxnullable_ro",
        "//src/tests/JIT/Directed/nullabletypes:value_d",
        "//src/tests/JIT/Directed/nullabletypes:value_do",
        "//src/tests/JIT/Directed/nullabletypes:value_ro",
    ],
)

coreclr_merged_test(
    name = "Directed_3",
    deps = [
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    test_deps = [
        "//src/tests/JIT/Directed/Arrays:Complex1",
        "//src/tests/JIT/Directed/Arrays:Complex2",
        "//src/tests/JIT/Directed/Arrays:LoopCloning",
        "//src/tests/JIT/Directed/Arrays:Simple1",
        "//src/tests/JIT/Directed/Arrays:Simple2",
        "//src/tests/JIT/Directed/Arrays:nintindexoutofrange",
        "//src/tests/JIT/Directed/BitTest:BitTest",
        "//src/tests/JIT/Directed/CheckedCtor:Generic_Test_CSharp_Base_1",
        "//src/tests/JIT/Directed/CheckedCtor:Generic_Test_CSharp_Base_2",
        "//src/tests/JIT/Directed/CheckedCtor:Generic_Test_CSharp_Base_3",
        "//src/tests/JIT/Directed/CheckedCtor:Generic_Test_CSharp_Base_4",
        "//src/tests/JIT/Directed/CheckedCtor:Generic_Test_CSharp_Base_6",
        "//src/tests/JIT/Directed/CheckedCtor:Generic_Test_CSharp_Peer_1",
        "//src/tests/JIT/Directed/CheckedCtor:Generic_Test_CSharp_Peer_2",
        "//src/tests/JIT/Directed/CheckedCtor:Generic_Test_CSharp_Peer_3",
        "//src/tests/JIT/Directed/CheckedCtor:Generic_Test_CSharp_Peer_4",
        "//src/tests/JIT/Directed/CheckedCtor:Generic_Test_CSharp_Peer_6",
        "//src/tests/JIT/Directed/CheckedCtor:Test_CSharp_Base_1",
        "//src/tests/JIT/Directed/CheckedCtor:Test_CSharp_Base_2",
        "//src/tests/JIT/Directed/CheckedCtor:Test_CSharp_Base_3",
        "//src/tests/JIT/Directed/CheckedCtor:Test_CSharp_Base_4",
        "//src/tests/JIT/Directed/CheckedCtor:Test_CSharp_Peer_1",
        "//src/tests/JIT/Directed/CheckedCtor:Test_CSharp_Peer_2",
        "//src/tests/JIT/Directed/CheckedCtor:Test_CSharp_Peer_3",
        "//src/tests/JIT/Directed/CheckedCtor:Test_CSharp_Peer_4",
        "//src/tests/JIT/Directed/ConstantFolding:folding_extends_int32_on_64_bit_hosts",
        "//src/tests/JIT/Directed/ConstantFolding:value_numbering_checked_arithmetic_with_constants_ro",
        "//src/tests/JIT/Directed/ConstantFolding:value_numbering_unordered_comparisons_of_constants_ro",
        "//src/tests/JIT/Directed/Convert:FPZero",
        "//src/tests/JIT/Directed/Convert:value_numbering_checked_casts_of_constants",
        "//src/tests/JIT/Directed/LoopAlignment:LoopsToProcess",
        "//src/tests/JIT/Directed/Misc/Concat:ConcatTest",
        "//src/tests/JIT/Directed/Misc/gettype:gettypetypeofmatrix_gettype",
        "//src/tests/JIT/Directed/StrAccess:straccess1_cs_d",
        "//src/tests/JIT/Directed/StrAccess:straccess1_cs_do",
        "//src/tests/JIT/Directed/StrAccess:straccess1_cs_r",
        "//src/tests/JIT/Directed/StrAccess:straccess1_cs_ro",
        "//src/tests/JIT/Directed/StrAccess:straccess2_cs_d",
        "//src/tests/JIT/Directed/StrAccess:straccess2_cs_do",
        "//src/tests/JIT/Directed/StrAccess:straccess2_cs_r",
        "//src/tests/JIT/Directed/StrAccess:straccess2_cs_ro",
        "//src/tests/JIT/Directed/StrAccess:straccess3_cs_d",
        "//src/tests/JIT/Directed/StrAccess:straccess3_cs_do",
        "//src/tests/JIT/Directed/StrAccess:straccess3_cs_r",
        "//src/tests/JIT/Directed/StrAccess:straccess3_cs_ro",
        "//src/tests/JIT/Directed/StructABI:FieldListByteNodeTypeMismatchX86",
        "//src/tests/JIT/Directed/StructABI:MisSizedStructs",
        "//src/tests/JIT/Directed/StructABI:MisSizedStructs_ArmArch",
        "//src/tests/JIT/Directed/StructABI:SevenByteStruct",
        "//src/tests/JIT/Directed/StructABI:StructWithOverlappingFields",
        "//src/tests/JIT/Directed/StructABI:TypeMismatchedArgs",
        "//src/tests/JIT/Directed/StructABI:structfieldparam_r",
        "//src/tests/JIT/Directed/StructABI:structfieldparam_ro",
        "//src/tests/JIT/Directed/StructABI:structreturn",
        "//src/tests/JIT/Directed/StructPromote:FldSeqsInPromotedCpBlk",
        "//src/tests/JIT/Directed/StructPromote:SP1",
        "//src/tests/JIT/Directed/StructPromote:SP1a",
        "//src/tests/JIT/Directed/StructPromote:SP1a2",
        "//src/tests/JIT/Directed/StructPromote:SP1b",
        "//src/tests/JIT/Directed/StructPromote:SP1c",
        "//src/tests/JIT/Directed/StructPromote:SP1d",
        "//src/tests/JIT/Directed/StructPromote:SP2",
        "//src/tests/JIT/Directed/StructPromote:SP2a",
        "//src/tests/JIT/Directed/StructPromote:SP2b",
        "//src/tests/JIT/Directed/StructPromote:SP2c",
        "//src/tests/JIT/Directed/StructPromote:SpAddr",
        "//src/tests/JIT/Directed/StructPromote:SpAddrAT",
        "//src/tests/JIT/Directed/StructPromote/Unsafe:AccessInvalidFieldOffset",
        "//src/tests/JIT/Directed/StructPromote/Unsafe:ReadDoubleFromIntOffset",
        "//src/tests/JIT/Directed/StructPromote/Unsafe:ReadStructAsAnotherType",
        "//src/tests/JIT/Directed/TypedReference:TypedReference",
        "//src/tests/JIT/Directed/UnrollLoop:Dev10_846218",
        "//src/tests/JIT/Directed/UnrollLoop:loop1_cs_d",
        "//src/tests/JIT/Directed/UnrollLoop:loop1_cs_do",
        "//src/tests/JIT/Directed/UnrollLoop:loop1_cs_r",
        "//src/tests/JIT/Directed/UnrollLoop:loop1_cs_ro",
        "//src/tests/JIT/Directed/UnrollLoop:loop4_cs_d",
        "//src/tests/JIT/Directed/UnrollLoop:loop4_cs_do",
        "//src/tests/JIT/Directed/UnrollLoop:loop4_cs_r",
        "//src/tests/JIT/Directed/UnrollLoop:loop4_cs_ro",
        "//src/tests/JIT/Directed/UnrollLoop:loop6_cs_d",
        "//src/tests/JIT/Directed/UnrollLoop:loop6_cs_do",
        "//src/tests/JIT/Directed/UnrollLoop:loop6_cs_r",
        "//src/tests/JIT/Directed/UnrollLoop:loop6_cs_ro",
        "//src/tests/JIT/Directed/VectorABI:VectorMgdMgdArray_r",
        "//src/tests/JIT/Directed/VectorABI:VectorMgdMgdArray_ro",
        "//src/tests/JIT/Directed/VectorABI:VectorMgdMgdStatic_r",
        "//src/tests/JIT/Directed/VectorABI:VectorMgdMgdStatic_ro",
        "//src/tests/JIT/Directed/VectorABI:VectorMgdMgd_r",
        "//src/tests/JIT/Directed/VectorABI:VectorMgdMgd_ro",
        "//src/tests/JIT/Directed/debugging/poisoning:poison",
        "//src/tests/JIT/Directed/forceinlining:LargeNumberOfArgs",
        "//src/tests/JIT/Directed/forceinlining:NoMetaData",
        "//src/tests/JIT/Directed/forceinlining:Recursion",
        "//src/tests/JIT/Directed/gettypetypeof:gettypetypeofmatrix_gettypetypeof",
        "//src/tests/JIT/Directed/intrinsic/interlocked:IntrinsicTest_Overflow",
        "//src/tests/JIT/Directed/intrinsic/interlocked:cmpxchg",
        "//src/tests/JIT/Directed/intrinsic/interlocked:cse_cmpxchg",
        "//src/tests/JIT/Directed/intrinsic/interlocked:nullchecksuppress",
        "//src/tests/JIT/Directed/intrinsic/interlocked:regalloc1",
        "//src/tests/JIT/Directed/intrinsic/interlocked:regalloc2",
        "//src/tests/JIT/Directed/intrinsic/pow:pow0_cs_d",
        "//src/tests/JIT/Directed/intrinsic/pow:pow0_cs_do",
        "//src/tests/JIT/Directed/intrinsic/pow:pow0_cs_r",
        "//src/tests/JIT/Directed/intrinsic/pow:pow0_cs_ro",
        "//src/tests/JIT/Directed/intrinsic/pow:pow1",
        "//src/tests/JIT/Directed/intrinsic/pow:pow2_cs_d",
        "//src/tests/JIT/Directed/intrinsic/pow:pow2_cs_do",
        "//src/tests/JIT/Directed/intrinsic/pow:pow2_cs_r",
        "//src/tests/JIT/Directed/intrinsic/pow:pow2_cs_ro",
        "//src/tests/JIT/Directed/intrinsic/pow:pow3_cs_d",
        "//src/tests/JIT/Directed/intrinsic/pow:pow3_cs_do",
        "//src/tests/JIT/Directed/intrinsic/pow:pow3_cs_r",
        "//src/tests/JIT/Directed/intrinsic/pow:pow3_cs_ro",
        "//src/tests/JIT/Directed/lifetime:ObjBlkMemLiveness",
        "//src/tests/JIT/Directed/lifetime:PartialDefLiveness",
        "//src/tests/JIT/Directed/lifetime:lifetime1",
        "//src/tests/JIT/Directed/localloc:localloc3_cs_d",
        "//src/tests/JIT/Directed/localloc:localloc3_cs_do",
        "//src/tests/JIT/Directed/localloc:localloc3_cs_r",
        "//src/tests/JIT/Directed/localloc:localloc3_cs_ro",
        "//src/tests/JIT/Directed/newarr:newarr",
        "//src/tests/JIT/Directed/physicalpromotion:addressinterference",
        "//src/tests/JIT/Directed/physicalpromotion:fuzzlyn1",
        "//src/tests/JIT/Directed/physicalpromotion:fuzzlyn2",
        "//src/tests/JIT/Directed/physicalpromotion:mixedpromotion",
        "//src/tests/JIT/Directed/physicalpromotion:physicalpromotion",
        "//src/tests/JIT/Directed/physicalpromotion:readbackbeforeqmark",
    ],
)
