load("//src/tests:live_test.bzl", "coreclr_test")

coreclr_test(
    name = "GitHub_1674",
    srcs = ["TestConstraintOnDefaultInterfaceMethod.cs"],
    pri = 1,
    deps = [
        "//src/tests/Common:TestLibrary",
        "@paket.main//microsoft.dotnet.xunitextensions",
    ],
    size = "medium",
)
