load("//src/tests:live_test.bzl", "coreclr_test")

coreclr_test(
    name = "Runtime_57752_1",
    srcs = ["Runtime_57752_1.cs"],
    optimize = True,
    allow_unsafe_blocks = True,
)

coreclr_test(
    name = "Runtime_57752_2",
    srcs = ["Runtime_57752_2.cs"],
    optimize = True,
    allow_unsafe_blocks = True,
)
