load("//src/libraries:defs.bzl", "MULTITARGET_NOWARN", "netcoreapp_ref_assembly", "impl_assembly", "ref_impl_pair")
load("@bazel_skylib//lib:selects.bzl", "selects")

netcoreapp_ref_assembly(
    name = "ref_System.Runtime.Caching",
    srcs = [
        "ref/System.Runtime.Caching.cs",
    ],
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Collections.Specialized:ref_System.Collections.Specialized",
        "//src/libraries/System.ComponentModel:ref_System.ComponentModel",
        "//src/libraries/System.ObjectModel:ref_System.ObjectModel",
    ],
)

impl_assembly(
    name = "impl_System.Runtime.Caching",
    nowarn = MULTITARGET_NOWARN + ["CP0003", "NU5128", "CS1591", "nullable"],
    srcs = [
        "src/System/Runtime/Caching/Counters.cs",
        "src/System/Runtime/Caching/CacheEntryChangeMonitor.cs",
        "src/System/Runtime/Caching/CacheEntryRemovedArguments.cs",
        "src/System/Runtime/Caching/CacheEntryRemovedCallback.cs",
        "src/System/Runtime/Caching/CacheEntryRemovedReason.cs",
        "src/System/Runtime/Caching/CacheEntryUpdateArguments.cs",
        "src/System/Runtime/Caching/CacheEntryUpdateCallback.cs",
        "src/System/Runtime/Caching/CacheExpires.cs",
        "src/System/Runtime/Caching/CacheItem.cs",
        "src/System/Runtime/Caching/CacheItemPolicy.cs",
        "src/System/Runtime/Caching/CacheItemPriority.cs",
        "src/System/Runtime/Caching/CacheMemoryMonitor.cs",
        "src/System/Runtime/Caching/CacheUsage.cs",
        "src/System/Runtime/Caching/ChangeMonitor.cs",
        "src/System/Runtime/Caching/Dbg.cs",
        "src/System/Runtime/Caching/DefaultCacheCapabilities.cs",
        "src/System/Runtime/Caching/EntryState.cs",
        "src/System/Runtime/Caching/FileChangeMonitor.cs",
        "src/System/Runtime/Caching/FileChangeNotificationSystem.cs",
        "src/System/Runtime/Caching/HostFileChangeMonitor.cs",
        "src/System/Runtime/Caching/MemoryCache.cs",
        "src/System/Runtime/Caching/MemoryCacheEntry.cs",
        "src/System/Runtime/Caching/MemoryCacheEntryChangeMonitor.cs",
        "src/System/Runtime/Caching/MemoryCacheKey.cs",
        "src/System/Runtime/Caching/MemoryCacheKeyEqualityComparer.cs",
        "src/System/Runtime/Caching/MemoryCacheStatistics.cs",
        "src/System/Runtime/Caching/MemoryCacheStore.cs",
        "src/System/Runtime/Caching/MemoryMonitor.cs",
        "src/System/Runtime/Caching/ObjectCache.cs",
        "src/System/Runtime/Caching/OnChangedCallback.cs",
        "src/System/Runtime/Caching/CounterName.cs",
        "src/System/Runtime/Caching/PhysicalMemoryMonitor.cs",
        "src/System/Runtime/Caching/SafeBitVector32.cs",
        "src/System/Runtime/Caching/SRef.cs",
        "src/System/Runtime/Caching/Configuration/CachingSectionGroup.cs",
        "src/System/Runtime/Caching/Configuration/ConfigUtil.cs",
        "src/System/Runtime/Caching/Configuration/MemoryCacheElement.cs",
        "src/System/Runtime/Caching/Configuration/MemoryCacheSection.cs",
        "src/System/Runtime/Caching/Configuration/MemoryCacheSettingsCollection.cs",
        "src/System/Runtime/Caching/Hosting/IApplicationIdentifier.cs",
        "src/System/Runtime/Caching/Hosting/IFileChangeNotificationSystem.cs",
        "src/System/Runtime/Caching/Hosting/IMemoryCacheManager.cs",
        "src/System/Runtime/Caching/Resources/RH.cs",
    ] + selects.with_or({
        ("@platforms//os:linux", "@platforms//os:macos"): [
            "src/System/Runtime/Caching/PhysicalMemoryMonitor.Unix.cs",
        ],
        "//conditions:default": [
            "src/System/Runtime/Caching/MemoryMonitor.Windows.cs",
            "src/System/Runtime/Caching/PhysicalMemoryMonitor.Windows.cs",
            "//src/libraries/Common:src/Interop/Windows/Interop.BOOL.cs",
            "//src/libraries/Common:src/Interop/Windows/Kernel32/Interop.GlobalMemoryStatusEx.cs",
            "//src/libraries/Common:src/Interop/Windows/Kernel32/Interop.MEMORYSTATUSEX.cs",
            "//src/libraries/Common:src/Interop/Windows/Interop.Libraries.cs",
        ],
    }),
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Collections:ref_System.Collections",
        "//src/libraries/System.Collections.Specialized:ref_System.Collections.Specialized",
        "//src/libraries/System.ComponentModel:ref_System.ComponentModel",
        "//src/libraries/System.ComponentModel.TypeConverter:ref_System.ComponentModel.TypeConverter",
        "//src/libraries/System.Configuration.ConfigurationManager:ref_System.Configuration.ConfigurationManager",
        "//src/libraries/System.Diagnostics.Tracing:ref_System.Diagnostics.Tracing",
        "//src/libraries/System.IO.FileSystem.Watcher:ref_System.IO.FileSystem.Watcher",
        "//src/libraries/System.ObjectModel:ref_System.ObjectModel",
        "//src/libraries/System.Text.RegularExpressions:ref_System.Text.RegularExpressions",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/System.Threading.Thread:ref_System.Threading.Thread",
    ],
    resx_file = "src/Resources/Strings.resx",
    analyzers = [
        "//src/libraries/System.Text.Json:JsonSourceGenerator",
        "//src/libraries/System.Text.RegularExpressions:RegexGenerator",
    ],
    com_interface_generator = True,
    nullable = "disable",
    allow_unsafe_blocks = True,
)

ref_impl_pair(
    name = "live_System.Runtime.Caching",
    ref = ":ref_System.Runtime.Caching",
    lib = ":impl_System.Runtime.Caching",
    visibility = ["//visibility:public"],
)
