load("//src/tests:live_test.bzl", "coreclr_test")

coreclr_test(
    name = "MainProgramHandleTests",
    srcs = ["MainProgramHandleTests.cs"],
    deps = [
        "//src/tests/Common:TestLibrary",
        "@paket.main//microsoft.dotnet.xunitextensions",
    ],
    target_compatible_with = ["@platforms//os:windows"],
)
