load("//src/libraries:defs.bzl", "netcoreapp_impl_assembly")

netcoreapp_impl_assembly(
    name = "impl_System.Security.SecureString",
    skip_cs1591 = True,
    srcs = ["src/System.Security.SecureString.cs"],
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Runtime.InteropServices:ref_System.Runtime.InteropServices",
    ],
    os_targeted = True,
    exclude_sr = True,
)
