load("//src/tests:live_test.bzl", "coreclr_test")

coreclr_test(
    name = "GitHub_23199_Target_32Bit",
    srcs = ["GitHub_23199_Target_32Bit.cs"],
    pri = 1,
    optimize = True,
    size = "medium",
)

coreclr_test(
    name = "GitHub_23199_Target_64Bit",
    srcs = ["GitHub_23199_Target_64Bit.cs"],
    pri = 1,
    optimize = True,
    size = "medium",
)
