load("//src/tests:live_test.bzl", "coreclr_test")

coreclr_test(
    name = "test2_524070",
    srcs = ["test2.cs"],
    pri = 1,
    debug_type = "pdbonly",
    optimize = True,
    size = "medium",
)

coreclr_test(
    name = "test1_524070",
    srcs = ["test1.cs"],
    pri = 1,
    debug_type = "pdbonly",
    optimize = True,
    size = "medium",
)
