load("//src/tests:live_test.bzl", "library_test")
load("//:defs.bzl", "OPEN_SNK", "gen_resx_source", "resgen")

gen_resx_source(
    name = "gen_resx",
    out = "SR.g.cs",
    assembly_name = "System.Net.NameResolution.Pal.Tests",
    resx_file = "//src/libraries/System.Net.NameResolution:src/Resources/Strings.resx",
)

resgen(
    name = "strings_resx",
    out = "FxResources.System.Net.NameResolution.Pal.Tests.SR.resources",
    resx_file = "//src/libraries/System.Net.NameResolution:src/Resources/Strings.resx",
)

library_test(
    name = "System.Net.NameResolution.Pal.Tests",
    resources = [":strings_resx"],
    resource_logical_names = {"FxResources.System.Net.NameResolution.Pal.Tests.SR.resources": "FxResources.System.Net.NameResolution.Pal.Tests.SR.resources"},
    defines = select({
        "@platforms//os:linux": ["UNIX", "UNIX1_0"],
        "@platforms//os:macos": ["UNIX", "UNIX1_0"],
        "//conditions:default": [],
    }),
    srcs = [
        "AssemblyInfo.cs",
        "NameResolutionPalTests.cs",
        "Fakes/DnsFake.cs",
        "Fakes/IPAddressFakeExtensions.cs",
        "//src/libraries/System.Net.NameResolution:src/System/Net/IPHostEntry.cs",
        "//src/libraries/Common:src/System/Net/Logging/NetEventSource.Common.cs",
        "//src/libraries/Common:src/System/Net/Sockets/ProtocolType.cs",
        "//src/libraries/Common:src/System/Net/Sockets/SocketType.cs",
        "//src/libraries/Common:src/System/Net/Sockets/ProtocolFamily.cs",
        "//src/libraries/Common:src/System/Net/IPEndPointStatics.cs",
        "//src/libraries/Common:src/System/Net/IPAddressParserStatics.cs",
        "//src/libraries/Common:src/System/LocalAppContextSwitches.Common.cs",
        "//src/libraries/Common:src/System/Net/LocalAppContextSwitches.Net.cs",
        "//src/libraries/Common:src/System/Net/SocketProtocolSupportPal.cs",
        "//src/libraries/Common/tests:System/Net/Configuration.cs",
        "//src/libraries/Common/tests:System/Net/Configuration.Http.cs",
        "//src/libraries/Common:src/System/SR.cs",
        ":gen_resx",
    ] + select({
        "@platforms//os:linux": [
            "//src/libraries/System.Net.NameResolution:src/System/Net/NameResolutionPal.Unix.cs",
            "//src/libraries/Common:src/System/Net/SocketAddressPal.Unix.cs",
            "//src/libraries/Common:src/System/Net/InteropIPAddressExtensions.Unix.cs",
            "//src/libraries/Common:src/System/Net/SocketProtocolSupportPal.Unix.cs",
            "//src/libraries/Common:src/Interop/Unix/Interop.Errors.cs",
            "//src/libraries/Common:src/Interop/Unix/Interop.Libraries.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.ErrNo.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Close.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.GetHostName.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.GetNameInfo.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.HostEntry.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.IPAddress.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Socket.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.SocketAddress.cs",
        ],
        "@platforms//os:macos": [
            "//src/libraries/System.Net.NameResolution:src/System/Net/NameResolutionPal.Unix.cs",
            "//src/libraries/Common:src/System/Net/SocketAddressPal.Unix.cs",
            "//src/libraries/Common:src/System/Net/InteropIPAddressExtensions.Unix.cs",
            "//src/libraries/Common:src/System/Net/SocketProtocolSupportPal.Unix.cs",
            "//src/libraries/Common:src/Interop/Unix/Interop.Errors.cs",
            "//src/libraries/Common:src/Interop/Unix/Interop.Libraries.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.ErrNo.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Close.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.GetHostName.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.GetNameInfo.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.HostEntry.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.IPAddress.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Socket.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.SocketAddress.cs",
        ],
        "//conditions:default": [],
    }),
    deps = [
        "//src/libraries:ref_Microsoft.Win32.Primitives",
        "//src/libraries/Microsoft.Win32.Registry:ref_Microsoft.Win32.Registry",
        "//src/libraries/System.Diagnostics.DiagnosticSource:ref_System.Diagnostics.DiagnosticSource",
        "//src/libraries/System.Diagnostics.Tracing:ref_System.Diagnostics.Tracing",
        "//src/libraries/System.Net.NetworkInformation:ref_System.Net.NetworkInformation",
        "//src/libraries/System.Net.Primitives:ref_System.Net.Primitives",
        "//src/libraries/System.Net.Sockets:ref_System.Net.Sockets",
        "//src/libraries/System.Security.Claims:ref_System.Security.Claims",
        "//src/libraries/System.Security.Principal.Windows:ref_System.Security.Principal.Windows",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/System.Threading.Overlapped:ref_System.Threading.Overlapped",
        "//src/libraries/System.Threading.ThreadPool:ref_System.Threading.ThreadPool",
        "//src/libraries/Common/tests:TestUtilities",
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//microsoft.dotnet.xunitextensions",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    allow_unsafe_blocks = True,
    additionalfiles = ["//src/libraries/System.Net.NameResolution:src/Resources/Strings.resx"],
    size = "large",
    keyfile = OPEN_SNK,
)
