load("//src/libraries:defs.bzl", "netcoreapp_impl_assembly")

netcoreapp_impl_assembly(
    name = "impl_System.Web",
    skip_locals_init = False,
    srcs = [
        "src/System.Web.cs",
    ],
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Web.HttpUtility:ref_System.Web.HttpUtility",
    ],
    os_targeted = True,
    exclude_sr = True,
    assembly_version = "4.0.0.0",
    generate_documentation_file = False,
    library_import_generator = False,
)
