
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

/******************************************************************

DO NOT MODIFY. AUTOGENERATED FILE.
This file is generated using the logic from <root>/src/scripts/genDummyProvider.py

******************************************************************/


#ifdef TARGET_UNIX
#include "pal_mstypes.h"
#include "pal_error.h"
#include "pal.h"
#include "pal/stackstring.hpp"
#endif


extern "C" BOOL  EventXplatEnabledMonoProfilerContextLoaded(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerContextLoaded(
    const void* ObjectID,
    const uint64_t AppDomainID,
    const uint64_t ContextID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerContextUnloaded(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerContextUnloaded(
    const void* ObjectID,
    const uint64_t AppDomainID,
    const uint64_t ContextID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerAppDomainLoading(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerAppDomainLoading(
    const uint64_t AppDomainID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerAppDomainLoaded(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerAppDomainLoaded(
    const uint64_t AppDomainID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerAppDomainUnloading(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerAppDomainUnloading(
    const uint64_t AppDomainID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerAppDomainUnloaded(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerAppDomainUnloaded(
    const uint64_t AppDomainID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerAppDomainName(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerAppDomainName(
    const uint64_t AppDomainID,
    PCWSTR AppDomainName)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerJitBegin(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerJitBegin(
    const uint64_t MethodID,
    const uint64_t ModuleID,
    const unsigned int MethodToken)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerJitFailed(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerJitFailed(
    const uint64_t MethodID,
    const uint64_t ModuleID,
    const unsigned int MethodToken)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerJitDone(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerJitDone(
    const uint64_t MethodID,
    const uint64_t ModuleID,
    const unsigned int MethodToken)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerJitDone_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerJitDone_V1(
    const uint64_t MethodID,
    const uint64_t ModuleID,
    const unsigned int MethodToken,
    const unsigned int Count,
    int Values_ElementSize,
    const void* Values)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerJitChunkCreated(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerJitChunkCreated(
    const void* ChunkID,
    const uint64_t ChunkSize)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerJitChunkDestroyed(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerJitChunkDestroyed(
    const void* ChunkID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerJitCodeBuffer(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerJitCodeBuffer(
    const void* BufferID,
    const uint64_t BufferSize,
    const unsigned char BufferType)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerClassLoading(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerClassLoading(
    const uint64_t ClassID,
    const uint64_t ModuleID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerClassFailed(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerClassFailed(
    const uint64_t ClassID,
    const uint64_t ModuleID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerClassLoaded(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerClassLoaded(
    const uint64_t ClassID,
    const uint64_t ModuleID,
    PCWSTR ClassName)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerClassLoaded_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerClassLoaded_V1(
    const uint64_t ClassID,
    const uint64_t ModuleID,
    PCWSTR ClassName,
    const unsigned int Count,
    int Values_ElementSize,
    const void* Values)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerVTableLoading(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerVTableLoading(
    const uint64_t VTableID,
    const uint64_t ClassID,
    const uint64_t AppDomainID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerVTableFailed(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerVTableFailed(
    const uint64_t VTableID,
    const uint64_t ClassID,
    const uint64_t AppDomainID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerVTableLoaded(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerVTableLoaded(
    const uint64_t VTableID,
    const uint64_t ClassID,
    const uint64_t AppDomainID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerModuleLoading(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerModuleLoading(
    const uint64_t ModuleID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerModuleFailed(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerModuleFailed(
    const uint64_t ModuleID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerModuleLoaded(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerModuleLoaded(
    const uint64_t ModuleID,
    PCWSTR ModuleName,
    PCWSTR ModuleSignature)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerModuleUnloading(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerModuleUnloading(
    const uint64_t ModuleID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerModuleUnloaded(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerModuleUnloaded(
    const uint64_t ModuleID,
    PCWSTR ModuleName,
    PCWSTR ModuleSignature)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerAssemblyLoading(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerAssemblyLoading(
    const uint64_t AssemblyID,
    const uint64_t ModuleID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerAssemblyLoaded(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerAssemblyLoaded(
    const uint64_t AssemblyID,
    const uint64_t ModuleID,
    PCWSTR AssemblyName)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerAssemblyUnloading(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerAssemblyUnloading(
    const uint64_t AssemblyID,
    const uint64_t ModuleID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerAssemblyUnloaded(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerAssemblyUnloaded(
    const uint64_t AssemblyID,
    const uint64_t ModuleID,
    PCWSTR AssemblyName)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerMethodEnter(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerMethodEnter(
    const uint64_t MethodID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerMethodLeave(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerMethodLeave(
    const uint64_t MethodID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerMethodTailCall(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerMethodTailCall(
    const uint64_t MethodID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerMethodExceptionLeave(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerMethodExceptionLeave(
    const uint64_t MethodID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerMethodFree(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerMethodFree(
    const uint64_t MethodID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerMethodBeginInvoke(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerMethodBeginInvoke(
    const uint64_t MethodID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerMethodEndInvoke(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerMethodEndInvoke(
    const uint64_t MethodID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerExceptionThrow(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerExceptionThrow(
    const uint64_t TypeID,
    const void* ObjectID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerExceptionClause(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerExceptionClause(
    const unsigned char ClauseType,
    const unsigned int ClauseIdx,
    const uint64_t MethodID,
    const uint64_t TypeID,
    const void* ObjectID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerGCEvent(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerGCEvent(
    const unsigned char GCEventType,
    const unsigned int GCGeneration)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerGCAllocation(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerGCAllocation(
    const uint64_t VTableID,
    const void* ObjectID,
    const uint64_t ObjectSize)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerGCMoves(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerGCMoves(
    const unsigned int Count,
    int Values_ElementSize,
    const void* Values)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerGCResize(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerGCResize(
    const uint64_t NewSize)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerGCHandleCreated(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerGCHandleCreated(
    const uint64_t HandleID,
    const unsigned char HandleType,
    const void* ObjectID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerGCHandleDeleted(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerGCHandleDeleted(
    const uint64_t HandleID,
    const unsigned char HandleType)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerGCFinalizing(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerGCFinalizing(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerGCFinalized(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerGCFinalized(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerGCFinalizingObject(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerGCFinalizingObject(
    const void* ObjectID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerGCFinalizedObject(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerGCFinalizedObject(
    const void* ObjectID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerGCRootRegister(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerGCRootRegister(
    const void* RootID,
    const uint64_t RootSize,
    const unsigned char RootType,
    const uint64_t RootKeyID,
    PCWSTR RootKeyName)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerGCRootUnregister(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerGCRootUnregister(
    const void* RootID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerGCRoots(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerGCRoots(
    const unsigned int Count,
    int Values_ElementSize,
    const void* Values)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerGCHeapDumpStart(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerGCHeapDumpStart(
    PCWSTR HeapCollectParam)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerGCHeapDumpStop(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerGCHeapDumpStop(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerGCHeapDumpObjectReference(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerGCHeapDumpObjectReference(
    const void* ObjectID,
    const uint64_t VTableID,
    const uint64_t ObjectSize,
    const unsigned char ObjectGeneration,
    const unsigned int Count,
    int Values_ElementSize,
    const void* Values)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerMonitorContention(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerMonitorContention(
    const void* ObjectID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerMonitorFailed(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerMonitorFailed(
    const void* ObjectID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerMonitorAcquired(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerMonitorAcquired(
    const void* ObjectID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerThreadStarted(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerThreadStarted(
    const uint64_t ThreadID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerThreadStopping(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerThreadStopping(
    const uint64_t ThreadID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerThreadStopped(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerThreadStopped(
    const uint64_t ThreadID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerThreadExited(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerThreadExited(
    const uint64_t ThreadID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerThreadName(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerThreadName(
    const uint64_t ThreadID,
    PCWSTR ThreadName)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerJitDoneVerbose(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerJitDoneVerbose(
    const uint64_t MethodID,
    PCWSTR MethodNamespace,
    PCWSTR MethodName,
    PCWSTR MethodSignature)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerGCHeapDumpVTableClassReference(){ return FALSE; }

extern "C" ULONG  FireEtXplatMonoProfilerGCHeapDumpVTableClassReference(
    const uint64_t VTableID,
    const uint64_t ClassID,
    const uint64_t ModuleID,
    PCWSTR ClassName)
{
    return ERROR_SUCCESS;
}


