
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

/******************************************************************

DO NOT MODIFY. AUTOGENERATED FILE.
This file is generated using the logic from <root>/src/scripts/genDummyProvider.py

******************************************************************/


#ifdef TARGET_UNIX
#include "pal_mstypes.h"
#include "pal_error.h"
#include "pal.h"
#include "pal/stackstring.hpp"
#endif


extern "C" BOOL  EventXplatEnabledGCDecision(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCDecision(
    const BOOL DoCompact)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCDecision_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCDecision_V1(
    const BOOL DoCompact,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCSettings(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCSettings(
    const uint64_t SegmentSize,
    const uint64_t LargeObjectSegmentSize,
    const BOOL ServerGC)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCSettings_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCSettings_V1(
    const uint64_t SegmentSize,
    const uint64_t LargeObjectSegmentSize,
    const BOOL ServerGC,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCOptimized(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCOptimized(
    const uint64_t DesiredAllocation,
    const uint64_t NewAllocation,
    const unsigned int GenerationNumber)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCOptimized_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCOptimized_V1(
    const uint64_t DesiredAllocation,
    const uint64_t NewAllocation,
    const unsigned int GenerationNumber,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCPerHeapHistory(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCPerHeapHistory(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCPerHeapHistory_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCPerHeapHistory_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCGlobalHeapHistory(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCGlobalHeapHistory(
    const uint64_t FinalYoungestDesired,
    const signed int NumHeaps,
    const unsigned int CondemnedGeneration,
    const unsigned int Gen0ReductionCount,
    const unsigned int Reason,
    const unsigned int GlobalMechanisms)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCGlobalHeapHistory_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCGlobalHeapHistory_V1(
    const uint64_t FinalYoungestDesired,
    const signed int NumHeaps,
    const unsigned int CondemnedGeneration,
    const unsigned int Gen0ReductionCount,
    const unsigned int Reason,
    const unsigned int GlobalMechanisms,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCJoin(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCJoin(
    const unsigned int Heap,
    const unsigned int JoinTime,
    const unsigned int JoinType)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCJoin_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCJoin_V1(
    const unsigned int Heap,
    const unsigned int JoinTime,
    const unsigned int JoinType,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledPrvGCMarkStackRoots(){ return FALSE; }

extern "C" ULONG  FireEtXplatPrvGCMarkStackRoots(
    const unsigned int HeapNum)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledPrvGCMarkStackRoots_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatPrvGCMarkStackRoots_V1(
    const unsigned int HeapNum,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledPrvGCMarkFinalizeQueueRoots(){ return FALSE; }

extern "C" ULONG  FireEtXplatPrvGCMarkFinalizeQueueRoots(
    const unsigned int HeapNum)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledPrvGCMarkFinalizeQueueRoots_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatPrvGCMarkFinalizeQueueRoots_V1(
    const unsigned int HeapNum,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledPrvGCMarkHandles(){ return FALSE; }

extern "C" ULONG  FireEtXplatPrvGCMarkHandles(
    const unsigned int HeapNum)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledPrvGCMarkHandles_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatPrvGCMarkHandles_V1(
    const unsigned int HeapNum,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledPrvGCMarkCards(){ return FALSE; }

extern "C" ULONG  FireEtXplatPrvGCMarkCards(
    const unsigned int HeapNum)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledPrvGCMarkCards_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatPrvGCMarkCards_V1(
    const unsigned int HeapNum,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledBGCBegin(){ return FALSE; }

extern "C" ULONG  FireEtXplatBGCBegin(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledBGC1stNonConEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatBGC1stNonConEnd(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledBGC1stConEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatBGC1stConEnd(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledBGC2ndNonConBegin(){ return FALSE; }

extern "C" ULONG  FireEtXplatBGC2ndNonConBegin(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledBGC2ndNonConEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatBGC2ndNonConEnd(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledBGC2ndConBegin(){ return FALSE; }

extern "C" ULONG  FireEtXplatBGC2ndConBegin(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledBGC2ndConEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatBGC2ndConEnd(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledBGCPlanEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatBGCPlanEnd(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledBGCSweepEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatBGCSweepEnd(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledBGCDrainMark(){ return FALSE; }

extern "C" ULONG  FireEtXplatBGCDrainMark(
    const uint64_t Objects,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledBGCRevisit(){ return FALSE; }

extern "C" ULONG  FireEtXplatBGCRevisit(
    const uint64_t Pages,
    const uint64_t Objects,
    const unsigned int IsLarge,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledBGCOverflow(){ return FALSE; }

extern "C" ULONG  FireEtXplatBGCOverflow(
    const uint64_t Min,
    const uint64_t Max,
    const uint64_t Objects,
    const unsigned int IsLarge,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledBGCOverflow_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatBGCOverflow_V1(
    const uint64_t Min,
    const uint64_t Max,
    const uint64_t Objects,
    const unsigned int IsLarge,
    const unsigned short ClrInstanceID,
    const unsigned int GenNumber)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledBGCAllocWaitBegin(){ return FALSE; }

extern "C" ULONG  FireEtXplatBGCAllocWaitBegin(
    const unsigned int Reason,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledBGCAllocWaitEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatBGCAllocWaitEnd(
    const unsigned int Reason,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCFullNotify(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCFullNotify(
    const unsigned int GenNumber,
    const unsigned int IsAlloc)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCFullNotify_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCFullNotify_V1(
    const unsigned int GenNumber,
    const unsigned int IsAlloc,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledBGC1stSweepEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatBGC1stSweepEnd(
    const unsigned int GenNumber,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledEEStartupStart(){ return FALSE; }

extern "C" ULONG  FireEtXplatEEStartupStart(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledEEStartupStart_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatEEStartupStart_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledEEStartupEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatEEStartupEnd(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledEEStartupEnd_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatEEStartupEnd_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledEEConfigSetup(){ return FALSE; }

extern "C" ULONG  FireEtXplatEEConfigSetup(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledEEConfigSetup_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatEEConfigSetup_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledEEConfigSetupEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatEEConfigSetupEnd(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledEEConfigSetupEnd_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatEEConfigSetupEnd_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledLdSysBases(){ return FALSE; }

extern "C" ULONG  FireEtXplatLdSysBases(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledLdSysBases_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatLdSysBases_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledLdSysBasesEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatLdSysBasesEnd(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledLdSysBasesEnd_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatLdSysBasesEnd_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledExecExe(){ return FALSE; }

extern "C" ULONG  FireEtXplatExecExe(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledExecExe_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatExecExe_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledExecExeEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatExecExeEnd(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledExecExeEnd_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatExecExeEnd_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMain(){ return FALSE; }

extern "C" ULONG  FireEtXplatMain(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMain_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatMain_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMainEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatMainEnd(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMainEnd_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatMainEnd_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledApplyPolicyStart(){ return FALSE; }

extern "C" ULONG  FireEtXplatApplyPolicyStart(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledApplyPolicyStart_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatApplyPolicyStart_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledApplyPolicyEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatApplyPolicyEnd(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledApplyPolicyEnd_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatApplyPolicyEnd_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledLdLibShFolder(){ return FALSE; }

extern "C" ULONG  FireEtXplatLdLibShFolder(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledLdLibShFolder_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatLdLibShFolder_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledLdLibShFolderEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatLdLibShFolderEnd(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledLdLibShFolderEnd_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatLdLibShFolderEnd_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledPrestubWorker(){ return FALSE; }

extern "C" ULONG  FireEtXplatPrestubWorker(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledPrestubWorker_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatPrestubWorker_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledPrestubWorkerEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatPrestubWorkerEnd(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledPrestubWorkerEnd_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatPrestubWorkerEnd_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGetInstallationStart(){ return FALSE; }

extern "C" ULONG  FireEtXplatGetInstallationStart(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGetInstallationStart_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatGetInstallationStart_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGetInstallationEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatGetInstallationEnd(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGetInstallationEnd_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatGetInstallationEnd_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledOpenHModule(){ return FALSE; }

extern "C" ULONG  FireEtXplatOpenHModule(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledOpenHModule_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatOpenHModule_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledOpenHModuleEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatOpenHModuleEnd(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledOpenHModuleEnd_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatOpenHModuleEnd_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledExplicitBindStart(){ return FALSE; }

extern "C" ULONG  FireEtXplatExplicitBindStart(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledExplicitBindStart_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatExplicitBindStart_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledExplicitBindEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatExplicitBindEnd(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledExplicitBindEnd_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatExplicitBindEnd_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledParseXml(){ return FALSE; }

extern "C" ULONG  FireEtXplatParseXml(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledParseXml_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatParseXml_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledParseXmlEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatParseXmlEnd(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledParseXmlEnd_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatParseXmlEnd_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledInitDefaultDomain(){ return FALSE; }

extern "C" ULONG  FireEtXplatInitDefaultDomain(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledInitDefaultDomain_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatInitDefaultDomain_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledInitDefaultDomainEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatInitDefaultDomainEnd(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledInitDefaultDomainEnd_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatInitDefaultDomainEnd_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledInitSecurity(){ return FALSE; }

extern "C" ULONG  FireEtXplatInitSecurity(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledInitSecurity_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatInitSecurity_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledInitSecurityEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatInitSecurityEnd(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledInitSecurityEnd_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatInitSecurityEnd_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledAllowBindingRedirs(){ return FALSE; }

extern "C" ULONG  FireEtXplatAllowBindingRedirs(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledAllowBindingRedirs_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatAllowBindingRedirs_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledAllowBindingRedirsEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatAllowBindingRedirsEnd(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledAllowBindingRedirsEnd_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatAllowBindingRedirsEnd_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledEEConfigSync(){ return FALSE; }

extern "C" ULONG  FireEtXplatEEConfigSync(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledEEConfigSync_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatEEConfigSync_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledEEConfigSyncEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatEEConfigSyncEnd(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledEEConfigSyncEnd_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatEEConfigSyncEnd_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledFusionBinding(){ return FALSE; }

extern "C" ULONG  FireEtXplatFusionBinding(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledFusionBinding_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatFusionBinding_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledFusionBindingEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatFusionBindingEnd(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledFusionBindingEnd_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatFusionBindingEnd_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledLoaderCatchCall(){ return FALSE; }

extern "C" ULONG  FireEtXplatLoaderCatchCall(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledLoaderCatchCall_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatLoaderCatchCall_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledLoaderCatchCallEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatLoaderCatchCallEnd(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledLoaderCatchCallEnd_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatLoaderCatchCallEnd_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledFusionInit(){ return FALSE; }

extern "C" ULONG  FireEtXplatFusionInit(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledFusionInit_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatFusionInit_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledFusionInitEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatFusionInitEnd(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledFusionInitEnd_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatFusionInitEnd_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledFusionAppCtx(){ return FALSE; }

extern "C" ULONG  FireEtXplatFusionAppCtx(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledFusionAppCtx_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatFusionAppCtx_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledFusionAppCtxEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatFusionAppCtxEnd(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledFusionAppCtxEnd_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatFusionAppCtxEnd_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledFusion2EE(){ return FALSE; }

extern "C" ULONG  FireEtXplatFusion2EE(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledFusion2EE_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatFusion2EE_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledFusion2EEEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatFusion2EEEnd(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledFusion2EEEnd_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatFusion2EEEnd_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledSecurityCatchCall(){ return FALSE; }

extern "C" ULONG  FireEtXplatSecurityCatchCall(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledSecurityCatchCall_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatSecurityCatchCall_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledSecurityCatchCallEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatSecurityCatchCallEnd(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledSecurityCatchCallEnd_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatSecurityCatchCallEnd_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledCLRStackWalkPrivate(){ return FALSE; }

extern "C" ULONG  FireEtXplatCLRStackWalkPrivate(
    const unsigned short ClrInstanceID,
    const unsigned char Reserved1,
    const unsigned char Reserved2,
    const unsigned int FrameCount,
    const void** Stack)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledModuleRangeLoadPrivate(){ return FALSE; }

extern "C" ULONG  FireEtXplatModuleRangeLoadPrivate(
    const unsigned short ClrInstanceID,
    const uint64_t ModuleID,
    const unsigned int RangeBegin,
    const unsigned int RangeSize,
    const unsigned char RangeType,
    const unsigned char IBCType,
    const unsigned short SectionType)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledBindingPolicyPhaseStart(){ return FALSE; }

extern "C" ULONG  FireEtXplatBindingPolicyPhaseStart(
    const unsigned int AppDomainID,
    const unsigned int LoadContextID,
    const unsigned int FromLoaderCache,
    const unsigned int DynamicLoad,
    PCWSTR AssemblyCodebase,
    PCWSTR AssemblyName,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledBindingPolicyPhaseEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatBindingPolicyPhaseEnd(
    const unsigned int AppDomainID,
    const unsigned int LoadContextID,
    const unsigned int FromLoaderCache,
    const unsigned int DynamicLoad,
    PCWSTR AssemblyCodebase,
    PCWSTR AssemblyName,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledBindingNgenPhaseStart(){ return FALSE; }

extern "C" ULONG  FireEtXplatBindingNgenPhaseStart(
    const unsigned int AppDomainID,
    const unsigned int LoadContextID,
    const unsigned int FromLoaderCache,
    const unsigned int DynamicLoad,
    PCWSTR AssemblyCodebase,
    PCWSTR AssemblyName,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledBindingNgenPhaseEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatBindingNgenPhaseEnd(
    const unsigned int AppDomainID,
    const unsigned int LoadContextID,
    const unsigned int FromLoaderCache,
    const unsigned int DynamicLoad,
    PCWSTR AssemblyCodebase,
    PCWSTR AssemblyName,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledBindingLookupAndProbingPhaseStart(){ return FALSE; }

extern "C" ULONG  FireEtXplatBindingLookupAndProbingPhaseStart(
    const unsigned int AppDomainID,
    const unsigned int LoadContextID,
    const unsigned int FromLoaderCache,
    const unsigned int DynamicLoad,
    PCWSTR AssemblyCodebase,
    PCWSTR AssemblyName,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledBindingLookupAndProbingPhaseEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatBindingLookupAndProbingPhaseEnd(
    const unsigned int AppDomainID,
    const unsigned int LoadContextID,
    const unsigned int FromLoaderCache,
    const unsigned int DynamicLoad,
    PCWSTR AssemblyCodebase,
    PCWSTR AssemblyName,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledLoaderPhaseStart(){ return FALSE; }

extern "C" ULONG  FireEtXplatLoaderPhaseStart(
    const unsigned int AppDomainID,
    const unsigned int LoadContextID,
    const unsigned int FromLoaderCache,
    const unsigned int DynamicLoad,
    PCWSTR AssemblyCodebase,
    PCWSTR AssemblyName,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledLoaderPhaseEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatLoaderPhaseEnd(
    const unsigned int AppDomainID,
    const unsigned int LoadContextID,
    const unsigned int FromLoaderCache,
    const unsigned int DynamicLoad,
    PCWSTR AssemblyCodebase,
    PCWSTR AssemblyName,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledBindingPhaseStart(){ return FALSE; }

extern "C" ULONG  FireEtXplatBindingPhaseStart(
    const unsigned int AppDomainID,
    const unsigned int LoadContextID,
    const unsigned int FromLoaderCache,
    const unsigned int DynamicLoad,
    PCWSTR AssemblyCodebase,
    PCWSTR AssemblyName,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledBindingPhaseEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatBindingPhaseEnd(
    const unsigned int AppDomainID,
    const unsigned int LoadContextID,
    const unsigned int FromLoaderCache,
    const unsigned int DynamicLoad,
    PCWSTR AssemblyCodebase,
    PCWSTR AssemblyName,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledBindingDownloadPhaseStart(){ return FALSE; }

extern "C" ULONG  FireEtXplatBindingDownloadPhaseStart(
    const unsigned int AppDomainID,
    const unsigned int LoadContextID,
    const unsigned int FromLoaderCache,
    const unsigned int DynamicLoad,
    PCWSTR AssemblyCodebase,
    PCWSTR AssemblyName,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledBindingDownloadPhaseEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatBindingDownloadPhaseEnd(
    const unsigned int AppDomainID,
    const unsigned int LoadContextID,
    const unsigned int FromLoaderCache,
    const unsigned int DynamicLoad,
    PCWSTR AssemblyCodebase,
    PCWSTR AssemblyName,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledLoaderAssemblyInitPhaseStart(){ return FALSE; }

extern "C" ULONG  FireEtXplatLoaderAssemblyInitPhaseStart(
    const unsigned int AppDomainID,
    const unsigned int LoadContextID,
    const unsigned int FromLoaderCache,
    const unsigned int DynamicLoad,
    PCWSTR AssemblyCodebase,
    PCWSTR AssemblyName,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledLoaderAssemblyInitPhaseEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatLoaderAssemblyInitPhaseEnd(
    const unsigned int AppDomainID,
    const unsigned int LoadContextID,
    const unsigned int FromLoaderCache,
    const unsigned int DynamicLoad,
    PCWSTR AssemblyCodebase,
    PCWSTR AssemblyName,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledLoaderMappingPhaseStart(){ return FALSE; }

extern "C" ULONG  FireEtXplatLoaderMappingPhaseStart(
    const unsigned int AppDomainID,
    const unsigned int LoadContextID,
    const unsigned int FromLoaderCache,
    const unsigned int DynamicLoad,
    PCWSTR AssemblyCodebase,
    PCWSTR AssemblyName,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledLoaderMappingPhaseEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatLoaderMappingPhaseEnd(
    const unsigned int AppDomainID,
    const unsigned int LoadContextID,
    const unsigned int FromLoaderCache,
    const unsigned int DynamicLoad,
    PCWSTR AssemblyCodebase,
    PCWSTR AssemblyName,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledLoaderDeliverEventsPhaseStart(){ return FALSE; }

extern "C" ULONG  FireEtXplatLoaderDeliverEventsPhaseStart(
    const unsigned int AppDomainID,
    const unsigned int LoadContextID,
    const unsigned int FromLoaderCache,
    const unsigned int DynamicLoad,
    PCWSTR AssemblyCodebase,
    PCWSTR AssemblyName,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledLoaderDeliverEventsPhaseEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatLoaderDeliverEventsPhaseEnd(
    const unsigned int AppDomainID,
    const unsigned int LoadContextID,
    const unsigned int FromLoaderCache,
    const unsigned int DynamicLoad,
    PCWSTR AssemblyCodebase,
    PCWSTR AssemblyName,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledEvidenceGenerated(){ return FALSE; }

extern "C" ULONG  FireEtXplatEvidenceGenerated(
    const unsigned int Type,
    const unsigned int AppDomain,
    PCWSTR ILImage,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledModuleTransparencyComputationStart(){ return FALSE; }

extern "C" ULONG  FireEtXplatModuleTransparencyComputationStart(
    PCWSTR Module,
    const unsigned int AppDomainID,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledModuleTransparencyComputationEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatModuleTransparencyComputationEnd(
    PCWSTR Module,
    const unsigned int AppDomainID,
    const BOOL IsAllCritical,
    const BOOL IsAllTransparent,
    const BOOL IsTreatAsSafe,
    const BOOL IsOpportunisticallyCritical,
    const unsigned int SecurityRuleSet,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledTypeTransparencyComputationStart(){ return FALSE; }

extern "C" ULONG  FireEtXplatTypeTransparencyComputationStart(
    PCWSTR Type,
    PCWSTR Module,
    const unsigned int AppDomainID,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledTypeTransparencyComputationEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatTypeTransparencyComputationEnd(
    PCWSTR Type,
    PCWSTR Module,
    const unsigned int AppDomainID,
    const BOOL IsAllCritical,
    const BOOL IsAllTransparent,
    const BOOL IsCritical,
    const BOOL IsTreatAsSafe,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMethodTransparencyComputationStart(){ return FALSE; }

extern "C" ULONG  FireEtXplatMethodTransparencyComputationStart(
    PCWSTR Method,
    PCWSTR Module,
    const unsigned int AppDomainID,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMethodTransparencyComputationEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatMethodTransparencyComputationEnd(
    PCWSTR Method,
    PCWSTR Module,
    const unsigned int AppDomainID,
    const BOOL IsCritical,
    const BOOL IsTreatAsSafe,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledFieldTransparencyComputationStart(){ return FALSE; }

extern "C" ULONG  FireEtXplatFieldTransparencyComputationStart(
    PCWSTR Field,
    PCWSTR Module,
    const unsigned int AppDomainID,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledFieldTransparencyComputationEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatFieldTransparencyComputationEnd(
    PCWSTR Field,
    PCWSTR Module,
    const unsigned int AppDomainID,
    const BOOL IsCritical,
    const BOOL IsTreatAsSafe,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledTokenTransparencyComputationStart(){ return FALSE; }

extern "C" ULONG  FireEtXplatTokenTransparencyComputationStart(
    const unsigned int Token,
    PCWSTR Module,
    const unsigned int AppDomainID,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledTokenTransparencyComputationEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatTokenTransparencyComputationEnd(
    const unsigned int Token,
    PCWSTR Module,
    const unsigned int AppDomainID,
    const BOOL IsCritical,
    const BOOL IsTreatAsSafe,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledNgenBindEvent(){ return FALSE; }

extern "C" ULONG  FireEtXplatNgenBindEvent(
    const unsigned short ClrInstanceID,
    const uint64_t BindingID,
    const unsigned int ReasonCode,
    PCWSTR AssemblyName)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledJittedMethodRichDebugInfo(){ return FALSE; }

extern "C" ULONG  FireEtXplatJittedMethodRichDebugInfo(
    const unsigned short ClrInstanceID,
    const uint64_t MethodID,
    const uint64_t ReJITID,
    const uint64_t ILVersionID,
    const unsigned int ChunkIndex,
    const unsigned int DataSize,
    const BYTE* Data)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledFailFast(){ return FALSE; }

extern "C" ULONG  FireEtXplatFailFast(
    PCWSTR FailFastUserMessage,
    const void* FailedEIP,
    const unsigned int OSExitCode,
    const unsigned int ClrExitCode,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledPrvFinalizeObject(){ return FALSE; }

extern "C" ULONG  FireEtXplatPrvFinalizeObject(
    const void* TypeID,
    const void* ObjectID,
    const unsigned short ClrInstanceID,
    PCWSTR TypeName)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledCCWRefCountChangeAnsi(){ return FALSE; }

extern "C" ULONG  FireEtXplatCCWRefCountChangeAnsi(
    const void* HandleID,
    const void* ObjectID,
    const void* COMInterfacePointer,
    const unsigned int NewRefCount,
    const uint64_t AppDomainID,
    LPCSTR ClassName,
    LPCSTR NameSpace,
    PCWSTR Operation,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledPrvSetGCHandle(){ return FALSE; }

extern "C" ULONG  FireEtXplatPrvSetGCHandle(
    const void* HandleID,
    const void* ObjectID,
    const unsigned int Kind,
    const unsigned int Generation,
    const uint64_t AppDomainID,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledPrvDestroyGCHandle(){ return FALSE; }

extern "C" ULONG  FireEtXplatPrvDestroyGCHandle(
    const void* HandleID,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledFusionMessageEvent(){ return FALSE; }

extern "C" ULONG  FireEtXplatFusionMessageEvent(
    const unsigned short ClrInstanceID,
    const BOOL Prepend,
    PCWSTR Message)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledFusionErrorCodeEvent(){ return FALSE; }

extern "C" ULONG  FireEtXplatFusionErrorCodeEvent(
    const unsigned short ClrInstanceID,
    const unsigned int Category,
    const unsigned int ErrorCode)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledPinPlugAtGCTime(){ return FALSE; }

extern "C" ULONG  FireEtXplatPinPlugAtGCTime(
    const void* PlugStart,
    const void* PlugEnd,
    const void* GapBeforeSize,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledCCWRefCountChange(){ return FALSE; }

extern "C" ULONG  FireEtXplatCCWRefCountChange(
    const void* HandleID,
    const void* ObjectID,
    const void* COMInterfacePointer,
    const unsigned int NewRefCount,
    const uint64_t AppDomainID,
    PCWSTR ClassName,
    PCWSTR NameSpace,
    PCWSTR Operation,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledAllocRequest(){ return FALSE; }

extern "C" ULONG  FireEtXplatAllocRequest(
    const void* LoaderHeapPtr,
    const void* MemoryAddress,
    const unsigned int RequestSize,
    const unsigned int Unused1,
    const uint64_t Unused2,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMulticoreJit(){ return FALSE; }

extern "C" ULONG  FireEtXplatMulticoreJit(
    const unsigned short ClrInstanceID,
    PCWSTR String1,
    PCWSTR String2,
    const signed int Int1,
    const signed int Int2,
    const signed int Int3)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMulticoreJitMethodCodeReturned(){ return FALSE; }

extern "C" ULONG  FireEtXplatMulticoreJitMethodCodeReturned(
    const unsigned short ClrInstanceID,
    const uint64_t ModuleID,
    const uint64_t MethodID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledIInspectableRuntimeClassName(){ return FALSE; }

extern "C" ULONG  FireEtXplatIInspectableRuntimeClassName(
    PCWSTR TypeName,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledWinRTUnbox(){ return FALSE; }

extern "C" ULONG  FireEtXplatWinRTUnbox(
    PCWSTR TypeName,
    PCWSTR SecondTypeName,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledCreateRCW(){ return FALSE; }

extern "C" ULONG  FireEtXplatCreateRCW(
    PCWSTR TypeName,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledRCWVariance(){ return FALSE; }

extern "C" ULONG  FireEtXplatRCWVariance(
    PCWSTR TypeName,
    PCWSTR InterfaceTypeName,
    PCWSTR VariantInterfaceTypeName,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledRCWIEnumerableCasting(){ return FALSE; }

extern "C" ULONG  FireEtXplatRCWIEnumerableCasting(
    PCWSTR TypeName,
    PCWSTR SecondTypeName,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledCreateCCW(){ return FALSE; }

extern "C" ULONG  FireEtXplatCreateCCW(
    PCWSTR TypeName,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledCCWVariance(){ return FALSE; }

extern "C" ULONG  FireEtXplatCCWVariance(
    PCWSTR TypeName,
    PCWSTR InterfaceTypeName,
    PCWSTR VariantInterfaceTypeName,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledObjectVariantMarshallingToNative(){ return FALSE; }

extern "C" ULONG  FireEtXplatObjectVariantMarshallingToNative(
    PCWSTR TypeName,
    const signed int Int1,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGetTypeFromGUID(){ return FALSE; }

extern "C" ULONG  FireEtXplatGetTypeFromGUID(
    PCWSTR TypeName,
    PCWSTR SecondTypeName,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGetTypeFromProgID(){ return FALSE; }

extern "C" ULONG  FireEtXplatGetTypeFromProgID(
    PCWSTR TypeName,
    PCWSTR SecondTypeName,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledConvertToCallbackEtw(){ return FALSE; }

extern "C" ULONG  FireEtXplatConvertToCallbackEtw(
    PCWSTR TypeName,
    PCWSTR SecondTypeName,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledBeginCreateManagedReference(){ return FALSE; }

extern "C" ULONG  FireEtXplatBeginCreateManagedReference(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledEndCreateManagedReference(){ return FALSE; }

extern "C" ULONG  FireEtXplatEndCreateManagedReference(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledObjectVariantMarshallingToManaged(){ return FALSE; }

extern "C" ULONG  FireEtXplatObjectVariantMarshallingToManaged(
    PCWSTR TypeName,
    const signed int Int1,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}


