
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

/******************************************************************

DO NOT MODIFY. AUTOGENERATED FILE.
This file is generated using the logic from <root>/src/scripts/genDummyProvider.py

******************************************************************/


#ifdef TARGET_UNIX
#include "pal_mstypes.h"
#include "pal_error.h"
#include "pal.h"
#include "pal/stackstring.hpp"
#endif


extern "C" BOOL  EventXplatEnabledStressLogEvent(){ return FALSE; }

extern "C" ULONG  FireEtXplatStressLogEvent(
    const unsigned int Facility,
    const unsigned char LogLevel,
    LPCSTR Message)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledStressLogEvent_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatStressLogEvent_V1(
    const unsigned int Facility,
    const unsigned char LogLevel,
    LPCSTR Message,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledCLRStackWalkStress(){ return FALSE; }

extern "C" ULONG  FireEtXplatCLRStackWalkStress(
    const unsigned short ClrInstanceID,
    const unsigned char Reserved1,
    const unsigned char Reserved2,
    const unsigned int FrameCount,
    const void** Stack)
{
    return ERROR_SUCCESS;
}


