
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

/******************************************************************

DO NOT MODIFY. AUTOGENERATED FILE.
This file is generated using the logic from <root>/src/scripts/genDummyProvider.py

******************************************************************/


#ifdef TARGET_UNIX
#include "pal_mstypes.h"
#include "pal_error.h"
#include "pal.h"
#include "pal/stackstring.hpp"
#endif


extern "C" BOOL  EventXplatEnabledCLRStackWalkDCStart(){ return FALSE; }

extern "C" ULONG  FireEtXplatCLRStackWalkDCStart(
    const unsigned short ClrInstanceID,
    const unsigned char Reserved1,
    const unsigned char Reserved2,
    const unsigned int FrameCount,
    const void** Stack)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCSettingsRundown(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCSettingsRundown(
    const uint64_t HardLimit,
    const uint64_t LOHThreshold,
    const uint64_t PhysicalMemoryConfig,
    const uint64_t Gen0MinBudgetConfig,
    const uint64_t Gen0MaxBudgetConfig,
    const unsigned int HighMemPercentConfig,
    const unsigned int BitSettings,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMethodDCStart(){ return FALSE; }

extern "C" ULONG  FireEtXplatMethodDCStart(
    const uint64_t MethodID,
    const uint64_t ModuleID,
    const uint64_t MethodStartAddress,
    const unsigned int MethodSize,
    const unsigned int MethodToken,
    const unsigned int MethodFlags)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMethodDCStart_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatMethodDCStart_V1(
    const uint64_t MethodID,
    const uint64_t ModuleID,
    const uint64_t MethodStartAddress,
    const unsigned int MethodSize,
    const unsigned int MethodToken,
    const unsigned int MethodFlags,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMethodDCStart_V2(){ return FALSE; }

extern "C" ULONG  FireEtXplatMethodDCStart_V2(
    const uint64_t MethodID,
    const uint64_t ModuleID,
    const uint64_t MethodStartAddress,
    const unsigned int MethodSize,
    const unsigned int MethodToken,
    const unsigned int MethodFlags,
    const unsigned short ClrInstanceID,
    const uint64_t ReJITID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMethodDCEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatMethodDCEnd(
    const uint64_t MethodID,
    const uint64_t ModuleID,
    const uint64_t MethodStartAddress,
    const unsigned int MethodSize,
    const unsigned int MethodToken,
    const unsigned int MethodFlags)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMethodDCEnd_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatMethodDCEnd_V1(
    const uint64_t MethodID,
    const uint64_t ModuleID,
    const uint64_t MethodStartAddress,
    const unsigned int MethodSize,
    const unsigned int MethodToken,
    const unsigned int MethodFlags,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMethodDCEnd_V2(){ return FALSE; }

extern "C" ULONG  FireEtXplatMethodDCEnd_V2(
    const uint64_t MethodID,
    const uint64_t ModuleID,
    const uint64_t MethodStartAddress,
    const unsigned int MethodSize,
    const unsigned int MethodToken,
    const unsigned int MethodFlags,
    const unsigned short ClrInstanceID,
    const uint64_t ReJITID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMethodDCStartVerbose(){ return FALSE; }

extern "C" ULONG  FireEtXplatMethodDCStartVerbose(
    const uint64_t MethodID,
    const uint64_t ModuleID,
    const uint64_t MethodStartAddress,
    const unsigned int MethodSize,
    const unsigned int MethodToken,
    const unsigned int MethodFlags,
    PCWSTR MethodNamespace,
    PCWSTR MethodName,
    PCWSTR MethodSignature)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMethodDCStartVerbose_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatMethodDCStartVerbose_V1(
    const uint64_t MethodID,
    const uint64_t ModuleID,
    const uint64_t MethodStartAddress,
    const unsigned int MethodSize,
    const unsigned int MethodToken,
    const unsigned int MethodFlags,
    PCWSTR MethodNamespace,
    PCWSTR MethodName,
    PCWSTR MethodSignature,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMethodDCStartVerbose_V2(){ return FALSE; }

extern "C" ULONG  FireEtXplatMethodDCStartVerbose_V2(
    const uint64_t MethodID,
    const uint64_t ModuleID,
    const uint64_t MethodStartAddress,
    const unsigned int MethodSize,
    const unsigned int MethodToken,
    const unsigned int MethodFlags,
    PCWSTR MethodNamespace,
    PCWSTR MethodName,
    PCWSTR MethodSignature,
    const unsigned short ClrInstanceID,
    const uint64_t ReJITID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMethodDCEndVerbose(){ return FALSE; }

extern "C" ULONG  FireEtXplatMethodDCEndVerbose(
    const uint64_t MethodID,
    const uint64_t ModuleID,
    const uint64_t MethodStartAddress,
    const unsigned int MethodSize,
    const unsigned int MethodToken,
    const unsigned int MethodFlags,
    PCWSTR MethodNamespace,
    PCWSTR MethodName,
    PCWSTR MethodSignature)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMethodDCEndVerbose_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatMethodDCEndVerbose_V1(
    const uint64_t MethodID,
    const uint64_t ModuleID,
    const uint64_t MethodStartAddress,
    const unsigned int MethodSize,
    const unsigned int MethodToken,
    const unsigned int MethodFlags,
    PCWSTR MethodNamespace,
    PCWSTR MethodName,
    PCWSTR MethodSignature,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMethodDCEndVerbose_V2(){ return FALSE; }

extern "C" ULONG  FireEtXplatMethodDCEndVerbose_V2(
    const uint64_t MethodID,
    const uint64_t ModuleID,
    const uint64_t MethodStartAddress,
    const unsigned int MethodSize,
    const unsigned int MethodToken,
    const unsigned int MethodFlags,
    PCWSTR MethodNamespace,
    PCWSTR MethodName,
    PCWSTR MethodSignature,
    const unsigned short ClrInstanceID,
    const uint64_t ReJITID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledDCStartComplete(){ return FALSE; }

extern "C" ULONG  FireEtXplatDCStartComplete(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledDCStartComplete_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatDCStartComplete_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledDCEndComplete(){ return FALSE; }

extern "C" ULONG  FireEtXplatDCEndComplete(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledDCEndComplete_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatDCEndComplete_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledDCStartInit(){ return FALSE; }

extern "C" ULONG  FireEtXplatDCStartInit(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledDCStartInit_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatDCStartInit_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledDCEndInit(){ return FALSE; }

extern "C" ULONG  FireEtXplatDCEndInit(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledDCEndInit_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatDCEndInit_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMethodDCStartILToNativeMap(){ return FALSE; }

extern "C" ULONG  FireEtXplatMethodDCStartILToNativeMap(
    const uint64_t MethodID,
    const uint64_t ReJITID,
    const unsigned char MethodExtent,
    const unsigned short CountOfMapEntries,
    const unsigned int* ILOffsets,
    const unsigned int* NativeOffsets,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMethodDCStartILToNativeMap_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatMethodDCStartILToNativeMap_V1(
    const uint64_t MethodID,
    const uint64_t ReJITID,
    const unsigned char MethodExtent,
    const unsigned short CountOfMapEntries,
    const unsigned int* ILOffsets,
    const unsigned int* NativeOffsets,
    const unsigned short ClrInstanceID,
    const uint64_t ILVersionID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMethodDCEndILToNativeMap(){ return FALSE; }

extern "C" ULONG  FireEtXplatMethodDCEndILToNativeMap(
    const uint64_t MethodID,
    const uint64_t ReJITID,
    const unsigned char MethodExtent,
    const unsigned short CountOfMapEntries,
    const unsigned int* ILOffsets,
    const unsigned int* NativeOffsets,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMethodDCEndILToNativeMap_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatMethodDCEndILToNativeMap_V1(
    const uint64_t MethodID,
    const uint64_t ReJITID,
    const unsigned char MethodExtent,
    const unsigned short CountOfMapEntries,
    const unsigned int* ILOffsets,
    const unsigned int* NativeOffsets,
    const unsigned short ClrInstanceID,
    const uint64_t ILVersionID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledDomainModuleDCStart(){ return FALSE; }

extern "C" ULONG  FireEtXplatDomainModuleDCStart(
    const uint64_t ModuleID,
    const uint64_t AssemblyID,
    const uint64_t AppDomainID,
    const unsigned int ModuleFlags,
    const unsigned int Reserved1,
    PCWSTR ModuleILPath,
    PCWSTR ModuleNativePath)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledDomainModuleDCStart_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatDomainModuleDCStart_V1(
    const uint64_t ModuleID,
    const uint64_t AssemblyID,
    const uint64_t AppDomainID,
    const unsigned int ModuleFlags,
    const unsigned int Reserved1,
    PCWSTR ModuleILPath,
    PCWSTR ModuleNativePath,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledDomainModuleDCEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatDomainModuleDCEnd(
    const uint64_t ModuleID,
    const uint64_t AssemblyID,
    const uint64_t AppDomainID,
    const unsigned int ModuleFlags,
    const unsigned int Reserved1,
    PCWSTR ModuleILPath,
    PCWSTR ModuleNativePath)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledDomainModuleDCEnd_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatDomainModuleDCEnd_V1(
    const uint64_t ModuleID,
    const uint64_t AssemblyID,
    const uint64_t AppDomainID,
    const unsigned int ModuleFlags,
    const unsigned int Reserved1,
    PCWSTR ModuleILPath,
    PCWSTR ModuleNativePath,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledModuleDCStart(){ return FALSE; }

extern "C" ULONG  FireEtXplatModuleDCStart(
    const uint64_t ModuleID,
    const uint64_t AssemblyID,
    const unsigned int ModuleFlags,
    const unsigned int Reserved1,
    PCWSTR ModuleILPath,
    PCWSTR ModuleNativePath)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledModuleDCStart_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatModuleDCStart_V1(
    const uint64_t ModuleID,
    const uint64_t AssemblyID,
    const unsigned int ModuleFlags,
    const unsigned int Reserved1,
    PCWSTR ModuleILPath,
    PCWSTR ModuleNativePath,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledModuleDCStart_V2(){ return FALSE; }

extern "C" ULONG  FireEtXplatModuleDCStart_V2(
    const uint64_t ModuleID,
    const uint64_t AssemblyID,
    const unsigned int ModuleFlags,
    const unsigned int Reserved1,
    PCWSTR ModuleILPath,
    PCWSTR ModuleNativePath,
    const unsigned short ClrInstanceID,
    const GUID* ManagedPdbSignature,
    const unsigned int ManagedPdbAge,
    PCWSTR ManagedPdbBuildPath,
    const GUID* NativePdbSignature,
    const unsigned int NativePdbAge,
    PCWSTR NativePdbBuildPath)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledModuleDCEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatModuleDCEnd(
    const uint64_t ModuleID,
    const uint64_t AssemblyID,
    const unsigned int ModuleFlags,
    const unsigned int Reserved1,
    PCWSTR ModuleILPath,
    PCWSTR ModuleNativePath)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledModuleDCEnd_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatModuleDCEnd_V1(
    const uint64_t ModuleID,
    const uint64_t AssemblyID,
    const unsigned int ModuleFlags,
    const unsigned int Reserved1,
    PCWSTR ModuleILPath,
    PCWSTR ModuleNativePath,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledModuleDCEnd_V2(){ return FALSE; }

extern "C" ULONG  FireEtXplatModuleDCEnd_V2(
    const uint64_t ModuleID,
    const uint64_t AssemblyID,
    const unsigned int ModuleFlags,
    const unsigned int Reserved1,
    PCWSTR ModuleILPath,
    PCWSTR ModuleNativePath,
    const unsigned short ClrInstanceID,
    const GUID* ManagedPdbSignature,
    const unsigned int ManagedPdbAge,
    PCWSTR ManagedPdbBuildPath,
    const GUID* NativePdbSignature,
    const unsigned int NativePdbAge,
    PCWSTR NativePdbBuildPath)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledModuleDCEnd_V3(){ return FALSE; }

extern "C" ULONG  FireEtXplatModuleDCEnd_V3(
    const uint64_t ModuleID,
    const uint64_t AssemblyID,
    const unsigned int ModuleFlags,
    const unsigned int Reserved1,
    PCWSTR ModuleILPath,
    PCWSTR ModuleNativePath,
    const unsigned short ClrInstanceID,
    const GUID* ManagedPdbSignature,
    const unsigned int ManagedPdbAge,
    PCWSTR ManagedPdbBuildPath,
    const GUID* NativePdbSignature,
    const unsigned int NativePdbAge,
    PCWSTR NativePdbBuildPath,
    PCWSTR NativeBuildID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledAssemblyDCStart(){ return FALSE; }

extern "C" ULONG  FireEtXplatAssemblyDCStart(
    const uint64_t AssemblyID,
    const uint64_t AppDomainID,
    const unsigned int AssemblyFlags,
    PCWSTR FullyQualifiedAssemblyName)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledAssemblyDCStart_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatAssemblyDCStart_V1(
    const uint64_t AssemblyID,
    const uint64_t AppDomainID,
    const uint64_t BindingID,
    const unsigned int AssemblyFlags,
    PCWSTR FullyQualifiedAssemblyName,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledAssemblyDCEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatAssemblyDCEnd(
    const uint64_t AssemblyID,
    const uint64_t AppDomainID,
    const unsigned int AssemblyFlags,
    PCWSTR FullyQualifiedAssemblyName)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledAssemblyDCEnd_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatAssemblyDCEnd_V1(
    const uint64_t AssemblyID,
    const uint64_t AppDomainID,
    const uint64_t BindingID,
    const unsigned int AssemblyFlags,
    PCWSTR FullyQualifiedAssemblyName,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledAppDomainDCStart(){ return FALSE; }

extern "C" ULONG  FireEtXplatAppDomainDCStart(
    const uint64_t AppDomainID,
    const unsigned int AppDomainFlags,
    PCWSTR AppDomainName)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledAppDomainDCStart_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatAppDomainDCStart_V1(
    const uint64_t AppDomainID,
    const unsigned int AppDomainFlags,
    PCWSTR AppDomainName,
    const unsigned int AppDomainIndex,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledAppDomainDCEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatAppDomainDCEnd(
    const uint64_t AppDomainID,
    const unsigned int AppDomainFlags,
    PCWSTR AppDomainName)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledAppDomainDCEnd_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatAppDomainDCEnd_V1(
    const uint64_t AppDomainID,
    const unsigned int AppDomainFlags,
    PCWSTR AppDomainName,
    const unsigned int AppDomainIndex,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledThreadDC(){ return FALSE; }

extern "C" ULONG  FireEtXplatThreadDC(
    const uint64_t ManagedThreadID,
    const uint64_t AppDomainID,
    const unsigned int Flags,
    const unsigned int ManagedThreadIndex,
    const unsigned int OSThreadID,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledModuleRangeDCStart(){ return FALSE; }

extern "C" ULONG  FireEtXplatModuleRangeDCStart(
    const unsigned short ClrInstanceID,
    const uint64_t ModuleID,
    const unsigned int RangeBegin,
    const unsigned int RangeSize,
    const unsigned char RangeType)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledModuleRangeDCEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatModuleRangeDCEnd(
    const unsigned short ClrInstanceID,
    const uint64_t ModuleID,
    const unsigned int RangeBegin,
    const unsigned int RangeSize,
    const unsigned char RangeType)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledRuntimeInformationDCStart(){ return FALSE; }

extern "C" ULONG  FireEtXplatRuntimeInformationDCStart(
    const unsigned short ClrInstanceID,
    const unsigned short Sku,
    const unsigned short BclMajorVersion,
    const unsigned short BclMinorVersion,
    const unsigned short BclBuildNumber,
    const unsigned short BclQfeNumber,
    const unsigned short VMMajorVersion,
    const unsigned short VMMinorVersion,
    const unsigned short VMBuildNumber,
    const unsigned short VMQfeNumber,
    const unsigned int StartupFlags,
    const unsigned char StartupMode,
    PCWSTR CommandLine,
    const GUID* ComObjectGuid,
    PCWSTR RuntimeDllPath)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledTieredCompilationSettingsDCStart(){ return FALSE; }

extern "C" ULONG  FireEtXplatTieredCompilationSettingsDCStart(
    const unsigned short ClrInstanceID,
    const unsigned int Flags)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledExecutionCheckpointDCEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatExecutionCheckpointDCEnd(
    const unsigned short ClrInstanceID,
    PCWSTR Name,
    const int64_t Timestamp)
{
    return ERROR_SUCCESS;
}


