
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

/******************************************************************

DO NOT MODIFY. AUTOGENERATED FILE.
This file is generated using the logic from <root>/src/scripts/genDummyProvider.py

******************************************************************/


#ifdef TARGET_UNIX
#include "pal_mstypes.h"
#include "pal_error.h"
#include "pal.h"
#include "pal/stackstring.hpp"
#endif


extern "C" BOOL  EventXplatEnabledGCStart(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCStart(
    const unsigned int Count,
    const unsigned int Reason)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCStart_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCStart_V1(
    const unsigned int Count,
    const unsigned int Depth,
    const unsigned int Reason,
    const unsigned int Type,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCStart_V2(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCStart_V2(
    const unsigned int Count,
    const unsigned int Depth,
    const unsigned int Reason,
    const unsigned int Type,
    const unsigned short ClrInstanceID,
    const uint64_t ClientSequenceNumber)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCEnd(
    const unsigned int Count,
    const unsigned short Depth)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCEnd_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCEnd_V1(
    const unsigned int Count,
    const unsigned int Depth,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCRestartEEEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCRestartEEEnd(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCRestartEEEnd_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCRestartEEEnd_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCHeapStats(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCHeapStats(
    const uint64_t GenerationSize0,
    const uint64_t TotalPromotedSize0,
    const uint64_t GenerationSize1,
    const uint64_t TotalPromotedSize1,
    const uint64_t GenerationSize2,
    const uint64_t TotalPromotedSize2,
    const uint64_t GenerationSize3,
    const uint64_t TotalPromotedSize3,
    const uint64_t FinalizationPromotedSize,
    const uint64_t FinalizationPromotedCount,
    const unsigned int PinnedObjectCount,
    const unsigned int SinkBlockCount,
    const unsigned int GCHandleCount)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCHeapStats_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCHeapStats_V1(
    const uint64_t GenerationSize0,
    const uint64_t TotalPromotedSize0,
    const uint64_t GenerationSize1,
    const uint64_t TotalPromotedSize1,
    const uint64_t GenerationSize2,
    const uint64_t TotalPromotedSize2,
    const uint64_t GenerationSize3,
    const uint64_t TotalPromotedSize3,
    const uint64_t FinalizationPromotedSize,
    const uint64_t FinalizationPromotedCount,
    const unsigned int PinnedObjectCount,
    const unsigned int SinkBlockCount,
    const unsigned int GCHandleCount,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCHeapStats_V2(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCHeapStats_V2(
    const uint64_t GenerationSize0,
    const uint64_t TotalPromotedSize0,
    const uint64_t GenerationSize1,
    const uint64_t TotalPromotedSize1,
    const uint64_t GenerationSize2,
    const uint64_t TotalPromotedSize2,
    const uint64_t GenerationSize3,
    const uint64_t TotalPromotedSize3,
    const uint64_t FinalizationPromotedSize,
    const uint64_t FinalizationPromotedCount,
    const unsigned int PinnedObjectCount,
    const unsigned int SinkBlockCount,
    const unsigned int GCHandleCount,
    const unsigned short ClrInstanceID,
    const uint64_t GenerationSize4,
    const uint64_t TotalPromotedSize4)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCCreateSegment(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCCreateSegment(
    const uint64_t Address,
    const uint64_t Size,
    const unsigned int Type)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCCreateSegment_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCCreateSegment_V1(
    const uint64_t Address,
    const uint64_t Size,
    const unsigned int Type,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCFreeSegment(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCFreeSegment(
    const uint64_t Address)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCFreeSegment_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCFreeSegment_V1(
    const uint64_t Address,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCRestartEEBegin(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCRestartEEBegin(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCRestartEEBegin_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCRestartEEBegin_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCSuspendEEEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCSuspendEEEnd(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCSuspendEEEnd_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCSuspendEEEnd_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCSuspendEEBegin(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCSuspendEEBegin(
    const unsigned short Reason)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCSuspendEEBegin_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCSuspendEEBegin_V1(
    const unsigned int Reason,
    const unsigned int Count,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCAllocationTick(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCAllocationTick(
    const unsigned int AllocationAmount,
    const unsigned int AllocationKind)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCAllocationTick_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCAllocationTick_V1(
    const unsigned int AllocationAmount,
    const unsigned int AllocationKind,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCAllocationTick_V2(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCAllocationTick_V2(
    const unsigned int AllocationAmount,
    const unsigned int AllocationKind,
    const unsigned short ClrInstanceID,
    const uint64_t AllocationAmount64,
    const void* TypeID,
    PCWSTR TypeName,
    const unsigned int HeapIndex)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCAllocationTick_V3(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCAllocationTick_V3(
    const unsigned int AllocationAmount,
    const unsigned int AllocationKind,
    const unsigned short ClrInstanceID,
    const uint64_t AllocationAmount64,
    const void* TypeID,
    PCWSTR TypeName,
    const unsigned int HeapIndex,
    const void* Address)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCAllocationTick_V4(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCAllocationTick_V4(
    const unsigned int AllocationAmount,
    const unsigned int AllocationKind,
    const unsigned short ClrInstanceID,
    const uint64_t AllocationAmount64,
    const void* TypeID,
    PCWSTR TypeName,
    const unsigned int HeapIndex,
    const void* Address,
    const uint64_t ObjectSize)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCCreateConcurrentThread(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCCreateConcurrentThread(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCCreateConcurrentThread_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCCreateConcurrentThread_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCTerminateConcurrentThread(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCTerminateConcurrentThread(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCTerminateConcurrentThread_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCTerminateConcurrentThread_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCFinalizersEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCFinalizersEnd(
    const unsigned int Count)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCFinalizersEnd_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCFinalizersEnd_V1(
    const unsigned int Count,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCFinalizersBegin(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCFinalizersBegin(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCFinalizersBegin_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCFinalizersBegin_V1(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledBulkType(){ return FALSE; }

extern "C" ULONG  FireEtXplatBulkType(
    const unsigned int Count,
    const unsigned short ClrInstanceID,
    int Values_ElementSize,
    const void* Values)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCBulkRootEdge(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCBulkRootEdge(
    const unsigned int Index,
    const unsigned int Count,
    const unsigned short ClrInstanceID,
    int Values_ElementSize,
    const void* Values)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCBulkRootConditionalWeakTableElementEdge(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCBulkRootConditionalWeakTableElementEdge(
    const unsigned int Index,
    const unsigned int Count,
    const unsigned short ClrInstanceID,
    int Values_ElementSize,
    const void* Values)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCBulkNode(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCBulkNode(
    const unsigned int Index,
    const unsigned int Count,
    const unsigned short ClrInstanceID,
    int Values_ElementSize,
    const void* Values)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCBulkEdge(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCBulkEdge(
    const unsigned int Index,
    const unsigned int Count,
    const unsigned short ClrInstanceID,
    int Values_ElementSize,
    const void* Values)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCSampledObjectAllocationHigh(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCSampledObjectAllocationHigh(
    const void* Address,
    const void* TypeID,
    const unsigned int ObjectCountForTypeSample,
    const uint64_t TotalSizeForTypeSample,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCBulkSurvivingObjectRanges(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCBulkSurvivingObjectRanges(
    const unsigned int Index,
    const unsigned int Count,
    const unsigned short ClrInstanceID,
    int Values_ElementSize,
    const void* Values)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCBulkMovedObjectRanges(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCBulkMovedObjectRanges(
    const unsigned int Index,
    const unsigned int Count,
    const unsigned short ClrInstanceID,
    int Values_ElementSize,
    const void* Values)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCGenerationRange(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCGenerationRange(
    const unsigned char Generation,
    const void* RangeStart,
    const uint64_t RangeUsedLength,
    const uint64_t RangeReservedLength,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCMarkStackRoots(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCMarkStackRoots(
    const unsigned int HeapNum,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCMarkFinalizeQueueRoots(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCMarkFinalizeQueueRoots(
    const unsigned int HeapNum,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCMarkHandles(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCMarkHandles(
    const unsigned int HeapNum,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCMarkOlderGenerationRoots(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCMarkOlderGenerationRoots(
    const unsigned int HeapNum,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledFinalizeObject(){ return FALSE; }

extern "C" ULONG  FireEtXplatFinalizeObject(
    const void* TypeID,
    const void* ObjectID,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledSetGCHandle(){ return FALSE; }

extern "C" ULONG  FireEtXplatSetGCHandle(
    const void* HandleID,
    const void* ObjectID,
    const unsigned int Kind,
    const unsigned int Generation,
    const uint64_t AppDomainID,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledDestroyGCHandle(){ return FALSE; }

extern "C" ULONG  FireEtXplatDestroyGCHandle(
    const void* HandleID,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCSampledObjectAllocationLow(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCSampledObjectAllocationLow(
    const void* Address,
    const void* TypeID,
    const unsigned int ObjectCountForTypeSample,
    const uint64_t TotalSizeForTypeSample,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledPinObjectAtGCTime(){ return FALSE; }

extern "C" ULONG  FireEtXplatPinObjectAtGCTime(
    const void* HandleID,
    const void* ObjectID,
    const uint64_t ObjectSize,
    PCWSTR TypeName,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCTriggered(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCTriggered(
    const unsigned int Reason,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCBulkRootCCW(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCBulkRootCCW(
    const unsigned int Count,
    const unsigned short ClrInstanceID,
    int Values_ElementSize,
    const void* Values)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCBulkRCW(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCBulkRCW(
    const unsigned int Count,
    const unsigned short ClrInstanceID,
    int Values_ElementSize,
    const void* Values)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCBulkRootStaticVar(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCBulkRootStaticVar(
    const unsigned int Count,
    const uint64_t AppDomainID,
    const unsigned short ClrInstanceID,
    int Values_ElementSize,
    const void* Values)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCDynamicEvent(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCDynamicEvent(
    PCWSTR Name,
    const unsigned int DataSize,
    const BYTE* Data,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledWorkerThreadCreate(){ return FALSE; }

extern "C" ULONG  FireEtXplatWorkerThreadCreate(
    const unsigned int WorkerThreadCount,
    const unsigned int RetiredWorkerThreads)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledWorkerThreadTerminate(){ return FALSE; }

extern "C" ULONG  FireEtXplatWorkerThreadTerminate(
    const unsigned int WorkerThreadCount,
    const unsigned int RetiredWorkerThreads)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledWorkerThreadRetire(){ return FALSE; }

extern "C" ULONG  FireEtXplatWorkerThreadRetire(
    const unsigned int WorkerThreadCount,
    const unsigned int RetiredWorkerThreads)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledWorkerThreadUnretire(){ return FALSE; }

extern "C" ULONG  FireEtXplatWorkerThreadUnretire(
    const unsigned int WorkerThreadCount,
    const unsigned int RetiredWorkerThreads)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledIOThreadCreate(){ return FALSE; }

extern "C" ULONG  FireEtXplatIOThreadCreate(
    const unsigned int IOThreadCount,
    const unsigned int RetiredIOThreads)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledIOThreadCreate_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatIOThreadCreate_V1(
    const unsigned int IOThreadCount,
    const unsigned int RetiredIOThreads,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledIOThreadTerminate(){ return FALSE; }

extern "C" ULONG  FireEtXplatIOThreadTerminate(
    const unsigned int IOThreadCount,
    const unsigned int RetiredIOThreads)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledIOThreadTerminate_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatIOThreadTerminate_V1(
    const unsigned int IOThreadCount,
    const unsigned int RetiredIOThreads,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledIOThreadRetire(){ return FALSE; }

extern "C" ULONG  FireEtXplatIOThreadRetire(
    const unsigned int IOThreadCount,
    const unsigned int RetiredIOThreads)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledIOThreadRetire_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatIOThreadRetire_V1(
    const unsigned int IOThreadCount,
    const unsigned int RetiredIOThreads,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledIOThreadUnretire(){ return FALSE; }

extern "C" ULONG  FireEtXplatIOThreadUnretire(
    const unsigned int IOThreadCount,
    const unsigned int RetiredIOThreads)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledIOThreadUnretire_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatIOThreadUnretire_V1(
    const unsigned int IOThreadCount,
    const unsigned int RetiredIOThreads,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledThreadpoolSuspensionSuspendThread(){ return FALSE; }

extern "C" ULONG  FireEtXplatThreadpoolSuspensionSuspendThread(
    const unsigned int ClrThreadID,
    const unsigned int CpuUtilization)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledThreadpoolSuspensionResumeThread(){ return FALSE; }

extern "C" ULONG  FireEtXplatThreadpoolSuspensionResumeThread(
    const unsigned int ClrThreadID,
    const unsigned int CpuUtilization)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledThreadPoolWorkerThreadStart(){ return FALSE; }

extern "C" ULONG  FireEtXplatThreadPoolWorkerThreadStart(
    const unsigned int ActiveWorkerThreadCount,
    const unsigned int RetiredWorkerThreadCount,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledThreadPoolWorkerThreadStop(){ return FALSE; }

extern "C" ULONG  FireEtXplatThreadPoolWorkerThreadStop(
    const unsigned int ActiveWorkerThreadCount,
    const unsigned int RetiredWorkerThreadCount,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledThreadPoolWorkerThreadRetirementStart(){ return FALSE; }

extern "C" ULONG  FireEtXplatThreadPoolWorkerThreadRetirementStart(
    const unsigned int ActiveWorkerThreadCount,
    const unsigned int RetiredWorkerThreadCount,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledThreadPoolWorkerThreadRetirementStop(){ return FALSE; }

extern "C" ULONG  FireEtXplatThreadPoolWorkerThreadRetirementStop(
    const unsigned int ActiveWorkerThreadCount,
    const unsigned int RetiredWorkerThreadCount,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledThreadPoolWorkerThreadAdjustmentSample(){ return FALSE; }

extern "C" ULONG  FireEtXplatThreadPoolWorkerThreadAdjustmentSample(
    const double Throughput,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledThreadPoolWorkerThreadAdjustmentAdjustment(){ return FALSE; }

extern "C" ULONG  FireEtXplatThreadPoolWorkerThreadAdjustmentAdjustment(
    const double AverageThroughput,
    const unsigned int NewWorkerThreadCount,
    const unsigned int Reason,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledThreadPoolWorkerThreadAdjustmentStats(){ return FALSE; }

extern "C" ULONG  FireEtXplatThreadPoolWorkerThreadAdjustmentStats(
    const double Duration,
    const double Throughput,
    const double ThreadWave,
    const double ThroughputWave,
    const double ThroughputErrorEstimate,
    const double AverageThroughputErrorEstimate,
    const double ThroughputRatio,
    const double Confidence,
    const double NewControlSetting,
    const unsigned short NewThreadWaveMagnitude,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledThreadPoolWorkerThreadWait(){ return FALSE; }

extern "C" ULONG  FireEtXplatThreadPoolWorkerThreadWait(
    const unsigned int ActiveWorkerThreadCount,
    const unsigned int RetiredWorkerThreadCount,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledYieldProcessorMeasurement(){ return FALSE; }

extern "C" ULONG  FireEtXplatYieldProcessorMeasurement(
    const unsigned short ClrInstanceID,
    const double NsPerYield,
    const double EstablishedNsPerYield)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledThreadPoolMinMaxThreads(){ return FALSE; }

extern "C" ULONG  FireEtXplatThreadPoolMinMaxThreads(
    const unsigned short MinWorkerThreads,
    const unsigned short MaxWorkerThreads,
    const unsigned short MinIOCompletionThreads,
    const unsigned short MaxIOCompletionThreads,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledThreadPoolWorkingThreadCount(){ return FALSE; }

extern "C" ULONG  FireEtXplatThreadPoolWorkingThreadCount(
    const unsigned int Count,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledThreadPoolEnqueue(){ return FALSE; }

extern "C" ULONG  FireEtXplatThreadPoolEnqueue(
    const void* WorkID,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledThreadPoolDequeue(){ return FALSE; }

extern "C" ULONG  FireEtXplatThreadPoolDequeue(
    const void* WorkID,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledThreadPoolIOEnqueue(){ return FALSE; }

extern "C" ULONG  FireEtXplatThreadPoolIOEnqueue(
    const void* NativeOverlapped,
    const void* Overlapped,
    const BOOL MultiDequeues,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledThreadPoolIODequeue(){ return FALSE; }

extern "C" ULONG  FireEtXplatThreadPoolIODequeue(
    const void* NativeOverlapped,
    const void* Overlapped,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledThreadPoolIOPack(){ return FALSE; }

extern "C" ULONG  FireEtXplatThreadPoolIOPack(
    const void* NativeOverlapped,
    const void* Overlapped,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledThreadCreating(){ return FALSE; }

extern "C" ULONG  FireEtXplatThreadCreating(
    const void* ID,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledThreadRunning(){ return FALSE; }

extern "C" ULONG  FireEtXplatThreadRunning(
    const void* ID,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMethodDetails(){ return FALSE; }

extern "C" ULONG  FireEtXplatMethodDetails(
    const uint64_t MethodID,
    const uint64_t TypeID,
    const unsigned int MethodToken,
    const unsigned int TypeParameterCount,
    const uint64_t LoaderModuleID,
    const uint64_t* TypeParameters)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledTypeLoadStart(){ return FALSE; }

extern "C" ULONG  FireEtXplatTypeLoadStart(
    const unsigned int TypeLoadStartID,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledTypeLoadStop(){ return FALSE; }

extern "C" ULONG  FireEtXplatTypeLoadStop(
    const unsigned int TypeLoadStartID,
    const unsigned short ClrInstanceID,
    const unsigned short LoadLevel,
    const uint64_t TypeID,
    PCWSTR TypeName)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledExceptionThrown(){ return FALSE; }

extern "C" ULONG  FireEtXplatExceptionThrown(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledExceptionThrown_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatExceptionThrown_V1(
    PCWSTR ExceptionType,
    PCWSTR ExceptionMessage,
    const void* ExceptionEIP,
    const unsigned int ExceptionHRESULT,
    const unsigned short ExceptionFlags,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledExceptionCatchStart(){ return FALSE; }

extern "C" ULONG  FireEtXplatExceptionCatchStart(
    const uint64_t EntryEIP,
    const uint64_t MethodID,
    PCWSTR MethodName,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledExceptionCatchStop(){ return FALSE; }

extern "C" ULONG  FireEtXplatExceptionCatchStop(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledExceptionFinallyStart(){ return FALSE; }

extern "C" ULONG  FireEtXplatExceptionFinallyStart(
    const uint64_t EntryEIP,
    const uint64_t MethodID,
    PCWSTR MethodName,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledExceptionFinallyStop(){ return FALSE; }

extern "C" ULONG  FireEtXplatExceptionFinallyStop(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledExceptionFilterStart(){ return FALSE; }

extern "C" ULONG  FireEtXplatExceptionFilterStart(
    const uint64_t EntryEIP,
    const uint64_t MethodID,
    PCWSTR MethodName,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledExceptionFilterStop(){ return FALSE; }

extern "C" ULONG  FireEtXplatExceptionFilterStop(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledExceptionThrownStop(){ return FALSE; }

extern "C" ULONG  FireEtXplatExceptionThrownStop(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledContention(){ return FALSE; }

extern "C" ULONG  FireEtXplatContention(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledContentionStart_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatContentionStart_V1(
    const unsigned char ContentionFlags,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledContentionStart_V2(){ return FALSE; }

extern "C" ULONG  FireEtXplatContentionStart_V2(
    const unsigned char ContentionFlags,
    const unsigned short ClrInstanceID,
    const void* LockID,
    const void* AssociatedObjectID,
    const uint64_t LockOwnerThreadID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledContentionStop(){ return FALSE; }

extern "C" ULONG  FireEtXplatContentionStop(
    const unsigned char ContentionFlags,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledContentionStop_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatContentionStop_V1(
    const unsigned char ContentionFlags,
    const unsigned short ClrInstanceID,
    const double DurationNs)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledContentionLockCreated(){ return FALSE; }

extern "C" ULONG  FireEtXplatContentionLockCreated(
    const void* LockID,
    const void* AssociatedObjectID,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledCLRStackWalk(){ return FALSE; }

extern "C" ULONG  FireEtXplatCLRStackWalk(
    const unsigned short ClrInstanceID,
    const unsigned char Reserved1,
    const unsigned char Reserved2,
    const unsigned int FrameCount,
    const void** Stack)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledAppDomainMemAllocated(){ return FALSE; }

extern "C" ULONG  FireEtXplatAppDomainMemAllocated(
    const uint64_t AppDomainID,
    const uint64_t Allocated,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledAppDomainMemSurvived(){ return FALSE; }

extern "C" ULONG  FireEtXplatAppDomainMemSurvived(
    const uint64_t AppDomainID,
    const uint64_t Survived,
    const uint64_t ProcessSurvived,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledThreadCreated(){ return FALSE; }

extern "C" ULONG  FireEtXplatThreadCreated(
    const uint64_t ManagedThreadID,
    const uint64_t AppDomainID,
    const unsigned int Flags,
    const unsigned int ManagedThreadIndex,
    const unsigned int OSThreadID,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledThreadTerminated(){ return FALSE; }

extern "C" ULONG  FireEtXplatThreadTerminated(
    const uint64_t ManagedThreadID,
    const uint64_t AppDomainID,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledThreadDomainEnter(){ return FALSE; }

extern "C" ULONG  FireEtXplatThreadDomainEnter(
    const uint64_t ManagedThreadID,
    const uint64_t AppDomainID,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledILStubGenerated(){ return FALSE; }

extern "C" ULONG  FireEtXplatILStubGenerated(
    const unsigned short ClrInstanceID,
    const uint64_t ModuleID,
    const uint64_t StubMethodID,
    const unsigned int StubFlags,
    const unsigned int ManagedInteropMethodToken,
    PCWSTR ManagedInteropMethodNamespace,
    PCWSTR ManagedInteropMethodName,
    PCWSTR ManagedInteropMethodSignature,
    PCWSTR NativeMethodSignature,
    PCWSTR StubMethodSignature,
    PCWSTR StubMethodILCode)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledILStubCacheHit(){ return FALSE; }

extern "C" ULONG  FireEtXplatILStubCacheHit(
    const unsigned short ClrInstanceID,
    const uint64_t ModuleID,
    const uint64_t StubMethodID,
    const unsigned int ManagedInteropMethodToken,
    PCWSTR ManagedInteropMethodNamespace,
    PCWSTR ManagedInteropMethodName,
    PCWSTR ManagedInteropMethodSignature)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledDCStartCompleteV2(){ return FALSE; }

extern "C" ULONG  FireEtXplatDCStartCompleteV2(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledDCEndCompleteV2(){ return FALSE; }

extern "C" ULONG  FireEtXplatDCEndCompleteV2(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMethodDCStartV2(){ return FALSE; }

extern "C" ULONG  FireEtXplatMethodDCStartV2(
    const uint64_t MethodID,
    const uint64_t ModuleID,
    const uint64_t MethodStartAddress,
    const unsigned int MethodSize,
    const unsigned int MethodToken,
    const unsigned int MethodFlags)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMethodDCEndV2(){ return FALSE; }

extern "C" ULONG  FireEtXplatMethodDCEndV2(
    const uint64_t MethodID,
    const uint64_t ModuleID,
    const uint64_t MethodStartAddress,
    const unsigned int MethodSize,
    const unsigned int MethodToken,
    const unsigned int MethodFlags)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMethodDCStartVerboseV2(){ return FALSE; }

extern "C" ULONG  FireEtXplatMethodDCStartVerboseV2(
    const uint64_t MethodID,
    const uint64_t ModuleID,
    const uint64_t MethodStartAddress,
    const unsigned int MethodSize,
    const unsigned int MethodToken,
    const unsigned int MethodFlags,
    PCWSTR MethodNamespace,
    PCWSTR MethodName,
    PCWSTR MethodSignature)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMethodDCEndVerboseV2(){ return FALSE; }

extern "C" ULONG  FireEtXplatMethodDCEndVerboseV2(
    const uint64_t MethodID,
    const uint64_t ModuleID,
    const uint64_t MethodStartAddress,
    const unsigned int MethodSize,
    const unsigned int MethodToken,
    const unsigned int MethodFlags,
    PCWSTR MethodNamespace,
    PCWSTR MethodName,
    PCWSTR MethodSignature)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMethodLoad(){ return FALSE; }

extern "C" ULONG  FireEtXplatMethodLoad(
    const uint64_t MethodID,
    const uint64_t ModuleID,
    const uint64_t MethodStartAddress,
    const unsigned int MethodSize,
    const unsigned int MethodToken,
    const unsigned int MethodFlags)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMethodLoad_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatMethodLoad_V1(
    const uint64_t MethodID,
    const uint64_t ModuleID,
    const uint64_t MethodStartAddress,
    const unsigned int MethodSize,
    const unsigned int MethodToken,
    const unsigned int MethodFlags,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMethodLoad_V2(){ return FALSE; }

extern "C" ULONG  FireEtXplatMethodLoad_V2(
    const uint64_t MethodID,
    const uint64_t ModuleID,
    const uint64_t MethodStartAddress,
    const unsigned int MethodSize,
    const unsigned int MethodToken,
    const unsigned int MethodFlags,
    const unsigned short ClrInstanceID,
    const uint64_t ReJITID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledR2RGetEntryPoint(){ return FALSE; }

extern "C" ULONG  FireEtXplatR2RGetEntryPoint(
    const uint64_t MethodID,
    PCWSTR MethodNamespace,
    PCWSTR MethodName,
    PCWSTR MethodSignature,
    const uint64_t EntryPoint,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledR2RGetEntryPointStart(){ return FALSE; }

extern "C" ULONG  FireEtXplatR2RGetEntryPointStart(
    const uint64_t MethodID,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMethodUnload(){ return FALSE; }

extern "C" ULONG  FireEtXplatMethodUnload(
    const uint64_t MethodID,
    const uint64_t ModuleID,
    const uint64_t MethodStartAddress,
    const unsigned int MethodSize,
    const unsigned int MethodToken,
    const unsigned int MethodFlags)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMethodUnload_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatMethodUnload_V1(
    const uint64_t MethodID,
    const uint64_t ModuleID,
    const uint64_t MethodStartAddress,
    const unsigned int MethodSize,
    const unsigned int MethodToken,
    const unsigned int MethodFlags,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMethodUnload_V2(){ return FALSE; }

extern "C" ULONG  FireEtXplatMethodUnload_V2(
    const uint64_t MethodID,
    const uint64_t ModuleID,
    const uint64_t MethodStartAddress,
    const unsigned int MethodSize,
    const unsigned int MethodToken,
    const unsigned int MethodFlags,
    const unsigned short ClrInstanceID,
    const uint64_t ReJITID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMethodLoadVerbose(){ return FALSE; }

extern "C" ULONG  FireEtXplatMethodLoadVerbose(
    const uint64_t MethodID,
    const uint64_t ModuleID,
    const uint64_t MethodStartAddress,
    const unsigned int MethodSize,
    const unsigned int MethodToken,
    const unsigned int MethodFlags,
    PCWSTR MethodNamespace,
    PCWSTR MethodName,
    PCWSTR MethodSignature)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMethodLoadVerbose_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatMethodLoadVerbose_V1(
    const uint64_t MethodID,
    const uint64_t ModuleID,
    const uint64_t MethodStartAddress,
    const unsigned int MethodSize,
    const unsigned int MethodToken,
    const unsigned int MethodFlags,
    PCWSTR MethodNamespace,
    PCWSTR MethodName,
    PCWSTR MethodSignature,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMethodLoadVerbose_V2(){ return FALSE; }

extern "C" ULONG  FireEtXplatMethodLoadVerbose_V2(
    const uint64_t MethodID,
    const uint64_t ModuleID,
    const uint64_t MethodStartAddress,
    const unsigned int MethodSize,
    const unsigned int MethodToken,
    const unsigned int MethodFlags,
    PCWSTR MethodNamespace,
    PCWSTR MethodName,
    PCWSTR MethodSignature,
    const unsigned short ClrInstanceID,
    const uint64_t ReJITID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMethodUnloadVerbose(){ return FALSE; }

extern "C" ULONG  FireEtXplatMethodUnloadVerbose(
    const uint64_t MethodID,
    const uint64_t ModuleID,
    const uint64_t MethodStartAddress,
    const unsigned int MethodSize,
    const unsigned int MethodToken,
    const unsigned int MethodFlags,
    PCWSTR MethodNamespace,
    PCWSTR MethodName,
    PCWSTR MethodSignature)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMethodUnloadVerbose_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatMethodUnloadVerbose_V1(
    const uint64_t MethodID,
    const uint64_t ModuleID,
    const uint64_t MethodStartAddress,
    const unsigned int MethodSize,
    const unsigned int MethodToken,
    const unsigned int MethodFlags,
    PCWSTR MethodNamespace,
    PCWSTR MethodName,
    PCWSTR MethodSignature,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMethodUnloadVerbose_V2(){ return FALSE; }

extern "C" ULONG  FireEtXplatMethodUnloadVerbose_V2(
    const uint64_t MethodID,
    const uint64_t ModuleID,
    const uint64_t MethodStartAddress,
    const unsigned int MethodSize,
    const unsigned int MethodToken,
    const unsigned int MethodFlags,
    PCWSTR MethodNamespace,
    PCWSTR MethodName,
    PCWSTR MethodSignature,
    const unsigned short ClrInstanceID,
    const uint64_t ReJITID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMethodJittingStarted(){ return FALSE; }

extern "C" ULONG  FireEtXplatMethodJittingStarted(
    const uint64_t MethodID,
    const uint64_t ModuleID,
    const unsigned int MethodToken,
    const unsigned int MethodILSize,
    PCWSTR MethodNamespace,
    PCWSTR MethodName,
    PCWSTR MethodSignature)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMethodJittingStarted_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatMethodJittingStarted_V1(
    const uint64_t MethodID,
    const uint64_t ModuleID,
    const unsigned int MethodToken,
    const unsigned int MethodILSize,
    PCWSTR MethodNamespace,
    PCWSTR MethodName,
    PCWSTR MethodSignature,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMethodJitMemoryAllocatedForCode(){ return FALSE; }

extern "C" ULONG  FireEtXplatMethodJitMemoryAllocatedForCode(
    const uint64_t MethodID,
    const uint64_t ModuleID,
    const uint64_t JitHotCodeRequestSize,
    const uint64_t JitRODataRequestSize,
    const uint64_t AllocatedSizeForJitCode,
    const unsigned int JitAllocFlag,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMethodJitInliningSucceeded(){ return FALSE; }

extern "C" ULONG  FireEtXplatMethodJitInliningSucceeded(
    PCWSTR MethodBeingCompiledNamespace,
    PCWSTR MethodBeingCompiledName,
    PCWSTR MethodBeingCompiledNameSignature,
    PCWSTR InlinerNamespace,
    PCWSTR InlinerName,
    PCWSTR InlinerNameSignature,
    PCWSTR InlineeNamespace,
    PCWSTR InlineeName,
    PCWSTR InlineeNameSignature,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMethodJitInliningFailedAnsi(){ return FALSE; }

extern "C" ULONG  FireEtXplatMethodJitInliningFailedAnsi(
    PCWSTR MethodBeingCompiledNamespace,
    PCWSTR MethodBeingCompiledName,
    PCWSTR MethodBeingCompiledNameSignature,
    PCWSTR InlinerNamespace,
    PCWSTR InlinerName,
    PCWSTR InlinerNameSignature,
    PCWSTR InlineeNamespace,
    PCWSTR InlineeName,
    PCWSTR InlineeNameSignature,
    const BOOL FailAlways,
    LPCSTR FailReason,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMethodJitTailCallSucceeded(){ return FALSE; }

extern "C" ULONG  FireEtXplatMethodJitTailCallSucceeded(
    PCWSTR MethodBeingCompiledNamespace,
    PCWSTR MethodBeingCompiledName,
    PCWSTR MethodBeingCompiledNameSignature,
    PCWSTR CallerNamespace,
    PCWSTR CallerName,
    PCWSTR CallerNameSignature,
    PCWSTR CalleeNamespace,
    PCWSTR CalleeName,
    PCWSTR CalleeNameSignature,
    const BOOL TailPrefix,
    const unsigned int TailCallType,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMethodJitTailCallFailedAnsi(){ return FALSE; }

extern "C" ULONG  FireEtXplatMethodJitTailCallFailedAnsi(
    PCWSTR MethodBeingCompiledNamespace,
    PCWSTR MethodBeingCompiledName,
    PCWSTR MethodBeingCompiledNameSignature,
    PCWSTR CallerNamespace,
    PCWSTR CallerName,
    PCWSTR CallerNameSignature,
    PCWSTR CalleeNamespace,
    PCWSTR CalleeName,
    PCWSTR CalleeNameSignature,
    const BOOL TailPrefix,
    LPCSTR FailReason,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMethodILToNativeMap(){ return FALSE; }

extern "C" ULONG  FireEtXplatMethodILToNativeMap(
    const uint64_t MethodID,
    const uint64_t ReJITID,
    const unsigned char MethodExtent,
    const unsigned short CountOfMapEntries,
    const unsigned int* ILOffsets,
    const unsigned int* NativeOffsets,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMethodILToNativeMap_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatMethodILToNativeMap_V1(
    const uint64_t MethodID,
    const uint64_t ReJITID,
    const unsigned char MethodExtent,
    const unsigned short CountOfMapEntries,
    const unsigned int* ILOffsets,
    const unsigned int* NativeOffsets,
    const unsigned short ClrInstanceID,
    const uint64_t ILVersionID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMethodJitTailCallFailed(){ return FALSE; }

extern "C" ULONG  FireEtXplatMethodJitTailCallFailed(
    PCWSTR MethodBeingCompiledNamespace,
    PCWSTR MethodBeingCompiledName,
    PCWSTR MethodBeingCompiledNameSignature,
    PCWSTR CallerNamespace,
    PCWSTR CallerName,
    PCWSTR CallerNameSignature,
    PCWSTR CalleeNamespace,
    PCWSTR CalleeName,
    PCWSTR CalleeNameSignature,
    const BOOL TailPrefix,
    PCWSTR FailReason,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMethodJitInliningFailed(){ return FALSE; }

extern "C" ULONG  FireEtXplatMethodJitInliningFailed(
    PCWSTR MethodBeingCompiledNamespace,
    PCWSTR MethodBeingCompiledName,
    PCWSTR MethodBeingCompiledNameSignature,
    PCWSTR InlinerNamespace,
    PCWSTR InlinerName,
    PCWSTR InlinerNameSignature,
    PCWSTR InlineeNamespace,
    PCWSTR InlineeName,
    PCWSTR InlineeNameSignature,
    const BOOL FailAlways,
    PCWSTR FailReason,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledModuleDCStartV2(){ return FALSE; }

extern "C" ULONG  FireEtXplatModuleDCStartV2(
    const uint64_t ModuleID,
    const uint64_t AssemblyID,
    const unsigned int ModuleFlags,
    const unsigned int Reserved1,
    PCWSTR ModuleILPath,
    PCWSTR ModuleNativePath)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledModuleDCEndV2(){ return FALSE; }

extern "C" ULONG  FireEtXplatModuleDCEndV2(
    const uint64_t ModuleID,
    const uint64_t AssemblyID,
    const unsigned int ModuleFlags,
    const unsigned int Reserved1,
    PCWSTR ModuleILPath,
    PCWSTR ModuleNativePath)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledDomainModuleLoad(){ return FALSE; }

extern "C" ULONG  FireEtXplatDomainModuleLoad(
    const uint64_t ModuleID,
    const uint64_t AssemblyID,
    const uint64_t AppDomainID,
    const unsigned int ModuleFlags,
    const unsigned int Reserved1,
    PCWSTR ModuleILPath,
    PCWSTR ModuleNativePath)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledDomainModuleLoad_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatDomainModuleLoad_V1(
    const uint64_t ModuleID,
    const uint64_t AssemblyID,
    const uint64_t AppDomainID,
    const unsigned int ModuleFlags,
    const unsigned int Reserved1,
    PCWSTR ModuleILPath,
    PCWSTR ModuleNativePath,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledModuleLoad(){ return FALSE; }

extern "C" ULONG  FireEtXplatModuleLoad(
    const uint64_t ModuleID,
    const uint64_t AssemblyID,
    const unsigned int ModuleFlags,
    const unsigned int Reserved1,
    PCWSTR ModuleILPath,
    PCWSTR ModuleNativePath)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledModuleLoad_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatModuleLoad_V1(
    const uint64_t ModuleID,
    const uint64_t AssemblyID,
    const unsigned int ModuleFlags,
    const unsigned int Reserved1,
    PCWSTR ModuleILPath,
    PCWSTR ModuleNativePath,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledModuleLoad_V2(){ return FALSE; }

extern "C" ULONG  FireEtXplatModuleLoad_V2(
    const uint64_t ModuleID,
    const uint64_t AssemblyID,
    const unsigned int ModuleFlags,
    const unsigned int Reserved1,
    PCWSTR ModuleILPath,
    PCWSTR ModuleNativePath,
    const unsigned short ClrInstanceID,
    const GUID* ManagedPdbSignature,
    const unsigned int ManagedPdbAge,
    PCWSTR ManagedPdbBuildPath,
    const GUID* NativePdbSignature,
    const unsigned int NativePdbAge,
    PCWSTR NativePdbBuildPath)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledModuleLoad_V3(){ return FALSE; }

extern "C" ULONG  FireEtXplatModuleLoad_V3(
    const uint64_t ModuleID,
    const uint64_t AssemblyID,
    const unsigned int ModuleFlags,
    const unsigned int Reserved1,
    PCWSTR ModuleILPath,
    PCWSTR ModuleNativePath,
    const unsigned short ClrInstanceID,
    const GUID* ManagedPdbSignature,
    const unsigned int ManagedPdbAge,
    PCWSTR ManagedPdbBuildPath,
    const GUID* NativePdbSignature,
    const unsigned int NativePdbAge,
    PCWSTR NativePdbBuildPath,
    PCWSTR NativeBuildID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledModuleUnload(){ return FALSE; }

extern "C" ULONG  FireEtXplatModuleUnload(
    const uint64_t ModuleID,
    const uint64_t AssemblyID,
    const unsigned int ModuleFlags,
    const unsigned int Reserved1,
    PCWSTR ModuleILPath,
    PCWSTR ModuleNativePath)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledModuleUnload_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatModuleUnload_V1(
    const uint64_t ModuleID,
    const uint64_t AssemblyID,
    const unsigned int ModuleFlags,
    const unsigned int Reserved1,
    PCWSTR ModuleILPath,
    PCWSTR ModuleNativePath,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledModuleUnload_V2(){ return FALSE; }

extern "C" ULONG  FireEtXplatModuleUnload_V2(
    const uint64_t ModuleID,
    const uint64_t AssemblyID,
    const unsigned int ModuleFlags,
    const unsigned int Reserved1,
    PCWSTR ModuleILPath,
    PCWSTR ModuleNativePath,
    const unsigned short ClrInstanceID,
    const GUID* ManagedPdbSignature,
    const unsigned int ManagedPdbAge,
    PCWSTR ManagedPdbBuildPath,
    const GUID* NativePdbSignature,
    const unsigned int NativePdbAge,
    PCWSTR NativePdbBuildPath)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledAssemblyLoad(){ return FALSE; }

extern "C" ULONG  FireEtXplatAssemblyLoad(
    const uint64_t AssemblyID,
    const uint64_t AppDomainID,
    const unsigned int AssemblyFlags,
    PCWSTR FullyQualifiedAssemblyName)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledAssemblyLoad_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatAssemblyLoad_V1(
    const uint64_t AssemblyID,
    const uint64_t AppDomainID,
    const uint64_t BindingID,
    const unsigned int AssemblyFlags,
    PCWSTR FullyQualifiedAssemblyName,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledAssemblyUnload(){ return FALSE; }

extern "C" ULONG  FireEtXplatAssemblyUnload(
    const uint64_t AssemblyID,
    const uint64_t AppDomainID,
    const unsigned int AssemblyFlags,
    PCWSTR FullyQualifiedAssemblyName)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledAssemblyUnload_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatAssemblyUnload_V1(
    const uint64_t AssemblyID,
    const uint64_t AppDomainID,
    const uint64_t BindingID,
    const unsigned int AssemblyFlags,
    PCWSTR FullyQualifiedAssemblyName,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledAppDomainLoad(){ return FALSE; }

extern "C" ULONG  FireEtXplatAppDomainLoad(
    const uint64_t AppDomainID,
    const unsigned int AppDomainFlags,
    PCWSTR AppDomainName)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledAppDomainLoad_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatAppDomainLoad_V1(
    const uint64_t AppDomainID,
    const unsigned int AppDomainFlags,
    PCWSTR AppDomainName,
    const unsigned int AppDomainIndex,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledAppDomainUnload(){ return FALSE; }

extern "C" ULONG  FireEtXplatAppDomainUnload(
    const uint64_t AppDomainID,
    const unsigned int AppDomainFlags,
    PCWSTR AppDomainName)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledAppDomainUnload_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatAppDomainUnload_V1(
    const uint64_t AppDomainID,
    const unsigned int AppDomainFlags,
    PCWSTR AppDomainName,
    const unsigned int AppDomainIndex,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledModuleRangeLoad(){ return FALSE; }

extern "C" ULONG  FireEtXplatModuleRangeLoad(
    const unsigned short ClrInstanceID,
    const uint64_t ModuleID,
    const unsigned int RangeBegin,
    const unsigned int RangeSize,
    const unsigned char RangeType)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledStrongNameVerificationStart(){ return FALSE; }

extern "C" ULONG  FireEtXplatStrongNameVerificationStart(
    const unsigned int VerificationFlags,
    const unsigned int ErrorCode,
    PCWSTR FullyQualifiedAssemblyName)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledStrongNameVerificationStart_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatStrongNameVerificationStart_V1(
    const unsigned int VerificationFlags,
    const unsigned int ErrorCode,
    PCWSTR FullyQualifiedAssemblyName,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledStrongNameVerificationStop(){ return FALSE; }

extern "C" ULONG  FireEtXplatStrongNameVerificationStop(
    const unsigned int VerificationFlags,
    const unsigned int ErrorCode,
    PCWSTR FullyQualifiedAssemblyName)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledStrongNameVerificationStop_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatStrongNameVerificationStop_V1(
    const unsigned int VerificationFlags,
    const unsigned int ErrorCode,
    PCWSTR FullyQualifiedAssemblyName,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledAuthenticodeVerificationStart(){ return FALSE; }

extern "C" ULONG  FireEtXplatAuthenticodeVerificationStart(
    const unsigned int VerificationFlags,
    const unsigned int ErrorCode,
    PCWSTR ModulePath)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledAuthenticodeVerificationStart_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatAuthenticodeVerificationStart_V1(
    const unsigned int VerificationFlags,
    const unsigned int ErrorCode,
    PCWSTR ModulePath,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledAuthenticodeVerificationStop(){ return FALSE; }

extern "C" ULONG  FireEtXplatAuthenticodeVerificationStop(
    const unsigned int VerificationFlags,
    const unsigned int ErrorCode,
    PCWSTR ModulePath)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledAuthenticodeVerificationStop_V1(){ return FALSE; }

extern "C" ULONG  FireEtXplatAuthenticodeVerificationStop_V1(
    const unsigned int VerificationFlags,
    const unsigned int ErrorCode,
    PCWSTR ModulePath,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledRuntimeInformationStart(){ return FALSE; }

extern "C" ULONG  FireEtXplatRuntimeInformationStart(
    const unsigned short ClrInstanceID,
    const unsigned short Sku,
    const unsigned short BclMajorVersion,
    const unsigned short BclMinorVersion,
    const unsigned short BclBuildNumber,
    const unsigned short BclQfeNumber,
    const unsigned short VMMajorVersion,
    const unsigned short VMMinorVersion,
    const unsigned short VMBuildNumber,
    const unsigned short VMQfeNumber,
    const unsigned int StartupFlags,
    const unsigned char StartupMode,
    PCWSTR CommandLine,
    const GUID* ComObjectGuid,
    PCWSTR RuntimeDllPath)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledIncreaseMemoryPressure(){ return FALSE; }

extern "C" ULONG  FireEtXplatIncreaseMemoryPressure(
    const uint64_t BytesAllocated,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledDecreaseMemoryPressure(){ return FALSE; }

extern "C" ULONG  FireEtXplatDecreaseMemoryPressure(
    const uint64_t BytesFreed,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCMarkWithType(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCMarkWithType(
    const unsigned int HeapNum,
    const unsigned short ClrInstanceID,
    const unsigned int Type,
    const uint64_t Bytes)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCJoin_V2(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCJoin_V2(
    const unsigned int Heap,
    const unsigned int JoinTime,
    const unsigned int JoinType,
    const unsigned short ClrInstanceID,
    const unsigned int JoinID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCPerHeapHistory_V3(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCPerHeapHistory_V3(
    const unsigned short ClrInstanceID,
    const void* FreeListAllocated,
    const void* FreeListRejected,
    const void* EndOfSegAllocated,
    const void* CondemnedAllocated,
    const void* PinnedAllocated,
    const void* PinnedAllocatedAdvance,
    const unsigned int RunningFreeListEfficiency,
    const unsigned int CondemnReasons0,
    const unsigned int CondemnReasons1,
    const unsigned int CompactMechanisms,
    const unsigned int ExpandMechanisms,
    const unsigned int HeapIndex,
    const void* ExtraGen0Commit,
    const unsigned int Count,
    int Values_ElementSize,
    const void* Values)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCGlobalHeapHistory_V2(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCGlobalHeapHistory_V2(
    const uint64_t FinalYoungestDesired,
    const signed int NumHeaps,
    const unsigned int CondemnedGeneration,
    const unsigned int Gen0ReductionCount,
    const unsigned int Reason,
    const unsigned int GlobalMechanisms,
    const unsigned short ClrInstanceID,
    const unsigned int PauseMode,
    const unsigned int MemoryPressure)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCGlobalHeapHistory_V3(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCGlobalHeapHistory_V3(
    const uint64_t FinalYoungestDesired,
    const signed int NumHeaps,
    const unsigned int CondemnedGeneration,
    const unsigned int Gen0ReductionCount,
    const unsigned int Reason,
    const unsigned int GlobalMechanisms,
    const unsigned short ClrInstanceID,
    const unsigned int PauseMode,
    const unsigned int MemoryPressure,
    const unsigned int CondemnReasons0,
    const unsigned int CondemnReasons1)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCGlobalHeapHistory_V4(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCGlobalHeapHistory_V4(
    const uint64_t FinalYoungestDesired,
    const signed int NumHeaps,
    const unsigned int CondemnedGeneration,
    const unsigned int Gen0ReductionCount,
    const unsigned int Reason,
    const unsigned int GlobalMechanisms,
    const unsigned short ClrInstanceID,
    const unsigned int PauseMode,
    const unsigned int MemoryPressure,
    const unsigned int CondemnReasons0,
    const unsigned int CondemnReasons1,
    const unsigned int Count,
    int Values_ElementSize,
    const void* Values)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGenAwareBegin(){ return FALSE; }

extern "C" ULONG  FireEtXplatGenAwareBegin(
    const unsigned int Count,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGenAwareEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatGenAwareEnd(
    const unsigned int Count,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCLOHCompact(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCLOHCompact(
    const unsigned short ClrInstanceID,
    const unsigned short Count,
    int Values_ElementSize,
    const void* Values)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledGCFitBucketInfo(){ return FALSE; }

extern "C" ULONG  FireEtXplatGCFitBucketInfo(
    const unsigned short ClrInstanceID,
    const unsigned short BucketKind,
    const uint64_t TotalSize,
    const unsigned short Count,
    int Values_ElementSize,
    const void* Values)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledDebugIPCEventStart(){ return FALSE; }

extern "C" ULONG  FireEtXplatDebugIPCEventStart(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledDebugIPCEventEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatDebugIPCEventEnd(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledDebugExceptionProcessingStart(){ return FALSE; }

extern "C" ULONG  FireEtXplatDebugExceptionProcessingStart(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledDebugExceptionProcessingEnd(){ return FALSE; }

extern "C" ULONG  FireEtXplatDebugExceptionProcessingEnd(
)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledCodeSymbols(){ return FALSE; }

extern "C" ULONG  FireEtXplatCodeSymbols(
    const uint64_t ModuleId,
    const unsigned short TotalChunks,
    const unsigned short ChunkNumber,
    const unsigned int ChunkLength,
    const BYTE* Chunk,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledEventSource(){ return FALSE; }

extern "C" ULONG  FireEtXplatEventSource(
    const signed int EventID,
    PCWSTR EventName,
    PCWSTR EventSourceName,
    PCWSTR Payload)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledTieredCompilationSettings(){ return FALSE; }

extern "C" ULONG  FireEtXplatTieredCompilationSettings(
    const unsigned short ClrInstanceID,
    const unsigned int Flags)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledTieredCompilationPause(){ return FALSE; }

extern "C" ULONG  FireEtXplatTieredCompilationPause(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledTieredCompilationResume(){ return FALSE; }

extern "C" ULONG  FireEtXplatTieredCompilationResume(
    const unsigned short ClrInstanceID,
    const unsigned int NewMethodCount)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledTieredCompilationBackgroundJitStart(){ return FALSE; }

extern "C" ULONG  FireEtXplatTieredCompilationBackgroundJitStart(
    const unsigned short ClrInstanceID,
    const unsigned int PendingMethodCount)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledTieredCompilationBackgroundJitStop(){ return FALSE; }

extern "C" ULONG  FireEtXplatTieredCompilationBackgroundJitStop(
    const unsigned short ClrInstanceID,
    const unsigned int PendingMethodCount,
    const unsigned int JittedMethodCount)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledAssemblyLoadStart(){ return FALSE; }

extern "C" ULONG  FireEtXplatAssemblyLoadStart(
    const unsigned short ClrInstanceID,
    PCWSTR AssemblyName,
    PCWSTR AssemblyPath,
    PCWSTR RequestingAssembly,
    PCWSTR AssemblyLoadContext,
    PCWSTR RequestingAssemblyLoadContext)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledAssemblyLoadStop(){ return FALSE; }

extern "C" ULONG  FireEtXplatAssemblyLoadStop(
    const unsigned short ClrInstanceID,
    PCWSTR AssemblyName,
    PCWSTR AssemblyPath,
    PCWSTR RequestingAssembly,
    PCWSTR AssemblyLoadContext,
    PCWSTR RequestingAssemblyLoadContext,
    const BOOL Success,
    PCWSTR ResultAssemblyName,
    PCWSTR ResultAssemblyPath,
    const BOOL Cached)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledResolutionAttempted(){ return FALSE; }

extern "C" ULONG  FireEtXplatResolutionAttempted(
    const unsigned short ClrInstanceID,
    PCWSTR AssemblyName,
    const unsigned short Stage,
    PCWSTR AssemblyLoadContext,
    const unsigned short Result,
    PCWSTR ResultAssemblyName,
    PCWSTR ResultAssemblyPath,
    PCWSTR ErrorMessage)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledAssemblyLoadContextResolvingHandlerInvoked(){ return FALSE; }

extern "C" ULONG  FireEtXplatAssemblyLoadContextResolvingHandlerInvoked(
    const unsigned short ClrInstanceID,
    PCWSTR AssemblyName,
    PCWSTR HandlerName,
    PCWSTR AssemblyLoadContext,
    PCWSTR ResultAssemblyName,
    PCWSTR ResultAssemblyPath)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledAppDomainAssemblyResolveHandlerInvoked(){ return FALSE; }

extern "C" ULONG  FireEtXplatAppDomainAssemblyResolveHandlerInvoked(
    const unsigned short ClrInstanceID,
    PCWSTR AssemblyName,
    PCWSTR HandlerName,
    PCWSTR ResultAssemblyName,
    PCWSTR ResultAssemblyPath)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledAssemblyLoadFromResolveHandlerInvoked(){ return FALSE; }

extern "C" ULONG  FireEtXplatAssemblyLoadFromResolveHandlerInvoked(
    const unsigned short ClrInstanceID,
    PCWSTR AssemblyName,
    const BOOL IsTrackedLoad,
    PCWSTR RequestingAssemblyPath,
    PCWSTR ComputedRequestedAssemblyPath)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledKnownPathProbed(){ return FALSE; }

extern "C" ULONG  FireEtXplatKnownPathProbed(
    const unsigned short ClrInstanceID,
    PCWSTR FilePath,
    const unsigned short Source,
    const signed int Result)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledJitInstrumentationData(){ return FALSE; }

extern "C" ULONG  FireEtXplatJitInstrumentationData(
    const unsigned short ClrInstanceID,
    const unsigned int MethodFlags,
    const unsigned int DataSize,
    const uint64_t MethodID,
    const BYTE* Data)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledJitInstrumentationDataVerbose(){ return FALSE; }

extern "C" ULONG  FireEtXplatJitInstrumentationDataVerbose(
    const unsigned short ClrInstanceID,
    const unsigned int MethodFlags,
    const unsigned int DataSize,
    const uint64_t MethodID,
    const uint64_t ModuleID,
    const unsigned int MethodToken,
    PCWSTR MethodNamespace,
    PCWSTR MethodName,
    PCWSTR MethodSignature,
    const BYTE* Data)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledProfilerMessage(){ return FALSE; }

extern "C" ULONG  FireEtXplatProfilerMessage(
    const unsigned short ClrInstanceID,
    PCWSTR Message)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledExecutionCheckpoint(){ return FALSE; }

extern "C" ULONG  FireEtXplatExecutionCheckpoint(
    const unsigned short ClrInstanceID,
    PCWSTR Name,
    const int64_t Timestamp)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledWaitHandleWaitStart(){ return FALSE; }

extern "C" ULONG  FireEtXplatWaitHandleWaitStart(
    const unsigned char WaitSource,
    const void* AssociatedObjectID,
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledWaitHandleWaitStop(){ return FALSE; }

extern "C" ULONG  FireEtXplatWaitHandleWaitStop(
    const unsigned short ClrInstanceID)
{
    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledAllocationSampled(){ return FALSE; }

extern "C" ULONG  FireEtXplatAllocationSampled(
    const unsigned int AllocationKind,
    const unsigned short ClrInstanceID,
    const void* TypeID,
    PCWSTR TypeName,
    const void* Address,
    const uint64_t ObjectSize,
    const uint64_t SampledByteOffset)
{
    return ERROR_SUCCESS;
}


