load("//src/tests:live_test.bzl", "coreclr_test")

coreclr_test(
    name = "typetestcloning",
    srcs = ["typetestcloning.cs"],
    optimize = True,
    deps = [
        "//src/libraries/System.Threading.Thread:ref_System.Threading.Thread",
        "//src/libraries/System.Threading:ref_System.Threading",
    ],
)

coreclr_test(
    name = "enumerablecloning",
    srcs = ["enumerablecloning.cs"],
    optimize = True,
    deps = [
        "//src/libraries/System.Threading.Thread:ref_System.Threading.Thread",
        "//src/libraries/System.Threading:ref_System.Threading",
    ],
)
