load("//src/libraries:defs.bzl", "netcoreapp_ref_assembly", "netcoreapp_impl_assembly")

exports_files([
    "ref/System.Xml.XPath.cs",
])

netcoreapp_ref_assembly(
    name = "ref_System.Xml.XPath",
    srcs = [
        "ref/System.Xml.XPath.cs",
        "ref/System.Xml.XPath.Forwards.cs",
    ],
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Xml.ReaderWriter:ref_System.Xml.ReaderWriter",
    ],
)

netcoreapp_impl_assembly(
    name = "impl_System.Xml.XPath",
    srcs = [],
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Private.Xml:impl_System.Private.Xml",
    ],
    partial_facade = True,
    generate_facades = True,
    facade_contract_assembly = ":ref_System.Xml.XPath",
    exclude_sr = True,
    include_dll_safe_search_path = False,
)
