load("//src/libraries:defs.bzl", "COMMON_GENERATOR_ANALYZERS", "MULTITARGET_NOWARN", "netcoreapp_ref_assembly", "impl_assembly", "ref_impl_pair")

exports_files([
    "ref/Microsoft.Extensions.FileProviders.Composite.cs",
])

netcoreapp_ref_assembly(
    name = "ref_Microsoft.Extensions.FileProviders.Composite",
    srcs = [
        "ref/Microsoft.Extensions.FileProviders.Composite.cs",
    ],
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/Microsoft.Extensions.FileProviders.Abstractions:ref_Microsoft.Extensions.FileProviders.Abstractions",
        "//src/libraries/Microsoft.Extensions.Primitives:ref_Microsoft.Extensions.Primitives",
    ],
)

impl_assembly(
    name = "impl_Microsoft.Extensions.FileProviders.Composite",
    nowarn = MULTITARGET_NOWARN + ["CP0003"],
    exclude_sr = True,
    srcs = glob(["src/**/*.cs"]),
    analyzers = COMMON_GENERATOR_ANALYZERS,
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/Microsoft.Extensions.FileProviders.Abstractions:ref_Microsoft.Extensions.FileProviders.Abstractions",
        "//src/libraries/Microsoft.Extensions.Primitives:ref_Microsoft.Extensions.Primitives",
        "//src/libraries/System.Collections:ref_System.Collections",
        "//src/libraries/System.Linq:ref_System.Linq",
    ],
)

ref_impl_pair(
    name = "live_Microsoft.Extensions.FileProviders.Composite",
    ref = ":ref_Microsoft.Extensions.FileProviders.Composite",
    lib = ":impl_Microsoft.Extensions.FileProviders.Composite",
    visibility = ["//visibility:public"],
)
