load("//:defs.bzl", "NETCOREAPP_CURRENT", "OPEN_SNK", "csharp_library")

# MSBuild project name is AssemblyVersion1 but produces
# System.Runtime.Loader.Test.VersionDowngrade.dll (AssemblyName override).
csharp_library(
    name = "System.Runtime.Loader.Test.VersionDowngrade",
    out = "System.Runtime.Loader.Test.AssemblyVersion1",
    srcs = ["VersionTestClass.cs"],
    target_frameworks = [NETCOREAPP_CURRENT],
    keyfile = OPEN_SNK,
    nullable = "annotations",
    nowarn = [
        "CA1510",
        "CA1511",
        "CA1512",
        "CA1513",
        "CA1845",
        "CA1846",
        "CA1847",
        "IL2121",
        "SYSLIB0011",
        "SYSLIB0050",
        "SYSLIB0051",
    ],
    msbuild_analyzer_config = "style",
    interceptors_namespaces = ";Microsoft.Extensions.Validation.Generated",
    include_default_ruleset = False,
    include_syslib_warnaserror = False,
    visibility = ["//src/libraries/System.Runtime.Loader/tests:__subpackages__"],
)
