load("//src/libraries:defs.bzl", "COMMON_GENERATOR_ANALYZERS", "MULTITARGET_NOWARN", "netcoreapp_ref_assembly", "impl_assembly", "ref_impl_pair")
load("//:defs.bzl", "OPEN_SNK")

exports_files(["ref/System.Data.Odbc.cs"])

netcoreapp_ref_assembly(
    name = "ref_System.Data.Odbc",
    srcs = ["ref/System.Data.Odbc.cs"],
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries:ref_System.ComponentModel.Primitives",
        "//src/libraries/System.ComponentModel.TypeConverter:ref_System.ComponentModel.TypeConverter",
        "//src/libraries/System.Data.Common:ref_System.Data.Common",
    ],
)

impl_assembly(
    name = "impl_System.Data.Odbc",
    keyfile = OPEN_SNK,
    pnse = True,
    pnse_message = "SR.Odbc_PlatformNotSupported",
    pnse_ref_srcs = ["ref/System.Data.Odbc.cs"],
    nowarn = MULTITARGET_NOWARN + ["CP0003", "CS1591", "CA1838", "CA2249", "SA1121"],
    srcs = [],
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries:ref_System.ComponentModel.Primitives",
        "//src/libraries/System.ComponentModel.TypeConverter:ref_System.ComponentModel.TypeConverter",
        "//src/libraries/System.Data.Common:ref_System.Data.Common",
    ],
    resx_file = "src/Resources/Strings.resx",
    allow_unsafe_blocks = True,
    analyzers = COMMON_GENERATOR_ANALYZERS,
    resources = ["src/Resources/System.Data.Odbc.OdbcMetaData.xml"],
    resource_logical_names = {"System.Data.Odbc.OdbcMetaData.xml": "System.Data.Odbc.OdbcMetaData.xml"},
    supported_os_platforms_short = ["windows"],
)

ref_impl_pair(
    name = "live_System.Data.Odbc",
    ref = ":ref_System.Data.Odbc",
    lib = ":impl_System.Data.Odbc",
    visibility = ["//visibility:public"],
)
