load("//src/libraries:defs.bzl", "netcoreapp_impl_assembly")

netcoreapp_impl_assembly(
    name = "impl_System.Xml.XmlDocument",
    skip_cs1591 = True,
    srcs = ["src/System.Xml.XmlDocument.cs"],
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Xml.ReaderWriter:ref_System.Xml.ReaderWriter",
    ],
    os_targeted = True,
    exclude_sr = True,
)
