load("//src/tests:live_test.bzl", "library_test")
load("//:defs.bzl", "OPEN_SNK", "gen_resx_source", "resgen")

gen_resx_source(
    name = "gen_resx",
    out = "SR.g.cs",
    assembly_name = "System.Net.Http.Functional.Tests",
    include_default_values = select({
        "//:libs_debug": True,
        "//conditions:default": False,
    }),
    resx_file = "//src/libraries/System.Net.Http:src/Resources/Strings.resx",
)

resgen(
    name = "strings_resx",
    out = "FxResources.System.Net.Http.Functional.Tests.SR.resources",
    resx_file = "//src/libraries/System.Net.Http:src/Resources/Strings.resx",
)

library_test(
    name = "System.Net.Http.Functional.Tests",
    defines = ["HTTP3", "LINUX", "LINUX1_0", "SYSNETHTTP_NO_OPENSSL"],
    nowarn = ["SYSLIB0011"],
    srcs = glob(
        ["*.cs"],
        exclude = [
            "AndroidKeyStoreHelper.cs",
            "ImpersonatedAuthTests.cs",
            "MultiInterfaceNonRewindableReadOnlyStream.cs",
            "MultiInterfaceReadOnlyStream.cs",
            "MultiInterfaceStreamContent.cs",
            "NtAuthTests.Windows.cs",
        ],
    ) + [
        "//src/libraries/Common:src/DisableRuntimeMarshalling.cs",
        "//src/libraries/Common:src/Interop/Linux/Interop.Libraries.cs",
        "//src/libraries/Common:src/Interop/Unix/Interop.Libraries.cs",
        "//src/libraries/Common:src/Interop/Unix/System.Net.Security.Native/Interop.NetSecurityNative.IsNtlmInstalled.cs",
        "//src/libraries/Common:src/System/IO/DelegatingStream.cs",
        "//src/libraries/Common:src/System/Net/ArrayBuffer.cs",
        "//src/libraries/Common:src/System/Net/Logging/NetEventSource.Common.cs",
        "//src/libraries/Common:src/System/Net/MultiArrayBuffer.cs",
        "//src/libraries/Common:src/System/Net/Security/MD4.cs",
        "//src/libraries/Common:src/System/Net/Security/RC4.cs",
        "//src/libraries/Common:src/System/SR.cs",
        "//src/libraries/Common:src/System/Net/StreamBuffer.cs",
        "//src/libraries/Common/tests:System/Buffers/NativeMemoryManager.cs",
        "//src/libraries/Common/tests:System/Diagnostics/Tracing/ConsoleEventListener.cs",
        "//src/libraries/Common/tests:System/Diagnostics/Tracing/TestEventListener.cs",
        "//src/libraries/Common/tests:System/IO/ByteLoggingStream.cs",
        "//src/libraries/Common/tests:System/IO/ConnectedStreams.cs",
        "//src/libraries/Common/tests:System/IO/DelegateDelegatingStream.cs",
        "//src/libraries/Common/tests:System/IO/DelegateStream.cs",
        "//src/libraries/Common/tests:System/Net/ActivityRecorder.cs",
        "//src/libraries/Common/tests:System/Net/Capability.Security.cs",
        "//src/libraries/Common/tests:System/Net/Capability.Security.Unix.cs",
        "//src/libraries/Common/tests:System/Net/Configuration.Certificates.cs",
        "//src/libraries/Common/tests:System/Net/Configuration.Certificates.Dynamic.cs",
        "//src/libraries/Common/tests:System/Net/Configuration.Http.cs",
        "//src/libraries/Common/tests:System/Net/Configuration.Security.cs",
        "//src/libraries/Common/tests:System/Net/Configuration.Sockets.cs",
        "//src/libraries/Common/tests:System/Net/Configuration.cs",
        "//src/libraries/Common/tests:System/Net/EventSourceTestLogging.cs",
        "//src/libraries/Common/tests:System/Net/HttpsTestServer.cs",
        "//src/libraries/Common/tests:System/Net/RemoteExecutorExtensions.cs",
        "//src/libraries/Common/tests:System/Net/RemoteServerQuery.cs",
        "//src/libraries/Common/tests:System/Net/SslProtocolSupport.cs",
        "//src/libraries/Common/tests:System/Net/TestWebProxies.cs",
        "//src/libraries/Common/tests:System/Net/VerboseTestLogging.cs",
        "//src/libraries/Common/tests:System/Net/Http/ByteAtATimeContent.cs",
        "//src/libraries/Common/tests:System/Net/Http/ChannelBindingAwareContent.cs",
        "//src/libraries/Common/tests:System/Net/Http/CustomContent.cs",
        "//src/libraries/Common/tests:System/Net/Http/DefaultCredentialsTest.cs",
        "//src/libraries/Common/tests:System/Net/Http/DribbleStream.cs",
        "//src/libraries/Common/tests:System/Net/Http/GenericLoopbackServer.cs",
        "//src/libraries/Common/tests:System/Net/Http/HPackEncoder.cs",
        "//src/libraries/Common/tests:System/Net/Http/Http2Frames.cs",
        "//src/libraries/Common/tests:System/Net/Http/Http2LoopbackConnection.cs",
        "//src/libraries/Common/tests:System/Net/Http/Http2LoopbackServer.cs",
        "//src/libraries/Common/tests:System/Net/Http/Http3LoopbackConnection.cs",
        "//src/libraries/Common/tests:System/Net/Http/Http3LoopbackServer.cs",
        "//src/libraries/Common/tests:System/Net/Http/Http3LoopbackStream.cs",
        "//src/libraries/Common/tests:System/Net/Http/HttpAgnosticLoopbackServer.cs",
        "//src/libraries/Common/tests:System/Net/Http/HttpClientHandlerTest.AcceptAllCerts.cs",
        "//src/libraries/Common/tests:System/Net/Http/HttpClientHandlerTest.cs",
        "//src/libraries/Common/tests:System/Net/Http/HttpClientHandlerTest.Asynchrony.cs",
        "//src/libraries/Common/tests:System/Net/Http/HttpClientHandlerTest.Authentication.cs",
        "//src/libraries/Common/tests:System/Net/Http/HttpClientHandlerTest.AutoRedirect.cs",
        "//src/libraries/Common/tests:System/Net/Http/HttpClientHandlerTest.Cancellation.cs",
        "//src/libraries/Common/tests:System/Net/Http/HttpClientHandlerTest.ClientCertificates.cs",
        "//src/libraries/Common/tests:System/Net/Http/HttpClientHandlerTest.Cookies.cs",
        "//src/libraries/Common/tests:System/Net/Http/HttpClientHandlerTest.Decompression.cs",
        "//src/libraries/Common/tests:System/Net/Http/HttpClientHandlerTest.DefaultProxyCredentials.cs",
        "//src/libraries/Common/tests:System/Net/Http/HttpClientHandlerTest.MaxConnectionsPerServer.cs",
        "//src/libraries/Common/tests:System/Net/Http/HttpClientHandlerTest.MaxResponseHeadersLength.cs",
        "//src/libraries/Common/tests:System/Net/Http/HttpClientHandlerTest.Proxy.cs",
        "//src/libraries/Common/tests:System/Net/Http/HttpClientHandlerTest.RemoteServer.cs",
        "//src/libraries/Common/tests:System/Net/Http/HttpClientHandlerTest.ServerCertificates.cs",
        "//src/libraries/Common/tests:System/Net/Http/HttpClientHandlerTest.SslProtocols.cs",
        "//src/libraries/Common/tests:System/Net/Http/HttpClientHandlerTestBase.cs",
        "//src/libraries/Common/tests:System/Net/Http/HttpClientEKUTest.cs",
        "//src/libraries/Common/tests:System/Net/Http/HttpClient.SelectedSitesTest.cs",
        "//src/libraries/Common/tests:System/Net/Http/HttpProtocolTests.cs",
        "//src/libraries/Common/tests:System/Net/Http/HuffmanDecoder.cs",
        "//src/libraries/Common/tests:System/Net/Http/HuffmanEncoder.cs",
        "//src/libraries/Common/tests:System/Net/Http/IdnaProtocolTests.cs",
        "//src/libraries/Common/tests:System/Net/Http/LoopbackProxyServer.cs",
        "//src/libraries/Common/tests:System/Net/Http/LoopbackServer.AuthenticationHelpers.cs",
        "//src/libraries/Common/tests:System/Net/Http/LoopbackServer.cs",
        "//src/libraries/Common/tests:System/Net/Http/PostScenarioTest.cs",
        "//src/libraries/Common/tests:System/Net/Http/QPackTestDecoder.cs",
        "//src/libraries/Common/tests:System/Net/Http/QPackTestEncoder.cs",
        "//src/libraries/Common/tests:System/Net/Http/RepeatedFlushContent.cs",
        "//src/libraries/Common/tests:System/Net/Http/ResponseStreamTest.cs",
        "//src/libraries/Common/tests:System/Net/Http/SyncBlockingContent.cs",
        "//src/libraries/Common/tests:System/Net/Http/TestHelper.cs",
        "//src/libraries/Common/tests:System/Net/Http/ThrowingContent.cs",
        "//src/libraries/Common/tests:System/Net/Security/FakeNegotiateServer.cs",
        "//src/libraries/Common/tests:System/Net/Security/FakeNtlmServer.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/X509Certificates/CertificateAuthority.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/X509Certificates/RevocationResponder.cs",
        "//src/libraries/Common/tests:System/Threading/Tasks/GetStateMachineData.cs",
        "//src/libraries/Common/tests:System/Threading/Tasks/TaskTimeoutExtensions.cs",
        "//src/libraries/Common/tests:System/Threading/TrackingSynchronizationContext.cs",
        "//src/libraries/Common/tests:TestUtilities/System/DisableParallelization.cs",
        ":gen_resx",
    ],
    deps = [
        "//src/libraries:ref_Microsoft.Win32.Primitives",
        "//src/libraries:ref_System.Threading.Tasks",
        "//src/libraries/Common/tests:StreamConformanceTests",
        "//src/libraries/Common/tests:TestUtilities",
        "//src/libraries/System.Collections.Concurrent:ref_System.Collections.Concurrent",
        "//src/libraries/System.Collections.Immutable:ref_System.Collections.Immutable",
        "//src/libraries/System.Diagnostics.DiagnosticSource:ref_System.Diagnostics.DiagnosticSource",
        "//src/libraries/System.Diagnostics.TraceSource:ref_System.Diagnostics.TraceSource",
        "//src/libraries/System.Diagnostics.Tracing:ref_System.Diagnostics.Tracing",
        "//src/libraries/System.Data.Common:ref_System.Data.Common",
        "//src/libraries/System.DirectoryServices.Protocols:ref_System.DirectoryServices.Protocols",
        "//src/libraries/System.Formats.Asn1:ref_System.Formats.Asn1",
        "//src/libraries/System.IO.Compression:ref_System.IO.Compression",
        "//src/libraries/System.IO.Compression.Brotli:ref_System.IO.Compression.Brotli",
        "//src/libraries/System.IO.Pipes:ref_System.IO.Pipes",
        "//src/libraries/System.IO.Pipelines:ref_System.IO.Pipelines",
        "//src/libraries/System.Net.Http:ref_System.Net.Http",
        "//src/libraries/System.Net.Requests:ref_System.Net.Requests",
        "//src/libraries/System.Net.HttpListener:ref_System.Net.HttpListener",
        "//src/libraries/System.Net.NameResolution:ref_System.Net.NameResolution",
        "//src/libraries/System.Net.NetworkInformation:ref_System.Net.NetworkInformation",
        "//src/libraries/System.Net.Primitives:ref_System.Net.Primitives",
        "//src/libraries/System.Net.Quic:ref_System.Net.Quic",
        "//src/libraries/System.Net.Security:ref_System.Net.Security",
        "//src/libraries/System.Net.Sockets:ref_System.Net.Sockets",
        "//src/libraries/System.Net.WebHeaderCollection:ref_System.Net.WebHeaderCollection",
        "//src/libraries/System.Net.WebProxy:ref_System.Net.WebProxy",
        "//src/libraries/System.Net.WebSockets:ref_System.Net.WebSockets",
        "//src/libraries/System.Runtime.Serialization.Formatters:ref_System.Runtime.Serialization.Formatters",
        "//src/libraries/System.Security.Cryptography:ref_System.Security.Cryptography",
        "//src/libraries/System.Security.Claims:ref_System.Security.Claims",
        "//src/libraries/System.Security.Principal.Windows:ref_System.Security.Principal.Windows",
        "//src/libraries/System.Text.RegularExpressions:ref_System.Text.RegularExpressions",
        "//src/libraries/System.Text.Json:ref_System.Text.Json",
        "//src/libraries/System.Threading.Channels:ref_System.Threading.Channels",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/System.Threading.Thread:ref_System.Threading.Thread",
        "//src/libraries/System.Threading.Tasks.Parallel:ref_System.Threading.Tasks.Parallel",
        "//src/libraries/System.Threading.ThreadPool:ref_System.Threading.ThreadPool",
        "//src/libraries/System.Runtime.Numerics:ref_System.Runtime.Numerics",
        "//src/libraries/System.Web.HttpUtility:ref_System.Web.HttpUtility",
        "@paket.main//microsoft.dotnet.remoteexecutor",
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//microsoft.dotnet.xunitextensions",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    additionalfiles = ["//src/libraries/System.Net.Http:src/Resources/Strings.resx"],
    resources = [
        ":strings_resx",
        "SelectedSitesTest.txt",
    ],
    resource_logical_names = {
        "FxResources.System.Net.Http.Functional.Tests.SR.resources": "FxResources.System.Net.Http.Functional.Tests.SR.resources",
    },
    data = ["@paket.main//system.net.testdata:content_files"],
    allow_unsafe_blocks = True,
    size = "large",
    keyfile = OPEN_SNK,
    target_compatible_with = ["@platforms//os:linux"],
)
