load("//src/tests:live_test.bzl", "library_test")
load("//:defs.bzl", "OPEN_SNK", "gen_resx_source", "resgen")

gen_resx_source(
    name = "gen_resx",
    out = "SR.g.cs",
    assembly_name = "System.Net.Http.Unit.Tests",
    include_default_values = select({
        "//:libs_debug": True,
        "//conditions:default": False,
    }),
    resx_file = "//src/libraries/System.Net.Http:src/Resources/Strings.resx",
)

resgen(
    name = "strings_resx",
    out = "FxResources.System.Net.Http.Unit.Tests.SR.resources",
    resx_file = "//src/libraries/System.Net.Http:src/Resources/Strings.resx",
)

library_test(
    name = "System.Net.Http.Unit.Tests",
    srcs = glob(
        ["**/*.cs"],
        exclude = [
            "Fakes/MacProxy.cs",
        ],
    ) + [
        # Common source files
        "//src/libraries/Common:src/System/HexConverter.cs",
        "//src/libraries/Common:src/System/NotImplemented.cs",
        "//src/libraries/Common:src/System/CharArrayHelpers.cs",
        "//src/libraries/Common:src/System/Text/StringBuilderCache.cs",
        "//src/libraries/Common:src/System/Net/ArrayBuffer.cs",
        "//src/libraries/Common:src/System/Net/InternalException.cs",
        "//src/libraries/Common:src/System/Net/HttpDateParser.cs",
        "//src/libraries/Common:src/System/Net/HttpKnownHeaderNames.cs",
        "//src/libraries/Common:src/System/Net/HttpStatusDescription.cs",
        "//src/libraries/Common:src/System/Net/Logging/NetEventSource.Common.cs",
        "//src/libraries/Common:src/System/Net/Logging/NetEventSource.Common.Associate.cs",
        "//src/libraries/Common:src/System/Net/Http/UriRedactionHelper.cs",
        "//src/libraries/Common:src/System/Net/UriScheme.cs",
        "//src/libraries/Common:src/System/Text/SimpleRegex.cs",
        "//src/libraries/Common:src/System/IO/DelegatingStream.cs",
        "//src/libraries/Common:src/System/Net/Http/HttpHandlerDefaults.cs",
        "//src/libraries/Common:src/Interop/Windows/Interop.Libraries.cs",
        "//src/libraries/Common:src/Interop/Windows/Interop.HRESULT_FROM_WIN32.cs",
        "//src/libraries/Common:src/Interop/Windows/Advapi32/Interop.RegNotifyChangeKeyValue.cs",
        "//src/libraries/Common:src/Interop/Windows/WinHttp/Interop.SafeWinHttpHandle.cs",
        "//src/libraries/Common:src/System/Runtime/ExceptionServices/ExceptionStackTrace.cs",
        "//src/libraries/Common:src/Interop/Windows/WinHttp/Interop.winhttp_types.cs",
        "//src/libraries/Common:src/System/Obsoletions.cs",
        "//src/libraries/Common:src/System/Text/ValueStringBuilder.cs",
        "//src/libraries/Common:src/System/Text/ValueStringBuilder.AppendSpanFormattable.cs",
        # aspnetcore HPack/QPack common source
        "//src/libraries/Common:src/System/Net/Http/aspnetcore/IHttpStreamHeadersHandler.cs",
        "//src/libraries/Common:src/System/Net/Http/aspnetcore/Http2/Hpack/DynamicTable.cs",
        "//src/libraries/Common:src/System/Net/Http/aspnetcore/Http2/Hpack/HeaderField.cs",
        "//src/libraries/Common:src/System/Net/Http/aspnetcore/Http2/Hpack/HPackDecoder.cs",
        "//src/libraries/Common:src/System/Net/Http/aspnetcore/Http2/Hpack/HPackDecodingException.cs",
        "//src/libraries/Common:src/System/Net/Http/aspnetcore/Http2/Hpack/HPackEncoder.cs",
        "//src/libraries/Common:src/System/Net/Http/aspnetcore/Http2/Hpack/HPackEncodingException.cs",
        "//src/libraries/Common:src/System/Net/Http/aspnetcore/Http2/Hpack/Huffman.cs",
        "//src/libraries/Common:src/System/Net/Http/aspnetcore/Http2/Hpack/HuffmanDecodingException.cs",
        "//src/libraries/Common:src/System/Net/Http/aspnetcore/Http2/Hpack/IntegerDecoder.cs",
        "//src/libraries/Common:src/System/Net/Http/aspnetcore/Http2/Hpack/IntegerEncoder.cs",
        "//src/libraries/Common:src/System/Net/Http/aspnetcore/Http2/Hpack/H2StaticTable.cs",
        "//src/libraries/Common:src/System/Net/Http/aspnetcore/Http2/Hpack/H2StaticTable.Http2.cs",
        "//src/libraries/Common:src/System/Net/Http/aspnetcore/Http2/Hpack/StatusCodes.cs",
        "//src/libraries/Common:src/System/Net/Http/aspnetcore/Http3/QPack/H3StaticTable.cs",
        "//src/libraries/Common:src/System/Net/Http/aspnetcore/Http3/QPack/H3StaticTable.Http3.cs",
        "//src/libraries/Common:src/System/Net/Http/aspnetcore/Http3/QPack/HeaderField.cs",
        "//src/libraries/Common:src/System/Net/Http/aspnetcore/Http3/QPack/QPackEncoder.cs",
        "//src/libraries/Common:src/System/Net/Http/aspnetcore/Http3/QPack/QPackDecoder.cs",
        "//src/libraries/Common:src/System/Net/Http/aspnetcore/Http3/QPack/QPackEncodingException.cs",
        "//src/libraries/Common:src/System/Net/Http/aspnetcore/Http3/QPack/QPackDecodingException.cs",
        # Common test files
        "//src/libraries/Common/tests:System/Net/Configuration.cs",
        "//src/libraries/Common/tests:System/Net/Configuration.Http.cs",
        "//src/libraries/Common/tests:System/ShouldNotBeInvokedException.cs",
        "//src/libraries/Common/tests:System/Net/Http/HPackEncoder.cs",
        "//src/libraries/Common/tests:System/Net/Http/HuffmanEncoder.cs",
        "//src/libraries/Common/tests:System/Net/RemoteExecutorExtensions.cs",
        # aspnetcore test files
        "//src/libraries/Common/tests:Tests/System/Net/aspnetcore/Http2/DynamicTableTest.cs",
        "//src/libraries/Common/tests:Tests/System/Net/aspnetcore/Http2/HPackDecoderTest.cs",
        "//src/libraries/Common/tests:Tests/System/Net/aspnetcore/Http2/HPackIntegerTest.cs",
        "//src/libraries/Common/tests:Tests/System/Net/aspnetcore/Http2/HuffmanDecodingTests.cs",
        "//src/libraries/Common/tests:Tests/System/Net/aspnetcore/Http3/QPackDecoderTest.cs",
        # Production source files from System.Net.Http
        "//src/libraries/System.Net.Http:src/System/Net/Http/SocketsHttpHandler/AuthenticationHelper.Digest.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/SocketsHttpHandler/HttpKeepAlivePingPolicy.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/HttpBaseStream.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/ByteArrayContent.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/CancellationHelper.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/ClientCertificateOption.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/DelegatingHandler.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/EmptyContent.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/EmptyReadStream.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/FormUrlEncodedContent.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/GlobalHttpSettings.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/HeaderEncodingSelector.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/HttpUtilities.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/AltSvcHeaderParser.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/AltSvcHeaderValue.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/AuthenticationHeaderValue.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/BaseHeaderParser.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/ByteArrayHeaderParser.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/CacheControlHeaderParser.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/CacheControlHeaderValue.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/ContentDispositionHeaderValue.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/ContentRangeHeaderValue.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/CookieHeaderParser.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/DateHeaderParser.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/EntityTagHeaderValue.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/GenericHeaderParser.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/HeaderDescriptor.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/HeaderStringValues.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/HeaderUtilities.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/HttpContentHeaders.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/HttpGeneralHeaders.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/HttpHeaderParser.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/HttpHeaders.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/HttpHeadersNonValidated.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/HttpHeaderType.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/HttpHeaderValueCollection.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/HttpRequestHeaders.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/HttpResponseHeaders.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/Int32NumberHeaderParser.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/Int64NumberHeaderParser.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/KnownHeaders.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/KnownHeader.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/KnownHeader.Http2And3.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/MediaTypeHeaderParser.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/MediaTypeHeaderValue.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/MediaTypeWithQualityHeaderValue.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/NameValueHeaderValue.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/NameValueWithParametersHeaderValue.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/ObjectCollection.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/ProductHeaderValue.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/ProductInfoHeaderParser.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/ProductInfoHeaderValue.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/QPackStaticTable.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/RangeConditionHeaderValue.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/RangeHeaderValue.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/RangeItemHeaderValue.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/RetryConditionHeaderValue.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/StringWithQualityHeaderValue.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/TimeSpanHeaderParser.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/TransferCodingHeaderParser.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/TransferCodingHeaderValue.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/TransferCodingWithQualityHeaderValue.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/UriHeaderParser.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/ViaHeaderValue.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/Headers/WarningHeaderValue.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/DiagnosticsHelper.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/HttpClient.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/HttpHandlerDefaults.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/HttpCompletionOption.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/HttpContent.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/HttpIOException.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/HttpMessageHandler.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/HttpMessageInvoker.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/HttpMethod.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/HttpParseResult.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/HttpRequestError.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/HttpRequestException.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/RequestRetryType.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/HttpRequestMessage.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/HttpRequestOptions.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/HttpRequestOptionsKey.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/HttpResponseMessage.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/HttpRuleParser.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/HttpVersionPolicy.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/MessageProcessingHandler.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/MultipartContent.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/MultipartFormDataContent.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/NetEventSource.Http.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/StreamContent.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/StreamToStreamCopy.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/StringContent.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/SocketsHttpHandler/RuntimeSettingParser.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/SocketsHttpHandler/HttpEnvironmentProxy.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/SocketsHttpHandler/HttpEnvironmentProxy.Unix.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/SocketsHttpHandler/HttpUtilities.SocketsHttpHandler.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/SocketsHttpHandler/SystemProxyInfo.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/SocketsHttpHandler/SystemProxyInfo.Unix.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/SocketsHttpHandler/HttpNoProxy.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/SocketsHttpHandler/HttpWindowsProxy.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/SocketsHttpHandler/WinInetProxyHelper.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/SocketsHttpHandler/IMultiWebProxy.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/SocketsHttpHandler/MultiProxy.cs",
        "//src/libraries/System.Net.Http:src/System/Net/Http/SocketsHttpHandler/FailedProxyCache.cs",
        # WinHttpHandler source files
        "//src/libraries/System.Net.Http.WinHttpHandler:src/System/Net/Http/WinHttpException.cs",
        "//src/libraries/System.Net.Http.WinHttpHandler:src/System/Net/Http/WinHttpTraceHelper.cs",
        # WinHttpHandler test files
        "//src/libraries/System.Net.Http.WinHttpHandler:tests/UnitTests/FakeInterop.cs",
        "//src/libraries/System.Net.Http.WinHttpHandler:tests/UnitTests/FakeRegistry.cs",
        "//src/libraries/System.Net.Http.WinHttpHandler:tests/UnitTests/FakeSafeWinHttpHandle.cs",
        "//src/libraries/System.Net.Http.WinHttpHandler:tests/UnitTests/TestControl.cs",
        "//src/libraries/System.Net.Http.WinHttpHandler:tests/UnitTests/APICallHistory.cs",
        "//src/libraries/System.Net.Http.WinHttpHandler:tests/UnitTests/TestServer.cs",
        # SR support
        "//src/libraries/Common:src/System/SR.cs",
        ":gen_resx",
    ],
    deps = [
        "//src/libraries/Microsoft.Win32.Registry:ref_Microsoft.Win32.Registry",
        "//src/libraries/System.Net.Primitives:ref_System.Net.Primitives",
        "//src/libraries/System.Net.Security:ref_System.Net.Security",
        "//src/libraries/System.Net.Sockets:ref_System.Net.Sockets",
        "//src/libraries/System.Net.NetworkInformation:ref_System.Net.NetworkInformation",
        "//src/libraries/System.Net.Quic:ref_System.Net.Quic",
        "//src/libraries/System.Security.Cryptography:ref_System.Security.Cryptography",
        "//src/libraries/System.Diagnostics.DiagnosticSource:ref_System.Diagnostics.DiagnosticSource",
        "//src/libraries/System.Collections.Concurrent:ref_System.Collections.Concurrent",
        "//src/libraries/System.Collections.Immutable:ref_System.Collections.Immutable",
        "//src/libraries/System.Diagnostics.Tracing:ref_System.Diagnostics.Tracing",
        "//src/libraries/System.IO.Compression:ref_System.IO.Compression",
        "//src/libraries/System.Text.RegularExpressions:ref_System.Text.RegularExpressions",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/System.Threading.Thread:ref_System.Threading.Thread",
        "//src/libraries/System.Threading.ThreadPool:ref_System.Threading.ThreadPool",
        "//src/libraries:ref_Microsoft.Win32.Primitives",
        "//src/libraries/Common/tests:TestUtilities",
        "@paket.main//microsoft.diagnostics.runtime",
        "@paket.main//microsoft.dotnet.remoteexecutor",
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//microsoft.dotnet.xunitextensions",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    additionalfiles = ["//src/libraries/System.Net.Http:src/Resources/Strings.resx"],
    resources = [":strings_resx"],
    resource_logical_names = {
        "FxResources.System.Net.Http.Unit.Tests.SR.resources": "FxResources.System.Net.Http.Unit.Tests.SR.resources",
    },
    allow_unsafe_blocks = True,
    os_targeted = "unix",
    keyfile = OPEN_SNK,
    size = "large",
)
