load("//src/tests:live_test.bzl", "library_test")

library_test(
    name = "System.Text.Encoding.Extensions.Tests",
    srcs = glob(["*.cs"]),
    deps = [
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//microsoft.dotnet.xunitextensions",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    allow_unsafe_blocks = True,
    keyfile = "@nuget.microsoft.dotnet.arcade.sdk.v10.0.0-beta.26102.102//:tools/snk/Open.snk",
)
