load("//src/tests:live_test.bzl", "coreclr_test")

coreclr_test(
    name = "DevDiv_816617_ro",
    srcs = ["DevDiv_816617.cs"],
    pri = 1,
    optimize = True,
    size = "medium",
)

coreclr_test(
    name = "DevDiv_816617_d",
    srcs = ["DevDiv_816617.cs"],
    pri = 1,
    debug_type = "full",
    optimize = False,
    size = "medium",
)

coreclr_test(
    name = "DevDiv_816617_r",
    srcs = ["DevDiv_816617.cs"],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "DevDiv_816617_do",
    srcs = ["DevDiv_816617.cs"],
    pri = 1,
    debug_type = "full",
    optimize = True,
    size = "medium",
)
