load("//src/libraries:defs.bzl", "netcoreapp_ref_assembly", "netcoreapp_impl_assembly", "ref_impl_pair")

exports_files([
    "ref/System.Diagnostics.Contracts.cs",
])

netcoreapp_ref_assembly(
    name = "ref_System.Diagnostics.Contracts",
    srcs = [
        "ref/System.Diagnostics.Contracts.cs",
    ],
    deps = [
        "//src/libraries:ref_System.Runtime",
    ],
)

netcoreapp_impl_assembly(
    name = "impl_System.Diagnostics.Contracts",
    include_editorconfig = False,
    nowarn = ["CS1591"],
    srcs = [],
    deps = [
        "//src/coreclr/System.Private.CoreLib:impl_System.Private.CoreLib",
    ],
    partial_facade = True,
    generate_facades = True,
    facade_contract_assembly = ":ref_System.Diagnostics.Contracts",
    exclude_sr = True,
)

ref_impl_pair(
    name = "live_System.Diagnostics.Contracts",
    ref = ":ref_System.Diagnostics.Contracts",
    lib = ":impl_System.Diagnostics.Contracts",
    visibility = ["//visibility:public"],
)