load("//src/tests:live_test.bzl", "coreclr_test")

coreclr_test(
    name = "b08046cs",
    srcs = ["SyncGCHole.cs"],
    pri = 1,
    debug_type = "pdbonly",
    optimize = True,
    deps = [
        "//src/libraries/System.Threading.Thread:ref_System.Threading.Thread",
        "//src/libraries/System.Threading:ref_System.Threading",
    ],
    size = "medium",
)
