load("//src/libraries:defs.bzl", "MULTITARGET_NOWARN", "netcoreapp_ref_assembly", "impl_assembly", "ref_impl_pair")

exports_files([
    "ref/System.Security.Cryptography.ProtectedData.cs",
])

netcoreapp_ref_assembly(
    name = "ref_System.Security.Cryptography.ProtectedData",
    srcs = [
        "ref/System.Security.Cryptography.ProtectedData.cs",
    ],
    deps = [
        "//src/libraries:ref_System.Runtime",
    ],
)

impl_assembly(
    name = "impl_System.Security.Cryptography.ProtectedData",
    include_runtime_async = False,
    event_source_generator = False,
    allow_unsafe_blocks = True,
    analyzers = [
        "//src/libraries/System.Runtime.InteropServices:ComInterfaceGenerator",
        "//src/libraries/System.Text.Json:JsonSourceGenerator",
        "//src/libraries/System.Text.RegularExpressions:RegexGenerator",
    ],
    nowarn = MULTITARGET_NOWARN + ["CP0003", "CS1591", "NU5128"],
    srcs = [
        "src/System/Security/Cryptography/DataProtectionScope.cs",
        "src/System/Security/Cryptography/ProtectedData.cs",
        "//src/libraries/Common:src/DisableRuntimeMarshalling.cs",
        "//src/libraries/Common:src/Interop/Windows/Crypt32/Interop.CryptProtectData.cs",
        "//src/libraries/Common:src/Interop/Windows/Crypt32/Interop.CryptProtectDataFlags.cs",
        "//src/libraries/Common:src/Interop/Windows/Crypt32/Interop.CryptUnprotectData.cs",
        "//src/libraries/Common:src/Interop/Windows/Crypt32/Interop.DATA_BLOB.cs",
        "//src/libraries/Common:src/Interop/Windows/Interop.Errors.cs",
        "//src/libraries/Common:src/Interop/Windows/Interop.Libraries.cs",
        "//src/libraries/Common:src/Interop/Windows/Kernel32/Interop.FormatMessage.cs",
        "//src/libraries/Common:src/System/HResults.cs",
        "//src/libraries/Common:src/System/Security/Cryptography/CryptoThrowHelper.Windows.cs",
    ],
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Runtime.InteropServices:ref_System.Runtime.InteropServices",
    ],
    resx_file = "src/Resources/Strings.resx",
    supported_os_platforms_short = ["windows"],
    assembly_description = "Provides access to Windows Data Protection Api.\n\nCommonly Used Types:\nSystem.Security.Cryptography.DataProtectionScope\nSystem.Security.Cryptography.ProtectedData",
)

ref_impl_pair(
    name = "live_System.Security.Cryptography.ProtectedData",
    ref = ":ref_System.Security.Cryptography.ProtectedData",
    lib = ":impl_System.Security.Cryptography.ProtectedData",
    visibility = ["//visibility:public"],
)
