load("//src/libraries:defs.bzl", "netcoreapp_impl_assembly")

netcoreapp_impl_assembly(
    name = "impl_System.ServiceProcess",
    srcs = [
        "src/System.ServiceProcess.cs",
    ],
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/shims/stubs:ref_System.Security.Permissions",
        "//src/libraries/shims/stubs:ref_System.ServiceProcess.ServiceController",
    ],
    exclude_sr = True,
)
