load("//:defs.bzl", "ECMA_SNK")
load("//src/libraries:defs.bzl", "netcoreapp_impl_assembly")

netcoreapp_impl_assembly(
    name = "impl_System.ServiceProcess",
    generate_documentation_file = False,
    library_import_generator = False,
    skip_locals_init = False,
    srcs = [
        "src/System.ServiceProcess.cs",
    ],
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/shims/stubs:ref_System.Security.Permissions",
        "//src/libraries/shims/stubs:ref_System.ServiceProcess.ServiceController",
    ],
    os_targeted = True,
    exclude_sr = True,
    assembly_version = "4.0.0.0",
)
