load("//src/tests:live_test.bzl", "il_coreclr_test")

il_coreclr_test(
    name = "ldobj_R4_d",
    srcs = ["ldobj_R4_d.il", "ldobj_R4.il"],
    pri = 1,
    debug_type = "full",
)

il_coreclr_test(
    name = "ldobj_V_d",
    srcs = ["ldobj_V_d.il", "ldobj_V.il"],
    pri = 1,
    debug_type = "full",
)

il_coreclr_test(
    name = "ldobj_R4_r",
    srcs = ["ldobj_R4_r.il", "ldobj_R4.il"],
    pri = 1,
    debug_type = "pdbonly",
)

il_coreclr_test(
    name = "ldobj_I_r",
    srcs = ["ldobj_I_r.il", "ldobj_I.il"],
    pri = 1,
    debug_type = "pdbonly",
)

il_coreclr_test(
    name = "ldobj_U2_d",
    srcs = ["ldobj_U2_d.il", "ldobj_U2.il"],
    pri = 1,
    debug_type = "full",
)

il_coreclr_test(
    name = "ldobj_U2_r",
    srcs = ["ldobj_U2_r.il", "ldobj_U2.il"],
    pri = 1,
    debug_type = "pdbonly",
)

il_coreclr_test(
    name = "ldobj_R8_d",
    srcs = ["ldobj_R8_d.il", "ldobj_R8.il"],
    pri = 1,
    debug_type = "full",
)

il_coreclr_test(
    name = "ldobj_I_d",
    srcs = ["ldobj_I_d.il", "ldobj_I.il"],
    pri = 1,
    debug_type = "full",
)

il_coreclr_test(
    name = "ldobj_I8_r",
    srcs = ["ldobj_I8_r.il", "ldobj_I8.il"],
    pri = 1,
    debug_type = "pdbonly",
)

il_coreclr_test(
    name = "ldobj_R8_r",
    srcs = ["ldobj_R8_r.il", "ldobj_R8.il"],
    pri = 1,
    debug_type = "pdbonly",
)

il_coreclr_test(
    name = "ldobj_V_r",
    srcs = ["ldobj_V_r.il", "ldobj_V.il"],
    pri = 1,
    debug_type = "pdbonly",
)

il_coreclr_test(
    name = "ldobj_I8_d",
    srcs = ["ldobj_I8_d.il", "ldobj_I8.il"],
    pri = 1,
    debug_type = "full",
)
