load("//src/libraries:defs.bzl", "COMMON_GENERATOR_ANALYZERS", "MULTITARGET_NOWARN", "netcoreapp_ref_assembly", "impl_assembly", "ref_impl_pair")

exports_files([
    "ref/Microsoft.Extensions.Logging.EventSource.cs",
])

netcoreapp_ref_assembly(
    name = "ref_Microsoft.Extensions.Logging.EventSource",
    srcs = [
        "ref/Microsoft.Extensions.Logging.EventSource.cs",
    ],
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/Microsoft.Extensions.Logging:ref_Microsoft.Extensions.Logging",
        "//src/libraries/Microsoft.Extensions.Logging.Abstractions:ref_Microsoft.Extensions.Logging.Abstractions",
        "//src/libraries/System.Diagnostics.Tracing:ref_System.Diagnostics.Tracing",
    ],
)

impl_assembly(
    name = "impl_Microsoft.Extensions.Logging.EventSource",
    allow_unsafe_blocks = True,
    nowarn = MULTITARGET_NOWARN + ["CP0003", "PKG0001"],
    exclude_sr = True,
    srcs = glob(["src/**/*.cs"]) + [
        "//src/libraries/Common:src/Extensions/Logging/NullExternalScopeProvider.cs",
        "//src/libraries/Common:src/Extensions/Logging/NullScope.cs",
    ],
    analyzers = COMMON_GENERATOR_ANALYZERS,
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions:ref_Microsoft.Extensions.DependencyInjection.Abstractions",
        "//src/libraries/Microsoft.Extensions.Logging:ref_Microsoft.Extensions.Logging",
        "//src/libraries/Microsoft.Extensions.Logging.Abstractions:ref_Microsoft.Extensions.Logging.Abstractions",
        "//src/libraries/Microsoft.Extensions.Options:ref_Microsoft.Extensions.Options",
        "//src/libraries/Microsoft.Extensions.Primitives:ref_Microsoft.Extensions.Primitives",
        "//src/libraries/System.Collections:ref_System.Collections",
        "//src/libraries/System.Collections.Concurrent:ref_System.Collections.Concurrent",
        "//src/libraries/System.ComponentModel:ref_System.ComponentModel",
        "//src/libraries/System.Diagnostics.DiagnosticSource:ref_System.Diagnostics.DiagnosticSource",
        "//src/libraries/System.Diagnostics.Tracing:ref_System.Diagnostics.Tracing",
        "//src/libraries/System.Linq:ref_System.Linq",
        "//src/libraries/System.Memory:ref_System.Memory",
        "//src/libraries/System.Text.Json:ref_System.Text.Json",
        "//src/libraries/System.Threading:ref_System.Threading",
    ],
)

ref_impl_pair(
    name = "live_Microsoft.Extensions.Logging.EventSource",
    ref = ":ref_Microsoft.Extensions.Logging.EventSource",
    lib = ":impl_Microsoft.Extensions.Logging.EventSource",
    visibility = ["//visibility:public"],
)
