load("//:defs.bzl", "csharp_library")

genrule(
    name = "AssemblyInfo",
    outs = ["AssemblyInfo.g.cs"],
    cmd = "echo '[assembly: System.Reflection.AssemblyFileVersion(\"10.0.0.0\")]' > $@",
)

csharp_library(
    name = "ILCompiler.RyuJit",
    srcs = [
        ":AssemblyInfo",
        "Compiler/DependencyAnalysis/MethodCodeNode.cs",
        "Compiler/DependencyAnalysis/RyuJitNodeFactory.cs",
        "Compiler/ProfileDataManager.cs",
        "Compiler/RyuJitCompilation.cs",
        "Compiler/RyuJitCompilationBuilder.cs",
        "JitInterface/CorInfoImpl.RyuJit.cs",
    ] + [
        "//src/coreclr/tools/Common:Internal/Runtime/CorConstants.cs",
        "//src/coreclr/tools/Common:Internal/Runtime/MethodTable.Constants.cs",
        "//src/coreclr/tools/Common:Internal/Runtime/RiscVLoongArch64FpStruct.cs",
        "//src/coreclr/tools/Common:JitInterface/CorInfoImpl.cs",
        "//src/coreclr/tools/Common:JitInterface/CorInfoImpl_generated.cs",
        "//src/coreclr/tools/Common:JitInterface/IJitHashableOnly.cs",
        "//src/coreclr/tools/Common:JitInterface/JitConfigProvider.cs",
        "//src/coreclr/tools/Common:JitInterface/JitTypeNameFormatter.cs",
        "//src/coreclr/tools/Common:JitInterface/SwiftPhysicalLowering.cs",
        "//src/coreclr/tools/Common:JitInterface/SystemVStructClassificator.cs",
        "//src/coreclr/tools/Common:JitInterface/UnboxingMethodDesc.cs",
        "//src/coreclr/tools/Common:JitInterface/UnboxingMethodDescFactory.cs",
        "//src/coreclr/tools/Common:Pgo/TypeSystemEntityOrUnknown.cs",
        "//src/coreclr/tools/Common:System/Collections/Generic/ArrayBuilder.cs",
        "//src/coreclr/tools/Common:System/FormattingHelpers.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/HelperExtensions.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/ILReader.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/Stubs/TypeSystemThrowingILEmitter.cs",
    ] + [
        "//src/coreclr/tools/aot/ILCompiler.Compiler:Compiler/JitHelper.cs",
        "//src/coreclr/tools/aot/ILCompiler.ReadyToRun:Compiler/FileLayoutOptimizer.cs",
        "//src/coreclr/tools/aot/ILCompiler.ReadyToRun:Compiler/PettisHansenSort/CallGraphNode.cs",
        "//src/coreclr/tools/aot/ILCompiler.ReadyToRun:Compiler/PettisHansenSort/DisjointSetForest.cs",
        "//src/coreclr/tools/aot/ILCompiler.ReadyToRun:Compiler/PettisHansenSort/PettisHansen.cs",
        "//src/coreclr/tools/aot/ILCompiler.ReadyToRun:Compiler/ProfileData.cs",
        "//src/coreclr/tools/aot/ILCompiler.ReadyToRun:IBC/IBCDataModel.cs",
        "//src/coreclr/tools/aot/ILCompiler.ReadyToRun:IBC/IBCProfileData.cs",
        "//src/coreclr/tools/aot/ILCompiler.ReadyToRun:IBC/MIbcProfileParser.cs",
    ],
    compiler_options = ["/unsafe"],
    deps = [
        "//src/coreclr/tools/aot/ILCompiler.Compiler",
        "//src/coreclr/tools/aot/ILCompiler.DependencyAnalysisFramework",
        "//src/coreclr/tools/aot/ILCompiler.MetadataTransform",
        "//src/coreclr/tools/aot/ILCompiler.TypeSystem",
    ],
    target_frameworks = ["net10.0"],
    visibility = ["//visibility:public"],
)
