load("//:defs.bzl", "csharp_library", "gen_assembly_info", "gen_target_framework_attrs")

gen_assembly_info(
    name = "assemblyinfo_ILCompiler.RyuJit",
    out = "ILCompiler.RyuJit.AssemblyInfo.cs",
    assembly_name = "ILCompiler.RyuJit",
    cls_compliant = False,
    is_aot_compatible = False,
    include_serviceable = False,
    include_description = False,
    assembly_configuration = "Release",
    include_dll_safe_search_path = 0,
)

gen_target_framework_attrs(
    name = "tfmattrs_ILCompiler.RyuJit",
    out = ".NETCoreApp,Version=v10.0.AssemblyAttributes.cs",
)

csharp_library(
    name = "ILCompiler.RyuJit",
    nowarn = ["1591"],
    msbuild_analyzer_config = "style",
    include_default_ruleset = False,
    skip_analyzers = True,
    interceptors_namespaces = ";Microsoft.Extensions.Validation.Generated",
    compiler_options = ["/warnaserror+:NU1605"],
    srcs = [
        ":assemblyinfo_ILCompiler.RyuJit",
        ":tfmattrs_ILCompiler.RyuJit",
        "Compiler/DependencyAnalysis/MethodCodeNode.cs",
        "Compiler/DependencyAnalysis/RyuJitNodeFactory.cs",
        "Compiler/ProfileDataManager.cs",
        "Compiler/RyuJitCompilation.cs",
        "Compiler/RyuJitCompilationBuilder.cs",
        "JitInterface/CorInfoImpl.RyuJit.cs",
    ] + [
        "//src/coreclr/tools/Common:Internal/Runtime/CorConstants.cs",
        "//src/coreclr/tools/Common:Internal/Runtime/MethodTable.Constants.cs",
        "//src/coreclr/tools/Common:Internal/Runtime/RiscVLoongArch64FpStruct.cs",
        "//src/coreclr/tools/Common:JitInterface/CorInfoImpl.cs",
        "//src/coreclr/tools/Common:JitInterface/CorInfoImpl_generated.cs",
        "//src/coreclr/tools/Common:JitInterface/IJitHashableOnly.cs",
        "//src/coreclr/tools/Common:JitInterface/JitConfigProvider.cs",
        "//src/coreclr/tools/Common:JitInterface/JitTypeNameFormatter.cs",
        "//src/coreclr/tools/Common:JitInterface/SwiftPhysicalLowering.cs",
        "//src/coreclr/tools/Common:JitInterface/SystemVStructClassificator.cs",
        "//src/coreclr/tools/Common:JitInterface/UnboxingMethodDesc.cs",
        "//src/coreclr/tools/Common:JitInterface/UnboxingMethodDescFactory.cs",
        "//src/coreclr/tools/Common:Pgo/TypeSystemEntityOrUnknown.cs",
        "//src/coreclr/tools/Common:System/Collections/Generic/ArrayBuilder.cs",
        "//src/coreclr/tools/Common:System/FormattingHelpers.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/HelperExtensions.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/ILReader.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/Stubs/TypeSystemThrowingILEmitter.cs",
    ] + [
        "//src/coreclr/tools/aot/ILCompiler.Compiler:Compiler/JitHelper.cs",
        "//src/coreclr/tools/aot/ILCompiler.ReadyToRun:Compiler/FileLayoutOptimizer.cs",
        "//src/coreclr/tools/aot/ILCompiler.ReadyToRun:Compiler/PettisHansenSort/CallGraphNode.cs",
        "//src/coreclr/tools/aot/ILCompiler.ReadyToRun:Compiler/PettisHansenSort/DisjointSetForest.cs",
        "//src/coreclr/tools/aot/ILCompiler.ReadyToRun:Compiler/PettisHansenSort/PettisHansen.cs",
        "//src/coreclr/tools/aot/ILCompiler.ReadyToRun:Compiler/ProfileData.cs",
        "//src/coreclr/tools/aot/ILCompiler.ReadyToRun:IBC/IBCDataModel.cs",
        "//src/coreclr/tools/aot/ILCompiler.ReadyToRun:IBC/IBCProfileData.cs",
        "//src/coreclr/tools/aot/ILCompiler.ReadyToRun:IBC/MIbcProfileParser.cs",
    ],
    allow_unsafe_blocks = True,
    analyzers = [
        "//src/tools/illink/src/ILLink.RoslynAnalyzer",
    ],
    deps = [
        "//src/coreclr/tools/aot/ILCompiler.Compiler",
        "//src/coreclr/tools/aot/ILCompiler.DependencyAnalysisFramework",
        "//src/coreclr/tools/aot/ILCompiler.MetadataTransform",
        "//src/coreclr/tools/aot/ILCompiler.TypeSystem",
        "@paket.main//microsoft.diasymreader",
    ],
    target_frameworks = ["net10.0"],
    visibility = ["//visibility:public"],
)
