load("//src/tests:live_test.bzl", "coreclr_test")

coreclr_test(
    name = "Runtime_95315",
    srcs = ["Runtime_95315.cs"],
    optimize = True,
    allow_unsafe_blocks = True,
    deps = [
        "//src/libraries/System.Threading.Thread:ref_System.Threading.Thread",
        "//src/libraries/System.Threading:ref_System.Threading",
    ],
)
