load("//src/tests:live_test.bzl", "coreclr_test")

coreclr_test(
    name = "Avx10v1_Vector256_r",
    srcs = [
        "Program.Avx10v1_Vector256.cs",
        "//src/tests/JIT/HardwareIntrinsics/X86/Shared:Program.cs",
    ],
)

coreclr_test(
    name = "Avx10v1_Vector256_ro",
    srcs = [
        "Program.Avx10v1_Vector256.cs",
        "//src/tests/JIT/HardwareIntrinsics/X86/Shared:Program.cs",
    ],
    optimize = True,
)
