load("//src/libraries:defs.bzl", "netcoreapp_ref_assembly", "netcoreapp_impl_assembly")

netcoreapp_ref_assembly(
    name = "ref_System.Net.Primitives",
    srcs = [
        "ref/System.Net.Primitives.cs",
    ],
    deps = [
        "//src/libraries:ref_Microsoft.Win32.Primitives",
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Runtime.InteropServices:ref_System.Runtime.InteropServices",
    ],
)

netcoreapp_impl_assembly(
    name = "impl_System.Net.Primitives",
    analyzers = [
        "//src/libraries/System.Runtime.InteropServices:LibraryImportGenerator",
        "//src/libraries/System.Runtime.InteropServices:Microsoft.Interop.SourceGeneration",
    ],
    srcs = glob(
        ["src/System/**/*.cs"],
        exclude = [
            "src/System/Net/SocketException.Windows.cs",
            "src/System/Net/SocketException.Unix.cs",
        ],
    ) + [
        "//src/libraries/Common:src/System/Net/CookieComparer.cs",
        "//src/libraries/Common:src/System/Net/CookieFields.cs",
        "//src/libraries/Common:src/System/Net/CookieParser.cs",
        "//src/libraries/Common:src/System/Net/IPAddressParserStatics.cs",
        "//src/libraries/Common:src/System/Net/IPEndPointExtensions.cs",
        "//src/libraries/Common:src/System/Net/IPv4AddressHelper.Common.cs",
        "//src/libraries/Common:src/System/Net/IPv6AddressHelper.Common.cs",
        "//src/libraries/Common:src/System/Net/HttpKnownHeaderNames.cs",
        "//src/libraries/Common:src/System/Net/TcpValidationHelpers.cs",
        "//src/libraries/Common:src/System/Net/UriScheme.cs",
        "//src/libraries/Common:src/System/Net/SocketAddress.cs",
        "//src/libraries/Common:src/System/Net/SocketAddressExtensions.cs",
        "//src/libraries/Common:src/System/Net/NegotiationInfoClass.cs",
        "//src/libraries/Common:src/System/Net/CredentialCacheKey.cs",
        "//src/libraries/Common:src/System/Net/Logging/NetEventSource.Common.cs",
        "//src/libraries/Common:src/System/Text/StringBuilderCache.cs",
        "//src/libraries/Common:src/System/HexConverter.cs",
        "//src/libraries/Common:src/System/NotImplemented.cs",
        "//src/libraries/Common:src/System/Obsoletions.cs",
        "//src/libraries/Common:src/Interop/Windows/Crypt32/Interop.Alg.cs",
        "//src/libraries/Common:src/Interop/Windows/SChannel/Interop.SchProtocols.cs",
        "//src/libraries/Common:src/Interop/Windows/WinSock/Interop.ErrorCodes.cs",
    ] + select({
        "@platforms//os:linux": [
            "src/System/Net/SocketException.Unix.cs",
            "//src/libraries/Common:src/System/Net/SocketAddressPal.Unix.cs",
            "//src/libraries/Common:src/System/Net/Sockets/SocketErrorPal.Unix.cs",
            "//src/libraries/Common:src/System/Net/NetworkInformation/HostInformationPal.Unix.cs",
            "//src/libraries/Common:src/System/Net/NetworkInformation/InterfaceInfoPal.Unix.cs",
            "//src/libraries/Common:src/Interop/Unix/Interop.Errors.cs",
            "//src/libraries/Common:src/Interop/Unix/Interop.Libraries.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.IPAddress.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.SocketAddress.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.GetDomainName.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.GetHostName.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.GetNameInfo.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.HostEntry.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.InterfaceNameToIndex.cs",
        ],
        "@platforms//os:macos": [
            "src/System/Net/SocketException.Unix.cs",
            "//src/libraries/Common:src/System/Net/SocketAddressPal.Unix.cs",
            "//src/libraries/Common:src/System/Net/Sockets/SocketErrorPal.Unix.cs",
            "//src/libraries/Common:src/System/Net/NetworkInformation/HostInformationPal.Unix.cs",
            "//src/libraries/Common:src/System/Net/NetworkInformation/InterfaceInfoPal.Unix.cs",
            "//src/libraries/Common:src/Interop/Unix/Interop.Errors.cs",
            "//src/libraries/Common:src/Interop/Unix/Interop.Libraries.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.IPAddress.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.SocketAddress.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.GetDomainName.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.GetHostName.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.GetNameInfo.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.HostEntry.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.InterfaceNameToIndex.cs",
        ],
    }),
    resx_file = "src/Resources/Strings.resx",
    allow_unsafe_blocks = True,
    defines = ["SYSTEM_NET_PRIMITIVES_DLL"],
    deps = [
        "//src/libraries:ref_Microsoft.Win32.Primitives",
        "//src/libraries/System.Collections:ref_System.Collections",
        "//src/libraries/System.Collections.NonGeneric:ref_System.Collections.NonGeneric",
        "//src/libraries/System.Diagnostics.Tracing:ref_System.Diagnostics.Tracing",
        "//src/libraries/System.Memory:ref_System.Memory",
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Runtime.InteropServices:ref_System.Runtime.InteropServices",
        "//src/libraries/System.Runtime.Intrinsics:ref_System.Runtime.Intrinsics",
        "//src/libraries/System.Threading:ref_System.Threading",
    ],
)
