load("//:defs.bzl", "ECMA_SNK", "SHAREDLIB1024_SNK")
load("//src/libraries:defs.bzl", "netcoreapp_impl_assembly")

netcoreapp_impl_assembly(
    name = "impl_System.ServiceModel.Web",
    keyfile = SHAREDLIB1024_SNK,
    generate_documentation_file = False,
    library_import_generator = False,
    skip_locals_init = False,
    srcs = [
        "src/System.ServiceModel.Web.cs",
    ],
    deps = [
        "//src/libraries/System.Runtime.Serialization.Json:ref_System.Runtime.Serialization.Json",
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/shims/stubs:ref_System.ServiceModel.Syndication",
    ],
    os_targeted = True,
    exclude_sr = True,
    assembly_version = "4.0.0.0",
)
