load("//src/tests:live_test.bzl", "library_test")

library_test(
    name = "System.Collections.Immutable.Tests",
    srcs = glob(["**/*.cs"]) + [
        "//src/libraries/System.Collections.Immutable:src/System/Polyfills.cs",
        "//src/libraries/System.Collections.Immutable:src/System/Collections/Frozen/String/Hashing.cs",
        "//src/libraries/System.Collections.Immutable:src/System/Collections/Frozen/String/KeyAnalyzer.cs",
        "//src/libraries/System.Collections.Immutable:src/Validation/Requires.cs",
        "//src/libraries/Common/tests:System/Collections/CollectionAsserts.cs",
        "//src/libraries/Common/tests:System/Collections/DelegateEqualityComparer.cs",
        "//src/libraries/Common/tests:System/Collections/ICollection.NonGeneric.Tests.cs",
        "//src/libraries/Common/tests:System/Collections/ICollection.Generic.Tests.cs",
        "//src/libraries/Common/tests:System/Collections/IDictionary.NonGeneric.Tests.cs",
        "//src/libraries/Common/tests:System/Collections/IDictionary.Generic.Tests.cs",
        "//src/libraries/Common/tests:System/Collections/IEnumerable.NonGeneric.Tests.cs",
        "//src/libraries/Common/tests:System/Collections/IEnumerable.Generic.Tests.cs",
        "//src/libraries/Common/tests:System/Collections/IList.NonGeneric.Tests.cs",
        "//src/libraries/Common/tests:System/Collections/IList.Generic.Tests.cs",
        "//src/libraries/Common/tests:System/Collections/IGenericSharedAPI.Tests.cs",
        "//src/libraries/Common/tests:System/Collections/ISet.Generic.Tests.cs",
        "//src/libraries/Common/tests:System/Collections/TestBase.NonGeneric.cs",
        "//src/libraries/Common/tests:System/Collections/TestBase.Generic.cs",
        "//src/libraries/Common/tests:System/Collections/DebugView.Tests.cs",
        "//src/libraries/Common/tests:System/Collections/TestingTypes.cs",
        "//src/libraries/Common/tests:System/Diagnostics/DebuggerAttributes.cs",
        "//src/libraries/Common/tests:System/ShouldNotBeInvokedException.cs",
    ],
    deps = [
        "//src/libraries/System.Collections.Immutable:impl_System.Collections.Immutable",
        "//src/libraries/System.Collections.Concurrent:ref_System.Collections.Concurrent",
        "//src/libraries/System.Net.Primitives:ref_System.Net.Primitives",
        "//src/libraries/System.Reflection.Emit:ref_System.Reflection.Emit",
        "//src/libraries/System.Reflection.Emit.ILGeneration:ref_System.Reflection.Emit.ILGeneration",
        "//src/libraries/System.Reflection.Primitives:ref_System.Reflection.Primitives",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/Common/tests:TestUtilities",
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//microsoft.dotnet.xunitextensions",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    allow_unsafe_blocks = True,
    nowarn = ["CS0436"],
    size = "large",
    keyfile = "@nuget.microsoft.dotnet.arcade.sdk.v10.0.0-beta.26102.102//:tools/snk/Open.snk",
)
