load("//src/tests:live_test.bzl", "coreclr_test")

coreclr_test(
    name = "NG_Standard",
    srcs = [
        "common.cs",
        "ng_standard.cs",
    ],
    pri = 1,
    deps = [
        "//src/tests/Common:TestLibrary",
        "@paket.main//microsoft.dotnet.xunitextensions",
    ],
    size = "medium",
)

coreclr_test(
    name = "NegativeGenerics",
    srcs = ["negativegenerics.cs"],
    pri = 1,
    deps = [
        "//src/tests/Common:TestLibrary",
        "@paket.main//microsoft.dotnet.xunitextensions",
    ],
    size = "medium",
)
