load("//src/libraries:defs.bzl", "netcoreapp_ref_assembly", "netcoreapp_impl_assembly")

netcoreapp_ref_assembly(
    name = "ref_System.Net.Sockets",
    srcs = [
        "ref/System.Net.Sockets.cs",
    ],
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Net.Primitives:ref_System.Net.Primitives",
    ],
)

netcoreapp_impl_assembly(
    name = "impl_System.Net.Sockets",
    com_interface_generator = True,
    nowarn = ["CS1591"],
    os_targeted = "unix",
    srcs = glob(
        ["src/System/**/*.cs"],
        exclude = [
            "src/System/Net/Sockets/DynamicWinsockMethods.cs",
            "src/System/Net/Sockets/IOControlKeepAlive.Windows.cs",
            "src/System/Net/Sockets/SafeSocketHandle.Unix.cs",
            "src/System/Net/Sockets/SafeSocketHandle.Unix.OptionTracking.cs",
            "src/System/Net/Sockets/SafeSocketHandle.Windows.cs",
            "src/System/Net/Sockets/Socket.Unix.cs",
            "src/System/Net/Sockets/Socket.Windows.cs",
            "src/System/Net/Sockets/SocketAsyncContext.Unix.cs",
            "src/System/Net/Sockets/SocketAsyncContext.Wasi.cs",
            "src/System/Net/Sockets/SocketAsyncEngine.Unix.cs",
            "src/System/Net/Sockets/SocketAsyncEngine.Wasi.cs",
            "src/System/Net/Sockets/SocketAsyncEventArgs.Unix.cs",
            "src/System/Net/Sockets/SocketAsyncEventArgs.Windows.cs",
            "src/System/Net/Sockets/SocketPal.Unix.cs",
            "src/System/Net/Sockets/SocketPal.Wasi.cs",
            "src/System/Net/Sockets/SocketPal.Windows.cs",
            "src/System/Net/Sockets/UnixDomainSocketEndPoint.Unix.cs",
            "src/System/Net/Sockets/UnixDomainSocketEndPoint.Wasi.cs",
            "src/System/Net/Sockets/UnixDomainSocketEndPoint.Windows.cs",
        ],
    ) + [
        # Common sources
        "//src/libraries/Common:src/DisableRuntimeMarshalling.cs",
        "//src/libraries/Common:src/System/Net/Logging/NetEventSource.Common.cs",
        "//src/libraries/Common:src/System/Net/Logging/NetEventSource.Common.DumpBuffer.cs",
        "//src/libraries/Common:src/System/Net/InternalException.cs",
        "//src/libraries/Common:src/System/Net/DebugSafeHandleMinusOneIsInvalid.cs",
        "//src/libraries/Common:src/System/Net/IPEndPointExtensions.cs",
        "//src/libraries/Common:src/System/Net/IPEndPointStatics.cs",
        "//src/libraries/Common:src/System/Net/IPAddressParserStatics.cs",
        "//src/libraries/Common:src/System/Net/ExceptionCheck.cs",
        "//src/libraries/Common:src/System/Net/RangeValidationHelpers.cs",
        "//src/libraries/Common:src/System/Net/TcpValidationHelpers.cs",
        "//src/libraries/Common:src/System/Net/SocketAddressExtensions.cs",
        "//src/libraries/Common:src/System/Net/SocketProtocolSupportPal.cs",
        "//src/libraries/Common:src/System/LocalAppContextSwitches.Common.cs",
        "//src/libraries/Common:src/System/Net/LocalAppContextSwitches.Net.cs",
        "//src/libraries/Common:src/System/Net/Sockets/SocketExceptionFactory.cs",
        "//src/libraries/Common:src/System/Net/Sockets/ProtocolFamily.cs",
        "//src/libraries/Common:src/System/Net/Sockets/ProtocolType.cs",
        "//src/libraries/Common:src/System/Net/Sockets/SocketType.cs",
    ] + select({
        "@platforms//os:linux": [
            # Unix-only src files (unix, not wasi)
            "src/System/Net/Sockets/UnixDomainSocketEndPoint.Unix.cs",
            "src/System/Net/Sockets/SocketAsyncEngine.Unix.cs",
            # Unix shared src files (unix + wasi)
            "src/System/Net/Sockets/SafeSocketHandle.Unix.cs",
            "src/System/Net/Sockets/SafeSocketHandle.Unix.OptionTracking.cs",
            "src/System/Net/Sockets/Socket.Unix.cs",
            "src/System/Net/Sockets/SocketAsyncContext.Unix.cs",
            "src/System/Net/Sockets/SocketAsyncEventArgs.Unix.cs",
            "src/System/Net/Sockets/SocketPal.Unix.cs",
            # Unix Common files
            "//src/libraries/Common:src/System/Net/InteropIPAddressExtensions.Unix.cs",
            "//src/libraries/Common:src/System/Net/SocketAddressPal.Unix.cs",
            "//src/libraries/Common:src/System/Net/SocketProtocolSupportPal.Unix.cs",
            "//src/libraries/Common:src/System/Net/Sockets/SocketErrorPal.Unix.cs",
            "//src/libraries/Common:src/System/Net/Sockets/SocketExceptionFactory.Unix.cs",
            "//src/libraries/Common:src/Interop/Unix/Interop.Errors.cs",
            "//src/libraries/Common:src/Interop/Unix/Interop.Libraries.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Accept.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Bind.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Close.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Connect.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Fcntl.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Disconnect.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.GetBytesAvailable.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.GetDomainSocketSizes.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.GetMaximumAddressSize.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.GetPeerName.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.GetSocketErrorOption.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.GetSocketType.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.GetSockName.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.GetSockOpt.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.IPAddress.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.IPPacketInformation.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.LingerOption.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.SendFile.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.SetSendTimeout.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.SetReceiveTimeout.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Stat.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Listen.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.IOVector.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.MessageHeader.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.MulticastOption.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Poll.cs",
            "//src/libraries/Common:src/Interop/Unix/Interop.Poll.Structs.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.PlatformSocketSupport.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Read.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Receive.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.ReceiveMessage.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Send.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Select.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.SendMessage.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.SetSockOpt.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Shutdown.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Socket.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.SocketAddress.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Pipe.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Write.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.SocketEvent.cs",
        ],
        "@platforms//os:macos": [
            # Unix-only src files (unix, not wasi)
            "src/System/Net/Sockets/UnixDomainSocketEndPoint.Unix.cs",
            "src/System/Net/Sockets/SocketAsyncEngine.Unix.cs",
            # Unix shared src files (unix + wasi)
            "src/System/Net/Sockets/SafeSocketHandle.Unix.cs",
            "src/System/Net/Sockets/SafeSocketHandle.Unix.OptionTracking.cs",
            "src/System/Net/Sockets/Socket.Unix.cs",
            "src/System/Net/Sockets/SocketAsyncContext.Unix.cs",
            "src/System/Net/Sockets/SocketAsyncEventArgs.Unix.cs",
            "src/System/Net/Sockets/SocketPal.Unix.cs",
            # Unix Common files (shared with Linux)
            "//src/libraries/Common:src/System/Net/InteropIPAddressExtensions.Unix.cs",
            "//src/libraries/Common:src/System/Net/SocketAddressPal.Unix.cs",
            "//src/libraries/Common:src/System/Net/SocketProtocolSupportPal.Unix.cs",
            "//src/libraries/Common:src/System/Net/Sockets/SocketErrorPal.Unix.cs",
            "//src/libraries/Common:src/System/Net/Sockets/SocketExceptionFactory.Unix.cs",
            "//src/libraries/Common:src/Interop/Unix/Interop.Errors.cs",
            "//src/libraries/Common:src/Interop/Unix/Interop.Libraries.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Accept.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Bind.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Close.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Connect.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Fcntl.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Disconnect.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.GetBytesAvailable.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.GetDomainSocketSizes.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.GetMaximumAddressSize.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.GetPeerName.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.GetSocketErrorOption.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.GetSocketType.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.GetSockName.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.GetSockOpt.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.IPAddress.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.IPPacketInformation.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.LingerOption.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.SendFile.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.SetSendTimeout.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.SetReceiveTimeout.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Stat.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Listen.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.IOVector.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.MessageHeader.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.MulticastOption.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Poll.cs",
            "//src/libraries/Common:src/Interop/Unix/Interop.Poll.Structs.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.PlatformSocketSupport.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Read.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Receive.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.ReceiveMessage.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Send.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Select.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.SendMessage.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.SetSockOpt.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Shutdown.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Socket.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.SocketAddress.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Pipe.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Write.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.SocketEvent.cs",
        ],
    }),
    resx_file = "src/Resources/Strings.resx",
    allow_unsafe_blocks = True,
    defines = ["SYSTEM_NET_SOCKETS_DLL"] + select({
        "@platforms//os:macos": ["SYSTEM_NET_SOCKETS_APPLE_PLATFROM"],
        "//conditions:default": [],
    }),
    deps = [
        "//src/libraries:ref_Microsoft.Win32.Primitives",
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Collections:ref_System.Collections",
        "//src/libraries/System.Collections.Concurrent:ref_System.Collections.Concurrent",
        "//src/libraries/System.Diagnostics.DiagnosticSource:ref_System.Diagnostics.DiagnosticSource",
        "//src/libraries/System.Diagnostics.Tracing:ref_System.Diagnostics.Tracing",
        "//src/libraries/System.Memory:ref_System.Memory",
        "//src/libraries/System.Net.NameResolution:ref_System.Net.NameResolution",
        "//src/libraries/System.Net.Primitives:ref_System.Net.Primitives",
        "//src/libraries/System.Runtime.InteropServices:ref_System.Runtime.InteropServices",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/System.Threading.Overlapped:ref_System.Threading.Overlapped",
        "//src/libraries/System.Threading.Thread:ref_System.Threading.Thread",
        "//src/libraries/System.Threading.ThreadPool:ref_System.Threading.ThreadPool",
    ],
    supported_os_platforms = ["unix"],
)
