load("//src/tests:live_test.bzl", "coreclr_test")

coreclr_test(
    name = "ProfileCastClassAndIsInst",
    srcs = ["ProfileCastClassAndIsInst.cs"],
    optimize = True,
    deps = [
        "//src/libraries/System.Threading.Thread:ref_System.Threading.Thread",
        "//src/libraries/System.Threading:ref_System.Threading",
    ],
)

coreclr_test(
    name = "ProfileCastClassAndIsInst_random3",
    srcs = ["ProfileCastClassAndIsInst.cs"],
    optimize = True,
    deps = [
        "//src/libraries/System.Threading.Thread:ref_System.Threading.Thread",
        "//src/libraries/System.Threading:ref_System.Threading",
    ],
)

coreclr_test(
    name = "ProfileCastClassAndIsInst_random2",
    srcs = ["ProfileCastClassAndIsInst.cs"],
    optimize = True,
    deps = [
        "//src/libraries/System.Threading.Thread:ref_System.Threading.Thread",
        "//src/libraries/System.Threading:ref_System.Threading",
    ],
)

coreclr_test(
    name = "ProfileCastClassAndIsInst_random1",
    srcs = ["ProfileCastClassAndIsInst.cs"],
    optimize = True,
    deps = [
        "//src/libraries/System.Threading.Thread:ref_System.Threading.Thread",
        "//src/libraries/System.Threading:ref_System.Threading",
    ],
)
