load("//src/tests:live_test.bzl", "il_coreclr_test")

il_coreclr_test(
    name = "initobj_unaligned_1",
    srcs = ["initobj.il"],
    pri = 1,
    debug_type = "pdbonly",
    optimize = True,
)

il_coreclr_test(
    name = "add_unaligned_1",
    srcs = ["add.il"],
    pri = 1,
)

il_coreclr_test(
    name = "Box_Unbox_unaligned_1",
    srcs = ["Box_Unbox.il"],
    pri = 1,
    debug_type = "pdbonly",
    optimize = True,
)

il_coreclr_test(
    name = "localloc_unaligned_1",
    srcs = ["localloc.il"],
    pri = 1,
    debug_type = "pdbonly",
    optimize = True,
)

il_coreclr_test(
    name = "cpblk_unaligned_1",
    srcs = ["cpblk.il"],
    pri = 1,
    debug_type = "pdbonly",
    optimize = True,
)

il_coreclr_test(
    name = "array_tests_unaligned_1",
    srcs = ["array_tests.il"],
    pri = 1,
    debug_type = "pdbonly",
    optimize = True,
)

il_coreclr_test(
    name = "cpobj_unaligned_1",
    srcs = ["cpobj.il"],
    pri = 1,
    debug_type = "pdbonly",
    optimize = True,
)

il_coreclr_test(
    name = "field_tests_unaligned_1",
    srcs = ["field_tests.il"],
    pri = 1,
    debug_type = "pdbonly",
    optimize = True,
)

il_coreclr_test(
    name = "fielda_tests_unaligned_1",
    srcs = ["fielda_tests.il"],
    pri = 1,
    debug_type = "pdbonly",
    optimize = True,
)

il_coreclr_test(
    name = "ldind_stind_unaligned_1",
    srcs = ["ldind_stind.il"],
    pri = 1,
    debug_type = "pdbonly",
    optimize = True,
)

il_coreclr_test(
    name = "ldobj_unaligned_1",
    srcs = ["ldobj.il"],
    pri = 1,
    debug_type = "pdbonly",
    optimize = True,
)

il_coreclr_test(
    name = "ldloca_unaligned_1",
    srcs = ["ldloca.il"],
    pri = 1,
    debug_type = "pdbonly",
    optimize = True,
)

il_coreclr_test(
    name = "initblk_unaligned_1",
    srcs = ["initblk.il"],
    pri = 1,
    debug_type = "pdbonly",
    optimize = True,
)
