load("//src/tests:live_test.bzl", "library_test")

library_test(
    name = "System.Collections.Specialized.Tests",
    srcs = glob(["**/*.cs"]) + [
        "//src/libraries/Common/tests:System/Collections/CollectionAsserts.cs",
        "//src/libraries/Common/tests:System/Collections/ICollection.NonGeneric.Tests.cs",
        "//src/libraries/Common/tests:System/Collections/IDictionary.NonGeneric.Tests.cs",
        "//src/libraries/Common/tests:System/Collections/IEnumerable.NonGeneric.Tests.cs",
        "//src/libraries/Common/tests:System/Collections/IEnumerable.NonGeneric.Serialization.Tests.cs",
        "//src/libraries/Common/tests:System/Collections/TestBase.NonGeneric.cs",
        "//src/libraries/Common/tests:System/Collections/TestingTypes.cs",
        "//src/libraries/Common/tests:System/Diagnostics/DebuggerAttributes.cs",
        "//src/libraries/Common/tests:System/Runtime/Serialization/Formatters/BinaryFormatterHelpers.cs",
    ],
    deps = [
        "//src/libraries/System.Runtime.Serialization.Formatters:impl_System.Runtime.Serialization.Formatters",
        "//src/libraries/System.Collections.Concurrent:ref_System.Collections.Concurrent",
        "//src/libraries/System.Collections.Immutable:ref_System.Collections.Immutable",
        "//src/libraries/Common/tests:TestUtilities",
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//microsoft.dotnet.xunitextensions",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    nowarn = [
        "SYSLIB0011",
        "SYSLIB0050",
        "SYSLIB0051",
    ],
    size = "large",
    keyfile = "@nuget.microsoft.dotnet.arcade.sdk.v10.0.0-beta.26102.102//:tools/snk/Open.snk",
)
