load("//src/libraries:defs.bzl", "netcoreapp_impl_assembly")

netcoreapp_impl_assembly(
    name = "impl_System.Drawing",
    srcs = [
        "src/System.Drawing.cs",
    ],
    deps = [
        "//src/libraries/System.ComponentModel.TypeConverter:ref_System.ComponentModel.TypeConverter",
        "//src/libraries/System.Drawing.Primitives:ref_System.Drawing.Primitives",
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/shims/stubs:ref_System.Configuration.ConfigurationManager",
        "//src/libraries/shims/stubs:ref_System.Drawing.Common",
        "//src/libraries/shims/stubs:ref_System.Security.Permissions",
    ],
    exclude_sr = True,
)
