load("//src/tests:live_test.bzl", "coreclr_test")

coreclr_test(
    name = "Sve_r",
    srcs = [
        "Program.Sve.cs",
        "//src/tests/JIT/HardwareIntrinsics/Arm/Shared:Helpers.cs",
        "//src/tests/JIT/HardwareIntrinsics/Arm/Shared:Program.cs",
    ],
    tags = ["manual"],  # Needs additional deps not yet available
)

coreclr_test(
    name = "Sve_ro",
    srcs = [
        "Program.Sve.cs",
        "//src/tests/JIT/HardwareIntrinsics/Arm/Shared:Helpers.cs",
        "//src/tests/JIT/HardwareIntrinsics/Arm/Shared:Program.cs",
    ],
    optimize = True,
    tags = ["manual"],  # Needs additional deps not yet available
)
