load("//src/tests:live_test.bzl", "il_coreclr_test")

il_coreclr_test(
    name = "dynblk_order_r",
    srcs = ["dynblk_order_r.il", "dynblk_order.il"],
    pri = 1,
    debug_type = "pdbonly",
    optimize = True,
)

il_coreclr_test(
    name = "initblk3_r",
    srcs = ["initblk3_r.il", "initblk3.il"],
    debug_type = "pdbonly",
)

il_coreclr_test(
    name = "cpblk3_d",
    srcs = ["cpblk3_d.il", "cpblk3.il"],
    pri = 1,
    debug_type = "full",
)

il_coreclr_test(
    name = "initblk3_d",
    srcs = ["initblk3_d.il", "initblk3.il"],
    debug_type = "full",
)

il_coreclr_test(
    name = "cpblk3_r",
    srcs = ["cpblk3_r.il", "cpblk3.il"],
    pri = 1,
    debug_type = "pdbonly",
)

il_coreclr_test(
    name = "dynblk_order_d",
    srcs = ["dynblk_order_d.il", "dynblk_order.il"],
    pri = 1,
    debug_type = "full",
)

il_coreclr_test(
    name = "dynblk_r",
    srcs = ["dynblk_r.il", "dynblk.il"],
    debug_type = "pdbonly",
)

il_coreclr_test(
    name = "dynblk_d",
    srcs = ["dynblk_d.il", "dynblk.il"],
    debug_type = "full",
)
