load("//src/tests:live_test.bzl", "library_test")

library_test(
    name = "System.ObjectModel.Tests",
    srcs = glob(
        ["**/*.cs"],
        exclude = ["TrimmingTests/**"],
    ) + [
        "//src/libraries/Common/tests:System/Collections/IEnumerableTest.cs",
        "//src/libraries/Common/tests:System/Collections/ICollectionTest.cs",
        "//src/libraries/Common/tests:System/Collections/IListTest.cs",
        "//src/libraries/Common/tests:System/Collections/IDictionaryTest.cs",
        "//src/libraries/Common/tests:System/Collections/Utils.cs",
        "//src/libraries/Common/tests:System/ShouldNotBeInvokedException.cs",
        "//src/libraries/Common/tests:System/Diagnostics/DebuggerAttributes.cs",
        "//src/libraries/Common/tests:System/Runtime/Serialization/Formatters/BinaryFormatterHelpers.cs",
    ],
    deps = [
        "//src/libraries/System.ObjectModel:impl_System.ObjectModel",
        "//src/libraries/System.Runtime.Serialization.Formatters:impl_System.Runtime.Serialization.Formatters",
        "//src/libraries/System.Collections.Concurrent:ref_System.Collections.Concurrent",
        "//src/libraries/System.Collections.Immutable:ref_System.Collections.Immutable",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries:ref_System.Threading.Tasks",
        "//src/libraries/Common/tests:TestUtilities",
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//microsoft.dotnet.xunitextensions",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    size = "large",
    nowarn = ["SYSLIB0011", "SYSLIB0050", "SYSLIB0051"],
    keyfile = "@nuget.microsoft.dotnet.arcade.sdk.v10.0.0-beta.26102.102//:tools/snk/Open.snk",
)
