load("//src/tests:live_test.bzl", "library_test")
load("//:defs.bzl", "OPEN_SNK")

library_test(
    name = "System.Linq.Tests",
    srcs = glob(
        ["*.cs"],
        exclude = [
            # Not compiled by MSBuild test project
            "CreateOrderedEnumerableTests.cs",
        ],
    ) + [
        "//src/libraries/Common/tests:System/Linq/SkipTakeData.cs",
        "//src/libraries/Common/tests:System/Diagnostics/DebuggerAttributes.cs",
    ],
    deps = [
        "//src/libraries/System.Collections.Concurrent:ref_System.Collections.Concurrent",
        "//src/libraries/System.Collections.Immutable:ref_System.Collections.Immutable",
        "//src/libraries:ref_System.Linq.Expressions",
        "//src/libraries/System.Linq.Queryable:ref_System.Linq.Queryable",
        "//src/libraries/System.Runtime.Numerics:ref_System.Runtime.Numerics",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/Common/tests:TestUtilities",
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//microsoft.dotnet.xunitextensions",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    size = "large",
    keyfile = OPEN_SNK,
)
