load("//src/libraries:defs.bzl", "live_csharp_library")
load("//:defs.bzl", "ASPNETCORE_SNK")

live_csharp_library(
    name = "Microsoft.Extensions.DependencyInjection.Specification.Tests",
    srcs = glob(["**/*.cs"]),
    analyzers = [
        "//:source_build_analyzers",
        "//src/tools/illink/src/ILLink.RoslynAnalyzer",
        "//src/libraries/System.Runtime.InteropServices:ComInterfaceGenerator",
        "//src/libraries/System.Runtime.InteropServices.JavaScript:JSImportGenerator",
        "//src/libraries/System.Runtime.InteropServices:LibraryImportGenerator",
        "//src/libraries/System.Runtime.InteropServices:Microsoft.Interop.SourceGeneration",
        "//src/libraries/System.Text.Json:JsonSourceGenerator",
        "//src/libraries/System.Text.RegularExpressions:RegexGenerator",
    ],
    deps = [
        "//src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions:ref_Microsoft.Extensions.DependencyInjection.Abstractions",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/System.Collections.Concurrent:ref_System.Collections.Concurrent",
        "//src/libraries/System.Collections.Immutable:ref_System.Collections.Immutable",
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//xunit.extensibility.core",
    ],
    generate_documentation_file = True,
    interceptors_namespaces = ";Microsoft.Extensions.Validation.Generated",
    msbuild_analyzer_config = "source",
    nullable = "disable",
    nowarn = ["CA1510", "CA1511", "CA1512", "CA1513", "CA1845", "CA1846", "CA1847", "CA1852", "1591", "CP0003", "nullable"],
    treat_warnings_as_errors = True,
    warnings_not_as_errors = ["NU1901", "NU1902", "NU1903", "NU1904"],
    visibility = ["//visibility:public"],
    keyfile = ASPNETCORE_SNK,
)
