#ifndef PAL_CONFIG_H_INCLUDED
#define PAL_CONFIG_H_INCLUDED

#define HAVE_VM_FLAGS_SUPERPAGE_SIZE_ANY 0
#define HAVE_MAP_HUGETLB 0
#define HAVE_SYS_VMPARAM_H 1
#define HAVE_MACH_VM_TYPES_H 1
#define HAVE_MACH_VM_PARAM_H 1
#define HAVE_MACHINE_NPX_H 0
#define HAVE_MACHINE_REG_H 0
#define HAVE_MACHINE_VMPARAM_H 1
#define HAVE_PROCFS_H 0
#define HAVE_CRT_EXTERNS_H 1
#define HAVE_SYS_TIME_H 1
#define HAVE_PTHREAD_NP_H 0
#define HAVE_SYS_MEMBARRIER_H 0
#define HAVE_SYS_LWP_H 0
#define HAVE_LWP_H 0
#define HAVE_RUNETYPE_H 1
#define HAVE_GNU_LIBNAMES_H 0
#define HAVE_PRCTL_H 0
#define HAVE_AUXV_HWCAP_H 0
#define HAVE_SYS_PTRACE_H 1
#define HAVE_SYS_UCONTEXT_H 1
#define HAVE_SYS_MOUNT_H 1
#define HAVE_UCONTEXT_H 1
#define HAVE_GETAUXVAL 0

#define HAVE_KQUEUE 1
#define HAVE_PTHREAD_ATTR_GET_NP 0
#define HAVE_PTHREAD_GETATTR_NP 0
#define HAVE_PTHREAD_GETCPUCLOCKID 0
#define HAVE_PTHREAD_GETAFFINITY_NP 0
#define HAVE_CPUSET_T 0
#define HAVE_FSYNC 1
#define HAVE_FUTIMES 1
#define HAVE_SYSCTL 1
#define HAVE_SYSCTLBYNAME 1
#define HAVE_SYSCONF 1
#define HAVE_GMTIME_R 1
#define HAVE_POLL 1
#define HAVE_STATVFS 1
#define HAVE_NON_LEGACY_STATFS 1
#define HAVE_THREAD_SELF 0
#define HAVE__LWP_SELF 0
#define HAVE_MACH_THREADS 1
#define HAVE_MACH_EXCEPTIONS 1
#define HAVE_SIGALTSTACK 1
#define HAVE_VM_ALLOCATE 1
#define HAVE_VM_READ 1
#define HAVE_DIRECTIO 0
#define HAVE_SEMAPHORE_H 1
#define HAS_SYSV_SEMAPHORES 1
#define HAS_PTHREAD_MUTEXES 1
/* #undef HAVE_TTRACE */
#define HAVE_PIPE2 0
#define HAVE_SCHED_GETAFFINITY 0
#define HAVE_SCHED_SETAFFINITY 0
/* #undef HAVE_UNW_GET_SAVE_LOC */
/* #undef HAVE_UNW_GET_ACCESSORS */
#define HAVE_PUBLIC_XSTATE_STRUCT 0
#define HAVE__FPX_SW_BYTES_WITH_XSTATE_BV 0
#define HAVE_PR_SET_PTRACER 0

#define HAVE_BSD_REGS_T 0
#define HAVE_PT_REGS 0
#define HAVE_GREGSET_T 0
#define HAVE___GREGSET_T 0
#define HAVE_FPSTATE_GLIBC_RESERVED1 0
#define HAVE_UCONTEXT_T 1
#define SIZEOF_OFF_T 8
#define HAVE_FPREGS_WITH_CW 0

#define HAVE_YIELD_SYSCALL 0
#define HAVE_INFTIM 0
#define USER_H_DEFINES_DEBUG 0
#define HAVE__SC_PHYS_PAGES 1
#define HAVE__SC_AVPHYS_PAGES 0

#define REALPATH_SUPPORTS_NONEXISTENT_FILES 0
#define HAVE_BROKEN_FIFO_SELECT 0
#define HAVE_BROKEN_FIFO_KEVENT 0
#define UNWIND_CONTEXT_IS_UCONTEXT_T 0
#define HAVE_GET_PROC_INFO_IN_RANGE 0
#define HAVE_SCHED_GET_PRIORITY 1
#define HAVE_WORKING_GETTIMEOFDAY 1
#define HAVE_WORKING_CLOCK_GETTIME 1
#define HAVE_CLOCK_THREAD_CPUTIME 1
#define HAVE_CLOCK_MONOTONIC 1
#define HAVE_PTHREAD_CONDATTR_SETCLOCK 0
#define MMAP_ANON_IGNORES_PROTECTION 0
#define ONE_SHARED_MAPPING_PER_FILEREGION_PER_PROCESS 0
#define PTHREAD_CREATE_MODIFIES_ERRNO 0
#define SEM_INIT_MODIFIES_ERRNO 0
#define HAVE_PROCFS_CTL 0
#define HAVE_PROCFS_STAT 0
#define HAS_POSIX_SEMAPHORES 0

#define PAL_THREAD_PRIORITY_MIN 0
#define PAL_THREAD_PRIORITY_MAX 0

#define HAVE__NSGETENVIRON 1
#define DEADLOCK_WHEN_THREAD_IS_SUSPENDED_WHILE_BLOCKED_ON_MUTEX 1
#define PAL_PTRACE(cmd, pid, addr, data) ptrace((cmd), (pid), (caddr_t)(addr), (data))
#define SYNCHMGR_SUSPENSION_SAFE_CONDITION_SIGNALING 1
#define ERROR_FUNC_FOR_GLOB_HAS_FIXED_PARAMS 1
#define HAVE_FULLY_FEATURED_PTHREAD_MUTEXES 0
#define HAVE_FUNCTIONAL_PTHREAD_ROBUST_MUTEXES 0
/* #undef BSD_REGS_STYLE */
#define HAVE_SCHED_OTHER_ASSIGNABLE 1
#define SET_SCHEDPARAM_NEEDS_PRIVS 0

#define CHECK_TRACE_SPECIFIERS 0
#define OPEN64_IS_USED_INSTEAD_OF_OPEN 0
#define PAL_IGNORE_NORMAL_THREAD_PRIORITY 0
#define SELF_SUSPEND_FAILS_WITH_NATIVE_SUSPENSION 0
#define SIGWAIT_FAILS_WHEN_PASSED_FULL_SIGSET 0
#define WRITE_0_BYTES_HANGS_TTY 0
#define HAVE_FTRUNCATE_LARGE_LENGTH_SUPPORT 1

#endif // PAL_CONFIG_H_INCLUDED
