load("//src/tests:live_test.bzl", "il_coreclr_test")

il_coreclr_test(
    name = "refarg_box_val_d",
    srcs = ["refarg_box_val_d.il", "refarg_box_val.il"],
    pri = 1,
    debug_type = "full",
)

il_coreclr_test(
    name = "refarg_box_val_r",
    srcs = ["refarg_box_val_r.il", "refarg_box_val.il"],
    pri = 1,
    debug_type = "pdbonly",
)

il_coreclr_test(
    name = "refarg_box_f8_d",
    srcs = ["refarg_box_f8_d.il", "refarg_box_f8.il"],
    debug_type = "full",
)

il_coreclr_test(
    name = "refarg_box_f8_r",
    srcs = ["refarg_box_f8_r.il", "refarg_box_f8.il"],
    debug_type = "pdbonly",
)
