load("//src/libraries:defs.bzl", "COMMON_GENERATOR_ANALYZERS", "MULTITARGET_NOWARN", "netcoreapp_ref_assembly", "impl_assembly", "ref_impl_pair")

exports_files([
    "ref/Microsoft.Extensions.Options.DataAnnotations.cs",
])

netcoreapp_ref_assembly(
    name = "ref_Microsoft.Extensions.Options.DataAnnotations",
    srcs = [
        "ref/Microsoft.Extensions.Options.DataAnnotations.cs",
    ],
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions:ref_Microsoft.Extensions.DependencyInjection.Abstractions",
        "//src/libraries/Microsoft.Extensions.Options:ref_Microsoft.Extensions.Options",
    ],
)

impl_assembly(
    name = "impl_Microsoft.Extensions.Options.DataAnnotations",
    include_runtime_async = False,
    event_source_generator = False,
    analyzers = COMMON_GENERATOR_ANALYZERS,
    nowarn = MULTITARGET_NOWARN + ["CP0003"],
    exclude_sr = True,
    srcs = glob(["src/**/*.cs"]),
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions:ref_Microsoft.Extensions.DependencyInjection.Abstractions",
        "//src/libraries/Microsoft.Extensions.Options:ref_Microsoft.Extensions.Options",
        "//src/libraries/System.Collections:ref_System.Collections",
        "//src/libraries/System.ComponentModel:ref_System.ComponentModel",
        "//src/libraries/System.ComponentModel.Annotations:ref_System.ComponentModel.Annotations",
        "//src/libraries/System.Linq:ref_System.Linq",
    ],
)

ref_impl_pair(
    name = "live_Microsoft.Extensions.Options.DataAnnotations",
    ref = ":ref_Microsoft.Extensions.Options.DataAnnotations",
    lib = ":impl_Microsoft.Extensions.Options.DataAnnotations",
    visibility = ["//visibility:public"],
)
