load("//src/libraries:defs.bzl", "netcoreapp_impl_assembly")
load("//:defs.bzl", "OPEN_SNK")

exports_files([
    "src/ILLink/ILLink.Descriptors.LibraryBuild.xml",
    "src/Utils/DTDs/XHTML10/no_comments/xhtml1-frameset.dtd",
    "src/Utils/DTDs/XHTML10/no_comments/xhtml1-strict.dtd",
    "src/Utils/DTDs/XHTML10/no_comments/xhtml1-transitional.dtd",
    "src/Utils/DTDs/XHTML10/no_comments/xhtml-lat1.ent",
    "src/Utils/DTDs/XHTML10/no_comments/xhtml-special.ent",
    "src/Utils/DTDs/XHTML10/no_comments/xhtml-symbol.ent",
    "src/Utils/DTDs/RSS091/no_comments/rss-0.91.dtd",
])

netcoreapp_impl_assembly(
    name = "impl_System.Private.Xml",
    keyfile = OPEN_SNK,
    com_interface_generator = True,
    nowarn = ["CS1591"],
    srcs = [
        # Common files (from $(CommonPath))
        "//src/libraries/Common:src/System/Text/StringBuilderCache.cs",
        "//src/libraries/Common:src/System/HexConverter.cs",
        "//src/libraries/Common:src/System/LocalAppContextSwitches.Common.cs",
        "//src/libraries/Common:src/System/CSharpHelpers.cs",
        "//src/libraries/Common:src/System/Text/ValueStringBuilder.cs",
        "//src/libraries/Common:src/System/Text/ValueStringBuilder.AppendSpanFormattable.cs",
        "//src/libraries/Common:src/System/Obsoletions.cs",

        # BinaryXml
        "src/System/Xml/BinaryXml/XmlBinaryReader.cs",
        "src/System/Xml/BinaryXml/BinXmlToken.cs",
        "src/System/Xml/BinaryXml/SqlUtils.cs",

        # Misc
        "src/Misc/HResults.cs",

        # System.Xml base types
        "src/System/Xml/AsyncHelper.cs",
        "src/System/Xml/Base64Decoder.cs",
        "src/System/Xml/Base64Encoder.cs",
        "src/System/Xml/Base64EncoderAsync.cs",
        "src/System/Xml/BinHexDecoder.cs",
        "src/System/Xml/BinHexEncoder.cs",
        "src/System/Xml/BinHexEncoderAsync.cs",
        "src/System/Xml/BitStack.cs",
        "src/System/Xml/ByteStack.cs",
        "src/System/Xml/DiagnosticsSwitches.cs",
        "src/System/Xml/EmptyEnumerator.cs",
        "src/System/Xml/HWStack.cs",
        "src/System/Xml/IApplicationResourceStreamResolver.cs",
        "src/System/Xml/IHasXmlNode.cs",
        "src/System/Xml/IXmlLineInfo.cs",
        "src/System/Xml/IXmlNamespaceResolver.cs",
        "src/System/Xml/LineInfo.cs",
        "src/System/Xml/MTNameTable.cs",
        "src/System/Xml/NameTable.cs",
        "src/System/Xml/Ref.cs",
        "src/System/Xml/ValidateNames.cs",
        "src/System/Xml/XmlCharType.cs",
        "src/System/Xml/XmlComplianceUtil.cs",
        "src/System/Xml/XmlConvert.cs",
        "src/System/Xml/XmlDownloadManager.cs",
        "src/System/Xml/XmlEncoding.cs",
        "src/System/Xml/XmlException.cs",
        "src/System/Xml/XmlNamespacemanager.cs",
        "src/System/Xml/XmlNamespaceScope.cs",
        "src/System/Xml/XmlNameTable.cs",
        "src/System/Xml/XmlNodeOrder.cs",
        "src/System/Xml/XmlNodeType.cs",
        "src/System/Xml/XmlQualifiedName.cs",
        "src/System/Xml/XmlReservedNs.cs",
        "src/System/Xml/XmlResolver.cs",
        "src/System/Xml/XmlResolver.FileSystemResolver.cs",
        "src/System/Xml/XmlResolver.ThrowingResolver.cs",
        "src/System/Xml/XmlSecureResolver.cs",
        "src/System/Xml/XmlUrlResolver.cs",

        # Core
        "src/System/Xml/Core/CharEntityEncoderFallback.cs",
        "src/System/Xml/Core/ConformanceLevel.cs",
        "src/System/Xml/Core/DtdProcessing.cs",
        "src/System/Xml/Core/EntityHandling.cs",
        "src/System/Xml/Core/HtmlEncodedRawTextWriter.cs",
        "src/System/Xml/Core/HtmlUtf8RawTextWriter.cs",
        "src/System/Xml/Core/IDtdInfo.cs",
        "src/System/Xml/Core/IDtdParser.cs",
        "src/System/Xml/Core/IDtdParserAsync.cs",
        "src/System/Xml/Core/IDtdParserAdapter.cs",
        "src/System/Xml/Core/IDtdParserAdapterAsync.cs",
        "src/System/Xml/Core/IncrementalReadDecoders.cs",
        "src/System/Xml/Core/IValidationEventHandling.cs",
        "src/System/Xml/Core/LocalAppContextSwitches.cs",
        "src/System/Xml/Core/NamespaceHandling.cs",
        "src/System/Xml/Core/NewLineHandling.cs",
        "src/System/Xml/Core/IRemovableWriter.cs",
        "src/System/Xml/Core/QueryOutputWriter.cs",
        "src/System/Xml/Core/QueryOutputWriterV1.cs",
        "src/System/Xml/Core/ReadContentAsBinaryHelper.cs",
        "src/System/Xml/Core/ReadContentAsBinaryHelperAsync.cs",
        "src/System/Xml/Core/ReadOnlyTernaryTree.cs",
        "src/System/Xml/Core/ReadState.cs",
        "src/System/Xml/Core/TextEncodedRawTextWriter.cs",
        "src/System/Xml/Core/TextUtf8RawTextWriter.cs",
        "src/System/Xml/Core/ValidatingReaderNodeData.cs",
        "src/System/Xml/Core/ValidationType.cs",
        "src/System/Xml/Core/WhitespaceHandling.cs",
        "src/System/Xml/Core/XmlAsyncCheckReader.cs",
        "src/System/Xml/Core/XmlAsyncCheckWriter.cs",
        "src/System/Xml/Core/XmlAutoDetectWriter.cs",
        "src/System/Xml/Core/XmlCharCheckingReader.cs",
        "src/System/Xml/Core/XmlCharCheckingReaderAsync.cs",
        "src/System/Xml/Core/XmlCharCheckingWriter.cs",
        "src/System/Xml/Core/XmlCharCheckingWriterAsync.cs",
        "src/System/Xml/Core/XmlEncodedRawTextWriter.cs",
        "src/System/Xml/Core/XmlEncodedRawTextWriterAsync.cs",
        "src/System/Xml/Core/XmlEventCache.cs",
        "src/System/Xml/Core/XmlParserContext.cs",
        "src/System/Xml/Core/XmlRawWriter.cs",
        "src/System/Xml/Core/XmlRawWriterAsync.cs",
        "src/System/Xml/Core/XmlReader.cs",
        "src/System/Xml/Core/XmlReaderAsync.cs",
        "src/System/Xml/Core/XmlReaderSettings.cs",
        "src/System/Xml/Core/XmlSpace.cs",
        "src/System/Xml/Core/XmlSubtreeReader.cs",
        "src/System/Xml/Core/XmlSubtreeReaderAsync.cs",
        "src/System/Xml/Core/XmlTextEncoder.cs",
        "src/System/Xml/Core/XmlTextReader.cs",
        "src/System/Xml/Core/XmlTextReaderImpl.cs",
        "src/System/Xml/Core/XmlTextReaderImplAsync.cs",
        "src/System/Xml/Core/XmlTextReaderImplHelpers.cs",
        "src/System/Xml/Core/XmlTextReaderImplHelpersAsync.cs",
        "src/System/Xml/Core/XmlTextWriter.cs",
        "src/System/Xml/Core/XmlUtf8RawTextWriter.cs",
        "src/System/Xml/Core/XmlUtf8RawTextWriterAsync.cs",
        "src/System/Xml/Core/XmlValidatingReader.cs",
        "src/System/Xml/Core/XmlValidatingReaderImpl.cs",
        "src/System/Xml/Core/XmlValidatingReaderImplAsync.cs",
        "src/System/Xml/Core/XmlWellFormedWriter.cs",
        "src/System/Xml/Core/XmlWellFormedWriterAsync.cs",
        "src/System/Xml/Core/XmlWellFormedWriterHelpers.cs",
        "src/System/Xml/Core/XmlWellFormedWriterHelpersAsync.cs",
        "src/System/Xml/Core/XmlWrappingReader.cs",
        "src/System/Xml/Core/XmlWrappingReaderAsync.cs",
        "src/System/Xml/Core/XmlWrappingWriter.cs",
        "src/System/Xml/Core/XmlWrappingWriterAsync.cs",
        "src/System/Xml/Core/XmlWriter.cs",
        "src/System/Xml/Core/XmlWriterAsync.cs",
        "src/System/Xml/Core/XmlWriterSettings.cs",
        "src/System/Xml/Core/XsdValidatingReader.cs",
        "src/System/Xml/Core/XsdValidatingReaderAsync.cs",
        "src/System/Xml/Core/XsdCachingReader.cs",
        "src/System/Xml/Core/XsdCachingReaderAsync.cs",

        # Unix-specific (non-windows target)
        "src/System/Xml/Core/XmlTextReaderImpl.Unix.cs",

        # Dom
        "src/System/Xml/Dom/DocumentXmlWriter.cs",
        "src/System/Xml/Dom/DocumentXPathNavigator.cs",
        "src/System/Xml/Dom/DomNameTable.cs",
        "src/System/Xml/Dom/XmlAttribute.cs",
        "src/System/Xml/Dom/XmlAttributeCollection.cs",
        "src/System/Xml/Dom/XmlCDataSection.cs",
        "src/System/Xml/Dom/XmlCharacterData.cs",
        "src/System/Xml/Dom/XmlChildEnumerator.cs",
        "src/System/Xml/Dom/XmlChildNodes.cs",
        "src/System/Xml/Dom/XmlComment.cs",
        "src/System/Xml/Dom/XmlDeclaration.cs",
        "src/System/Xml/Dom/XmlDocument.cs",
        "src/System/Xml/Dom/XmlDocumentFragment.cs",
        "src/System/Xml/Dom/XmlDocumentType.cs",
        "src/System/Xml/Dom/DocumentSchemaValidator.cs",
        "src/System/Xml/Dom/XmlDomTextWriter.cs",
        "src/System/Xml/Dom/XmlElement.cs",
        "src/System/Xml/Dom/XmlElementList.cs",
        "src/System/Xml/Dom/XmlEntity.cs",
        "src/System/Xml/Dom/XmlEntityReference.cs",
        "src/System/Xml/Dom/XmlEventChangedAction.cs",
        "src/System/Xml/Dom/XmlImplementation.cs",
        "src/System/Xml/Dom/XmlLinkedNode.cs",
        "src/System/Xml/Dom/XmlLoader.cs",
        "src/System/Xml/Dom/XmlName.cs",
        "src/System/Xml/Dom/XmlNamedNodemap.cs",
        "src/System/Xml/Dom/XmlNamedNodeMap.SmallXmlNodeList.cs",
        "src/System/Xml/Dom/XmlNode.cs",
        "src/System/Xml/Dom/XmlNodeChangedEventArgs.cs",
        "src/System/Xml/Dom/XmlNodeChangedEventHandler.cs",
        "src/System/Xml/Dom/XmlNodeList.cs",
        "src/System/Xml/Dom/XmlNodeReader.cs",
        "src/System/Xml/Dom/XmlNotation.cs",
        "src/System/Xml/Dom/XmlProcessingInstruction.cs",
        "src/System/Xml/Dom/XmlSignificantWhiteSpace.cs",
        "src/System/Xml/Dom/XmlText.cs",
        "src/System/Xml/Dom/XmlUnspecifiedAttribute.cs",
        "src/System/Xml/Dom/XmlWhitespace.cs",
        "src/System/Xml/Dom/XPathNodeList.cs",

        # Cache (XPathDocument)
        "src/System/Xml/Cache/XPathDocumentBuilder.cs",
        "src/System/Xml/Cache/XPathDocumentIterator.cs",
        "src/System/Xml/Cache/XPathDocumentNavigator.cs",
        "src/System/Xml/Cache/XPathNode.cs",
        "src/System/Xml/Cache/XPathNodeHelper.cs",
        "src/System/Xml/Cache/XPathNodeInfoAtom.cs",

        # Resolvers
        "src/System/Xml/Resolvers/XmlKnownDtds.cs",
        "src/System/Xml/Resolvers/XmlPreloadedResolver.cs",
        "src/System/Xml/Resolvers/XmlPreloadedResolverAsync.cs",

        # XPath
        "src/System/Xml/XPath/IXPathNavigable.cs",
        "src/System/Xml/XPath/XPathDocument.cs",
        "src/System/Xml/XPath/XPathException.cs",
        "src/System/Xml/XPath/XPathExpr.cs",
        "src/System/Xml/XPath/XPathItem.cs",
        "src/System/Xml/XPath/XPathNamespaceScope.cs",
        "src/System/Xml/XPath/XPathNavigator.cs",
        "src/System/Xml/XPath/XPathNavigatorKeyComparer.cs",
        "src/System/Xml/XPath/XPathNavigatorReader.cs",
        "src/System/Xml/XPath/XPathNodeIterator.cs",
        "src/System/Xml/XPath/XPathNodeType.cs",

        # XPath Internal
        "src/System/Xml/XPath/Internal/AbsoluteQuery.cs",
        "src/System/Xml/XPath/Internal/AstNode.cs",
        "src/System/Xml/XPath/Internal/AttributeQuery.cs",
        "src/System/Xml/XPath/Internal/Axis.cs",
        "src/System/Xml/XPath/Internal/BaseAxisQuery.cs",
        "src/System/Xml/XPath/Internal/BooleanExpr.cs",
        "src/System/Xml/XPath/Internal/BooleanFunctions.cs",
        "src/System/Xml/XPath/Internal/CacheAxisQuery.cs",
        "src/System/Xml/XPath/Internal/CacheChildrenQuery.cs",
        "src/System/Xml/XPath/Internal/CacheOutputQuery.cs",
        "src/System/Xml/XPath/Internal/ChildrenQuery.cs",
        "src/System/Xml/XPath/Internal/ClonableStack.cs",
        "src/System/Xml/XPath/Internal/CompiledXPathExpr.cs",
        "src/System/Xml/XPath/Internal/ContextQuery.cs",
        "src/System/Xml/XPath/Internal/DescendantBaseQuery.cs",
        "src/System/Xml/XPath/Internal/DescendantQuery.cs",
        "src/System/Xml/XPath/Internal/DescendantoverDescendantQuery.cs",
        "src/System/Xml/XPath/Internal/DocumentorderQuery.cs",
        "src/System/Xml/XPath/Internal/EmptyQuery.cs",
        "src/System/Xml/XPath/Internal/ExtensionQuery.cs",
        "src/System/Xml/XPath/Internal/FunctionQuery.cs",
        "src/System/Xml/XPath/Internal/Filter.cs",
        "src/System/Xml/XPath/Internal/FilterQuery.cs",
        "src/System/Xml/XPath/Internal/FollowingQuery.cs",
        "src/System/Xml/XPath/Internal/FollSiblingQuery.cs",
        "src/System/Xml/XPath/Internal/ForwardPositionQuery.cs",
        "src/System/Xml/XPath/Internal/Function.cs",
        "src/System/Xml/XPath/Internal/Group.cs",
        "src/System/Xml/XPath/Internal/GroupQuery.cs",
        "src/System/Xml/XPath/Internal/IdQuery.cs",
        "src/System/Xml/XPath/Internal/IteratorFilter.cs",
        "src/System/Xml/XPath/Internal/Query.cs",
        "src/System/Xml/XPath/Internal/LogicalExpr.cs",
        "src/System/Xml/XPath/Internal/MergeFilterQuery.cs",
        "src/System/Xml/XPath/Internal/NamespaceQuery.cs",
        "src/System/Xml/XPath/Internal/NodeFunctions.cs",
        "src/System/Xml/XPath/Internal/NumberFunctions.cs",
        "src/System/Xml/XPath/Internal/NumericExpr.cs",
        "src/System/Xml/XPath/Internal/Operand.cs",
        "src/System/Xml/XPath/Internal/OperandQuery.cs",
        "src/System/Xml/XPath/Internal/Operator.cs",
        "src/System/Xml/XPath/Internal/ParentQuery.cs",
        "src/System/Xml/XPath/Internal/PrecedingQuery.cs",
        "src/System/Xml/XPath/Internal/PreSiblingQuery.cs",
        "src/System/Xml/XPath/Internal/QueryBuilder.cs",
        "src/System/Xml/XPath/Internal/UnionExpr.cs",
        "src/System/Xml/XPath/Internal/ResettableIterator.cs",
        "src/System/Xml/XPath/Internal/ReversePositionQuery.cs",
        "src/System/Xml/XPath/Internal/Root.cs",
        "src/System/Xml/XPath/Internal/SortQuery.cs",
        "src/System/Xml/XPath/Internal/StringFunctions.cs",
        "src/System/Xml/XPath/Internal/ValueQuery.cs",
        "src/System/Xml/XPath/Internal/Variable.cs",
        "src/System/Xml/XPath/Internal/VariableQuery.cs",
        "src/System/Xml/XPath/Internal/XPathAncestorIterator.cs",
        "src/System/Xml/XPath/Internal/XPathAncestorQuery.cs",
        "src/System/Xml/XPath/Internal/XPathArrayIterator.cs",
        "src/System/Xml/XPath/Internal/XPathAxisIterator.cs",
        "src/System/Xml/XPath/Internal/XPathChildIterator.cs",
        "src/System/Xml/XPath/Internal/XPathDescendantIterator.cs",
        "src/System/Xml/XPath/Internal/XPathEmptyIterator.cs",
        "src/System/Xml/XPath/Internal/XPathMultyIterator.cs",
        "src/System/Xml/XPath/Internal/XPathParser.cs",
        "src/System/Xml/XPath/Internal/XPathScanner.cs",
        "src/System/Xml/XPath/Internal/XPathSelectionIterator.cs",
        "src/System/Xml/XPath/Internal/XPathSelfQuery.cs",
        "src/System/Xml/XPath/Internal/XPathSingletonIterator.cs",

        # Xslt
        "src/System/Xml/Xslt/XslCompiledTransform.cs",
        "src/System/Xml/Xslt/XsltArgumentList.cs",
        "src/System/Xml/Xslt/XsltContext.cs",
        "src/System/Xml/Xslt/XsltException.cs",
        "src/System/Xml/Xslt/XslTransform.cs",
        "src/System/Xml/Xslt/XsltSettings.cs",

        # Schema
        "src/System/Xml/Schema/Asttree.cs",
        "src/System/Xml/Schema/AutoValidator.cs",
        "src/System/Xml/Schema/BaseProcessor.cs",
        "src/System/Xml/Schema/BaseValidator.cs",
        "src/System/Xml/Schema/BitSet.cs",
        "src/System/Xml/Schema/Chameleonkey.cs",
        "src/System/Xml/Schema/CompiledidEntityConstraint.cs",
        "src/System/Xml/Schema/SchemaSetCompiler.cs",
        "src/System/Xml/Schema/ConstraintStruct.cs",
        "src/System/Xml/Schema/ContentValidator.cs",
        "src/System/Xml/Schema/DataTypeImplementation.cs",
        "src/System/Xml/Schema/DtdParser.cs",
        "src/System/Xml/Schema/DtdParserAsync.cs",
        "src/System/Xml/Schema/DtdValidator.cs",
        "src/System/Xml/Schema/FacetChecker.cs",
        "src/System/Xml/Schema/IXmlSchemaInfo.cs",
        "src/System/Xml/Schema/NamespaceList.cs",
        "src/System/Xml/Schema/Parser.cs",
        "src/System/Xml/Schema/ParserAsync.cs",
        "src/System/Xml/Schema/Preprocessor.cs",
        "src/System/Xml/Schema/SchemaAttDef.cs",
        "src/System/Xml/Schema/SchemaBuilder.cs",
        "src/System/Xml/Schema/SchemaCollectionCompiler.cs",
        "src/System/Xml/Schema/SchemaCollectionpreProcessor.cs",
        "src/System/Xml/Schema/SchemaDeclBase.cs",
        "src/System/Xml/Schema/SchemaElementDecl.cs",
        "src/System/Xml/Schema/SchemaEntity.cs",
        "src/System/Xml/Schema/SchemaInfo.cs",
        "src/System/Xml/Schema/SchemaNames.cs",
        "src/System/Xml/Schema/SchemaNamespacemanager.cs",
        "src/System/Xml/Schema/SchemaNotation.cs",
        "src/System/Xml/Schema/SchemaType.cs",
        "src/System/Xml/Schema/ValidationEventArgs.cs",
        "src/System/Xml/Schema/ValidationEventHandler.cs",
        "src/System/Xml/Schema/ValidationState.cs",
        "src/System/Xml/Schema/XdrBuilder.cs",
        "src/System/Xml/Schema/XdrValidator.cs",
        "src/System/Xml/Schema/XmlAtomicValue.cs",
        "src/System/Xml/Schema/XmlSchema.cs",
        "src/System/Xml/Schema/XmlSchemaAll.cs",
        "src/System/Xml/Schema/XmlSchemaAnnotated.cs",
        "src/System/Xml/Schema/XmlSchemaAnnotation.cs",
        "src/System/Xml/Schema/XmlSchemaAny.cs",
        "src/System/Xml/Schema/XmlSchemaAnyAttribute.cs",
        "src/System/Xml/Schema/XmlSchemaAppInfo.cs",
        "src/System/Xml/Schema/XmlSchemaAttribute.cs",
        "src/System/Xml/Schema/XmlSchemaAttributeGroup.cs",
        "src/System/Xml/Schema/XmlSchemaAttributeGroupref.cs",
        "src/System/Xml/Schema/XmlSchemaChoice.cs",
        "src/System/Xml/Schema/XmlSchemaCollection.cs",
        "src/System/Xml/Schema/XmlSchemaComplexContent.cs",
        "src/System/Xml/Schema/XmlSchemaComplexContentExtension.cs",
        "src/System/Xml/Schema/XmlSchemaComplexContentRestriction.cs",
        "src/System/Xml/Schema/XmlSchemaComplexType.cs",
        "src/System/Xml/Schema/XmlSchemaContent.cs",
        "src/System/Xml/Schema/XmlSchemaContentModel.cs",
        "src/System/Xml/Schema/XmlSchemaContentProcessing.cs",
        "src/System/Xml/Schema/XmlSchemaContentType.cs",
        "src/System/Xml/Schema/XmlSchemaDataType.cs",
        "src/System/Xml/Schema/XmlSchemaDerivationMethod.cs",
        "src/System/Xml/Schema/XmlSchemaDocumentation.cs",
        "src/System/Xml/Schema/XmlSchemaElement.cs",
        "src/System/Xml/Schema/XmlSchemaException.cs",
        "src/System/Xml/Schema/XmlSchemaExternal.cs",
        "src/System/Xml/Schema/XmlSchemaFacet.cs",
        "src/System/Xml/Schema/XmlSchemaForm.cs",
        "src/System/Xml/Schema/XmlSchemaGroup.cs",
        "src/System/Xml/Schema/XmlSchemaGroupBase.cs",
        "src/System/Xml/Schema/XmlSchemaGroupRef.cs",
        "src/System/Xml/Schema/XmlSchemaIdEntityConstraint.cs",
        "src/System/Xml/Schema/XmlSchemaImport.cs",
        "src/System/Xml/Schema/XmlSchemaInclude.cs",
        "src/System/Xml/Schema/XmlSchemaInfo.cs",
        "src/System/Xml/Schema/XmlSchemaNotation.cs",
        "src/System/Xml/Schema/XmlSchemaObject.cs",
        "src/System/Xml/Schema/XmlSchemaObjectCollection.cs",
        "src/System/Xml/Schema/XmlSchemaObjectTable.cs",
        "src/System/Xml/Schema/XmlSchemaParticle.cs",
        "src/System/Xml/Schema/XmlSchemaRedefine.cs",
        "src/System/Xml/Schema/XmlSchemaSequence.cs",
        "src/System/Xml/Schema/XmlSchemaSet.cs",
        "src/System/Xml/Schema/XmlSchemaCompilationSettings.cs",
        "src/System/Xml/Schema/XmlSchemaSimpleContent.cs",
        "src/System/Xml/Schema/XmlSchemaSimpleContentExtension.cs",
        "src/System/Xml/Schema/XmlSchemaSimpleContentRestriction.cs",
        "src/System/Xml/Schema/XmlSchemaSimpleType.cs",
        "src/System/Xml/Schema/XmlSchemaSimpleTypeContent.cs",
        "src/System/Xml/Schema/XmlSchemaSimpleTypeList.cs",
        "src/System/Xml/Schema/XmlSchemaSimpleTypeRestriction.cs",
        "src/System/Xml/Schema/XmlSchemaSimpleTypeUnion.cs",
        "src/System/Xml/Schema/XmlSchemaSubstitutionGroup.cs",
        "src/System/Xml/Schema/XmlSchemaType.cs",
        "src/System/Xml/Schema/XmlSchemaUse.cs",
        "src/System/Xml/Schema/XmlSchemaValidationException.cs",
        "src/System/Xml/Schema/XmlSchemaValidator.cs",
        "src/System/Xml/Schema/XmlSchemaValidity.cs",
        "src/System/Xml/Schema/XmlSeverityType.cs",
        "src/System/Xml/Schema/XmlTokenizedType.cs",
        "src/System/Xml/Schema/XmlTypeCode.cs",
        "src/System/Xml/Schema/XmlValueConverter.cs",
        "src/System/Xml/Schema/XsdBuilder.cs",
        "src/System/Xml/Schema/XsdDateTime.cs",
        "src/System/Xml/Schema/XsdDuration.cs",
        "src/System/Xml/Schema/XsdValidator.cs",
        "src/System/Xml/Schema/Inference/Infer.cs",
        "src/System/Xml/Schema/Inference/XmlSchemaInferenceException.cs",

        # Serialization
        "src/System/Xml/Serialization/CodeGenerationoptions.cs",
        "src/System/Xml/Serialization/CodeGenerator.cs",
        "src/System/Xml/Serialization/CodeIdentifier.cs",
        "src/System/Xml/Serialization/CodeIdentifiers.cs",
        "src/System/Xml/Serialization/Compilation.cs",
        "src/System/Xml/Serialization/Compiler.cs",
        "src/System/Xml/Serialization/ContextAwareTables.cs",
        "src/System/Xml/Serialization/ImportContext.cs",
        "src/System/Xml/Serialization/indentedWriter.cs",
        "src/System/Xml/Serialization/IXmlSerializable.cs",
        "src/System/Xml/Serialization/IXmlTextParser.cs",
        "src/System/Xml/Serialization/Mappings.cs",
        "src/System/Xml/Serialization/Models.cs",
        "src/System/Xml/Serialization/NameTable.cs",
        "src/System/Xml/Serialization/ReflectionXmlSerializationReader.cs",
        "src/System/Xml/Serialization/ReflectionXmlSerializationWriter.cs",
        "src/System/Xml/Serialization/SchemaImporter.cs",
        "src/System/Xml/Serialization/SchemaObjectWriter.cs",
        "src/System/Xml/Serialization/SoapAttributeAttribute.cs",
        "src/System/Xml/Serialization/SoapAttributeOverrides.cs",
        "src/System/Xml/Serialization/SoapAttributes.cs",
        "src/System/Xml/Serialization/SoapElementAttribute.cs",
        "src/System/Xml/Serialization/SoapEnumAttribute.cs",
        "src/System/Xml/Serialization/SoapIgnoreAttribute.cs",
        "src/System/Xml/Serialization/SoapIncludeAttribute.cs",
        "src/System/Xml/Serialization/SoapReflectionImporter.cs",
        "src/System/Xml/Serialization/SoapSchemamember.cs",
        "src/System/Xml/Serialization/SoapTypeAttribute.cs",
        "src/System/Xml/Serialization/SourceInfo.cs",
        "src/System/Xml/Serialization/Types.cs",
        "src/System/Xml/Serialization/XmlAnyAttributeAttribute.cs",
        "src/System/Xml/Serialization/XmlAnyElementAttribute.cs",
        "src/System/Xml/Serialization/XmlAnyElementAttributes.cs",
        "src/System/Xml/Serialization/XmlArrayAttribute.cs",
        "src/System/Xml/Serialization/XmlArrayItemAttribute.cs",
        "src/System/Xml/Serialization/XmlArrayItemAttributes.cs",
        "src/System/Xml/Serialization/XmlAttributeAttribute.cs",
        "src/System/Xml/Serialization/XmlAttributeOverrides.cs",
        "src/System/Xml/Serialization/XmlAttributes.cs",
        "src/System/Xml/Serialization/XmlChoiceIdentifierAttribute.cs",
        "src/System/Xml/Serialization/Xmlcustomformatter.cs",
        "src/System/Xml/Serialization/XmlElementAttribute.cs",
        "src/System/Xml/Serialization/XmlElementAttributes.cs",
        "src/System/Xml/Serialization/XmlEnumAttribute.cs",
        "src/System/Xml/Serialization/XmlIgnoreAttribute.cs",
        "src/System/Xml/Serialization/XmlIncludeAttribute.cs",
        "src/System/Xml/Serialization/XmlMapping.cs",
        "src/System/Xml/Serialization/XmlMemberMapping.cs",
        "src/System/Xml/Serialization/XmlMembersMapping.cs",
        "src/System/Xml/Serialization/XmlNamespaceDeclarationsAttribute.cs",
        "src/System/Xml/Serialization/XmlReflectionImporter.cs",
        "src/System/Xml/Serialization/XmlReflectionMember.cs",
        "src/System/Xml/Serialization/XmlRootAttribute.cs",
        "src/System/Xml/Serialization/XmlSchemaExporter.cs",
        "src/System/Xml/Serialization/XmlSchemaImporter.cs",
        "src/System/Xml/Serialization/XmlSchemaProviderAttribute.cs",
        "src/System/Xml/Serialization/XmlSchemas.cs",
        "src/System/Xml/Serialization/XmlSerializationEventSource.cs",
        "src/System/Xml/Serialization/XmlSerializationGeneratedCode.cs",
        "src/System/Xml/Serialization/XmlSerializationILGen.cs",
        "src/System/Xml/Serialization/XmlSerializationReader.cs",
        "src/System/Xml/Serialization/XmlSerializationReaderILGen.cs",
        "src/System/Xml/Serialization/XmlSerializationWriter.cs",
        "src/System/Xml/Serialization/XmlSerializationWriterILGen.cs",
        "src/System/Xml/Serialization/XmlSerializerAssemblyAttribute.cs",
        "src/System/Xml/Serialization/XmlSerializer.cs",
        "src/System/Xml/Serialization/XmlSerializerFactory.cs",
        "src/System/Xml/Serialization/XmlSerializerNamespaces.cs",
        "src/System/Xml/Serialization/XmlSerializerVersionAttribute.cs",
        "src/System/Xml/Serialization/XmlTextAttribute.cs",
        "src/System/Xml/Serialization/XmlTypeAttribute.cs",
        "src/System/Xml/Serialization/XmlTypeMapping.cs",
        "src/System/Xml/Serialization/_Events.cs",
        "src/System/Xml/Serialization/TypeExtensions.cs",
        "src/System/Xml/Serialization/PrimitiveXmlSerializers.cs",
        "src/System/Xml/Serialization/Configuration/DateTimeSerializationSection.cs",
        "src/System/Xml/Serialization/Globals.cs",

        # Xsl IlGen
        "src/System/Xml/Xsl/IlGen/GenerateHelper.cs",
        "src/System/Xml/Xsl/IlGen/IteratorDescriptor.cs",
        "src/System/Xml/Xsl/IlGen/OptimizerPatterns.cs",
        "src/System/Xml/Xsl/IlGen/StaticDataManager.cs",
        "src/System/Xml/Xsl/IlGen/TailCallAnalyzer.cs",
        "src/System/Xml/Xsl/IlGen/XmlILAnnotation.cs",
        "src/System/Xml/Xsl/IlGen/XmlILConstructAnalyzer.cs",
        "src/System/Xml/Xsl/IlGen/XmlILModule.cs",
        "src/System/Xml/Xsl/IlGen/XmlILOptimization.cs",
        "src/System/Xml/Xsl/IlGen/XmlILOptimizerVisitor.cs",
        "src/System/Xml/Xsl/IlGen/XmlILTrace.cs",
        "src/System/Xml/Xsl/IlGen/XmlIlTypeHelper.cs",
        "src/System/Xml/Xsl/IlGen/XmlIlVisitor.cs",

        # Xsl core
        "src/System/Xml/Xsl/XmlIlGenerator.cs",
        "src/System/Xml/Xsl/XmlILCommand.cs",
        "src/System/Xml/Xsl/ISourceLineInfo.cs",
        "src/System/Xml/Xsl/ListBase.cs",
        "src/System/Xml/Xsl/Pair.cs",
        "src/System/Xml/Xsl/QueryReaderSettings.cs",
        "src/System/Xml/Xsl/SourceLineInfo.cs",
        "src/System/Xml/Xsl/XmlNodeKindFlags.cs",
        "src/System/Xml/Xsl/XmlQualifiedNameTest.cs",
        "src/System/Xml/Xsl/XmlQueryCardinality.cs",
        "src/System/Xml/Xsl/XmlQueryType.cs",
        "src/System/Xml/Xsl/XmlQueryTypeFactory.cs",
        "src/System/Xml/Xsl/XPathConvert.cs",
        "src/System/Xml/Xsl/XslException.cs",

        # QIL
        "src/System/Xml/Xsl/QIL/QilBinary.cs",
        "src/System/Xml/Xsl/QIL/QilChoice.cs",
        "src/System/Xml/Xsl/QIL/QilCloneVisitor.cs",
        "src/System/Xml/Xsl/QIL/QilDataSource.cs",
        "src/System/Xml/Xsl/QIL/QilExpression.cs",
        "src/System/Xml/Xsl/QIL/QilFactory.cs",
        "src/System/Xml/Xsl/QIL/QilFunction.cs",
        "src/System/Xml/Xsl/QIL/QilInvoke.cs",
        "src/System/Xml/Xsl/QIL/QilInvokeEarlyBound.cs",
        "src/System/Xml/Xsl/QIL/QilInvokeLateBound.cs",
        "src/System/Xml/Xsl/QIL/QilIterator.cs",
        "src/System/Xml/Xsl/QIL/QilList.cs",
        "src/System/Xml/Xsl/QIL/QilLiteral.cs",
        "src/System/Xml/Xsl/QIL/QilLoop.cs",
        "src/System/Xml/Xsl/QIL/QilName.cs",
        "src/System/Xml/Xsl/QIL/QilNode.cs",
        "src/System/Xml/Xsl/QIL/QilNodeType.cs",
        "src/System/Xml/Xsl/QIL/QilParameter.cs",
        "src/System/Xml/Xsl/QIL/QilPatternFactory.cs",
        "src/System/Xml/Xsl/QIL/QilPatternVisitor.cs",
        "src/System/Xml/Xsl/QIL/QilReference.cs",
        "src/System/Xml/Xsl/QIL/QilReplaceVisitor.cs",
        "src/System/Xml/Xsl/QIL/QilScopedVisitor.cs",
        "src/System/Xml/Xsl/QIL/QilSortKey.cs",
        "src/System/Xml/Xsl/QIL/QilStrConcat.cs",
        "src/System/Xml/Xsl/QIL/QilTargetType.cs",
        "src/System/Xml/Xsl/QIL/QilTernary.cs",
        "src/System/Xml/Xsl/QIL/QilTypeChecker.cs",
        "src/System/Xml/Xsl/QIL/QilUnary.cs",
        "src/System/Xml/Xsl/QIL/QilValidationVisitor.cs",
        "src/System/Xml/Xsl/QIL/QilVisitor.cs",
        "src/System/Xml/Xsl/QIL/QilXmlWriter.cs",
        "src/System/Xml/Xsl/QIL/SerializationHints.cs",
        "src/System/Xml/Xsl/QIL/SubstitutionList.cs",
        "src/System/Xml/Xsl/QIL/WhitespaceRule.cs",

        # Xsl Runtime
        "src/System/Xml/Xsl/Runtime/ContentIterators.cs",
        "src/System/Xml/Xsl/Runtime/DecimalFormatter.cs",
        "src/System/Xml/Xsl/Runtime/DocumentOrderComparer.cs",
        "src/System/Xml/Xsl/Runtime/DodSequenceMerge.cs",
        "src/System/Xml/Xsl/Runtime/EarlyBoundInfo.cs",
        "src/System/Xml/Xsl/Runtime/NumberFormatter.cs",
        "src/System/Xml/Xsl/Runtime/RtfNavigator.cs",
        "src/System/Xml/Xsl/Runtime/SetIterators.cs",
        "src/System/Xml/Xsl/Runtime/SiblingIterators.cs",
        "src/System/Xml/Xsl/Runtime/StringConcat.cs",
        "src/System/Xml/Xsl/Runtime/TreeIterators.cs",
        "src/System/Xml/Xsl/Runtime/WhitespaceRuleLookup.cs",
        "src/System/Xml/Xsl/Runtime/WhitespaceRuleReader.cs",
        "src/System/Xml/Xsl/Runtime/XmlAggregates.cs",
        "src/System/Xml/Xsl/Runtime/XmlAttributeCache.cs",
        "src/System/Xml/Xsl/Runtime/XmlCollation.cs",
        "src/System/Xml/Xsl/Runtime/XmlCollation.Unix.cs",
        "src/System/Xml/Xsl/Runtime/XmlExtensionFunction.cs",
        "src/System/Xml/Xsl/Runtime/XmlILIndex.cs",
        "src/System/Xml/Xsl/Runtime/XmlILStorageConverter.cs",
        "src/System/Xml/Xsl/Runtime/XmlIterators.cs",
        "src/System/Xml/Xsl/Runtime/XmlNavigatorFilter.cs",
        "src/System/Xml/Xsl/Runtime/XmlNavigatorStack.cs",
        "src/System/Xml/Xsl/Runtime/XmlQueryContext.cs",
        "src/System/Xml/Xsl/Runtime/XmlQueryOutput.cs",
        "src/System/Xml/Xsl/Runtime/XmlQueryRuntime.cs",
        "src/System/Xml/Xsl/Runtime/XmlQuerySequence.cs",
        "src/System/Xml/Xsl/Runtime/XmlQueryStaticData.cs",
        "src/System/Xml/Xsl/Runtime/XmlRawWriterWrapper.cs",
        "src/System/Xml/Xsl/Runtime/XmlSequenceWriter.cs",
        "src/System/Xml/Xsl/Runtime/XmlSortKey.cs",
        "src/System/Xml/Xsl/Runtime/XmlSortKeyAccumulator.cs",
        "src/System/Xml/Xsl/Runtime/XslNumber.cs",
        "src/System/Xml/Xsl/Runtime/XsltConvert.cs",
        "src/System/Xml/Xsl/Runtime/XsltFunctions.cs",
        "src/System/Xml/Xsl/Runtime/XsltLibrary.cs",

        # Xsl XPath
        "src/System/Xml/Xsl/XPath/IXpathBuilder.cs",
        "src/System/Xml/Xsl/XPath/IXPathEnvironment.cs",
        "src/System/Xml/Xsl/XPath/XPathAxis.cs",
        "src/System/Xml/Xsl/XPath/XPathBuilder.cs",
        "src/System/Xml/Xsl/XPath/XPathCompileException.cs",
        "src/System/Xml/Xsl/XPath/XPathContext.cs",
        "src/System/Xml/Xsl/XPath/XPathOperator.cs",
        "src/System/Xml/Xsl/XPath/XPathParser.cs",
        "src/System/Xml/Xsl/XPath/XPathQilFactory.cs",
        "src/System/Xml/Xsl/XPath/XPathScanner.cs",

        # XsltOld
        "src/System/Xml/Xsl/XsltOld/Action.cs",
        "src/System/Xml/Xsl/XsltOld/ActionFrame.cs",
        "src/System/Xml/Xsl/XsltOld/ApplyImportsAction.cs",
        "src/System/Xml/Xsl/XsltOld/ApplyTemplatesAction.cs",
        "src/System/Xml/Xsl/XsltOld/AttributeAction.cs",
        "src/System/Xml/Xsl/XsltOld/AttributeSetAction.cs",
        "src/System/Xml/Xsl/XsltOld/Avt.cs",
        "src/System/Xml/Xsl/XsltOld/AvtEvent.cs",
        "src/System/Xml/Xsl/XsltOld/BeginEvent.cs",
        "src/System/Xml/Xsl/XsltOld/BuilderInfo.cs",
        "src/System/Xml/Xsl/XsltOld/CallTemplateAction.cs",
        "src/System/Xml/Xsl/XsltOld/ChooseAction.cs",
        "src/System/Xml/Xsl/XsltOld/CommentAction.cs",
        "src/System/Xml/Xsl/XsltOld/CompiledAction.cs",
        "src/System/Xml/Xsl/XsltOld/Compiler.cs",
        "src/System/Xml/Xsl/XsltOld/ContainerAction.cs",
        "src/System/Xml/Xsl/XsltOld/CopyAction.cs",
        "src/System/Xml/Xsl/XsltOld/CopyAttributesAction.cs",
        "src/System/Xml/Xsl/XsltOld/CopyCodeAction.cs",
        "src/System/Xml/Xsl/XsltOld/CopyNamespacesAction.cs",
        "src/System/Xml/Xsl/XsltOld/CopyNodeSetAction.cs",
        "src/System/Xml/Xsl/XsltOld/CopyOfAction.cs",
        "src/System/Xml/Xsl/XsltOld/DocumentScope.cs",
        "src/System/Xml/Xsl/XsltOld/ElementAction.cs",
        "src/System/Xml/Xsl/XsltOld/EndEvent.cs",
        "src/System/Xml/Xsl/XsltOld/Event.cs",
        "src/System/Xml/Xsl/XsltOld/ForEachAction.cs",
        "src/System/Xml/Xsl/XsltOld/HtmlProps.cs",
        "src/System/Xml/Xsl/XsltOld/IfAction.cs",
        "src/System/Xml/Xsl/XsltOld/InputScope.cs",
        "src/System/Xml/Xsl/XsltOld/InputScopeManager.cs",
        "src/System/Xml/Xsl/XsltOld/IRecordOutput.cs",
        "src/System/Xml/Xsl/XsltOld/MessageAction.cs",
        "src/System/Xml/Xsl/XsltOld/NamespaceDecl.cs",
        "src/System/Xml/Xsl/XsltOld/NameSpaceEvent.cs",
        "src/System/Xml/Xsl/XsltOld/NavigatorInput.cs",
        "src/System/Xml/Xsl/XsltOld/NavigatorOutput.cs",
        "src/System/Xml/Xsl/XsltOld/newinstructionaction.cs",
        "src/System/Xml/Xsl/XsltOld/NumberAction.cs",
        "src/System/Xml/Xsl/XsltOld/OutKeywords.cs",
        "src/System/Xml/Xsl/XsltOld/OutputScope.cs",
        "src/System/Xml/Xsl/XsltOld/OutputScopeManager.cs",
        "src/System/Xml/Xsl/XsltOld/PrefixQName.cs",
        "src/System/Xml/Xsl/XsltOld/ProcessingInstructionAction.cs",
        "src/System/Xml/Xsl/XsltOld/Processor.cs",
        "src/System/Xml/Xsl/XsltOld/ReaderOutput.cs",
        "src/System/Xml/Xsl/XsltOld/RecordBuilder.cs",
        "src/System/Xml/Xsl/XsltOld/RootAction.cs",
        "src/System/Xml/Xsl/XsltOld/SequentialOutput.cs",
        "src/System/Xml/Xsl/XsltOld/SortAction.cs",
        "src/System/Xml/Xsl/XsltOld/StateMachine.cs",
        "src/System/Xml/Xsl/XsltOld/StringOutput.cs",
        "src/System/Xml/Xsl/XsltOld/Stylesheet.cs",
        "src/System/Xml/Xsl/XsltOld/TemplateAction.cs",
        "src/System/Xml/Xsl/XsltOld/TemplateBaseAction.cs",
        "src/System/Xml/Xsl/XsltOld/TemplateLookupAction.cs",
        "src/System/Xml/Xsl/XsltOld/TemplateManager.cs",
        "src/System/Xml/Xsl/XsltOld/TextAction.cs",
        "src/System/Xml/Xsl/XsltOld/TextEvent.cs",
        "src/System/Xml/Xsl/XsltOld/TextOnlyOutput.cs",
        "src/System/Xml/Xsl/XsltOld/TextOutput.cs",
        "src/System/Xml/Xsl/XsltOld/TheQuery.cs",
        "src/System/Xml/Xsl/XsltOld/UseAttributeSetsAction.cs",
        "src/System/Xml/Xsl/XsltOld/ValueOfAction.cs",
        "src/System/Xml/Xsl/XsltOld/VariableAction.cs",
        "src/System/Xml/Xsl/XsltOld/WithParamAction.cs",
        "src/System/Xml/Xsl/XsltOld/WriterOutput.cs",
        "src/System/Xml/Xsl/XsltOld/XsltCompileContext.cs",
        "src/System/Xml/Xsl/XsltOld/XsltDebugger.cs",
        "src/System/Xml/Xsl/XsltOld/XsltOutput.cs",

        # Xsl Xslt (new compiler)
        "src/System/Xml/Xsl/Xslt/Compiler.cs",
        "src/System/Xml/Xsl/Xslt/CompilerError.cs",
        "src/System/Xml/Xsl/Xslt/CompilerScopeManager.cs",
        "src/System/Xml/Xsl/Xslt/Focus.cs",
        "src/System/Xml/Xsl/Xslt/IErrorHelper.cs",
        "src/System/Xml/Xsl/Xslt/InvokeGenerator.cs",
        "src/System/Xml/Xsl/Xslt/KeyMatchBuilder.cs",
        "src/System/Xml/Xsl/Xslt/Keywords.cs",
        "src/System/Xml/Xsl/Xslt/MatcherBuilder.cs",
        "src/System/Xml/Xsl/Xslt/OutputScopeManager.cs",
        "src/System/Xml/Xsl/Xslt/QilGenerator.cs",
        "src/System/Xml/Xsl/Xslt/QilGeneratorEnv.cs",
        "src/System/Xml/Xsl/Xslt/QilStrConcatenator.cs",
        "src/System/Xml/Xsl/Xslt/Scripts.cs",
        "src/System/Xml/Xsl/Xslt/Stylesheet.cs",
        "src/System/Xml/Xsl/Xslt/XPathPatternBuilder.cs",
        "src/System/Xml/Xsl/Xslt/XPathPatternParser.cs",
        "src/System/Xml/Xsl/Xslt/XslAst.cs",
        "src/System/Xml/Xsl/Xslt/XslAstAnalyzer.cs",
        "src/System/Xml/Xsl/Xslt/XslFlags.cs",
        "src/System/Xml/Xsl/Xslt/XsltInput.cs",
        "src/System/Xml/Xsl/Xslt/XsltLoader.cs",
        "src/System/Xml/Xsl/Xslt/XsltQilFactory.cs",
        "src/System/Xml/Xsl/Xslt/XslVisitor.cs",
    ],
    deps = [
        "//src/libraries/System.Collections:ref_System.Collections",
        "//src/libraries/System.Collections.Concurrent:ref_System.Collections.Concurrent",
        "//src/libraries/System.Collections.NonGeneric:ref_System.Collections.NonGeneric",
        "//src/libraries/System.Collections.Specialized:ref_System.Collections.Specialized",
        "//src/libraries/System.Console:ref_System.Console",
        "//src/libraries/System.Diagnostics.TraceSource:ref_System.Diagnostics.TraceSource",
        "//src/libraries/System.Diagnostics.Tracing:ref_System.Diagnostics.Tracing",
        "//src/libraries/System.Linq.Expressions:ref_System.Linq.Expressions",
        "//src/libraries/System.Memory:ref_System.Memory",
        "//src/libraries/System.Net.Http:ref_System.Net.Http",
        "//src/libraries/System.Net.Primitives:ref_System.Net.Primitives",
        "//src/libraries/System.ObjectModel:ref_System.ObjectModel",
        "//src/libraries/System.Reflection.Emit:ref_System.Reflection.Emit",
        "//src/libraries/System.Reflection.Emit.ILGeneration:ref_System.Reflection.Emit.ILGeneration",
        "//src/libraries/System.Reflection.Emit.Lightweight:ref_System.Reflection.Emit.Lightweight",
        "//src/libraries/System.Reflection.Primitives:ref_System.Reflection.Primitives",
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Runtime.InteropServices:ref_System.Runtime.InteropServices",
        "//src/libraries/System.Runtime.Loader:ref_System.Runtime.Loader",
        "//src/libraries/System.Security.Cryptography:ref_System.Security.Cryptography",
        "//src/libraries/System.Text.Encoding.Extensions:ref_System.Text.Encoding.Extensions",
        "//src/libraries/System.Text.RegularExpressions:ref_System.Text.RegularExpressions",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/System.Threading.Thread:ref_System.Threading.Thread",
    ],
    resx_file = "src/Resources/Strings.resx",
    resources = [
        "src/Utils/DTDs/RSS091/no_comments/rss-0.91.dtd",
        "src/Utils/DTDs/XHTML10/no_comments/xhtml-lat1.ent",
        "src/Utils/DTDs/XHTML10/no_comments/xhtml-special.ent",
        "src/Utils/DTDs/XHTML10/no_comments/xhtml-symbol.ent",
        "src/Utils/DTDs/XHTML10/no_comments/xhtml1-frameset.dtd",
        "src/Utils/DTDs/XHTML10/no_comments/xhtml1-strict.dtd",
        "src/Utils/DTDs/XHTML10/no_comments/xhtml1-transitional.dtd",
    ],
    resource_logical_names = {
        "rss-0.91.dtd": "rss-0.91.dtd",
        "xhtml-lat1.ent": "xhtml-lat1.ent",
        "xhtml-special.ent": "xhtml-special.ent",
        "xhtml-symbol.ent": "xhtml-symbol.ent",
        "xhtml1-frameset.dtd": "xhtml1-frameset.dtd",
        "xhtml1-strict.dtd": "xhtml1-strict.dtd",
        "xhtml1-transitional.dtd": "xhtml1-transitional.dtd",
    },
    analyzers = [
        "//src/libraries/System.Text.RegularExpressions:RegexGenerator",
    ],
)
