load("//src/tests:live_test.bzl", "coreclr_test")

coreclr_test(
    name = "Runtime_115815",
    srcs = ["Runtime_115815.cs"],
    optimize = True,
    deps = [
        "//src/libraries/System.Threading.Thread:ref_System.Threading.Thread",
        "//src/libraries/System.Threading:ref_System.Threading",
    ],
)
