load("//src/tests:live_test.bzl", "library_test")
load("//:defs.bzl", "OPEN_SNK")

library_test(
    name = "System.Security.AccessControl.Tests",
    srcs = glob(["**/*.cs"]),
    deps = [
        "//src/libraries/System.Security.AccessControl:ref_System.Security.AccessControl",
        "//src/libraries/System.IO.FileSystem.AccessControl:ref_System.IO.FileSystem.AccessControl",
        "//src/libraries/System.Security.Principal.Windows:ref_System.Security.Principal.Windows",
        "//src/libraries/System.Collections.Concurrent:ref_System.Collections.Concurrent",
        "//src/libraries/System.Collections.Immutable:ref_System.Collections.Immutable",
        "//src/libraries/Common/tests:TestUtilities",
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//microsoft.dotnet.xunitextensions",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    keyfile = OPEN_SNK,
    target_compatible_with = ["@platforms//os:windows"],
)
