load("//src/tests:live_test.bzl", "library_test")
load("//src/libraries:defs.bzl", "MULTITARGET_NOWARN")
load("//:defs.bzl", "OPEN_SNK")

library_test(
    name = "System.Threading.Channels.Tests",
    srcs = glob(["*.cs"]) + [
        "//src/libraries/Common/tests:System/Diagnostics/DebuggerAttributes.cs",
        "//src/libraries/Common/tests:System/Threading/Tasks/TaskTimeoutExtensions.cs",
    ],
    deps = [
        "//src/libraries/System.Threading.Channels:ref_System.Threading.Channels",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/System.Threading.ThreadPool:ref_System.Threading.ThreadPool",
        "//src/libraries/System.IO.FileSystem.DriveInfo:ref_System.IO.FileSystem.DriveInfo",
        "//src/libraries/System.Runtime.Serialization.Formatters:ref_System.Runtime.Serialization.Formatters",
        "//src/libraries/Common/tests:TestUtilities",
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//microsoft.dotnet.xunitextensions",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    nowarn = MULTITARGET_NOWARN + [
        "SYSLIB0011",
    ],
    size = "large",
    keyfile = OPEN_SNK,
)
