exports_files([
    "Microsoft.VisualBasic.Core.ForwardedTypes.cs",
    "Microsoft.Win32.SystemEvents.ForwardedTypes.cs",
    "System.Configuration.ConfigurationManager.ForwardedTypes.cs",
    "System.Data.Odbc.ForwardedTypes.cs",
    "System.Data.OleDb.ForwardedTypes.cs",
    "System.Data.SqlClient.ForwardedTypes.cs",
    "System.Diagnostics.EventLog.ForwardedTypes.cs",
    "System.Diagnostics.PerformanceCounter.ForwardedTypes.cs",
    "System.Drawing.Common.ForwardedTypes.cs",
    "System.IO.Packaging.ForwardedTypes.cs",
    "System.IO.Pipes.AccessControl.ForwardedTypes.cs",
    "System.IO.Ports.ForwardedTypes.cs",
    "System.Runtime.Serialization.Schema.ForwardedTypes.cs",
    "System.Security.Cryptography.ProtectedData.ForwardedTypes.cs",
    "System.Security.Permissions.ForwardedTypes.cs",
    "System.ServiceModel.Syndication.ForwardedTypes.cs",
    "System.ServiceProcess.ServiceController.ForwardedTypes.cs",
    "System.Threading.AccessControl.ForwardedTypes.cs",
    "System.Windows.Extensions.ForwardedTypes.cs",
])
