// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

namespace Microsoft.VisualBasic { public static class AppWinStyle { } }
namespace Microsoft.VisualBasic { public static class CallType { } }
namespace Microsoft.VisualBasic { public static class Collection { } }
namespace Microsoft.VisualBasic { public static class ComClassAttribute { } }
namespace Microsoft.VisualBasic { public static class CompareMethod { } }
namespace Microsoft.VisualBasic { public static class Constants { } }
namespace Microsoft.VisualBasic { public static class ControlChars { } }
namespace Microsoft.VisualBasic { public static class Conversion { } }
namespace Microsoft.VisualBasic { public static class DateAndTime { } }
namespace Microsoft.VisualBasic { public static class DateFormat { } }
namespace Microsoft.VisualBasic { public static class DateInterval { } }
namespace Microsoft.VisualBasic { public static class DueDate { } }
namespace Microsoft.VisualBasic { public static class ErrObject { } }
namespace Microsoft.VisualBasic { public static class FileAttribute { } }
namespace Microsoft.VisualBasic { public static class FileSystem { } }
namespace Microsoft.VisualBasic { public static class Financial { } }
namespace Microsoft.VisualBasic { public static class FirstDayOfWeek { } }
namespace Microsoft.VisualBasic { public static class FirstWeekOfYear { } }
namespace Microsoft.VisualBasic { public static class HideModuleNameAttribute { } }
namespace Microsoft.VisualBasic { public static class Information { } }
namespace Microsoft.VisualBasic { public static class Interaction { } }
namespace Microsoft.VisualBasic { public static class MsgBoxResult { } }
namespace Microsoft.VisualBasic { public static class MsgBoxStyle { } }
namespace Microsoft.VisualBasic { public static class MyGroupCollectionAttribute { } }
namespace Microsoft.VisualBasic { public static class OpenAccess { } }
namespace Microsoft.VisualBasic { public static class OpenMode { } }
namespace Microsoft.VisualBasic { public static class OpenShare { } }
namespace Microsoft.VisualBasic { public static class SpcInfo { } }
namespace Microsoft.VisualBasic { public static class Strings { } }
namespace Microsoft.VisualBasic { public static class TabInfo { } }
namespace Microsoft.VisualBasic { public static class TriState { } }
namespace Microsoft.VisualBasic { public static class VBFixedArrayAttribute { } }
namespace Microsoft.VisualBasic { public static class VBFixedStringAttribute { } }
namespace Microsoft.VisualBasic { public static class VBMath { } }
namespace Microsoft.VisualBasic { public static class VariantType { } }
namespace Microsoft.VisualBasic { public static class VbStrConv { } }
namespace Microsoft.VisualBasic.CompilerServices { public static class BooleanType { } }
namespace Microsoft.VisualBasic.CompilerServices { public static class ByteType { } }
namespace Microsoft.VisualBasic.CompilerServices { public static class CharArrayType { } }
namespace Microsoft.VisualBasic.CompilerServices { public static class CharType { } }
namespace Microsoft.VisualBasic.CompilerServices { public static class Conversions { } }
namespace Microsoft.VisualBasic.CompilerServices { public static class DateType { } }
namespace Microsoft.VisualBasic.CompilerServices { public static class DecimalType { } }
namespace Microsoft.VisualBasic.CompilerServices { public static class DesignerGeneratedAttribute { } }
namespace Microsoft.VisualBasic.CompilerServices { public static class DoubleType { } }
namespace Microsoft.VisualBasic.CompilerServices { public static class IncompleteInitialization { } }
namespace Microsoft.VisualBasic.CompilerServices { public static class IntegerType { } }
namespace Microsoft.VisualBasic.CompilerServices { public static class LateBinding { } }
namespace Microsoft.VisualBasic.CompilerServices { public static class LikeOperator { } }
namespace Microsoft.VisualBasic.CompilerServices { public static class LongType { } }
namespace Microsoft.VisualBasic.CompilerServices { public static class NewLateBinding { } }
namespace Microsoft.VisualBasic.CompilerServices { public static class ObjectFlowControl { } }
namespace Microsoft.VisualBasic.CompilerServices { public static class ObjectType { } }
namespace Microsoft.VisualBasic.CompilerServices { public static class Operators { } }
namespace Microsoft.VisualBasic.CompilerServices { public static class OptionCompareAttribute { } }
namespace Microsoft.VisualBasic.CompilerServices { public static class OptionTextAttribute { } }
namespace Microsoft.VisualBasic.CompilerServices { public static class ProjectData { } }
namespace Microsoft.VisualBasic.CompilerServices { public static class ShortType { } }
namespace Microsoft.VisualBasic.CompilerServices { public static class SingleType { } }
namespace Microsoft.VisualBasic.CompilerServices { public static class StandardModuleAttribute { } }
namespace Microsoft.VisualBasic.CompilerServices { public static class StaticLocalInitFlag { } }
namespace Microsoft.VisualBasic.CompilerServices { public static class StringType { } }
namespace Microsoft.VisualBasic.CompilerServices { public static class Utils { } }
namespace Microsoft.VisualBasic.CompilerServices { public static class Versioned { } }
namespace Microsoft.VisualBasic.FileIO { public static class DeleteDirectoryOption { } }
namespace Microsoft.VisualBasic.FileIO { public static class FieldType { } }
namespace Microsoft.VisualBasic.FileIO { public static class FileSystem { } }
namespace Microsoft.VisualBasic.FileIO { public static class MalformedLineException { } }
namespace Microsoft.VisualBasic.FileIO { public static class RecycleOption { } }
namespace Microsoft.VisualBasic.FileIO { public static class SearchOption { } }
namespace Microsoft.VisualBasic.FileIO { public static class SpecialDirectories { } }
namespace Microsoft.VisualBasic.FileIO { public static class TextFieldParser { } }
namespace Microsoft.VisualBasic.FileIO { public static class UICancelOption { } }
namespace Microsoft.VisualBasic.FileIO { public static class UIOption { } }
