// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

namespace System.Configuration { public static class AppSettingsReader { } }
namespace System.Configuration { public static class AppSettingsSection { } }
namespace System.Configuration { public static class ApplicationScopedSettingAttribute { } }
namespace System.Configuration { public static class ApplicationSettingsBase { } }
namespace System.Configuration { public static class ApplicationSettingsGroup { } }
namespace System.Configuration { public static class CallbackValidator { } }
namespace System.Configuration { public static class CallbackValidatorAttribute { } }
namespace System.Configuration { public static class ClientSettingsSection { } }
namespace System.Configuration { public static class CommaDelimitedStringCollection { } }
namespace System.Configuration { public static class CommaDelimitedStringCollectionConverter { } }
namespace System.Configuration { public static class ConfigXmlDocument { } }
namespace System.Configuration { public static class Configuration { } }
namespace System.Configuration { public static class ConfigurationAllowDefinition { } }
namespace System.Configuration { public static class ConfigurationAllowExeDefinition { } }
namespace System.Configuration { public static class ConfigurationCollectionAttribute { } }
namespace System.Configuration { public static class ConfigurationConverterBase { } }
namespace System.Configuration { public static class ConfigurationElement { } }
namespace System.Configuration { public static class ConfigurationElementCollection { } }
namespace System.Configuration { public static class ConfigurationElementCollectionType { } }
namespace System.Configuration { public static class ConfigurationElementProperty { } }
namespace System.Configuration { public static class ConfigurationErrorsException { } }
namespace System.Configuration { public static class ConfigurationException { } }
namespace System.Configuration { public static class ConfigurationFileMap { } }
namespace System.Configuration { public static class ConfigurationLocation { } }
namespace System.Configuration { public static class ConfigurationLocationCollection { } }
namespace System.Configuration { public static class ConfigurationLockCollection { } }
namespace System.Configuration { public static class ConfigurationManager { } }
namespace System.Configuration { public static class ConfigurationProperty { } }
namespace System.Configuration { public static class ConfigurationPropertyAttribute { } }
namespace System.Configuration { public static class ConfigurationPropertyCollection { } }
namespace System.Configuration { public static class ConfigurationPropertyOptions { } }
namespace System.Configuration { public static class ConfigurationSaveMode { } }
namespace System.Configuration { public static class ConfigurationSection { } }
namespace System.Configuration { public static class ConfigurationSectionCollection { } }
namespace System.Configuration { public static class ConfigurationSectionGroup { } }
namespace System.Configuration { public static class ConfigurationSectionGroupCollection { } }
namespace System.Configuration { public static class ConfigurationSettings { } }
namespace System.Configuration { public static class ConfigurationUserLevel { } }
namespace System.Configuration { public static class ConfigurationValidatorAttribute { } }
namespace System.Configuration { public static class ConfigurationValidatorBase { } }
namespace System.Configuration { public static class ConnectionStringSettings { } }
namespace System.Configuration { public static class ConnectionStringSettingsCollection { } }
namespace System.Configuration { public static class ConnectionStringsSection { } }
namespace System.Configuration { public static class ContextInformation { } }
namespace System.Configuration { public static class DefaultSection { } }
namespace System.Configuration { public static class DefaultSettingValueAttribute { } }
namespace System.Configuration { public static class DefaultValidator { } }
namespace System.Configuration { public static class DictionarySectionHandler { } }
namespace System.Configuration { public static class DpapiProtectedConfigurationProvider { } }
namespace System.Configuration { public static class ElementInformation { } }
namespace System.Configuration { public static class ExeConfigurationFileMap { } }
namespace System.Configuration { public static class ExeContext { } }
namespace System.Configuration { public static class GenericEnumConverter { } }
namespace System.Configuration { public static class IApplicationSettingsProvider { } }
namespace System.Configuration { public static class IConfigurationSectionHandler { } }
namespace System.Configuration { public static class IConfigurationSystem { } }
namespace System.Configuration { public static class IPersistComponentSettings { } }
namespace System.Configuration { public static class ISettingsProviderService { } }
namespace System.Configuration { public static class IdnElement { } }
namespace System.Configuration { public static class IgnoreSection { } }
namespace System.Configuration { public static class IgnoreSectionHandler { } }
namespace System.Configuration { public static class InfiniteIntConverter { } }
namespace System.Configuration { public static class InfiniteTimeSpanConverter { } }
namespace System.Configuration { public static class IntegerValidator { } }
namespace System.Configuration { public static class IntegerValidatorAttribute { } }
namespace System.Configuration.Internal { public static class DelegatingConfigHost { } }
namespace System.Configuration.Internal { public static class IConfigErrorInfo { } }
namespace System.Configuration.Internal { public static class IConfigSystem { } }
namespace System.Configuration.Internal { public static class IConfigurationManagerHelper { } }
namespace System.Configuration.Internal { public static class IConfigurationManagerInternal { } }
namespace System.Configuration.Internal { public static class IInternalConfigClientHost { } }
namespace System.Configuration.Internal { public static class IInternalConfigConfigurationFactory { } }
namespace System.Configuration.Internal { public static class IInternalConfigHost { } }
namespace System.Configuration.Internal { public static class IInternalConfigRecord { } }
namespace System.Configuration.Internal { public static class IInternalConfigRoot { } }
namespace System.Configuration.Internal { public static class IInternalConfigSettingsFactory { } }
namespace System.Configuration.Internal { public static class IInternalConfigSystem { } }
namespace System.Configuration.Internal { public static class InternalConfigEventArgs { } }
namespace System.Configuration.Internal { public static class InternalConfigEventHandler { } }
namespace System.Configuration.Internal { public static class StreamChangeCallback { } }
namespace System.Configuration { public static class IriParsingElement { } }
namespace System.Configuration { public static class KeyValueConfigurationCollection { } }
namespace System.Configuration { public static class KeyValueConfigurationElement { } }
namespace System.Configuration { public static class LocalFileSettingsProvider { } }
namespace System.Configuration { public static class LongValidator { } }
namespace System.Configuration { public static class LongValidatorAttribute { } }
namespace System.Configuration { public static class NameValueConfigurationCollection { } }
namespace System.Configuration { public static class NameValueConfigurationElement { } }
namespace System.Configuration { public static class NameValueFileSectionHandler { } }
namespace System.Configuration { public static class NameValueSectionHandler { } }
namespace System.Configuration { public static class NoSettingsVersionUpgradeAttribute { } }
namespace System.Configuration { public static class OverrideMode { } }
namespace System.Configuration { public static class PositiveTimeSpanValidator { } }
namespace System.Configuration { public static class PositiveTimeSpanValidatorAttribute { } }
namespace System.Configuration { public static class PropertyInformation { } }
namespace System.Configuration { public static class PropertyInformationCollection { } }
namespace System.Configuration { public static class PropertyValueOrigin { } }
namespace System.Configuration { public static class ProtectedConfiguration { } }
namespace System.Configuration { public static class ProtectedConfigurationProvider { } }
namespace System.Configuration { public static class ProtectedConfigurationProviderCollection { } }
namespace System.Configuration { public static class ProtectedConfigurationSection { } }
namespace System.Configuration { public static class ProtectedProviderSettings { } }
namespace System.Configuration.Provider { public static class ProviderBase { } }
namespace System.Configuration.Provider { public static class ProviderCollection { } }
namespace System.Configuration.Provider { public static class ProviderException { } }
namespace System.Configuration { public static class ProviderSettings { } }
namespace System.Configuration { public static class ProviderSettingsCollection { } }
namespace System.Configuration { public static class RegexStringValidator { } }
namespace System.Configuration { public static class RegexStringValidatorAttribute { } }
namespace System.Configuration { public static class RsaProtectedConfigurationProvider { } }
namespace System.Configuration { public static class SchemeSettingElement { } }
namespace System.Configuration { public static class SchemeSettingElementCollection { } }
namespace System.Configuration { public static class SectionInformation { } }
namespace System.Configuration { public static class SettingAttribute { } }
namespace System.Configuration { public static class SettingChangingEventArgs { } }
namespace System.Configuration { public static class SettingChangingEventHandler { } }
namespace System.Configuration { public static class SettingElement { } }
namespace System.Configuration { public static class SettingElementCollection { } }
namespace System.Configuration { public static class SettingValueElement { } }
namespace System.Configuration { public static class SettingsAttributeDictionary { } }
namespace System.Configuration { public static class SettingsBase { } }
namespace System.Configuration { public static class SettingsContext { } }
namespace System.Configuration { public static class SettingsDescriptionAttribute { } }
namespace System.Configuration { public static class SettingsGroupDescriptionAttribute { } }
namespace System.Configuration { public static class SettingsGroupNameAttribute { } }
namespace System.Configuration { public static class SettingsLoadedEventArgs { } }
namespace System.Configuration { public static class SettingsLoadedEventHandler { } }
namespace System.Configuration { public static class SettingsManageability { } }
namespace System.Configuration { public static class SettingsManageabilityAttribute { } }
namespace System.Configuration { public static class SettingsProperty { } }
namespace System.Configuration { public static class SettingsPropertyCollection { } }
namespace System.Configuration { public static class SettingsPropertyIsReadOnlyException { } }
namespace System.Configuration { public static class SettingsPropertyNotFoundException { } }
namespace System.Configuration { public static class SettingsPropertyValue { } }
namespace System.Configuration { public static class SettingsPropertyValueCollection { } }
namespace System.Configuration { public static class SettingsPropertyWrongTypeException { } }
namespace System.Configuration { public static class SettingsProvider { } }
namespace System.Configuration { public static class SettingsProviderAttribute { } }
namespace System.Configuration { public static class SettingsProviderCollection { } }
namespace System.Configuration { public static class SettingsSavingEventHandler { } }
namespace System.Configuration { public static class SettingsSerializeAs { } }
namespace System.Configuration { public static class SettingsSerializeAsAttribute { } }
namespace System.Configuration { public static class SingleTagSectionHandler { } }
namespace System.Configuration { public static class SpecialSetting { } }
namespace System.Configuration { public static class SpecialSettingAttribute { } }
namespace System.Configuration { public static class StringValidator { } }
namespace System.Configuration { public static class StringValidatorAttribute { } }
namespace System.Configuration { public static class SubclassTypeValidator { } }
namespace System.Configuration { public static class SubclassTypeValidatorAttribute { } }
namespace System.Configuration { public static class TimeSpanMinutesConverter { } }
namespace System.Configuration { public static class TimeSpanMinutesOrInfiniteConverter { } }
namespace System.Configuration { public static class TimeSpanSecondsConverter { } }
namespace System.Configuration { public static class TimeSpanSecondsOrInfiniteConverter { } }
namespace System.Configuration { public static class TimeSpanValidator { } }
namespace System.Configuration { public static class TimeSpanValidatorAttribute { } }
namespace System.Configuration { public static class TypeNameConverter { } }
namespace System.Configuration { public static class UriSection { } }
namespace System.Configuration { public static class UserScopedSettingAttribute { } }
namespace System.Configuration { public static class UserSettingsGroup { } }
namespace System.Configuration { public static class ValidatorCallback { } }
namespace System.Configuration { public static class WhiteSpaceTrimStringConverter { } }
namespace System.Drawing.Configuration { public static class SystemDrawingSection { } }
namespace System { public static class UriIdnScope { } }
