// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

namespace System { public static class ApplicationIdentity { } }
namespace System.Configuration { public static class ConfigurationPermission { } }
namespace System.Configuration { public static class ConfigurationPermissionAttribute { } }
namespace System.Data.Common { public static class DBDataPermission { } }
namespace System.Data.Common { public static class DBDataPermissionAttribute { } }
namespace System.Data.Odbc { public static class OdbcPermission { } }
namespace System.Data.Odbc { public static class OdbcPermissionAttribute { } }
namespace System.Data.OleDb { public static class OleDbPermission { } }
namespace System.Data.OleDb { public static class OleDbPermissionAttribute { } }
namespace System.Data.SqlClient { public static class SqlClientPermission { } }
namespace System.Data.SqlClient { public static class SqlClientPermissionAttribute { } }
namespace System.Diagnostics { public static class EventLogPermission { } }
namespace System.Diagnostics { public static class EventLogPermissionAccess { } }
namespace System.Diagnostics { public static class EventLogPermissionAttribute { } }
namespace System.Diagnostics { public static class EventLogPermissionEntry { } }
namespace System.Diagnostics { public static class EventLogPermissionEntryCollection { } }
namespace System.Diagnostics { public static class PerformanceCounterPermission { } }
namespace System.Diagnostics { public static class PerformanceCounterPermissionAccess { } }
namespace System.Diagnostics { public static class PerformanceCounterPermissionAttribute { } }
namespace System.Diagnostics { public static class PerformanceCounterPermissionEntry { } }
namespace System.Diagnostics { public static class PerformanceCounterPermissionEntryCollection { } }
namespace System.Drawing.Printing { public static class PrintingPermission { } }
namespace System.Drawing.Printing { public static class PrintingPermissionAttribute { } }
namespace System.Drawing.Printing { public static class PrintingPermissionLevel { } }
namespace System.Net { public static class DnsPermission { } }
namespace System.Net { public static class DnsPermissionAttribute { } }
namespace System.Net { public static class EndpointPermission { } }
namespace System.Net.Mail { public static class SmtpAccess { } }
namespace System.Net.Mail { public static class SmtpPermission { } }
namespace System.Net.Mail { public static class SmtpPermissionAttribute { } }
namespace System.Net { public static class NetworkAccess { } }
namespace System.Net.NetworkInformation { public static class NetworkInformationAccess { } }
namespace System.Net.NetworkInformation { public static class NetworkInformationPermission { } }
namespace System.Net.NetworkInformation { public static class NetworkInformationPermissionAttribute { } }
namespace System.Net.PeerToPeer.Collaboration { public static class PeerCollaborationPermission { } }
namespace System.Net.PeerToPeer.Collaboration { public static class PeerCollaborationPermissionAttribute { } }
namespace System.Net.PeerToPeer { public static class PnrpPermission { } }
namespace System.Net.PeerToPeer { public static class PnrpPermissionAttribute { } }
namespace System.Net.PeerToPeer { public static class PnrpScope { } }
namespace System.Net { public static class SocketPermission { } }
namespace System.Net { public static class SocketPermissionAttribute { } }
namespace System.Net { public static class TransportType { } }
namespace System.Net { public static class WebPermission { } }
namespace System.Net { public static class WebPermissionAttribute { } }
namespace System.Security { public static class CodeAccessPermission { } }
namespace System.Security { public static class HostProtectionException { } }
namespace System.Security { public static class HostSecurityManager { } }
namespace System.Security { public static class HostSecurityManagerOptions { } }
namespace System.Security { public static class IEvidenceFactory { } }
namespace System.Security { public static class ISecurityPolicyEncodable { } }
namespace System.Security { public static class NamedPermissionSet { } }
namespace System.Security.Permissions { public static class DataProtectionPermission { } }
namespace System.Security.Permissions { public static class DataProtectionPermissionAttribute { } }
namespace System.Security.Permissions { public static class DataProtectionPermissionFlags { } }
namespace System.Security.Permissions { public static class EnvironmentPermission { } }
namespace System.Security.Permissions { public static class EnvironmentPermissionAccess { } }
namespace System.Security.Permissions { public static class EnvironmentPermissionAttribute { } }
namespace System.Security.Permissions { public static class FileDialogPermission { } }
namespace System.Security.Permissions { public static class FileDialogPermissionAccess { } }
namespace System.Security.Permissions { public static class FileDialogPermissionAttribute { } }
namespace System.Security.Permissions { public static class FileIOPermission { } }
namespace System.Security.Permissions { public static class FileIOPermissionAccess { } }
namespace System.Security.Permissions { public static class FileIOPermissionAttribute { } }
namespace System.Security.Permissions { public static class GacIdentityPermission { } }
namespace System.Security.Permissions { public static class GacIdentityPermissionAttribute { } }
namespace System.Security.Permissions { public static class HostProtectionAttribute { } }
namespace System.Security.Permissions { public static class HostProtectionResource { } }
namespace System.Security.Permissions { public static class IUnrestrictedPermission { } }
namespace System.Security.Permissions { public static class IsolatedStorageContainment { } }
namespace System.Security.Permissions { public static class IsolatedStorageFilePermission { } }
namespace System.Security.Permissions { public static class IsolatedStorageFilePermissionAttribute { } }
namespace System.Security.Permissions { public static class IsolatedStoragePermission { } }
namespace System.Security.Permissions { public static class IsolatedStoragePermissionAttribute { } }
namespace System.Security.Permissions { public static class KeyContainerPermission { } }
namespace System.Security.Permissions { public static class KeyContainerPermissionAccessEntry { } }
namespace System.Security.Permissions { public static class KeyContainerPermissionAccessEntryCollection { } }
namespace System.Security.Permissions { public static class KeyContainerPermissionAccessEntryEnumerator { } }
namespace System.Security.Permissions { public static class KeyContainerPermissionAttribute { } }
namespace System.Security.Permissions { public static class KeyContainerPermissionFlags { } }
namespace System.Security.Permissions { public static class MediaPermission { } }
namespace System.Security.Permissions { public static class MediaPermissionAttribute { } }
namespace System.Security.Permissions { public static class MediaPermissionAudio { } }
namespace System.Security.Permissions { public static class MediaPermissionImage { } }
namespace System.Security.Permissions { public static class MediaPermissionVideo { } }
namespace System.Security.Permissions { public static class PermissionSetAttribute { } }
namespace System.Security.Permissions { public static class PrincipalPermission { } }
namespace System.Security.Permissions { public static class PrincipalPermissionAttribute { } }
namespace System.Security.Permissions { public static class PublisherIdentityPermission { } }
namespace System.Security.Permissions { public static class PublisherIdentityPermissionAttribute { } }
namespace System.Security.Permissions { public static class ReflectionPermission { } }
namespace System.Security.Permissions { public static class ReflectionPermissionAttribute { } }
namespace System.Security.Permissions { public static class ReflectionPermissionFlag { } }
namespace System.Security.Permissions { public static class RegistryPermission { } }
namespace System.Security.Permissions { public static class RegistryPermissionAccess { } }
namespace System.Security.Permissions { public static class RegistryPermissionAttribute { } }
namespace System.Security.Permissions { public static class ResourcePermissionBase { } }
namespace System.Security.Permissions { public static class ResourcePermissionBaseEntry { } }
namespace System.Security.Permissions { public static class SecurityPermission { } }
namespace System.Security.Permissions { public static class SiteIdentityPermission { } }
namespace System.Security.Permissions { public static class SiteIdentityPermissionAttribute { } }
namespace System.Security.Permissions { public static class StorePermission { } }
namespace System.Security.Permissions { public static class StorePermissionAttribute { } }
namespace System.Security.Permissions { public static class StorePermissionFlags { } }
namespace System.Security.Permissions { public static class StrongNameIdentityPermission { } }
namespace System.Security.Permissions { public static class StrongNameIdentityPermissionAttribute { } }
namespace System.Security.Permissions { public static class StrongNamePublicKeyBlob { } }
namespace System.Security.Permissions { public static class TypeDescriptorPermission { } }
namespace System.Security.Permissions { public static class TypeDescriptorPermissionAttribute { } }
namespace System.Security.Permissions { public static class TypeDescriptorPermissionFlags { } }
namespace System.Security.Permissions { public static class UIPermission { } }
namespace System.Security.Permissions { public static class UIPermissionAttribute { } }
namespace System.Security.Permissions { public static class UIPermissionClipboard { } }
namespace System.Security.Permissions { public static class UIPermissionWindow { } }
namespace System.Security.Permissions { public static class UrlIdentityPermission { } }
namespace System.Security.Permissions { public static class UrlIdentityPermissionAttribute { } }
namespace System.Security.Permissions { public static class WebBrowserPermission { } }
namespace System.Security.Permissions { public static class WebBrowserPermissionAttribute { } }
namespace System.Security.Permissions { public static class WebBrowserPermissionLevel { } }
namespace System.Security.Permissions { public static class ZoneIdentityPermission { } }
namespace System.Security.Permissions { public static class ZoneIdentityPermissionAttribute { } }
namespace System.Security.Policy { public static class AllMembershipCondition { } }
namespace System.Security.Policy { public static class ApplicationDirectory { } }
namespace System.Security.Policy { public static class ApplicationDirectoryMembershipCondition { } }
namespace System.Security.Policy { public static class ApplicationTrust { } }
namespace System.Security.Policy { public static class ApplicationTrustCollection { } }
namespace System.Security.Policy { public static class ApplicationTrustEnumerator { } }
namespace System.Security.Policy { public static class ApplicationVersionMatch { } }
namespace System.Security.Policy { public static class CodeConnectAccess { } }
namespace System.Security.Policy { public static class CodeGroup { } }
namespace System.Security.Policy { public static class FileCodeGroup { } }
namespace System.Security.Policy { public static class FirstMatchCodeGroup { } }
namespace System.Security.Policy { public static class GacInstalled { } }
namespace System.Security.Policy { public static class GacMembershipCondition { } }
namespace System.Security.Policy { public static class Hash { } }
namespace System.Security.Policy { public static class HashMembershipCondition { } }
namespace System.Security.Policy { public static class IIdentityPermissionFactory { } }
namespace System.Security.Policy { public static class IMembershipCondition { } }
namespace System.Security.Policy { public static class NetCodeGroup { } }
namespace System.Security.Policy { public static class PermissionRequestEvidence { } }
namespace System.Security.Policy { public static class PolicyException { } }
namespace System.Security.Policy { public static class PolicyLevel { } }
namespace System.Security.Policy { public static class PolicyStatement { } }
namespace System.Security.Policy { public static class PolicyStatementAttribute { } }
namespace System.Security.Policy { public static class Publisher { } }
namespace System.Security.Policy { public static class PublisherMembershipCondition { } }
namespace System.Security.Policy { public static class Site { } }
namespace System.Security.Policy { public static class SiteMembershipCondition { } }
namespace System.Security.Policy { public static class StrongName { } }
namespace System.Security.Policy { public static class StrongNameMembershipCondition { } }
namespace System.Security.Policy { public static class TrustManagerContext { } }
namespace System.Security.Policy { public static class TrustManagerUIContext { } }
namespace System.Security.Policy { public static class UnionCodeGroup { } }
namespace System.Security.Policy { public static class Url { } }
namespace System.Security.Policy { public static class UrlMembershipCondition { } }
namespace System.Security.Policy { public static class Zone { } }
namespace System.Security.Policy { public static class ZoneMembershipCondition { } }
namespace System.Security { public static class PolicyLevelType { } }
namespace System.Security { public static class SecurityContext { } }
namespace System.Security { public static class SecurityContextSource { } }
namespace System.Security { public static class SecurityManager { } }
namespace System.Security { public static class SecurityState { } }
namespace System.Security { public static class SecurityZone { } }
namespace System.Security { public static class XmlSyntaxException { } }
namespace System.ServiceProcess { public static class ServiceControllerPermission { } }
namespace System.ServiceProcess { public static class ServiceControllerPermissionAccess { } }
namespace System.ServiceProcess { public static class ServiceControllerPermissionAttribute { } }
namespace System.ServiceProcess { public static class ServiceControllerPermissionEntry { } }
namespace System.ServiceProcess { public static class ServiceControllerPermissionEntryCollection { } }
namespace System.Transactions { public static class DistributedTransactionPermission { } }
namespace System.Transactions { public static class DistributedTransactionPermissionAttribute { } }
namespace System.Web { public static class AspNetHostingPermission { } }
namespace System.Web { public static class AspNetHostingPermissionAttribute { } }
namespace System.Web { public static class AspNetHostingPermissionLevel { } }
