// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

namespace System.Drawing { public static class Bitmap { } }
namespace System.Drawing { public static class BitmapSuffixInSameAssemblyAttribute { } }
namespace System.Drawing { public static class BitmapSuffixInSatelliteAssemblyAttribute { } }
namespace System.Drawing { public static class Brush { } }
namespace System.Drawing { public static class Brushes { } }
namespace System.Drawing { public static class BufferedGraphics { } }
namespace System.Drawing { public static class BufferedGraphicsContext { } }
namespace System.Drawing { public static class BufferedGraphicsManager { } }
namespace System.Drawing { public static class CharacterRange { } }
namespace System.Drawing { public static class ContentAlignment { } }
namespace System.Drawing { public static class CopyPixelOperation { } }
namespace System.Drawing.Design { public static class CategoryNameCollection { } }
namespace System.Drawing.Drawing2D { public static class AdjustableArrowCap { } }
namespace System.Drawing.Drawing2D { public static class Blend { } }
namespace System.Drawing.Drawing2D { public static class ColorBlend { } }
namespace System.Drawing.Drawing2D { public static class CombineMode { } }
namespace System.Drawing.Drawing2D { public static class CompositingMode { } }
namespace System.Drawing.Drawing2D { public static class CompositingQuality { } }
namespace System.Drawing.Drawing2D { public static class CoordinateSpace { } }
namespace System.Drawing.Drawing2D { public static class CustomLineCap { } }
namespace System.Drawing.Drawing2D { public static class DashCap { } }
namespace System.Drawing.Drawing2D { public static class DashStyle { } }
namespace System.Drawing.Drawing2D { public static class FillMode { } }
namespace System.Drawing.Drawing2D { public static class FlushIntention { } }
namespace System.Drawing.Drawing2D { public static class GraphicsContainer { } }
namespace System.Drawing.Drawing2D { public static class GraphicsPath { } }
namespace System.Drawing.Drawing2D { public static class GraphicsPathIterator { } }
namespace System.Drawing.Drawing2D { public static class GraphicsState { } }
namespace System.Drawing.Drawing2D { public static class HatchBrush { } }
namespace System.Drawing.Drawing2D { public static class HatchStyle { } }
namespace System.Drawing.Drawing2D { public static class InterpolationMode { } }
namespace System.Drawing.Drawing2D { public static class LineCap { } }
namespace System.Drawing.Drawing2D { public static class LineJoin { } }
namespace System.Drawing.Drawing2D { public static class LinearGradientBrush { } }
namespace System.Drawing.Drawing2D { public static class LinearGradientMode { } }
namespace System.Drawing.Drawing2D { public static class Matrix { } }
namespace System.Drawing.Drawing2D { public static class MatrixOrder { } }
namespace System.Drawing.Drawing2D { public static class PathData { } }
namespace System.Drawing.Drawing2D { public static class PathGradientBrush { } }
namespace System.Drawing.Drawing2D { public static class PathPointType { } }
namespace System.Drawing.Drawing2D { public static class PenAlignment { } }
namespace System.Drawing.Drawing2D { public static class PenType { } }
namespace System.Drawing.Drawing2D { public static class PixelOffsetMode { } }
namespace System.Drawing.Drawing2D { public static class QualityMode { } }
namespace System.Drawing.Drawing2D { public static class RegionData { } }
namespace System.Drawing.Drawing2D { public static class SmoothingMode { } }
namespace System.Drawing.Drawing2D { public static class WarpMode { } }
namespace System.Drawing.Drawing2D { public static class WrapMode { } }
namespace System.Drawing { public static class Font { } }
namespace System.Drawing { public static class FontConverter { public static class FontNameConverter { } public static class FontUnitConverter { } } }
namespace System.Drawing { public static class FontFamily { } }
namespace System.Drawing { public static class FontStyle { } }
namespace System.Drawing { public static class Graphics { public static class DrawImageAbort { } public static class EnumerateMetafileProc { } } }
namespace System.Drawing { public static class GraphicsUnit { } }
namespace System.Drawing { public static class IDeviceContext { } }
namespace System.Drawing { public static class Icon { } }
namespace System.Drawing { public static class IconConverter { } }
namespace System.Drawing { public static class Image { public static class GetThumbnailImageAbort { } } }
namespace System.Drawing { public static class ImageAnimator { } }
namespace System.Drawing { public static class ImageConverter { } }
namespace System.Drawing { public static class ImageFormatConverter { } }
namespace System.Drawing.Imaging { public static class BitmapData { } }
namespace System.Drawing.Imaging { public static class ColorAdjustType { } }
namespace System.Drawing.Imaging { public static class ColorChannelFlag { } }
namespace System.Drawing.Imaging { public static class ColorMap { } }
namespace System.Drawing.Imaging { public static class ColorMapType { } }
namespace System.Drawing.Imaging { public static class ColorMatrix { } }
namespace System.Drawing.Imaging { public static class ColorMatrixFlag { } }
namespace System.Drawing.Imaging { public static class ColorMode { } }
namespace System.Drawing.Imaging { public static class ColorPalette { } }
namespace System.Drawing.Imaging { public static class EmfPlusRecordType { } }
namespace System.Drawing.Imaging { public static class EmfType { } }
namespace System.Drawing.Imaging { public static class Encoder { } }
namespace System.Drawing.Imaging { public static class EncoderParameter { } }
namespace System.Drawing.Imaging { public static class EncoderParameterValueType { } }
namespace System.Drawing.Imaging { public static class EncoderParameters { } }
namespace System.Drawing.Imaging { public static class EncoderValue { } }
namespace System.Drawing.Imaging { public static class FrameDimension { } }
namespace System.Drawing.Imaging { public static class ImageAttributes { } }
namespace System.Drawing.Imaging { public static class ImageCodecFlags { } }
namespace System.Drawing.Imaging { public static class ImageCodecInfo { } }
namespace System.Drawing.Imaging { public static class ImageFlags { } }
namespace System.Drawing.Imaging { public static class ImageFormat { } }
namespace System.Drawing.Imaging { public static class ImageLockMode { } }
namespace System.Drawing.Imaging { public static class MetaHeader { } }
namespace System.Drawing.Imaging { public static class Metafile { } }
namespace System.Drawing.Imaging { public static class MetafileFrameUnit { } }
namespace System.Drawing.Imaging { public static class MetafileHeader { } }
namespace System.Drawing.Imaging { public static class MetafileType { } }
namespace System.Drawing.Imaging { public static class PaletteFlags { } }
namespace System.Drawing.Imaging { public static class PixelFormat { } }
namespace System.Drawing.Imaging { public static class PlayRecordCallback { } }
namespace System.Drawing.Imaging { public static class PropertyItem { } }
namespace System.Drawing.Imaging { public static class WmfPlaceableFileHeader { } }
namespace System.Drawing { public static class Pen { } }
namespace System.Drawing { public static class Pens { } }
namespace System.Drawing.Printing { public static class Duplex { } }
namespace System.Drawing.Printing { public static class InvalidPrinterException { } }
namespace System.Drawing.Printing { public static class Margins { } }
namespace System.Drawing.Printing { public static class MarginsConverter { } }
namespace System.Drawing.Printing { public static class PageSettings { } }
namespace System.Drawing.Printing { public static class PaperKind { } }
namespace System.Drawing.Printing { public static class PaperSize { } }
namespace System.Drawing.Printing { public static class PaperSource { } }
namespace System.Drawing.Printing { public static class PaperSourceKind { } }
namespace System.Drawing.Printing { public static class PreviewPageInfo { } }
namespace System.Drawing.Printing { public static class PreviewPrintController { } }
namespace System.Drawing.Printing { public static class PrintAction { } }
namespace System.Drawing.Printing { public static class PrintController { } }
namespace System.Drawing.Printing { public static class PrintDocument { } }
namespace System.Drawing.Printing { public static class PrintEventArgs { } }
namespace System.Drawing.Printing { public static class PrintEventHandler { } }
namespace System.Drawing.Printing { public static class PrintPageEventArgs { } }
namespace System.Drawing.Printing { public static class PrintPageEventHandler { } }
namespace System.Drawing.Printing { public static class PrintRange { } }
namespace System.Drawing.Printing { public static class PrinterResolution { } }
namespace System.Drawing.Printing { public static class PrinterResolutionKind { } }
namespace System.Drawing.Printing { public static class PrinterSettings { public static class PaperSizeCollection { } public static class PaperSourceCollection { } public static class PrinterResolutionCollection { } public static class StringCollection { } } }
namespace System.Drawing.Printing { public static class PrinterUnit { } }
namespace System.Drawing.Printing { public static class PrinterUnitConvert { } }
namespace System.Drawing.Printing { public static class QueryPageSettingsEventArgs { } }
namespace System.Drawing.Printing { public static class QueryPageSettingsEventHandler { } }
namespace System.Drawing.Printing { public static class StandardPrintController { } }
namespace System.Drawing { public static class Region { } }
namespace System.Drawing { public static class RotateFlipType { } }
namespace System.Drawing { public static class SolidBrush { } }
namespace System.Drawing { public static class StringAlignment { } }
namespace System.Drawing { public static class StringDigitSubstitute { } }
namespace System.Drawing { public static class StringFormat { } }
namespace System.Drawing { public static class StringFormatFlags { } }
namespace System.Drawing { public static class StringTrimming { } }
namespace System.Drawing { public static class StringUnit { } }
namespace System.Drawing { public static class SystemBrushes { } }
namespace System.Drawing { public static class SystemFonts { } }
namespace System.Drawing { public static class SystemIcons { } }
namespace System.Drawing { public static class SystemPens { } }
namespace System.Drawing.Text { public static class FontCollection { } }
namespace System.Drawing.Text { public static class GenericFontFamilies { } }
namespace System.Drawing.Text { public static class HotkeyPrefix { } }
namespace System.Drawing.Text { public static class InstalledFontCollection { } }
namespace System.Drawing.Text { public static class PrivateFontCollection { } }
namespace System.Drawing.Text { public static class TextRenderingHint { } }
namespace System.Drawing { public static class TextureBrush { } }
namespace System.Drawing { public static class ToolboxBitmapAttribute { } }
