load("//src/tests:live_test.bzl", "library_test")

library_test(
    name = "System.IO.Compression.ZipFile.Tests",
    srcs = glob(["**/*.cs"]) + [
        "//src/libraries/Common/tests:System/IO/TempFile.cs",
        "//src/libraries/Common/tests:System/IO/TempDirectory.cs",
        "//src/libraries/Common/tests:System/IO/WrappedStream.cs",
        "//src/libraries/Common/tests:System/IO/Compression/CRC.cs",
        "//src/libraries/Common/tests:System/IO/Compression/FileData.cs",
        "//src/libraries/Common/tests:System/IO/Compression/LocalMemoryStream.cs",
        "//src/libraries/Common/tests:System/IO/Compression/StreamHelpers.cs",
        "//src/libraries/Common/tests:System/IO/Compression/ZipTestHelper.cs",
        "//src/libraries/Common/tests:System/IO/Compression/ZipTestHelper.ZipFile.cs",
        "//src/libraries/Common:src/DisableRuntimeMarshalling.cs",
        "//src/libraries/Common:src/Interop/Unix/Interop.Libraries.cs",
        "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Stat.cs",
    ],
    deps = [
        "//src/libraries/System.IO.Compression.ZipFile:ref_System.IO.Compression.ZipFile",
        "//src/libraries/System.IO.Compression:ref_System.IO.Compression",
        "//src/libraries/System.Collections.Concurrent:ref_System.Collections.Concurrent",
        "//src/libraries/System.Collections.Immutable:ref_System.Collections.Immutable",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/System.Threading.Thread:ref_System.Threading.Thread",
        "//src/libraries/Common/tests:TestUtilities",
        "@paket.main//microsoft.dotnet.remoteexecutor",
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//microsoft.dotnet.xunitextensions",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    allow_unsafe_blocks = True,
    analyzers = [
        "//src/libraries/System.Runtime.InteropServices:LibraryImportGenerator",
        "//src/libraries/System.Runtime.InteropServices:Microsoft.Interop.SourceGeneration",
    ],
    data = ["@paket.main//system.io.compression.testdata:content_files"],
    size = "large",
    writable_test_dir = True,
    keyfile = "@nuget.microsoft.dotnet.arcade.sdk.v10.0.0-beta.26102.102//:tools/snk/Open.snk",
)
