load("//src/libraries:defs.bzl", "netcoreapp_impl_assembly")

netcoreapp_impl_assembly(
    name = "impl_netstandard",
    skip_cs1591 = True,
    srcs = [
        "src/netstandard.cs",
        "//src/libraries/shims:System.Void.cs",
    ],
    deps = [
        "//src/libraries:ref_Microsoft.Win32.Primitives",
        "//src/libraries:ref_System.ComponentModel.Primitives",
        "//src/libraries:ref_System.Diagnostics.Process",
        "//src/libraries:ref_System.Linq.Expressions",
        "//src/libraries:ref_System.Runtime",
        "//src/libraries:ref_System.Text.RegularExpressions",
        "//src/libraries/System.Collections:ref_System.Collections",
        "//src/libraries/System.Collections.Concurrent:ref_System.Collections.Concurrent",
        "//src/libraries/System.Collections.NonGeneric:ref_System.Collections.NonGeneric",
        "//src/libraries/System.Collections.Specialized:ref_System.Collections.Specialized",
        "//src/libraries/System.ComponentModel:ref_System.ComponentModel",
        "//src/libraries/System.ComponentModel.EventBasedAsync:ref_System.ComponentModel.EventBasedAsync",
        "//src/libraries/System.ComponentModel.TypeConverter:ref_System.ComponentModel.TypeConverter",
        "//src/libraries/System.Console:ref_System.Console",
        "//src/libraries/System.Data.Common:ref_System.Data.Common",
        "//src/libraries/System.Diagnostics.Contracts:ref_System.Diagnostics.Contracts",
        "//src/libraries/System.Diagnostics.FileVersionInfo:ref_System.Diagnostics.FileVersionInfo",
        "//src/libraries/System.Diagnostics.StackTrace:ref_System.Diagnostics.StackTrace",
        "//src/libraries/System.Diagnostics.TextWriterTraceListener:ref_System.Diagnostics.TextWriterTraceListener",
        "//src/libraries/System.Diagnostics.TraceSource:ref_System.Diagnostics.TraceSource",
        "//src/libraries/System.Diagnostics.Tracing:ref_System.Diagnostics.Tracing",
        "//src/libraries/System.Drawing.Primitives:ref_System.Drawing.Primitives",
        "//src/libraries/System.IO.Compression:ref_System.IO.Compression",
        "//src/libraries/System.IO.Compression.Brotli:ref_System.IO.Compression.Brotli",
        "//src/libraries/System.IO.Compression.ZipFile:ref_System.IO.Compression.ZipFile",
        "//src/libraries/System.IO.FileSystem.DriveInfo:ref_System.IO.FileSystem.DriveInfo",
        "//src/libraries/System.IO.FileSystem.Watcher:ref_System.IO.FileSystem.Watcher",
        "//src/libraries/System.IO.IsolatedStorage:ref_System.IO.IsolatedStorage",
        "//src/libraries/System.IO.MemoryMappedFiles:ref_System.IO.MemoryMappedFiles",
        "//src/libraries/System.IO.Pipes:ref_System.IO.Pipes",
        "//src/libraries/System.Linq:ref_System.Linq",
        "//src/libraries/System.Linq.Parallel:ref_System.Linq.Parallel",
        "//src/libraries/System.Linq.Queryable:ref_System.Linq.Queryable",
        "//src/libraries/System.Memory:ref_System.Memory",
        "//src/libraries/System.Net.Http:ref_System.Net.Http",
        "//src/libraries/System.Net.HttpListener:ref_System.Net.HttpListener",
        "//src/libraries/System.Net.Mail:ref_System.Net.Mail",
        "//src/libraries/System.Net.NameResolution:ref_System.Net.NameResolution",
        "//src/libraries/System.Net.NetworkInformation:ref_System.Net.NetworkInformation",
        "//src/libraries/System.Net.Ping:ref_System.Net.Ping",
        "//src/libraries/System.Net.Primitives:ref_System.Net.Primitives",
        "//src/libraries/System.Net.Requests:ref_System.Net.Requests",
        "//src/libraries/System.Net.Security:ref_System.Net.Security",
        "//src/libraries/System.Net.Sockets:ref_System.Net.Sockets",
        "//src/libraries/System.Net.WebHeaderCollection:ref_System.Net.WebHeaderCollection",
        "//src/libraries/System.Net.WebClient:ref_System.Net.WebClient",
        "//src/libraries/System.Net.WebProxy:ref_System.Net.WebProxy",
        "//src/libraries/System.Net.WebSockets:ref_System.Net.WebSockets",
        "//src/libraries/System.Net.WebSockets.Client:ref_System.Net.WebSockets.Client",
        "//src/libraries/System.Numerics.Vectors:ref_System.Numerics.Vectors",
        "//src/libraries/System.ObjectModel:ref_System.ObjectModel",
        "//src/libraries/System.Reflection.DispatchProxy:ref_System.Reflection.DispatchProxy",
        "//src/libraries/System.Reflection.Emit:ref_System.Reflection.Emit",
        "//src/libraries/System.Reflection.Emit.ILGeneration:ref_System.Reflection.Emit.ILGeneration",
        "//src/libraries/System.Reflection.Emit.Lightweight:ref_System.Reflection.Emit.Lightweight",
        "//src/libraries/System.Reflection.Primitives:ref_System.Reflection.Primitives",
        "//src/libraries/System.Resources.Writer:ref_System.Resources.Writer",
        "//src/libraries/System.Runtime.CompilerServices.VisualC:ref_System.Runtime.CompilerServices.VisualC",
        "//src/libraries/System.Runtime.InteropServices:ref_System.Runtime.InteropServices",
        "//src/libraries/System.Runtime.Numerics:ref_System.Runtime.Numerics",
        "//src/libraries/System.Runtime.Serialization.Formatters:ref_System.Runtime.Serialization.Formatters",
        "//src/libraries/System.Runtime.Serialization.Json:ref_System.Runtime.Serialization.Json",
        "//src/libraries/System.Runtime.Serialization.Primitives:ref_System.Runtime.Serialization.Primitives",
        "//src/libraries/System.Runtime.Serialization.Xml:ref_System.Runtime.Serialization.Xml",
        "//src/libraries/System.Security.Claims:ref_System.Security.Claims",
        "//src/libraries/System.Security.Cryptography:ref_System.Security.Cryptography",
        "//src/libraries/System.Text.Encoding.Extensions:ref_System.Text.Encoding.Extensions",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/System.Threading.Overlapped:ref_System.Threading.Overlapped",
        "//src/libraries/System.Threading.Tasks.Parallel:ref_System.Threading.Tasks.Parallel",
        "//src/libraries/System.Threading.Thread:ref_System.Threading.Thread",
        "//src/libraries/System.Threading.ThreadPool:ref_System.Threading.ThreadPool",
        "//src/libraries/System.Transactions.Local:ref_System.Transactions.Local",
        "//src/libraries/System.Web.HttpUtility:ref_System.Web.HttpUtility",
        "//src/libraries/System.Xml.ReaderWriter:ref_System.Xml.ReaderWriter",
        "//src/libraries/System.Xml.XDocument:ref_System.Xml.XDocument",
        "//src/libraries/System.Xml.XmlSerializer:ref_System.Xml.XmlSerializer",
        "//src/libraries/System.Xml.XPath:ref_System.Xml.XPath",
        "//src/libraries/System.Xml.XPath.XDocument:ref_System.Xml.XPath.XDocument",
    ],
    os_targeted = True,
    exclude_sr = True,
    keyfile = "@nuget.microsoft.dotnet.arcade.sdk.v10.0.0-beta.26102.102//:tools/snk/Open.snk",
    assembly_version = "2.1.0.0",
)
