load("//:defs.bzl", "NETCOREAPP_CURRENT", "OPEN_SNK", "csharp_binary")

csharp_binary(
    name = "TestAppOutsideOfTPA",
    keyfile = OPEN_SNK,
    srcs = ["Program.cs"],
    include_default_ruleset = False,
    include_syslib_warnaserror = False,
    skip_analyzers = True,
    interceptors_namespaces = ";Microsoft.Extensions.Validation.Generated",
    msbuild_analyzer_config = "style",
    nowarn = ["IL2121", "SYSLIB0011", "SYSLIB0050", "SYSLIB0051"],
    nullable = "annotations",
    target_frameworks = [NETCOREAPP_CURRENT],
    deps = [
        "//src/libraries/System.Runtime/tests/System.Runtime.Extensions.Tests/AssemblyResolveTestApp",
    ],
    visibility = ["//src/libraries/System.Runtime/tests:__subpackages__"],
)
