load("//src/tests:live_test.bzl", "coreclr_test")

coreclr_test(
    name = "Crc32_r",
    srcs = ["Crc32.cs"],
    deps = [
        "//src/tests/Common:TestLibrary",
    
        "@paket.main//microsoft.dotnet.xunitextensions",
    ],
)

coreclr_test(
    name = "Crc32_ro",
    srcs = ["Crc32.cs"],
    optimize = True,
    deps = [
        "//src/tests/Common:TestLibrary",
    
        "@paket.main//microsoft.dotnet.xunitextensions",
    ],
)
