load("//src/libraries:defs.bzl", "netcoreapp_impl_assembly")

netcoreapp_impl_assembly(
    name = "impl_System.Private.DataContractSerialization",
    library_import_generator = False,
    analyzers = [
        "//src/libraries/System.Text.RegularExpressions:RegexGenerator",
    ],
    srcs = glob(["src/System/**/*.cs"]) + [
        "//src/libraries/Common:src/System/NotImplemented.cs",
        "//src/libraries/Common:src/System/HexConverter.cs",
        "//src/libraries/Common:src/System/CodeDom/CodeTypeReference.cs",
        "//src/libraries/Common:src/System/CodeDom/CodeTypeReferenceCollection.cs",
        "//src/libraries/Common:src/System/CodeDom/CodeObject.cs",
    ],
    resx_file = "src/Resources/Strings.resx",
    nowarn = ["CS0649", "CS1634", "CS1691", "CS1591"],
    allow_unsafe_blocks = True,
    deps = [
        "//src/libraries/System.Collections:ref_System.Collections",
        "//src/libraries/System.Collections.Concurrent:ref_System.Collections.Concurrent",
        "//src/libraries/System.Collections.NonGeneric:ref_System.Collections.NonGeneric",
        "//src/libraries/System.Collections.Specialized:ref_System.Collections.Specialized",
        "//src/libraries/System.Linq:ref_System.Linq",
        "//src/libraries/System.Memory:ref_System.Memory",
        "//src/libraries/System.Reflection.Emit.ILGeneration:ref_System.Reflection.Emit.ILGeneration",
        "//src/libraries/System.Reflection.Emit.Lightweight:ref_System.Reflection.Emit.Lightweight",
        "//src/libraries/System.Reflection.Primitives:ref_System.Reflection.Primitives",
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Runtime.Intrinsics:ref_System.Runtime.Intrinsics",
        "//src/libraries/System.Runtime.Loader:ref_System.Runtime.Loader",
        "//src/libraries/System.Runtime.Serialization.Formatters:ref_System.Runtime.Serialization.Formatters",
        "//src/libraries/System.Runtime.Serialization.Primitives:ref_System.Runtime.Serialization.Primitives",
        "//src/libraries/System.Text.Encoding.Extensions:ref_System.Text.Encoding.Extensions",
        "//src/libraries/System.Text.RegularExpressions:ref_System.Text.RegularExpressions",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/System.Threading.Thread:ref_System.Threading.Thread",
        "//src/libraries/System.Xml.ReaderWriter:ref_System.Xml.ReaderWriter",
        "//src/libraries/System.Xml.XDocument:ref_System.Xml.XDocument",
        "//src/libraries/System.Xml.XmlSerializer:ref_System.Xml.XmlSerializer",
    ],
)
