load("//src/libraries:defs.bzl", "COMMON_GENERATOR_ANALYZERS", "MULTITARGET_NOWARN", "netcoreapp_ref_assembly", "impl_assembly", "ref_impl_pair")

exports_files([
    "ref/Microsoft.Extensions.Logging.TraceSource.cs",
])

netcoreapp_ref_assembly(
    name = "ref_Microsoft.Extensions.Logging.TraceSource",
    srcs = [
        "ref/Microsoft.Extensions.Logging.TraceSource.cs",
    ],
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions:ref_Microsoft.Extensions.DependencyInjection.Abstractions",
        "//src/libraries/Microsoft.Extensions.Logging:ref_Microsoft.Extensions.Logging",
        "//src/libraries/Microsoft.Extensions.Logging.Abstractions:ref_Microsoft.Extensions.Logging.Abstractions",
        "//src/libraries/System.Diagnostics.TraceSource:ref_System.Diagnostics.TraceSource",
    ],
)

impl_assembly(
    name = "impl_Microsoft.Extensions.Logging.TraceSource",
    analyzers = COMMON_GENERATOR_ANALYZERS,
    nowarn = MULTITARGET_NOWARN + ["CP0003"],
    exclude_sr = True,
    srcs = glob(["src/**/*.cs"]),
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions:ref_Microsoft.Extensions.DependencyInjection.Abstractions",
        "//src/libraries/Microsoft.Extensions.Logging:ref_Microsoft.Extensions.Logging",
        "//src/libraries/Microsoft.Extensions.Logging.Abstractions:ref_Microsoft.Extensions.Logging.Abstractions",
        "//src/libraries/System.Collections:ref_System.Collections",
        "//src/libraries/System.Collections.Concurrent:ref_System.Collections.Concurrent",
        "//src/libraries/System.ComponentModel:ref_System.ComponentModel",
        "//src/libraries/System.Diagnostics.TraceSource:ref_System.Diagnostics.TraceSource",
        "//src/libraries/System.Memory:ref_System.Memory",
    ],
)

ref_impl_pair(
    name = "live_Microsoft.Extensions.Logging.TraceSource",
    ref = ":ref_Microsoft.Extensions.Logging.TraceSource",
    lib = ":impl_Microsoft.Extensions.Logging.TraceSource",
    visibility = ["//visibility:public"],
)
