
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

/******************************************************************

DO NOT MODIFY. AUTOGENERATED FILE.
This file is generated using the logic from <root>/src/scripts/genLttngProvider.py

******************************************************************/


#define TRACEPOINT_DEFINE
#define TRACEPOINT_PROBE_DYNAMIC_LINKAGE

#include "stdlib.h"
#include "pal_mstypes.h"
#include "pal_error.h"
#include "pal.h"
#include "pal/stackstring.hpp"
#include "tpdotnetruntimestress.h"

#ifndef tracepoint_enabled

extern "C" bool XplatEventLoggerIsEnabled();

#define tracepoint_enabled(provider, name) XplatEventLoggerIsEnabled()
#define do_tracepoint tracepoint
#endif

bool ResizeBuffer(char *&buffer, size_t& size, size_t currLen, size_t newSize, bool &fixedBuffer);
bool WriteToBuffer(PCWSTR str, char *&buffer, size_t& offset, size_t& size, bool &fixedBuffer);
bool WriteToBuffer(const char *str, char *&buffer, size_t& offset, size_t& size, bool &fixedBuffer);
bool WriteToBuffer(const BYTE *src, size_t len, char *&buffer, size_t& offset, size_t& size, bool &fixedBuffer);

template <typename T>
bool WriteToBuffer(const T &value, char *&buffer, size_t& offset, size_t& size, bool &fixedBuffer)
{
    if (sizeof(T) + offset > size)
    {
        if (!ResizeBuffer(buffer, size, offset, size + sizeof(T), fixedBuffer))
            return false;
    }

    memcpy(buffer + offset, (char *)&value, sizeof(T));
    offset += sizeof(T);
    return true;
}

// Local implementation of WCHAR (UTF-16) string length
static size_t lttng_strlen16(const WCHAR* string)
{
    size_t nChar = 0;
    while (*string++)
        nChar++;
    return nChar;
}
extern "C" BOOL  EventXplatEnabledStressLogEvent(){ return tracepoint_enabled(DotNETRuntimeStress, StressLogEvent); }

extern "C" ULONG  FireEtXplatStressLogEvent(
    const unsigned int Facility,
    const unsigned char LogLevel,
    LPCSTR Message)
{
    if (!EventXplatEnabledStressLogEvent())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeStress,
        StressLogEvent,
        Facility,
        LogLevel,
        Message);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledStressLogEvent_V1(){ return tracepoint_enabled(DotNETRuntimeStress, StressLogEvent_V1); }

extern "C" ULONG  FireEtXplatStressLogEvent_V1(
    const unsigned int Facility,
    const unsigned char LogLevel,
    LPCSTR Message,
    const unsigned short ClrInstanceID)
{
    if (!EventXplatEnabledStressLogEvent_V1())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeStress,
        StressLogEvent_V1,
        Facility,
        LogLevel,
        Message,
        ClrInstanceID);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledCLRStackWalkStress(){ return tracepoint_enabled(DotNETRuntimeStress, CLRStackWalkStress); }

extern "C" ULONG  FireEtXplatCLRStackWalkStress(
    const unsigned short ClrInstanceID,
    const unsigned char Reserved1,
    const unsigned char Reserved2,
    const unsigned int FrameCount,
    const void** Stack)
{
    if (!EventXplatEnabledCLRStackWalkStress())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeStress,
        CLRStackWalkStress,
        ClrInstanceID,
        Reserved1,
        Reserved2,
        FrameCount,
        (const size_t*) Stack);

    return ERROR_SUCCESS;
}


