
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

/******************************************************************

DO NOT MODIFY. AUTOGENERATED FILE.
This file is generated using the logic from <root>/src/scripts/genLttngProvider.py

******************************************************************/


#define TRACEPOINT_DEFINE
#define TRACEPOINT_PROBE_DYNAMIC_LINKAGE

#include "stdlib.h"
#include "pal_mstypes.h"
#include "pal_error.h"
#include "pal.h"
#include "pal/stackstring.hpp"
#include "tpdotnetruntimemonoprofiler.h"

#ifndef tracepoint_enabled

extern "C" bool XplatEventLoggerIsEnabled();

#define tracepoint_enabled(provider, name) XplatEventLoggerIsEnabled()
#define do_tracepoint tracepoint
#endif

bool ResizeBuffer(char *&buffer, size_t& size, size_t currLen, size_t newSize, bool &fixedBuffer);
bool WriteToBuffer(PCWSTR str, char *&buffer, size_t& offset, size_t& size, bool &fixedBuffer);
bool WriteToBuffer(const char *str, char *&buffer, size_t& offset, size_t& size, bool &fixedBuffer);
bool WriteToBuffer(const BYTE *src, size_t len, char *&buffer, size_t& offset, size_t& size, bool &fixedBuffer);

template <typename T>
bool WriteToBuffer(const T &value, char *&buffer, size_t& offset, size_t& size, bool &fixedBuffer)
{
    if (sizeof(T) + offset > size)
    {
        if (!ResizeBuffer(buffer, size, offset, size + sizeof(T), fixedBuffer))
            return false;
    }

    memcpy(buffer + offset, (char *)&value, sizeof(T));
    offset += sizeof(T);
    return true;
}

// Local implementation of WCHAR (UTF-16) string length
static size_t lttng_strlen16(const WCHAR* string)
{
    size_t nChar = 0;
    while (*string++)
        nChar++;
    return nChar;
}
extern "C" BOOL  EventXplatEnabledMonoProfilerContextLoaded(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerContextLoaded); }

extern "C" ULONG  FireEtXplatMonoProfilerContextLoaded(
    const void* ObjectID,
    const uint64_t AppDomainID,
    const uint64_t ContextID)
{
    if (!EventXplatEnabledMonoProfilerContextLoaded())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerContextLoaded,
        (const size_t) ObjectID,
        AppDomainID,
        ContextID);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerContextUnloaded(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerContextUnloaded); }

extern "C" ULONG  FireEtXplatMonoProfilerContextUnloaded(
    const void* ObjectID,
    const uint64_t AppDomainID,
    const uint64_t ContextID)
{
    if (!EventXplatEnabledMonoProfilerContextUnloaded())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerContextUnloaded,
        (const size_t) ObjectID,
        AppDomainID,
        ContextID);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerAppDomainLoading(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerAppDomainLoading); }

extern "C" ULONG  FireEtXplatMonoProfilerAppDomainLoading(
    const uint64_t AppDomainID)
{
    if (!EventXplatEnabledMonoProfilerAppDomainLoading())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerAppDomainLoading,
        AppDomainID);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerAppDomainLoaded(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerAppDomainLoaded); }

extern "C" ULONG  FireEtXplatMonoProfilerAppDomainLoaded(
    const uint64_t AppDomainID)
{
    if (!EventXplatEnabledMonoProfilerAppDomainLoaded())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerAppDomainLoaded,
        AppDomainID);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerAppDomainUnloading(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerAppDomainUnloading); }

extern "C" ULONG  FireEtXplatMonoProfilerAppDomainUnloading(
    const uint64_t AppDomainID)
{
    if (!EventXplatEnabledMonoProfilerAppDomainUnloading())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerAppDomainUnloading,
        AppDomainID);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerAppDomainUnloaded(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerAppDomainUnloaded); }

extern "C" ULONG  FireEtXplatMonoProfilerAppDomainUnloaded(
    const uint64_t AppDomainID)
{
    if (!EventXplatEnabledMonoProfilerAppDomainUnloaded())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerAppDomainUnloaded,
        AppDomainID);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerAppDomainName(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerAppDomainName); }

extern "C" ULONG  FireEtXplatMonoProfilerAppDomainName(
    const uint64_t AppDomainID,
    PCWSTR AppDomainName)
{
    if (!EventXplatEnabledMonoProfilerAppDomainName())
        return ERROR_SUCCESS;
    INT AppDomainName_path_size = -1;
    PathCharString AppDomainName_PS;
    INT AppDomainName_full_name_path_size = (lttng_strlen16(AppDomainName) + 1)*sizeof(WCHAR);
    CHAR* AppDomainName_full_name = AppDomainName_PS.OpenStringBuffer(AppDomainName_full_name_path_size );
    if (AppDomainName_full_name == NULL )    { return ERROR_WRITE_FAULT; }

    AppDomainName_path_size = WideCharToMultiByte( CP_ACP, 0, AppDomainName, -1, AppDomainName_full_name, AppDomainName_full_name_path_size, NULL, NULL );
    _ASSERTE(AppDomainName_path_size < AppDomainName_full_name_path_size );
    AppDomainName_PS.CloseBuffer(AppDomainName_path_size );
    if( AppDomainName_path_size == 0 ){ return ERROR_INVALID_PARAMETER; }
    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerAppDomainName,
        AppDomainID,
        AppDomainName_full_name);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerJitBegin(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerJitBegin); }

extern "C" ULONG  FireEtXplatMonoProfilerJitBegin(
    const uint64_t MethodID,
    const uint64_t ModuleID,
    const unsigned int MethodToken)
{
    if (!EventXplatEnabledMonoProfilerJitBegin())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerJitBegin,
        MethodID,
        ModuleID,
        MethodToken);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerJitFailed(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerJitFailed); }

extern "C" ULONG  FireEtXplatMonoProfilerJitFailed(
    const uint64_t MethodID,
    const uint64_t ModuleID,
    const unsigned int MethodToken)
{
    if (!EventXplatEnabledMonoProfilerJitFailed())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerJitFailed,
        MethodID,
        ModuleID,
        MethodToken);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerJitDone(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerJitDone); }

extern "C" ULONG  FireEtXplatMonoProfilerJitDone(
    const uint64_t MethodID,
    const uint64_t ModuleID,
    const unsigned int MethodToken)
{
    if (!EventXplatEnabledMonoProfilerJitDone())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerJitDone,
        MethodID,
        ModuleID,
        MethodToken);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerJitDone_V1(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerJitDone_V1); }

extern "C" ULONG  FireEtXplatMonoProfilerJitDone_V1(
    const uint64_t MethodID,
    const uint64_t ModuleID,
    const unsigned int MethodToken,
    const unsigned int Count,
    int Values_ElementSize,
    const void* Values)
{
    if (!EventXplatEnabledMonoProfilerJitDone_V1())
        return ERROR_SUCCESS;

    size_t size = 56;
    char stackBuffer[56];
    char *buffer = stackBuffer;
    size_t offset = 0;

    bool fixedBuffer = true;
    bool success = true;
    success &= WriteToBuffer(MethodID, buffer, offset, size, fixedBuffer);
    success &= WriteToBuffer(ModuleID, buffer, offset, size, fixedBuffer);
    success &= WriteToBuffer(MethodToken, buffer, offset, size, fixedBuffer);
    success &= WriteToBuffer(Count, buffer, offset, size, fixedBuffer);
    success &= WriteToBuffer((const BYTE *)Values, (int)Values_ElementSize * (int)Count, buffer, offset, size, fixedBuffer);

    if (!success)
    {
        if (!fixedBuffer)
            delete[] buffer;
        return ERROR_WRITE_FAULT;
    }

    do_tracepoint(DotNETRuntimeMonoProfiler, MonoProfilerJitDone_V1, offset, buffer);

    if (!fixedBuffer)
        delete[] buffer;

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerJitChunkCreated(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerJitChunkCreated); }

extern "C" ULONG  FireEtXplatMonoProfilerJitChunkCreated(
    const void* ChunkID,
    const uint64_t ChunkSize)
{
    if (!EventXplatEnabledMonoProfilerJitChunkCreated())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerJitChunkCreated,
        (const size_t) ChunkID,
        ChunkSize);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerJitChunkDestroyed(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerJitChunkDestroyed); }

extern "C" ULONG  FireEtXplatMonoProfilerJitChunkDestroyed(
    const void* ChunkID)
{
    if (!EventXplatEnabledMonoProfilerJitChunkDestroyed())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerJitChunkDestroyed,
        (const size_t) ChunkID);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerJitCodeBuffer(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerJitCodeBuffer); }

extern "C" ULONG  FireEtXplatMonoProfilerJitCodeBuffer(
    const void* BufferID,
    const uint64_t BufferSize,
    const unsigned char BufferType)
{
    if (!EventXplatEnabledMonoProfilerJitCodeBuffer())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerJitCodeBuffer,
        (const size_t) BufferID,
        BufferSize,
        BufferType);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerClassLoading(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerClassLoading); }

extern "C" ULONG  FireEtXplatMonoProfilerClassLoading(
    const uint64_t ClassID,
    const uint64_t ModuleID)
{
    if (!EventXplatEnabledMonoProfilerClassLoading())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerClassLoading,
        ClassID,
        ModuleID);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerClassFailed(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerClassFailed); }

extern "C" ULONG  FireEtXplatMonoProfilerClassFailed(
    const uint64_t ClassID,
    const uint64_t ModuleID)
{
    if (!EventXplatEnabledMonoProfilerClassFailed())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerClassFailed,
        ClassID,
        ModuleID);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerClassLoaded(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerClassLoaded); }

extern "C" ULONG  FireEtXplatMonoProfilerClassLoaded(
    const uint64_t ClassID,
    const uint64_t ModuleID,
    PCWSTR ClassName)
{
    if (!EventXplatEnabledMonoProfilerClassLoaded())
        return ERROR_SUCCESS;
    INT ClassName_path_size = -1;
    PathCharString ClassName_PS;
    INT ClassName_full_name_path_size = (lttng_strlen16(ClassName) + 1)*sizeof(WCHAR);
    CHAR* ClassName_full_name = ClassName_PS.OpenStringBuffer(ClassName_full_name_path_size );
    if (ClassName_full_name == NULL )    { return ERROR_WRITE_FAULT; }

    ClassName_path_size = WideCharToMultiByte( CP_ACP, 0, ClassName, -1, ClassName_full_name, ClassName_full_name_path_size, NULL, NULL );
    _ASSERTE(ClassName_path_size < ClassName_full_name_path_size );
    ClassName_PS.CloseBuffer(ClassName_path_size );
    if( ClassName_path_size == 0 ){ return ERROR_INVALID_PARAMETER; }
    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerClassLoaded,
        ClassID,
        ModuleID,
        ClassName_full_name);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerClassLoaded_V1(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerClassLoaded_V1); }

extern "C" ULONG  FireEtXplatMonoProfilerClassLoaded_V1(
    const uint64_t ClassID,
    const uint64_t ModuleID,
    PCWSTR ClassName,
    const unsigned int Count,
    int Values_ElementSize,
    const void* Values)
{
    if (!EventXplatEnabledMonoProfilerClassLoaded_V1())
        return ERROR_SUCCESS;

    size_t size = 116;
    char stackBuffer[116];
    char *buffer = stackBuffer;
    size_t offset = 0;

    bool fixedBuffer = true;
    bool success = true;
    success &= WriteToBuffer(ClassID, buffer, offset, size, fixedBuffer);
    success &= WriteToBuffer(ModuleID, buffer, offset, size, fixedBuffer);
    success &= WriteToBuffer(ClassName, buffer, offset, size, fixedBuffer);
    success &= WriteToBuffer(Count, buffer, offset, size, fixedBuffer);
    success &= WriteToBuffer((const BYTE *)Values, (int)Values_ElementSize * (int)Count, buffer, offset, size, fixedBuffer);

    if (!success)
    {
        if (!fixedBuffer)
            delete[] buffer;
        return ERROR_WRITE_FAULT;
    }

    do_tracepoint(DotNETRuntimeMonoProfiler, MonoProfilerClassLoaded_V1, offset, buffer);

    if (!fixedBuffer)
        delete[] buffer;

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerVTableLoading(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerVTableLoading); }

extern "C" ULONG  FireEtXplatMonoProfilerVTableLoading(
    const uint64_t VTableID,
    const uint64_t ClassID,
    const uint64_t AppDomainID)
{
    if (!EventXplatEnabledMonoProfilerVTableLoading())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerVTableLoading,
        VTableID,
        ClassID,
        AppDomainID);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerVTableFailed(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerVTableFailed); }

extern "C" ULONG  FireEtXplatMonoProfilerVTableFailed(
    const uint64_t VTableID,
    const uint64_t ClassID,
    const uint64_t AppDomainID)
{
    if (!EventXplatEnabledMonoProfilerVTableFailed())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerVTableFailed,
        VTableID,
        ClassID,
        AppDomainID);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerVTableLoaded(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerVTableLoaded); }

extern "C" ULONG  FireEtXplatMonoProfilerVTableLoaded(
    const uint64_t VTableID,
    const uint64_t ClassID,
    const uint64_t AppDomainID)
{
    if (!EventXplatEnabledMonoProfilerVTableLoaded())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerVTableLoaded,
        VTableID,
        ClassID,
        AppDomainID);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerModuleLoading(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerModuleLoading); }

extern "C" ULONG  FireEtXplatMonoProfilerModuleLoading(
    const uint64_t ModuleID)
{
    if (!EventXplatEnabledMonoProfilerModuleLoading())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerModuleLoading,
        ModuleID);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerModuleFailed(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerModuleFailed); }

extern "C" ULONG  FireEtXplatMonoProfilerModuleFailed(
    const uint64_t ModuleID)
{
    if (!EventXplatEnabledMonoProfilerModuleFailed())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerModuleFailed,
        ModuleID);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerModuleLoaded(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerModuleLoaded); }

extern "C" ULONG  FireEtXplatMonoProfilerModuleLoaded(
    const uint64_t ModuleID,
    PCWSTR ModuleName,
    PCWSTR ModuleSignature)
{
    if (!EventXplatEnabledMonoProfilerModuleLoaded())
        return ERROR_SUCCESS;
    INT ModuleName_path_size = -1;
    PathCharString ModuleName_PS;
    INT ModuleName_full_name_path_size = (lttng_strlen16(ModuleName) + 1)*sizeof(WCHAR);
    CHAR* ModuleName_full_name = ModuleName_PS.OpenStringBuffer(ModuleName_full_name_path_size );
    if (ModuleName_full_name == NULL )    { return ERROR_WRITE_FAULT; }
    INT ModuleSignature_path_size = -1;
    PathCharString ModuleSignature_PS;
    INT ModuleSignature_full_name_path_size = (lttng_strlen16(ModuleSignature) + 1)*sizeof(WCHAR);
    CHAR* ModuleSignature_full_name = ModuleSignature_PS.OpenStringBuffer(ModuleSignature_full_name_path_size );
    if (ModuleSignature_full_name == NULL )    { return ERROR_WRITE_FAULT; }

    ModuleName_path_size = WideCharToMultiByte( CP_ACP, 0, ModuleName, -1, ModuleName_full_name, ModuleName_full_name_path_size, NULL, NULL );
    _ASSERTE(ModuleName_path_size < ModuleName_full_name_path_size );
    ModuleName_PS.CloseBuffer(ModuleName_path_size );
    if( ModuleName_path_size == 0 ){ return ERROR_INVALID_PARAMETER; }
    ModuleSignature_path_size = WideCharToMultiByte( CP_ACP, 0, ModuleSignature, -1, ModuleSignature_full_name, ModuleSignature_full_name_path_size, NULL, NULL );
    _ASSERTE(ModuleSignature_path_size < ModuleSignature_full_name_path_size );
    ModuleSignature_PS.CloseBuffer(ModuleSignature_path_size );
    if( ModuleSignature_path_size == 0 ){ return ERROR_INVALID_PARAMETER; }
    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerModuleLoaded,
        ModuleID,
        ModuleName_full_name,
        ModuleSignature_full_name);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerModuleUnloading(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerModuleUnloading); }

extern "C" ULONG  FireEtXplatMonoProfilerModuleUnloading(
    const uint64_t ModuleID)
{
    if (!EventXplatEnabledMonoProfilerModuleUnloading())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerModuleUnloading,
        ModuleID);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerModuleUnloaded(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerModuleUnloaded); }

extern "C" ULONG  FireEtXplatMonoProfilerModuleUnloaded(
    const uint64_t ModuleID,
    PCWSTR ModuleName,
    PCWSTR ModuleSignature)
{
    if (!EventXplatEnabledMonoProfilerModuleUnloaded())
        return ERROR_SUCCESS;
    INT ModuleName_path_size = -1;
    PathCharString ModuleName_PS;
    INT ModuleName_full_name_path_size = (lttng_strlen16(ModuleName) + 1)*sizeof(WCHAR);
    CHAR* ModuleName_full_name = ModuleName_PS.OpenStringBuffer(ModuleName_full_name_path_size );
    if (ModuleName_full_name == NULL )    { return ERROR_WRITE_FAULT; }
    INT ModuleSignature_path_size = -1;
    PathCharString ModuleSignature_PS;
    INT ModuleSignature_full_name_path_size = (lttng_strlen16(ModuleSignature) + 1)*sizeof(WCHAR);
    CHAR* ModuleSignature_full_name = ModuleSignature_PS.OpenStringBuffer(ModuleSignature_full_name_path_size );
    if (ModuleSignature_full_name == NULL )    { return ERROR_WRITE_FAULT; }

    ModuleName_path_size = WideCharToMultiByte( CP_ACP, 0, ModuleName, -1, ModuleName_full_name, ModuleName_full_name_path_size, NULL, NULL );
    _ASSERTE(ModuleName_path_size < ModuleName_full_name_path_size );
    ModuleName_PS.CloseBuffer(ModuleName_path_size );
    if( ModuleName_path_size == 0 ){ return ERROR_INVALID_PARAMETER; }
    ModuleSignature_path_size = WideCharToMultiByte( CP_ACP, 0, ModuleSignature, -1, ModuleSignature_full_name, ModuleSignature_full_name_path_size, NULL, NULL );
    _ASSERTE(ModuleSignature_path_size < ModuleSignature_full_name_path_size );
    ModuleSignature_PS.CloseBuffer(ModuleSignature_path_size );
    if( ModuleSignature_path_size == 0 ){ return ERROR_INVALID_PARAMETER; }
    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerModuleUnloaded,
        ModuleID,
        ModuleName_full_name,
        ModuleSignature_full_name);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerAssemblyLoading(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerAssemblyLoading); }

extern "C" ULONG  FireEtXplatMonoProfilerAssemblyLoading(
    const uint64_t AssemblyID,
    const uint64_t ModuleID)
{
    if (!EventXplatEnabledMonoProfilerAssemblyLoading())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerAssemblyLoading,
        AssemblyID,
        ModuleID);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerAssemblyLoaded(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerAssemblyLoaded); }

extern "C" ULONG  FireEtXplatMonoProfilerAssemblyLoaded(
    const uint64_t AssemblyID,
    const uint64_t ModuleID,
    PCWSTR AssemblyName)
{
    if (!EventXplatEnabledMonoProfilerAssemblyLoaded())
        return ERROR_SUCCESS;
    INT AssemblyName_path_size = -1;
    PathCharString AssemblyName_PS;
    INT AssemblyName_full_name_path_size = (lttng_strlen16(AssemblyName) + 1)*sizeof(WCHAR);
    CHAR* AssemblyName_full_name = AssemblyName_PS.OpenStringBuffer(AssemblyName_full_name_path_size );
    if (AssemblyName_full_name == NULL )    { return ERROR_WRITE_FAULT; }

    AssemblyName_path_size = WideCharToMultiByte( CP_ACP, 0, AssemblyName, -1, AssemblyName_full_name, AssemblyName_full_name_path_size, NULL, NULL );
    _ASSERTE(AssemblyName_path_size < AssemblyName_full_name_path_size );
    AssemblyName_PS.CloseBuffer(AssemblyName_path_size );
    if( AssemblyName_path_size == 0 ){ return ERROR_INVALID_PARAMETER; }
    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerAssemblyLoaded,
        AssemblyID,
        ModuleID,
        AssemblyName_full_name);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerAssemblyUnloading(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerAssemblyUnloading); }

extern "C" ULONG  FireEtXplatMonoProfilerAssemblyUnloading(
    const uint64_t AssemblyID,
    const uint64_t ModuleID)
{
    if (!EventXplatEnabledMonoProfilerAssemblyUnloading())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerAssemblyUnloading,
        AssemblyID,
        ModuleID);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerAssemblyUnloaded(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerAssemblyUnloaded); }

extern "C" ULONG  FireEtXplatMonoProfilerAssemblyUnloaded(
    const uint64_t AssemblyID,
    const uint64_t ModuleID,
    PCWSTR AssemblyName)
{
    if (!EventXplatEnabledMonoProfilerAssemblyUnloaded())
        return ERROR_SUCCESS;
    INT AssemblyName_path_size = -1;
    PathCharString AssemblyName_PS;
    INT AssemblyName_full_name_path_size = (lttng_strlen16(AssemblyName) + 1)*sizeof(WCHAR);
    CHAR* AssemblyName_full_name = AssemblyName_PS.OpenStringBuffer(AssemblyName_full_name_path_size );
    if (AssemblyName_full_name == NULL )    { return ERROR_WRITE_FAULT; }

    AssemblyName_path_size = WideCharToMultiByte( CP_ACP, 0, AssemblyName, -1, AssemblyName_full_name, AssemblyName_full_name_path_size, NULL, NULL );
    _ASSERTE(AssemblyName_path_size < AssemblyName_full_name_path_size );
    AssemblyName_PS.CloseBuffer(AssemblyName_path_size );
    if( AssemblyName_path_size == 0 ){ return ERROR_INVALID_PARAMETER; }
    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerAssemblyUnloaded,
        AssemblyID,
        ModuleID,
        AssemblyName_full_name);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerMethodEnter(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerMethodEnter); }

extern "C" ULONG  FireEtXplatMonoProfilerMethodEnter(
    const uint64_t MethodID)
{
    if (!EventXplatEnabledMonoProfilerMethodEnter())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerMethodEnter,
        MethodID);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerMethodLeave(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerMethodLeave); }

extern "C" ULONG  FireEtXplatMonoProfilerMethodLeave(
    const uint64_t MethodID)
{
    if (!EventXplatEnabledMonoProfilerMethodLeave())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerMethodLeave,
        MethodID);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerMethodTailCall(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerMethodTailCall); }

extern "C" ULONG  FireEtXplatMonoProfilerMethodTailCall(
    const uint64_t MethodID)
{
    if (!EventXplatEnabledMonoProfilerMethodTailCall())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerMethodTailCall,
        MethodID);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerMethodExceptionLeave(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerMethodExceptionLeave); }

extern "C" ULONG  FireEtXplatMonoProfilerMethodExceptionLeave(
    const uint64_t MethodID)
{
    if (!EventXplatEnabledMonoProfilerMethodExceptionLeave())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerMethodExceptionLeave,
        MethodID);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerMethodFree(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerMethodFree); }

extern "C" ULONG  FireEtXplatMonoProfilerMethodFree(
    const uint64_t MethodID)
{
    if (!EventXplatEnabledMonoProfilerMethodFree())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerMethodFree,
        MethodID);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerMethodBeginInvoke(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerMethodBeginInvoke); }

extern "C" ULONG  FireEtXplatMonoProfilerMethodBeginInvoke(
    const uint64_t MethodID)
{
    if (!EventXplatEnabledMonoProfilerMethodBeginInvoke())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerMethodBeginInvoke,
        MethodID);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerMethodEndInvoke(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerMethodEndInvoke); }

extern "C" ULONG  FireEtXplatMonoProfilerMethodEndInvoke(
    const uint64_t MethodID)
{
    if (!EventXplatEnabledMonoProfilerMethodEndInvoke())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerMethodEndInvoke,
        MethodID);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerExceptionThrow(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerExceptionThrow); }

extern "C" ULONG  FireEtXplatMonoProfilerExceptionThrow(
    const uint64_t TypeID,
    const void* ObjectID)
{
    if (!EventXplatEnabledMonoProfilerExceptionThrow())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerExceptionThrow,
        TypeID,
        (const size_t) ObjectID);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerExceptionClause(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerExceptionClause); }

extern "C" ULONG  FireEtXplatMonoProfilerExceptionClause(
    const unsigned char ClauseType,
    const unsigned int ClauseIdx,
    const uint64_t MethodID,
    const uint64_t TypeID,
    const void* ObjectID)
{
    if (!EventXplatEnabledMonoProfilerExceptionClause())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerExceptionClause,
        ClauseType,
        ClauseIdx,
        MethodID,
        TypeID,
        (const size_t) ObjectID);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerGCEvent(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerGCEvent); }

extern "C" ULONG  FireEtXplatMonoProfilerGCEvent(
    const unsigned char GCEventType,
    const unsigned int GCGeneration)
{
    if (!EventXplatEnabledMonoProfilerGCEvent())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerGCEvent,
        GCEventType,
        GCGeneration);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerGCAllocation(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerGCAllocation); }

extern "C" ULONG  FireEtXplatMonoProfilerGCAllocation(
    const uint64_t VTableID,
    const void* ObjectID,
    const uint64_t ObjectSize)
{
    if (!EventXplatEnabledMonoProfilerGCAllocation())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerGCAllocation,
        VTableID,
        (const size_t) ObjectID,
        ObjectSize);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerGCMoves(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerGCMoves); }

extern "C" ULONG  FireEtXplatMonoProfilerGCMoves(
    const unsigned int Count,
    int Values_ElementSize,
    const void* Values)
{
    if (!EventXplatEnabledMonoProfilerGCMoves())
        return ERROR_SUCCESS;

    size_t size = 36;
    char stackBuffer[36];
    char *buffer = stackBuffer;
    size_t offset = 0;

    bool fixedBuffer = true;
    bool success = true;
    success &= WriteToBuffer(Count, buffer, offset, size, fixedBuffer);
    success &= WriteToBuffer((const BYTE *)Values, (int)Values_ElementSize * (int)Count, buffer, offset, size, fixedBuffer);

    if (!success)
    {
        if (!fixedBuffer)
            delete[] buffer;
        return ERROR_WRITE_FAULT;
    }

    do_tracepoint(DotNETRuntimeMonoProfiler, MonoProfilerGCMoves, offset, buffer);

    if (!fixedBuffer)
        delete[] buffer;

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerGCResize(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerGCResize); }

extern "C" ULONG  FireEtXplatMonoProfilerGCResize(
    const uint64_t NewSize)
{
    if (!EventXplatEnabledMonoProfilerGCResize())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerGCResize,
        NewSize);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerGCHandleCreated(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerGCHandleCreated); }

extern "C" ULONG  FireEtXplatMonoProfilerGCHandleCreated(
    const uint64_t HandleID,
    const unsigned char HandleType,
    const void* ObjectID)
{
    if (!EventXplatEnabledMonoProfilerGCHandleCreated())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerGCHandleCreated,
        HandleID,
        HandleType,
        (const size_t) ObjectID);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerGCHandleDeleted(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerGCHandleDeleted); }

extern "C" ULONG  FireEtXplatMonoProfilerGCHandleDeleted(
    const uint64_t HandleID,
    const unsigned char HandleType)
{
    if (!EventXplatEnabledMonoProfilerGCHandleDeleted())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerGCHandleDeleted,
        HandleID,
        HandleType);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerGCFinalizing(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerGCFinalizing); }

extern "C" ULONG  FireEtXplatMonoProfilerGCFinalizing(
)
{
    if (!EventXplatEnabledMonoProfilerGCFinalizing())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeMonoProfiler, MonoProfilerGCFinalizing);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerGCFinalized(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerGCFinalized); }

extern "C" ULONG  FireEtXplatMonoProfilerGCFinalized(
)
{
    if (!EventXplatEnabledMonoProfilerGCFinalized())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeMonoProfiler, MonoProfilerGCFinalized);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerGCFinalizingObject(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerGCFinalizingObject); }

extern "C" ULONG  FireEtXplatMonoProfilerGCFinalizingObject(
    const void* ObjectID)
{
    if (!EventXplatEnabledMonoProfilerGCFinalizingObject())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerGCFinalizingObject,
        (const size_t) ObjectID);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerGCFinalizedObject(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerGCFinalizedObject); }

extern "C" ULONG  FireEtXplatMonoProfilerGCFinalizedObject(
    const void* ObjectID)
{
    if (!EventXplatEnabledMonoProfilerGCFinalizedObject())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerGCFinalizedObject,
        (const size_t) ObjectID);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerGCRootRegister(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerGCRootRegister); }

extern "C" ULONG  FireEtXplatMonoProfilerGCRootRegister(
    const void* RootID,
    const uint64_t RootSize,
    const unsigned char RootType,
    const uint64_t RootKeyID,
    PCWSTR RootKeyName)
{
    if (!EventXplatEnabledMonoProfilerGCRootRegister())
        return ERROR_SUCCESS;
    INT RootKeyName_path_size = -1;
    PathCharString RootKeyName_PS;
    INT RootKeyName_full_name_path_size = (lttng_strlen16(RootKeyName) + 1)*sizeof(WCHAR);
    CHAR* RootKeyName_full_name = RootKeyName_PS.OpenStringBuffer(RootKeyName_full_name_path_size );
    if (RootKeyName_full_name == NULL )    { return ERROR_WRITE_FAULT; }

    RootKeyName_path_size = WideCharToMultiByte( CP_ACP, 0, RootKeyName, -1, RootKeyName_full_name, RootKeyName_full_name_path_size, NULL, NULL );
    _ASSERTE(RootKeyName_path_size < RootKeyName_full_name_path_size );
    RootKeyName_PS.CloseBuffer(RootKeyName_path_size );
    if( RootKeyName_path_size == 0 ){ return ERROR_INVALID_PARAMETER; }
    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerGCRootRegister,
        (const size_t) RootID,
        RootSize,
        RootType,
        RootKeyID,
        RootKeyName_full_name);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerGCRootUnregister(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerGCRootUnregister); }

extern "C" ULONG  FireEtXplatMonoProfilerGCRootUnregister(
    const void* RootID)
{
    if (!EventXplatEnabledMonoProfilerGCRootUnregister())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerGCRootUnregister,
        (const size_t) RootID);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerGCRoots(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerGCRoots); }

extern "C" ULONG  FireEtXplatMonoProfilerGCRoots(
    const unsigned int Count,
    int Values_ElementSize,
    const void* Values)
{
    if (!EventXplatEnabledMonoProfilerGCRoots())
        return ERROR_SUCCESS;

    size_t size = 36;
    char stackBuffer[36];
    char *buffer = stackBuffer;
    size_t offset = 0;

    bool fixedBuffer = true;
    bool success = true;
    success &= WriteToBuffer(Count, buffer, offset, size, fixedBuffer);
    success &= WriteToBuffer((const BYTE *)Values, (int)Values_ElementSize * (int)Count, buffer, offset, size, fixedBuffer);

    if (!success)
    {
        if (!fixedBuffer)
            delete[] buffer;
        return ERROR_WRITE_FAULT;
    }

    do_tracepoint(DotNETRuntimeMonoProfiler, MonoProfilerGCRoots, offset, buffer);

    if (!fixedBuffer)
        delete[] buffer;

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerGCHeapDumpStart(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerGCHeapDumpStart); }

extern "C" ULONG  FireEtXplatMonoProfilerGCHeapDumpStart(
    PCWSTR HeapCollectParam)
{
    if (!EventXplatEnabledMonoProfilerGCHeapDumpStart())
        return ERROR_SUCCESS;
    INT HeapCollectParam_path_size = -1;
    PathCharString HeapCollectParam_PS;
    INT HeapCollectParam_full_name_path_size = (lttng_strlen16(HeapCollectParam) + 1)*sizeof(WCHAR);
    CHAR* HeapCollectParam_full_name = HeapCollectParam_PS.OpenStringBuffer(HeapCollectParam_full_name_path_size );
    if (HeapCollectParam_full_name == NULL )    { return ERROR_WRITE_FAULT; }

    HeapCollectParam_path_size = WideCharToMultiByte( CP_ACP, 0, HeapCollectParam, -1, HeapCollectParam_full_name, HeapCollectParam_full_name_path_size, NULL, NULL );
    _ASSERTE(HeapCollectParam_path_size < HeapCollectParam_full_name_path_size );
    HeapCollectParam_PS.CloseBuffer(HeapCollectParam_path_size );
    if( HeapCollectParam_path_size == 0 ){ return ERROR_INVALID_PARAMETER; }
    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerGCHeapDumpStart,
        HeapCollectParam_full_name);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerGCHeapDumpStop(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerGCHeapDumpStop); }

extern "C" ULONG  FireEtXplatMonoProfilerGCHeapDumpStop(
)
{
    if (!EventXplatEnabledMonoProfilerGCHeapDumpStop())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeMonoProfiler, MonoProfilerGCHeapDumpStop);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerGCHeapDumpObjectReference(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerGCHeapDumpObjectReference); }

extern "C" ULONG  FireEtXplatMonoProfilerGCHeapDumpObjectReference(
    const void* ObjectID,
    const uint64_t VTableID,
    const uint64_t ObjectSize,
    const unsigned char ObjectGeneration,
    const unsigned int Count,
    int Values_ElementSize,
    const void* Values)
{
    if (!EventXplatEnabledMonoProfilerGCHeapDumpObjectReference())
        return ERROR_SUCCESS;

    size_t size = 61;
    char stackBuffer[61];
    char *buffer = stackBuffer;
    size_t offset = 0;

    bool fixedBuffer = true;
    bool success = true;
    success &= WriteToBuffer(ObjectID, buffer, offset, size, fixedBuffer);
    success &= WriteToBuffer(VTableID, buffer, offset, size, fixedBuffer);
    success &= WriteToBuffer(ObjectSize, buffer, offset, size, fixedBuffer);
    success &= WriteToBuffer(ObjectGeneration, buffer, offset, size, fixedBuffer);
    success &= WriteToBuffer(Count, buffer, offset, size, fixedBuffer);
    success &= WriteToBuffer((const BYTE *)Values, (int)Values_ElementSize * (int)Count, buffer, offset, size, fixedBuffer);

    if (!success)
    {
        if (!fixedBuffer)
            delete[] buffer;
        return ERROR_WRITE_FAULT;
    }

    do_tracepoint(DotNETRuntimeMonoProfiler, MonoProfilerGCHeapDumpObjectReference, offset, buffer);

    if (!fixedBuffer)
        delete[] buffer;

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerMonitorContention(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerMonitorContention); }

extern "C" ULONG  FireEtXplatMonoProfilerMonitorContention(
    const void* ObjectID)
{
    if (!EventXplatEnabledMonoProfilerMonitorContention())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerMonitorContention,
        (const size_t) ObjectID);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerMonitorFailed(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerMonitorFailed); }

extern "C" ULONG  FireEtXplatMonoProfilerMonitorFailed(
    const void* ObjectID)
{
    if (!EventXplatEnabledMonoProfilerMonitorFailed())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerMonitorFailed,
        (const size_t) ObjectID);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerMonitorAcquired(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerMonitorAcquired); }

extern "C" ULONG  FireEtXplatMonoProfilerMonitorAcquired(
    const void* ObjectID)
{
    if (!EventXplatEnabledMonoProfilerMonitorAcquired())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerMonitorAcquired,
        (const size_t) ObjectID);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerThreadStarted(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerThreadStarted); }

extern "C" ULONG  FireEtXplatMonoProfilerThreadStarted(
    const uint64_t ThreadID)
{
    if (!EventXplatEnabledMonoProfilerThreadStarted())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerThreadStarted,
        ThreadID);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerThreadStopping(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerThreadStopping); }

extern "C" ULONG  FireEtXplatMonoProfilerThreadStopping(
    const uint64_t ThreadID)
{
    if (!EventXplatEnabledMonoProfilerThreadStopping())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerThreadStopping,
        ThreadID);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerThreadStopped(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerThreadStopped); }

extern "C" ULONG  FireEtXplatMonoProfilerThreadStopped(
    const uint64_t ThreadID)
{
    if (!EventXplatEnabledMonoProfilerThreadStopped())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerThreadStopped,
        ThreadID);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerThreadExited(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerThreadExited); }

extern "C" ULONG  FireEtXplatMonoProfilerThreadExited(
    const uint64_t ThreadID)
{
    if (!EventXplatEnabledMonoProfilerThreadExited())
        return ERROR_SUCCESS;

    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerThreadExited,
        ThreadID);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerThreadName(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerThreadName); }

extern "C" ULONG  FireEtXplatMonoProfilerThreadName(
    const uint64_t ThreadID,
    PCWSTR ThreadName)
{
    if (!EventXplatEnabledMonoProfilerThreadName())
        return ERROR_SUCCESS;
    INT ThreadName_path_size = -1;
    PathCharString ThreadName_PS;
    INT ThreadName_full_name_path_size = (lttng_strlen16(ThreadName) + 1)*sizeof(WCHAR);
    CHAR* ThreadName_full_name = ThreadName_PS.OpenStringBuffer(ThreadName_full_name_path_size );
    if (ThreadName_full_name == NULL )    { return ERROR_WRITE_FAULT; }

    ThreadName_path_size = WideCharToMultiByte( CP_ACP, 0, ThreadName, -1, ThreadName_full_name, ThreadName_full_name_path_size, NULL, NULL );
    _ASSERTE(ThreadName_path_size < ThreadName_full_name_path_size );
    ThreadName_PS.CloseBuffer(ThreadName_path_size );
    if( ThreadName_path_size == 0 ){ return ERROR_INVALID_PARAMETER; }
    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerThreadName,
        ThreadID,
        ThreadName_full_name);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerJitDoneVerbose(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerJitDoneVerbose); }

extern "C" ULONG  FireEtXplatMonoProfilerJitDoneVerbose(
    const uint64_t MethodID,
    PCWSTR MethodNamespace,
    PCWSTR MethodName,
    PCWSTR MethodSignature)
{
    if (!EventXplatEnabledMonoProfilerJitDoneVerbose())
        return ERROR_SUCCESS;
    INT MethodNamespace_path_size = -1;
    PathCharString MethodNamespace_PS;
    INT MethodNamespace_full_name_path_size = (lttng_strlen16(MethodNamespace) + 1)*sizeof(WCHAR);
    CHAR* MethodNamespace_full_name = MethodNamespace_PS.OpenStringBuffer(MethodNamespace_full_name_path_size );
    if (MethodNamespace_full_name == NULL )    { return ERROR_WRITE_FAULT; }
    INT MethodName_path_size = -1;
    PathCharString MethodName_PS;
    INT MethodName_full_name_path_size = (lttng_strlen16(MethodName) + 1)*sizeof(WCHAR);
    CHAR* MethodName_full_name = MethodName_PS.OpenStringBuffer(MethodName_full_name_path_size );
    if (MethodName_full_name == NULL )    { return ERROR_WRITE_FAULT; }
    INT MethodSignature_path_size = -1;
    PathCharString MethodSignature_PS;
    INT MethodSignature_full_name_path_size = (lttng_strlen16(MethodSignature) + 1)*sizeof(WCHAR);
    CHAR* MethodSignature_full_name = MethodSignature_PS.OpenStringBuffer(MethodSignature_full_name_path_size );
    if (MethodSignature_full_name == NULL )    { return ERROR_WRITE_FAULT; }

    MethodNamespace_path_size = WideCharToMultiByte( CP_ACP, 0, MethodNamespace, -1, MethodNamespace_full_name, MethodNamespace_full_name_path_size, NULL, NULL );
    _ASSERTE(MethodNamespace_path_size < MethodNamespace_full_name_path_size );
    MethodNamespace_PS.CloseBuffer(MethodNamespace_path_size );
    if( MethodNamespace_path_size == 0 ){ return ERROR_INVALID_PARAMETER; }
    MethodName_path_size = WideCharToMultiByte( CP_ACP, 0, MethodName, -1, MethodName_full_name, MethodName_full_name_path_size, NULL, NULL );
    _ASSERTE(MethodName_path_size < MethodName_full_name_path_size );
    MethodName_PS.CloseBuffer(MethodName_path_size );
    if( MethodName_path_size == 0 ){ return ERROR_INVALID_PARAMETER; }
    MethodSignature_path_size = WideCharToMultiByte( CP_ACP, 0, MethodSignature, -1, MethodSignature_full_name, MethodSignature_full_name_path_size, NULL, NULL );
    _ASSERTE(MethodSignature_path_size < MethodSignature_full_name_path_size );
    MethodSignature_PS.CloseBuffer(MethodSignature_path_size );
    if( MethodSignature_path_size == 0 ){ return ERROR_INVALID_PARAMETER; }
    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerJitDoneVerbose,
        MethodID,
        MethodNamespace_full_name,
        MethodName_full_name,
        MethodSignature_full_name);

    return ERROR_SUCCESS;
}

extern "C" BOOL  EventXplatEnabledMonoProfilerGCHeapDumpVTableClassReference(){ return tracepoint_enabled(DotNETRuntimeMonoProfiler, MonoProfilerGCHeapDumpVTableClassReference); }

extern "C" ULONG  FireEtXplatMonoProfilerGCHeapDumpVTableClassReference(
    const uint64_t VTableID,
    const uint64_t ClassID,
    const uint64_t ModuleID,
    PCWSTR ClassName)
{
    if (!EventXplatEnabledMonoProfilerGCHeapDumpVTableClassReference())
        return ERROR_SUCCESS;
    INT ClassName_path_size = -1;
    PathCharString ClassName_PS;
    INT ClassName_full_name_path_size = (lttng_strlen16(ClassName) + 1)*sizeof(WCHAR);
    CHAR* ClassName_full_name = ClassName_PS.OpenStringBuffer(ClassName_full_name_path_size );
    if (ClassName_full_name == NULL )    { return ERROR_WRITE_FAULT; }

    ClassName_path_size = WideCharToMultiByte( CP_ACP, 0, ClassName, -1, ClassName_full_name, ClassName_full_name_path_size, NULL, NULL );
    _ASSERTE(ClassName_path_size < ClassName_full_name_path_size );
    ClassName_PS.CloseBuffer(ClassName_path_size );
    if( ClassName_path_size == 0 ){ return ERROR_INVALID_PARAMETER; }
    do_tracepoint(DotNETRuntimeMonoProfiler,
        MonoProfilerGCHeapDumpVTableClassReference,
        VTableID,
        ClassID,
        ModuleID,
        ClassName_full_name);

    return ERROR_SUCCESS;
}


