
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

/******************************************************************

DO NOT MODIFY. AUTOGENERATED FILE.
This file is generated using the logic from <root>/src/scripts/genLttngProvider.py

******************************************************************/


#include "palrt.h"
#include "pal.h"

#undef TRACEPOINT_PROVIDER

#define TRACEPOINT_PROVIDER DotNETRuntimeRundown


#undef TRACEPOINT_INCLUDE
#define TRACEPOINT_INCLUDE "./tpdotnetruntimerundown.h"

#if !defined(LTTNG_CORECLR_HDotNETRuntimeRundown) || defined(TRACEPOINT_HEADER_MULTI_READ)

#define LTTNG_CORECLR_HDotNETRuntimeRundown

#include <lttng/tracepoint.h>


#define GCSettingsRundown_TRACEPOINT_ARGS \
TP_ARGS( \
        const uint64_t, HardLimit, \
        const uint64_t, LOHThreshold, \
        const uint64_t, PhysicalMemoryConfig, \
        const uint64_t, Gen0MinBudgetConfig, \
        const uint64_t, Gen0MaxBudgetConfig, \
        const unsigned int, HighMemPercentConfig, \
        const unsigned int, BitSettings, \
        const unsigned short, ClrInstanceID \
)
TRACEPOINT_EVENT_CLASS(
    DotNETRuntimeRundown,
    GCSettingsRundown,
    GCSettingsRundown_TRACEPOINT_ARGS,
     TP_FIELDS(
        ctf_integer(uint64_t, HardLimit, HardLimit)
        ctf_integer(uint64_t, LOHThreshold, LOHThreshold)
        ctf_integer(uint64_t, PhysicalMemoryConfig, PhysicalMemoryConfig)
        ctf_integer(uint64_t, Gen0MinBudgetConfig, Gen0MinBudgetConfig)
        ctf_integer(uint64_t, Gen0MaxBudgetConfig, Gen0MaxBudgetConfig)
        ctf_integer(unsigned int, HighMemPercentConfig, HighMemPercentConfig)
        ctf_integer(unsigned int, BitSettings, BitSettings)
        ctf_integer(unsigned short, ClrInstanceID, ClrInstanceID)
    )
)

#define GCSettingsRundownT_TRACEPOINT_INSTANCE(name) \
TRACEPOINT_EVENT_INSTANCE(\
    DotNETRuntimeRundown,\
    GCSettingsRundown,\
    name ,\
    GCSettingsRundown_TRACEPOINT_ARGS \
)
#define RuntimeInformationRundown_TRACEPOINT_ARGS \
TP_ARGS( \
        const unsigned int, length, \
        const char *, __data__ \
)
TRACEPOINT_EVENT_CLASS(
    DotNETRuntimeRundown,
    RuntimeInformationRundown,
    RuntimeInformationRundown_TRACEPOINT_ARGS,
     TP_FIELDS(
        ctf_integer(ULONG, length, length)
        ctf_sequence(char, __data__, __data__, ULONG, length)
    )
)

#define RuntimeInformationRundownT_TRACEPOINT_INSTANCE(name) \
TRACEPOINT_EVENT_INSTANCE(\
    DotNETRuntimeRundown,\
    RuntimeInformationRundown,\
    name ,\
    RuntimeInformationRundown_TRACEPOINT_ARGS \
)
#define DomainModuleLoadUnloadRundown_TRACEPOINT_ARGS \
TP_ARGS( \
        const uint64_t, ModuleID, \
        const uint64_t, AssemblyID, \
        const uint64_t, AppDomainID, \
        const unsigned int, ModuleFlags, \
        const unsigned int, Reserved1, \
        const char*, ModuleILPath, \
        const char*, ModuleNativePath \
)
TRACEPOINT_EVENT_CLASS(
    DotNETRuntimeRundown,
    DomainModuleLoadUnloadRundown,
    DomainModuleLoadUnloadRundown_TRACEPOINT_ARGS,
     TP_FIELDS(
        ctf_integer(uint64_t, ModuleID, ModuleID)
        ctf_integer(uint64_t, AssemblyID, AssemblyID)
        ctf_integer(uint64_t, AppDomainID, AppDomainID)
        ctf_integer(unsigned int, ModuleFlags, ModuleFlags)
        ctf_integer(unsigned int, Reserved1, Reserved1)
        ctf_string(ModuleILPath, ModuleILPath)
        ctf_string(ModuleNativePath, ModuleNativePath)
    )
)

#define DomainModuleLoadUnloadRundownT_TRACEPOINT_INSTANCE(name) \
TRACEPOINT_EVENT_INSTANCE(\
    DotNETRuntimeRundown,\
    DomainModuleLoadUnloadRundown,\
    name ,\
    DomainModuleLoadUnloadRundown_TRACEPOINT_ARGS \
)
#define DomainModuleLoadUnloadRundown_V1_TRACEPOINT_ARGS \
TP_ARGS( \
        const uint64_t, ModuleID, \
        const uint64_t, AssemblyID, \
        const uint64_t, AppDomainID, \
        const unsigned int, ModuleFlags, \
        const unsigned int, Reserved1, \
        const char*, ModuleILPath, \
        const char*, ModuleNativePath, \
        const unsigned short, ClrInstanceID \
)
TRACEPOINT_EVENT_CLASS(
    DotNETRuntimeRundown,
    DomainModuleLoadUnloadRundown_V1,
    DomainModuleLoadUnloadRundown_V1_TRACEPOINT_ARGS,
     TP_FIELDS(
        ctf_integer(uint64_t, ModuleID, ModuleID)
        ctf_integer(uint64_t, AssemblyID, AssemblyID)
        ctf_integer(uint64_t, AppDomainID, AppDomainID)
        ctf_integer(unsigned int, ModuleFlags, ModuleFlags)
        ctf_integer(unsigned int, Reserved1, Reserved1)
        ctf_string(ModuleILPath, ModuleILPath)
        ctf_string(ModuleNativePath, ModuleNativePath)
        ctf_integer(unsigned short, ClrInstanceID, ClrInstanceID)
    )
)

#define DomainModuleLoadUnloadRundown_V1T_TRACEPOINT_INSTANCE(name) \
TRACEPOINT_EVENT_INSTANCE(\
    DotNETRuntimeRundown,\
    DomainModuleLoadUnloadRundown_V1,\
    name ,\
    DomainModuleLoadUnloadRundown_V1_TRACEPOINT_ARGS \
)
#define ModuleLoadUnloadRundown_TRACEPOINT_ARGS \
TP_ARGS( \
        const uint64_t, ModuleID, \
        const uint64_t, AssemblyID, \
        const unsigned int, ModuleFlags, \
        const unsigned int, Reserved1, \
        const char*, ModuleILPath, \
        const char*, ModuleNativePath \
)
TRACEPOINT_EVENT_CLASS(
    DotNETRuntimeRundown,
    ModuleLoadUnloadRundown,
    ModuleLoadUnloadRundown_TRACEPOINT_ARGS,
     TP_FIELDS(
        ctf_integer(uint64_t, ModuleID, ModuleID)
        ctf_integer(uint64_t, AssemblyID, AssemblyID)
        ctf_integer(unsigned int, ModuleFlags, ModuleFlags)
        ctf_integer(unsigned int, Reserved1, Reserved1)
        ctf_string(ModuleILPath, ModuleILPath)
        ctf_string(ModuleNativePath, ModuleNativePath)
    )
)

#define ModuleLoadUnloadRundownT_TRACEPOINT_INSTANCE(name) \
TRACEPOINT_EVENT_INSTANCE(\
    DotNETRuntimeRundown,\
    ModuleLoadUnloadRundown,\
    name ,\
    ModuleLoadUnloadRundown_TRACEPOINT_ARGS \
)
#define ModuleLoadUnloadRundown_V1_TRACEPOINT_ARGS \
TP_ARGS( \
        const uint64_t, ModuleID, \
        const uint64_t, AssemblyID, \
        const unsigned int, ModuleFlags, \
        const unsigned int, Reserved1, \
        const char*, ModuleILPath, \
        const char*, ModuleNativePath, \
        const unsigned short, ClrInstanceID \
)
TRACEPOINT_EVENT_CLASS(
    DotNETRuntimeRundown,
    ModuleLoadUnloadRundown_V1,
    ModuleLoadUnloadRundown_V1_TRACEPOINT_ARGS,
     TP_FIELDS(
        ctf_integer(uint64_t, ModuleID, ModuleID)
        ctf_integer(uint64_t, AssemblyID, AssemblyID)
        ctf_integer(unsigned int, ModuleFlags, ModuleFlags)
        ctf_integer(unsigned int, Reserved1, Reserved1)
        ctf_string(ModuleILPath, ModuleILPath)
        ctf_string(ModuleNativePath, ModuleNativePath)
        ctf_integer(unsigned short, ClrInstanceID, ClrInstanceID)
    )
)

#define ModuleLoadUnloadRundown_V1T_TRACEPOINT_INSTANCE(name) \
TRACEPOINT_EVENT_INSTANCE(\
    DotNETRuntimeRundown,\
    ModuleLoadUnloadRundown_V1,\
    name ,\
    ModuleLoadUnloadRundown_V1_TRACEPOINT_ARGS \
)
#define ModuleLoadUnloadRundown_V2_TRACEPOINT_ARGS \
TP_ARGS( \
        const unsigned int, length, \
        const char *, __data__ \
)
TRACEPOINT_EVENT_CLASS(
    DotNETRuntimeRundown,
    ModuleLoadUnloadRundown_V2,
    ModuleLoadUnloadRundown_V2_TRACEPOINT_ARGS,
     TP_FIELDS(
        ctf_integer(ULONG, length, length)
        ctf_sequence(char, __data__, __data__, ULONG, length)
    )
)

#define ModuleLoadUnloadRundown_V2T_TRACEPOINT_INSTANCE(name) \
TRACEPOINT_EVENT_INSTANCE(\
    DotNETRuntimeRundown,\
    ModuleLoadUnloadRundown_V2,\
    name ,\
    ModuleLoadUnloadRundown_V2_TRACEPOINT_ARGS \
)
#define ModuleLoadUnloadRundown_V3_TRACEPOINT_ARGS \
TP_ARGS( \
        const unsigned int, length, \
        const char *, __data__ \
)
TRACEPOINT_EVENT_CLASS(
    DotNETRuntimeRundown,
    ModuleLoadUnloadRundown_V3,
    ModuleLoadUnloadRundown_V3_TRACEPOINT_ARGS,
     TP_FIELDS(
        ctf_integer(ULONG, length, length)
        ctf_sequence(char, __data__, __data__, ULONG, length)
    )
)

#define ModuleLoadUnloadRundown_V3T_TRACEPOINT_INSTANCE(name) \
TRACEPOINT_EVENT_INSTANCE(\
    DotNETRuntimeRundown,\
    ModuleLoadUnloadRundown_V3,\
    name ,\
    ModuleLoadUnloadRundown_V3_TRACEPOINT_ARGS \
)
#define AssemblyLoadUnloadRundown_TRACEPOINT_ARGS \
TP_ARGS( \
        const uint64_t, AssemblyID, \
        const uint64_t, AppDomainID, \
        const unsigned int, AssemblyFlags, \
        const char*, FullyQualifiedAssemblyName \
)
TRACEPOINT_EVENT_CLASS(
    DotNETRuntimeRundown,
    AssemblyLoadUnloadRundown,
    AssemblyLoadUnloadRundown_TRACEPOINT_ARGS,
     TP_FIELDS(
        ctf_integer(uint64_t, AssemblyID, AssemblyID)
        ctf_integer(uint64_t, AppDomainID, AppDomainID)
        ctf_integer(unsigned int, AssemblyFlags, AssemblyFlags)
        ctf_string(FullyQualifiedAssemblyName, FullyQualifiedAssemblyName)
    )
)

#define AssemblyLoadUnloadRundownT_TRACEPOINT_INSTANCE(name) \
TRACEPOINT_EVENT_INSTANCE(\
    DotNETRuntimeRundown,\
    AssemblyLoadUnloadRundown,\
    name ,\
    AssemblyLoadUnloadRundown_TRACEPOINT_ARGS \
)
#define AssemblyLoadUnloadRundown_V1_TRACEPOINT_ARGS \
TP_ARGS( \
        const uint64_t, AssemblyID, \
        const uint64_t, AppDomainID, \
        const uint64_t, BindingID, \
        const unsigned int, AssemblyFlags, \
        const char*, FullyQualifiedAssemblyName, \
        const unsigned short, ClrInstanceID \
)
TRACEPOINT_EVENT_CLASS(
    DotNETRuntimeRundown,
    AssemblyLoadUnloadRundown_V1,
    AssemblyLoadUnloadRundown_V1_TRACEPOINT_ARGS,
     TP_FIELDS(
        ctf_integer(uint64_t, AssemblyID, AssemblyID)
        ctf_integer(uint64_t, AppDomainID, AppDomainID)
        ctf_integer(uint64_t, BindingID, BindingID)
        ctf_integer(unsigned int, AssemblyFlags, AssemblyFlags)
        ctf_string(FullyQualifiedAssemblyName, FullyQualifiedAssemblyName)
        ctf_integer(unsigned short, ClrInstanceID, ClrInstanceID)
    )
)

#define AssemblyLoadUnloadRundown_V1T_TRACEPOINT_INSTANCE(name) \
TRACEPOINT_EVENT_INSTANCE(\
    DotNETRuntimeRundown,\
    AssemblyLoadUnloadRundown_V1,\
    name ,\
    AssemblyLoadUnloadRundown_V1_TRACEPOINT_ARGS \
)
#define AppDomainLoadUnloadRundown_TRACEPOINT_ARGS \
TP_ARGS( \
        const uint64_t, AppDomainID, \
        const unsigned int, AppDomainFlags, \
        const char*, AppDomainName \
)
TRACEPOINT_EVENT_CLASS(
    DotNETRuntimeRundown,
    AppDomainLoadUnloadRundown,
    AppDomainLoadUnloadRundown_TRACEPOINT_ARGS,
     TP_FIELDS(
        ctf_integer(uint64_t, AppDomainID, AppDomainID)
        ctf_integer(unsigned int, AppDomainFlags, AppDomainFlags)
        ctf_string(AppDomainName, AppDomainName)
    )
)

#define AppDomainLoadUnloadRundownT_TRACEPOINT_INSTANCE(name) \
TRACEPOINT_EVENT_INSTANCE(\
    DotNETRuntimeRundown,\
    AppDomainLoadUnloadRundown,\
    name ,\
    AppDomainLoadUnloadRundown_TRACEPOINT_ARGS \
)
#define AppDomainLoadUnloadRundown_V1_TRACEPOINT_ARGS \
TP_ARGS( \
        const uint64_t, AppDomainID, \
        const unsigned int, AppDomainFlags, \
        const char*, AppDomainName, \
        const unsigned int, AppDomainIndex, \
        const unsigned short, ClrInstanceID \
)
TRACEPOINT_EVENT_CLASS(
    DotNETRuntimeRundown,
    AppDomainLoadUnloadRundown_V1,
    AppDomainLoadUnloadRundown_V1_TRACEPOINT_ARGS,
     TP_FIELDS(
        ctf_integer(uint64_t, AppDomainID, AppDomainID)
        ctf_integer(unsigned int, AppDomainFlags, AppDomainFlags)
        ctf_string(AppDomainName, AppDomainName)
        ctf_integer(unsigned int, AppDomainIndex, AppDomainIndex)
        ctf_integer(unsigned short, ClrInstanceID, ClrInstanceID)
    )
)

#define AppDomainLoadUnloadRundown_V1T_TRACEPOINT_INSTANCE(name) \
TRACEPOINT_EVENT_INSTANCE(\
    DotNETRuntimeRundown,\
    AppDomainLoadUnloadRundown_V1,\
    name ,\
    AppDomainLoadUnloadRundown_V1_TRACEPOINT_ARGS \
)
#define MethodLoadUnloadRundown_TRACEPOINT_ARGS \
TP_ARGS( \
        const uint64_t, MethodID, \
        const uint64_t, ModuleID, \
        const uint64_t, MethodStartAddress, \
        const unsigned int, MethodSize, \
        const unsigned int, MethodToken, \
        const unsigned int, MethodFlags \
)
TRACEPOINT_EVENT_CLASS(
    DotNETRuntimeRundown,
    MethodLoadUnloadRundown,
    MethodLoadUnloadRundown_TRACEPOINT_ARGS,
     TP_FIELDS(
        ctf_integer(uint64_t, MethodID, MethodID)
        ctf_integer(uint64_t, ModuleID, ModuleID)
        ctf_integer(uint64_t, MethodStartAddress, MethodStartAddress)
        ctf_integer(unsigned int, MethodSize, MethodSize)
        ctf_integer(unsigned int, MethodToken, MethodToken)
        ctf_integer(unsigned int, MethodFlags, MethodFlags)
    )
)

#define MethodLoadUnloadRundownT_TRACEPOINT_INSTANCE(name) \
TRACEPOINT_EVENT_INSTANCE(\
    DotNETRuntimeRundown,\
    MethodLoadUnloadRundown,\
    name ,\
    MethodLoadUnloadRundown_TRACEPOINT_ARGS \
)
#define MethodLoadUnloadRundown_V1_TRACEPOINT_ARGS \
TP_ARGS( \
        const uint64_t, MethodID, \
        const uint64_t, ModuleID, \
        const uint64_t, MethodStartAddress, \
        const unsigned int, MethodSize, \
        const unsigned int, MethodToken, \
        const unsigned int, MethodFlags, \
        const unsigned short, ClrInstanceID \
)
TRACEPOINT_EVENT_CLASS(
    DotNETRuntimeRundown,
    MethodLoadUnloadRundown_V1,
    MethodLoadUnloadRundown_V1_TRACEPOINT_ARGS,
     TP_FIELDS(
        ctf_integer(uint64_t, MethodID, MethodID)
        ctf_integer(uint64_t, ModuleID, ModuleID)
        ctf_integer(uint64_t, MethodStartAddress, MethodStartAddress)
        ctf_integer(unsigned int, MethodSize, MethodSize)
        ctf_integer(unsigned int, MethodToken, MethodToken)
        ctf_integer(unsigned int, MethodFlags, MethodFlags)
        ctf_integer(unsigned short, ClrInstanceID, ClrInstanceID)
    )
)

#define MethodLoadUnloadRundown_V1T_TRACEPOINT_INSTANCE(name) \
TRACEPOINT_EVENT_INSTANCE(\
    DotNETRuntimeRundown,\
    MethodLoadUnloadRundown_V1,\
    name ,\
    MethodLoadUnloadRundown_V1_TRACEPOINT_ARGS \
)
#define MethodLoadUnloadRundown_V2_TRACEPOINT_ARGS \
TP_ARGS( \
        const uint64_t, MethodID, \
        const uint64_t, ModuleID, \
        const uint64_t, MethodStartAddress, \
        const unsigned int, MethodSize, \
        const unsigned int, MethodToken, \
        const unsigned int, MethodFlags, \
        const unsigned short, ClrInstanceID, \
        const uint64_t, ReJITID \
)
TRACEPOINT_EVENT_CLASS(
    DotNETRuntimeRundown,
    MethodLoadUnloadRundown_V2,
    MethodLoadUnloadRundown_V2_TRACEPOINT_ARGS,
     TP_FIELDS(
        ctf_integer(uint64_t, MethodID, MethodID)
        ctf_integer(uint64_t, ModuleID, ModuleID)
        ctf_integer(uint64_t, MethodStartAddress, MethodStartAddress)
        ctf_integer(unsigned int, MethodSize, MethodSize)
        ctf_integer(unsigned int, MethodToken, MethodToken)
        ctf_integer(unsigned int, MethodFlags, MethodFlags)
        ctf_integer(unsigned short, ClrInstanceID, ClrInstanceID)
        ctf_integer(uint64_t, ReJITID, ReJITID)
    )
)

#define MethodLoadUnloadRundown_V2T_TRACEPOINT_INSTANCE(name) \
TRACEPOINT_EVENT_INSTANCE(\
    DotNETRuntimeRundown,\
    MethodLoadUnloadRundown_V2,\
    name ,\
    MethodLoadUnloadRundown_V2_TRACEPOINT_ARGS \
)
#define MethodLoadUnloadRundownVerbose_TRACEPOINT_ARGS \
TP_ARGS( \
        const uint64_t, MethodID, \
        const uint64_t, ModuleID, \
        const uint64_t, MethodStartAddress, \
        const unsigned int, MethodSize, \
        const unsigned int, MethodToken, \
        const unsigned int, MethodFlags, \
        const char*, MethodNamespace, \
        const char*, MethodName, \
        const char*, MethodSignature \
)
TRACEPOINT_EVENT_CLASS(
    DotNETRuntimeRundown,
    MethodLoadUnloadRundownVerbose,
    MethodLoadUnloadRundownVerbose_TRACEPOINT_ARGS,
     TP_FIELDS(
        ctf_integer(uint64_t, MethodID, MethodID)
        ctf_integer(uint64_t, ModuleID, ModuleID)
        ctf_integer(uint64_t, MethodStartAddress, MethodStartAddress)
        ctf_integer(unsigned int, MethodSize, MethodSize)
        ctf_integer(unsigned int, MethodToken, MethodToken)
        ctf_integer(unsigned int, MethodFlags, MethodFlags)
        ctf_string(MethodNamespace, MethodNamespace)
        ctf_string(MethodName, MethodName)
        ctf_string(MethodSignature, MethodSignature)
    )
)

#define MethodLoadUnloadRundownVerboseT_TRACEPOINT_INSTANCE(name) \
TRACEPOINT_EVENT_INSTANCE(\
    DotNETRuntimeRundown,\
    MethodLoadUnloadRundownVerbose,\
    name ,\
    MethodLoadUnloadRundownVerbose_TRACEPOINT_ARGS \
)
#define MethodLoadUnloadRundownVerbose_V1_TRACEPOINT_ARGS \
TP_ARGS( \
        const unsigned int, length, \
        const char *, __data__ \
)
TRACEPOINT_EVENT_CLASS(
    DotNETRuntimeRundown,
    MethodLoadUnloadRundownVerbose_V1,
    MethodLoadUnloadRundownVerbose_V1_TRACEPOINT_ARGS,
     TP_FIELDS(
        ctf_integer(ULONG, length, length)
        ctf_sequence(char, __data__, __data__, ULONG, length)
    )
)

#define MethodLoadUnloadRundownVerbose_V1T_TRACEPOINT_INSTANCE(name) \
TRACEPOINT_EVENT_INSTANCE(\
    DotNETRuntimeRundown,\
    MethodLoadUnloadRundownVerbose_V1,\
    name ,\
    MethodLoadUnloadRundownVerbose_V1_TRACEPOINT_ARGS \
)
#define MethodLoadUnloadRundownVerbose_V2_TRACEPOINT_ARGS \
TP_ARGS( \
        const unsigned int, length, \
        const char *, __data__ \
)
TRACEPOINT_EVENT_CLASS(
    DotNETRuntimeRundown,
    MethodLoadUnloadRundownVerbose_V2,
    MethodLoadUnloadRundownVerbose_V2_TRACEPOINT_ARGS,
     TP_FIELDS(
        ctf_integer(ULONG, length, length)
        ctf_sequence(char, __data__, __data__, ULONG, length)
    )
)

#define MethodLoadUnloadRundownVerbose_V2T_TRACEPOINT_INSTANCE(name) \
TRACEPOINT_EVENT_INSTANCE(\
    DotNETRuntimeRundown,\
    MethodLoadUnloadRundownVerbose_V2,\
    name ,\
    MethodLoadUnloadRundownVerbose_V2_TRACEPOINT_ARGS \
)
#define MethodILToNativeMapRundown_TRACEPOINT_ARGS \
TP_ARGS( \
        const unsigned int, length, \
        const char *, __data__ \
)
TRACEPOINT_EVENT_CLASS(
    DotNETRuntimeRundown,
    MethodILToNativeMapRundown,
    MethodILToNativeMapRundown_TRACEPOINT_ARGS,
     TP_FIELDS(
        ctf_integer(ULONG, length, length)
        ctf_sequence(char, __data__, __data__, ULONG, length)
    )
)

#define MethodILToNativeMapRundownT_TRACEPOINT_INSTANCE(name) \
TRACEPOINT_EVENT_INSTANCE(\
    DotNETRuntimeRundown,\
    MethodILToNativeMapRundown,\
    name ,\
    MethodILToNativeMapRundown_TRACEPOINT_ARGS \
)
#define MethodILToNativeMapRundown_V1_TRACEPOINT_ARGS \
TP_ARGS( \
        const unsigned int, length, \
        const char *, __data__ \
)
TRACEPOINT_EVENT_CLASS(
    DotNETRuntimeRundown,
    MethodILToNativeMapRundown_V1,
    MethodILToNativeMapRundown_V1_TRACEPOINT_ARGS,
     TP_FIELDS(
        ctf_integer(ULONG, length, length)
        ctf_sequence(char, __data__, __data__, ULONG, length)
    )
)

#define MethodILToNativeMapRundown_V1T_TRACEPOINT_INSTANCE(name) \
TRACEPOINT_EVENT_INSTANCE(\
    DotNETRuntimeRundown,\
    MethodILToNativeMapRundown_V1,\
    name ,\
    MethodILToNativeMapRundown_V1_TRACEPOINT_ARGS \
)
#define DCStartEnd_TRACEPOINT_ARGS \
TP_ARGS( \
        const unsigned short, ClrInstanceID \
)
TRACEPOINT_EVENT_CLASS(
    DotNETRuntimeRundown,
    DCStartEnd,
    DCStartEnd_TRACEPOINT_ARGS,
     TP_FIELDS(
        ctf_integer(unsigned short, ClrInstanceID, ClrInstanceID)
    )
)

#define DCStartEndT_TRACEPOINT_INSTANCE(name) \
TRACEPOINT_EVENT_INSTANCE(\
    DotNETRuntimeRundown,\
    DCStartEnd,\
    name ,\
    DCStartEnd_TRACEPOINT_ARGS \
)
#define ClrStackWalk_TRACEPOINT_ARGS \
TP_ARGS( \
        const unsigned short, ClrInstanceID, \
        const unsigned char, Reserved1, \
        const unsigned char, Reserved2, \
        const unsigned int, FrameCount, \
        const size_t*, Stack \
)
TRACEPOINT_EVENT_CLASS(
    DotNETRuntimeRundown,
    ClrStackWalk,
    ClrStackWalk_TRACEPOINT_ARGS,
     TP_FIELDS(
        ctf_integer(unsigned short, ClrInstanceID, ClrInstanceID)
        ctf_integer(unsigned char, Reserved1, Reserved1)
        ctf_integer(unsigned char, Reserved2, Reserved2)
        ctf_integer(unsigned int, FrameCount, FrameCount)
        ctf_sequence(size_t, Stack, Stack, size_t, 2)
    )
)

#define ClrStackWalkT_TRACEPOINT_INSTANCE(name) \
TRACEPOINT_EVENT_INSTANCE(\
    DotNETRuntimeRundown,\
    ClrStackWalk,\
    name ,\
    ClrStackWalk_TRACEPOINT_ARGS \
)
#define ThreadCreatedRundown_TRACEPOINT_ARGS \
TP_ARGS( \
        const uint64_t, ManagedThreadID, \
        const uint64_t, AppDomainID, \
        const unsigned int, Flags, \
        const unsigned int, ManagedThreadIndex, \
        const unsigned int, OSThreadID, \
        const unsigned short, ClrInstanceID \
)
TRACEPOINT_EVENT_CLASS(
    DotNETRuntimeRundown,
    ThreadCreatedRundown,
    ThreadCreatedRundown_TRACEPOINT_ARGS,
     TP_FIELDS(
        ctf_integer(uint64_t, ManagedThreadID, ManagedThreadID)
        ctf_integer(uint64_t, AppDomainID, AppDomainID)
        ctf_integer(unsigned int, Flags, Flags)
        ctf_integer(unsigned int, ManagedThreadIndex, ManagedThreadIndex)
        ctf_integer(unsigned int, OSThreadID, OSThreadID)
        ctf_integer(unsigned short, ClrInstanceID, ClrInstanceID)
    )
)

#define ThreadCreatedRundownT_TRACEPOINT_INSTANCE(name) \
TRACEPOINT_EVENT_INSTANCE(\
    DotNETRuntimeRundown,\
    ThreadCreatedRundown,\
    name ,\
    ThreadCreatedRundown_TRACEPOINT_ARGS \
)
#define ModuleRangeRundown_TRACEPOINT_ARGS \
TP_ARGS( \
        const unsigned short, ClrInstanceID, \
        const uint64_t, ModuleID, \
        const unsigned int, RangeBegin, \
        const unsigned int, RangeSize, \
        const unsigned char, RangeType \
)
TRACEPOINT_EVENT_CLASS(
    DotNETRuntimeRundown,
    ModuleRangeRundown,
    ModuleRangeRundown_TRACEPOINT_ARGS,
     TP_FIELDS(
        ctf_integer(unsigned short, ClrInstanceID, ClrInstanceID)
        ctf_integer(uint64_t, ModuleID, ModuleID)
        ctf_integer(unsigned int, RangeBegin, RangeBegin)
        ctf_integer(unsigned int, RangeSize, RangeSize)
        ctf_integer(unsigned char, RangeType, RangeType)
    )
)

#define ModuleRangeRundownT_TRACEPOINT_INSTANCE(name) \
TRACEPOINT_EVENT_INSTANCE(\
    DotNETRuntimeRundown,\
    ModuleRangeRundown,\
    name ,\
    ModuleRangeRundown_TRACEPOINT_ARGS \
)
#define TieredCompilationSettings_TRACEPOINT_ARGS \
TP_ARGS( \
        const unsigned short, ClrInstanceID, \
        const unsigned int, Flags \
)
TRACEPOINT_EVENT_CLASS(
    DotNETRuntimeRundown,
    TieredCompilationSettings,
    TieredCompilationSettings_TRACEPOINT_ARGS,
     TP_FIELDS(
        ctf_integer(unsigned short, ClrInstanceID, ClrInstanceID)
        ctf_integer(unsigned int, Flags, Flags)
    )
)

#define TieredCompilationSettingsT_TRACEPOINT_INSTANCE(name) \
TRACEPOINT_EVENT_INSTANCE(\
    DotNETRuntimeRundown,\
    TieredCompilationSettings,\
    name ,\
    TieredCompilationSettings_TRACEPOINT_ARGS \
)
#define ExecutionCheckpointRundown_TRACEPOINT_ARGS \
TP_ARGS( \
        const unsigned short, ClrInstanceID, \
        const char*, Name, \
        const int64_t, Timestamp \
)
TRACEPOINT_EVENT_CLASS(
    DotNETRuntimeRundown,
    ExecutionCheckpointRundown,
    ExecutionCheckpointRundown_TRACEPOINT_ARGS,
     TP_FIELDS(
        ctf_integer(unsigned short, ClrInstanceID, ClrInstanceID)
        ctf_string(Name, Name)
        ctf_integer(int64_t, Timestamp, Timestamp)
    )
)

#define ExecutionCheckpointRundownT_TRACEPOINT_INSTANCE(name) \
TRACEPOINT_EVENT_INSTANCE(\
    DotNETRuntimeRundown,\
    ExecutionCheckpointRundown,\
    name ,\
    ExecutionCheckpointRundown_TRACEPOINT_ARGS \
)

TRACEPOINT_EVENT_CLASS(
    DotNETRuntimeRundown,
    emptyTemplate ,
    TP_ARGS(),
    TP_FIELDS()
)
#define T_TRACEPOINT_INSTANCE(name) \
TRACEPOINT_EVENT_INSTANCE(\
    DotNETRuntimeRundown,\
    emptyTemplate,\
    name ,\
    TP_ARGS()\
)
ClrStackWalkT_TRACEPOINT_INSTANCE(CLRStackWalkDCStart)
GCSettingsRundownT_TRACEPOINT_INSTANCE(GCSettingsRundown)
MethodLoadUnloadRundownT_TRACEPOINT_INSTANCE(MethodDCStart)
MethodLoadUnloadRundown_V1T_TRACEPOINT_INSTANCE(MethodDCStart_V1)
MethodLoadUnloadRundown_V2T_TRACEPOINT_INSTANCE(MethodDCStart_V2)
MethodLoadUnloadRundownT_TRACEPOINT_INSTANCE(MethodDCEnd)
MethodLoadUnloadRundown_V1T_TRACEPOINT_INSTANCE(MethodDCEnd_V1)
MethodLoadUnloadRundown_V2T_TRACEPOINT_INSTANCE(MethodDCEnd_V2)
MethodLoadUnloadRundownVerboseT_TRACEPOINT_INSTANCE(MethodDCStartVerbose)
MethodLoadUnloadRundownVerbose_V1T_TRACEPOINT_INSTANCE(MethodDCStartVerbose_V1)
MethodLoadUnloadRundownVerbose_V2T_TRACEPOINT_INSTANCE(MethodDCStartVerbose_V2)
MethodLoadUnloadRundownVerboseT_TRACEPOINT_INSTANCE(MethodDCEndVerbose)
MethodLoadUnloadRundownVerbose_V1T_TRACEPOINT_INSTANCE(MethodDCEndVerbose_V1)
MethodLoadUnloadRundownVerbose_V2T_TRACEPOINT_INSTANCE(MethodDCEndVerbose_V2)
T_TRACEPOINT_INSTANCE(DCStartComplete)
DCStartEndT_TRACEPOINT_INSTANCE(DCStartComplete_V1)
T_TRACEPOINT_INSTANCE(DCEndComplete)
DCStartEndT_TRACEPOINT_INSTANCE(DCEndComplete_V1)
T_TRACEPOINT_INSTANCE(DCStartInit)
DCStartEndT_TRACEPOINT_INSTANCE(DCStartInit_V1)
T_TRACEPOINT_INSTANCE(DCEndInit)
DCStartEndT_TRACEPOINT_INSTANCE(DCEndInit_V1)
MethodILToNativeMapRundownT_TRACEPOINT_INSTANCE(MethodDCStartILToNativeMap)
MethodILToNativeMapRundown_V1T_TRACEPOINT_INSTANCE(MethodDCStartILToNativeMap_V1)
MethodILToNativeMapRundownT_TRACEPOINT_INSTANCE(MethodDCEndILToNativeMap)
MethodILToNativeMapRundown_V1T_TRACEPOINT_INSTANCE(MethodDCEndILToNativeMap_V1)
DomainModuleLoadUnloadRundownT_TRACEPOINT_INSTANCE(DomainModuleDCStart)
DomainModuleLoadUnloadRundown_V1T_TRACEPOINT_INSTANCE(DomainModuleDCStart_V1)
DomainModuleLoadUnloadRundownT_TRACEPOINT_INSTANCE(DomainModuleDCEnd)
DomainModuleLoadUnloadRundown_V1T_TRACEPOINT_INSTANCE(DomainModuleDCEnd_V1)
ModuleLoadUnloadRundownT_TRACEPOINT_INSTANCE(ModuleDCStart)
ModuleLoadUnloadRundown_V1T_TRACEPOINT_INSTANCE(ModuleDCStart_V1)
ModuleLoadUnloadRundown_V2T_TRACEPOINT_INSTANCE(ModuleDCStart_V2)
ModuleLoadUnloadRundownT_TRACEPOINT_INSTANCE(ModuleDCEnd)
ModuleLoadUnloadRundown_V1T_TRACEPOINT_INSTANCE(ModuleDCEnd_V1)
ModuleLoadUnloadRundown_V2T_TRACEPOINT_INSTANCE(ModuleDCEnd_V2)
ModuleLoadUnloadRundown_V3T_TRACEPOINT_INSTANCE(ModuleDCEnd_V3)
AssemblyLoadUnloadRundownT_TRACEPOINT_INSTANCE(AssemblyDCStart)
AssemblyLoadUnloadRundown_V1T_TRACEPOINT_INSTANCE(AssemblyDCStart_V1)
AssemblyLoadUnloadRundownT_TRACEPOINT_INSTANCE(AssemblyDCEnd)
AssemblyLoadUnloadRundown_V1T_TRACEPOINT_INSTANCE(AssemblyDCEnd_V1)
AppDomainLoadUnloadRundownT_TRACEPOINT_INSTANCE(AppDomainDCStart)
AppDomainLoadUnloadRundown_V1T_TRACEPOINT_INSTANCE(AppDomainDCStart_V1)
AppDomainLoadUnloadRundownT_TRACEPOINT_INSTANCE(AppDomainDCEnd)
AppDomainLoadUnloadRundown_V1T_TRACEPOINT_INSTANCE(AppDomainDCEnd_V1)
ThreadCreatedRundownT_TRACEPOINT_INSTANCE(ThreadDC)
ModuleRangeRundownT_TRACEPOINT_INSTANCE(ModuleRangeDCStart)
ModuleRangeRundownT_TRACEPOINT_INSTANCE(ModuleRangeDCEnd)
RuntimeInformationRundownT_TRACEPOINT_INSTANCE(RuntimeInformationDCStart)
TieredCompilationSettingsT_TRACEPOINT_INSTANCE(TieredCompilationSettingsDCStart)
ExecutionCheckpointRundownT_TRACEPOINT_INSTANCE(ExecutionCheckpointDCEnd)

#endif /* LTTNG_CORECLR_HDotNETRuntimeRundown */
#include <lttng/tracepoint-event.h>
