load("//src/tests:live_test.bzl", "library_test")

library_test(
    name = "System.Net.Sockets.Tests",
    srcs = glob(
        ["**/*.cs"],
        exclude = [
            "StartupTests.Windows.cs",
            "InlineCompletions.Unix.cs",
        ],
    ) + [
        "//src/libraries/Common/tests:System/Net/Configuration.cs",
        "//src/libraries/Common/tests:System/Net/Configuration.Sockets.cs",
        "//src/libraries/Common/tests:System/Net/Sockets/TestSettings.cs",
        "//src/libraries/Common/tests:System/Net/Sockets/Fletcher32.cs",
        "//src/libraries/Common/tests:System/Net/Sockets/SocketTestExtensions.cs",
        "//src/libraries/Common/tests:System/Net/Sockets/SocketTestServer.cs",
        "//src/libraries/Common/tests:System/Net/Sockets/SocketTestServerAsync.cs",
        "//src/libraries/Common/tests:System/Net/Sockets/SocketTestServerAPM.cs",
        "//src/libraries/Common/tests:System/Net/Sockets/SocketImplementationType.cs",
        "//src/libraries/Common/tests:System/Net/ActivityRecorder.cs",
        "//src/libraries/Common/tests:System/Net/TestLogging.cs",
        "//src/libraries/Common/tests:System/Net/VerboseTestLogging.cs",
        "//src/libraries/Common/tests:System/Net/EventSourceTestLogging.cs",
        "//src/libraries/Common/tests:System/Net/Capability.Sockets.cs",
        "//src/libraries/Common/tests:System/Net/RemoteExecutorExtensions.cs",
        "//src/libraries/Common/tests:System/ShouldNotBeInvokedException.cs",
        "//src/libraries/Common/tests:System/Threading/Tasks/TaskTimeoutExtensions.cs",
        "//src/libraries/Common/tests:System/Buffers/NativeMemoryManager.cs",
        "//src/libraries/Common/tests:System/Diagnostics/Tracing/TestEventListener.cs",
        "//src/libraries/Common/tests:System/IO/TempFile.cs",
        "//src/libraries/Common/tests:TestUtilities/System/DisableParallelization.cs",
        "//src/libraries/Common:src/System/Net/Logging/NetEventSource.Common.cs",
    ],
    deps = [
        "//src/libraries/System.Net.Primitives:ref_System.Net.Primitives",
        "//src/libraries/System.Net.Sockets:ref_System.Net.Sockets",
        "//src/libraries/System.Net.NameResolution:ref_System.Net.NameResolution",
        "//src/libraries/System.Net.NetworkInformation:ref_System.Net.NetworkInformation",
        "//src/libraries:ref_Microsoft.Win32.Primitives",
        "//src/libraries:ref_System.Threading.Tasks",
        "//src/libraries/System.Collections.Concurrent:ref_System.Collections.Concurrent",
        "//src/libraries/System.Collections.Immutable:ref_System.Collections.Immutable",
        "//src/libraries/System.Diagnostics.Tracing:ref_System.Diagnostics.Tracing",
        "//src/libraries/System.Diagnostics.DiagnosticSource:ref_System.Diagnostics.DiagnosticSource",
        "//src/libraries/System.IO.Pipes:ref_System.IO.Pipes",
        "//src/libraries/System.Runtime.Serialization.Formatters:ref_System.Runtime.Serialization.Formatters",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/System.Threading.Thread:ref_System.Threading.Thread",
        "//src/libraries/System.Threading.ThreadPool:ref_System.Threading.ThreadPool",
        "//src/libraries:ref_System.Text.RegularExpressions",
        "//src/libraries/Common/tests:TestUtilities",
        "//src/libraries/Common/tests:StreamConformanceTests",
        "@paket.main//microsoft.dotnet.remoteexecutor",
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//microsoft.dotnet.xunitextensions",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    allow_unsafe_blocks = True,
    size = "large",
    keyfile = "@nuget.microsoft.dotnet.arcade.sdk.v10.0.0-beta.26102.102//:tools/snk/Open.snk",
)
