load("//src/tests:live_test.bzl", "library_test")

library_test(
    name = "System.ComponentModel.Primitives.Tests",
    srcs = glob(
        ["**/*.cs"],
        exclude = [
            "System/ComponentModel/Design/**",
            "TrimmingTests/**",
        ],
    ),
    deps = [
        "//src/libraries/System.Collections.Concurrent:ref_System.Collections.Concurrent",
        "//src/libraries/System.Collections.Immutable:ref_System.Collections.Immutable",
        "//src/libraries/System.ComponentModel.TypeConverter:ref_System.ComponentModel.TypeConverter",
        "//src/libraries/System.Runtime.Serialization.Formatters:impl_System.Runtime.Serialization.Formatters",
        "//src/libraries/Common/tests:TestUtilities",
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//microsoft.dotnet.xunitextensions",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    keyfile = "@nuget.microsoft.dotnet.arcade.sdk.v10.0.0-beta.26102.102//:tools/snk/Open.snk",
)
