load("//src/tests:live_test.bzl", "library_test")
load("//src/libraries:defs.bzl", "MULTITARGET_NOWARN")
load("//:defs.bzl", "OPEN_SNK")

library_test(
    name = "System.Net.ServerSentEvents.Tests",
    nowarn = MULTITARGET_NOWARN,
    srcs = glob(["*.cs"]),
    deps = [
        "//src/libraries/System.Net.ServerSentEvents:impl_System.Net.ServerSentEvents",
        "//src/libraries/System.Text.Encodings.Web:ref_System.Text.Encodings.Web",
        "//src/libraries/System.Text.Json:ref_System.Text.Json",
        "//src/libraries/Common/tests:TestUtilities",
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//microsoft.dotnet.xunitextensions",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    keyfile = OPEN_SNK,
)
