load("//src/tests:live_test.bzl", "coreclr_test")

coreclr_test(
    name = "xaddmuly_cs_do",
    srcs = ["xaddmuly.cs"],
    pri = 1,
    debug_type = "full",
    optimize = True,
)

coreclr_test(
    name = "xaddmuly_cs_r",
    srcs = ["xaddmuly.cs"],
    pri = 1,
)

coreclr_test(
    name = "gcpoll",
    srcs = ["gcpoll.cs"],
    optimize = True,
)

coreclr_test(
    name = "xaddmuly_cs_d",
    srcs = ["xaddmuly.cs"],
    pri = 1,
    debug_type = "full",
    optimize = False,
)

coreclr_test(
    name = "xaddmuly_cs_ro",
    srcs = ["xaddmuly.cs"],
    pri = 1,
    optimize = True,
)
