load("//:defs.bzl", "OPEN_SNK", "resgen")
load("//:defs.bzl", "csharp_library")
load("//src/tests:live_test.bzl", "library_test")

resgen(
    name = "TestResx",
    out = "Resources.TestResx.resources",
    resx_file = "Resources/TestResx.resx",
)

csharp_library(
    name = "UnloadableTestTypes",
    srcs = ["UnloadableTestTypes/UnloadableTestTypes.cs"],
    target_frameworks = ["netstandard2.1"],
    nullable = "disable",
    analyzers = [
        "//src/libraries/System.Runtime.InteropServices:DownlevelLibraryImportGenerator",
        "//src/libraries/System.Runtime.InteropServices:Microsoft.Interop.SourceGeneration",
    ],
    keyfile = OPEN_SNK,
    nowarn = [
        "ESGEN001",
        "ESGEN002",
        "IL2121",
    ],
    msbuild_analyzer_config = "style",
    include_default_ruleset = False,
    include_syslib_warnaserror = False,
    include_runtime_async = False,
)

library_test(
    name = "System.ComponentModel.TypeConverter.Tests",
    srcs = glob(
        ["**/*.cs"],
        exclude = [
            "TrimmingTests/**",
            "UnloadableTestTypes/**",
        ],
    ) + [
        "//src/libraries/Common/tests:TestUtilities/System/DisableParallelization.cs",
    ],
    deps = [
        ":UnloadableTestTypes",
        "//src/libraries/System.ComponentModel.TypeConverter:ref_System.ComponentModel.TypeConverter",
        "//src/libraries/System.Collections.Concurrent:ref_System.Collections.Concurrent",
        "//src/libraries/System.Collections.Immutable:ref_System.Collections.Immutable",
        "//src/libraries/System.Diagnostics.Tracing:ref_System.Diagnostics.Tracing",
        "//src/libraries/System.Drawing.Primitives:ref_System.Drawing.Primitives",
        "//src/libraries/System.Net.Security:ref_System.Net.Security",
        "//src/libraries/System.Runtime.Serialization.Formatters:impl_System.Runtime.Serialization.Formatters",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/System.Threading.Thread:ref_System.Threading.Thread",
        "//src/libraries/System.Xml.XDocument:ref_System.Xml.XDocument",
        "//src/libraries/System.Xml.ReaderWriter:ref_System.Xml.ReaderWriter",
        "//src/libraries/Common/tests:TestUtilities",
        "@paket.main//moq",
        "//src/libraries/System.Linq.Expressions:ref_System.Linq.Expressions",
        "@paket.main//microsoft.dotnet.remoteexecutor",
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//microsoft.dotnet.xunitextensions",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    defines = ["FUNCTIONAL_TESTS"],
    resources = [":TestResx"],
    resource_logical_names = {"Resources.TestResx.resources": "Resources.TestResx.resources"},
    additionalfiles = ["Resources/TestResx.resx"],
    keyfile = OPEN_SNK,
    assembly_version = "9.9.9.9",
    nowarn = ["SYSLIB0011"],
    size = "large",
)
