load("//src/tests:live_test.bzl", "library_test")
load("//:defs.bzl", "OPEN_SNK")

library_test(
    name = "System.Runtime.Intrinsics.Tests",
    defines = select({"@platforms//os:linux": ["UNIX", "UNIX1_0"], "@platforms//os:macos": ["UNIX", "UNIX1_0"], "//conditions:default": []}),
    # Match MSBuild csproj: removes nullablePublicOnly and strict from Features.
    features_strict = False,
    features_nullable_public_only = False,
    srcs = glob(["**/*.cs"]) + [
        "//src/libraries/Common/tests:System/GenericMathTestMemberData.cs",
    ],
    deps = [
        "//src/libraries/System.Runtime.Numerics:ref_System.Runtime.Numerics",
        "//src/libraries/Common/tests:TestUtilities",
        "@paket.main//microsoft.dotnet.remoteexecutor",
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//microsoft.dotnet.xunitextensions",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    allow_unsafe_blocks = True,
    nowarn = [
        "1718",
        "SYSLIB0013",
    ],
    size = "large",
    keyfile = OPEN_SNK,
)
