load("//src/tests:live_test.bzl", "coreclr_merged_test")

coreclr_merged_test(
    name = "JIT.opt",
    deps = [
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    test_deps = [
        "//src/tests/JIT/opt/Add:IntAdd",
        "//src/tests/JIT/opt/And:IntAnd",
        "//src/tests/JIT/opt/And/Regressions:Regression1_And",
        "//src/tests/JIT/opt/AssertionPropagation:ArrBoundBinaryOp",
        "//src/tests/JIT/opt/AssertionPropagation:ArrBoundElim",
        "//src/tests/JIT/opt/AssertionPropagation:ArrBoundMinLength",
        "//src/tests/JIT/opt/AssertionPropagation:ArrBoundUnsigned",
        "//src/tests/JIT/opt/AssertionPropagation:ConstantProp",
        "//src/tests/JIT/opt/AssertionPropagation:CopyProp",
        "//src/tests/JIT/opt/AssertionPropagation:DynBlkNullAssertions",
        "//src/tests/JIT/opt/AssertionPropagation:LocalMorphBackedge",
        "//src/tests/JIT/opt/AssertionPropagation:NullCheckAssertion1",
        "//src/tests/JIT/opt/AssertionPropagation:NullCheckAssertion2",
        "//src/tests/JIT/opt/AssertionPropagation:NullCheckAssertion3",
        "//src/tests/JIT/opt/AssertionPropagation:NullCheckAssertion4",
        "//src/tests/JIT/opt/AssertionPropagation:NullCheckAssertion5",
        "//src/tests/JIT/opt/AssertionPropagation:NullCheckAssertion6",
        "//src/tests/JIT/opt/AssertionPropagation:NullCheckAssertion7",
        "//src/tests/JIT/opt/AssertionPropagation:TypeOfAssertion",
        "//src/tests/JIT/opt/AssertionPropagation/regression/dev10/bug573840:bug573840",
        "//src/tests/JIT/opt/CSE:CSEWithDoubleNegation",
        "//src/tests/JIT/opt/CSE:GitHub_16065a",
        "//src/tests/JIT/opt/CSE:GitHub_16065b",
        "//src/tests/JIT/opt/CSE:NarrowStore",
        "//src/tests/JIT/opt/Casts:IntCast",
        "//src/tests/JIT/opt/Casts:shared2",
        "//src/tests/JIT/opt/Casts:shared_Casts",
        "//src/tests/JIT/opt/Casts:tests",
        "//src/tests/JIT/opt/Cloning:Runtime_61040_1",
        "//src/tests/JIT/opt/Cloning:Runtime_61040_2",
        "//src/tests/JIT/opt/Cloning:Runtime_61040_3",
        "//src/tests/JIT/opt/Cloning:Runtime_61040_4",
        "//src/tests/JIT/opt/Cloning:Runtime_61040_5",
        "//src/tests/JIT/opt/Cloning:Runtime_70802",
        "//src/tests/JIT/opt/Cloning:callandindir",
        "//src/tests/JIT/opt/Cloning:loops_with_eh",
        "//src/tests/JIT/opt/Compares:compareAnd2Chains",
        "//src/tests/JIT/opt/Compares:compareAnd3Chains",
        "//src/tests/JIT/opt/Compares:compareAndTestChains",
        "//src/tests/JIT/opt/Compares:compares",
        "//src/tests/JIT/opt/Compares:conditionalIncrements",
        "//src/tests/JIT/opt/Compares:conditionalInverts",
        "//src/tests/JIT/opt/Compares:conditionalNegates",
        "//src/tests/JIT/opt/Compares:conditionalSimpleOps",
        "//src/tests/JIT/opt/DSE/Regressions:NotRedundantInitsAreRemoved_Github_48394",
        "//src/tests/JIT/opt/Devirtualization:EqualityComparer_GitHub_10050",
        "//src/tests/JIT/opt/Devirtualization:GDV_GenericInterface",
        "//src/tests/JIT/opt/Devirtualization:GitHub_10311",
        "//src/tests/JIT/opt/Devirtualization:GitHub_10858",
        "//src/tests/JIT/opt/Devirtualization:GitHub_50492",
        "//src/tests/JIT/opt/Devirtualization:GitHub_51918",
        "//src/tests/JIT/opt/Devirtualization:GitHub_59668",
        "//src/tests/JIT/opt/Devirtualization:GitHub_9945",
        "//src/tests/JIT/opt/Devirtualization:MultipleCanonicallyCompatibleImplementations",
        "//src/tests/JIT/opt/Devirtualization:arraypool",
        "//src/tests/JIT/opt/Devirtualization:box1",
        "//src/tests/JIT/opt/Devirtualization:box2",
        "//src/tests/JIT/opt/Devirtualization:comparable",
        "//src/tests/JIT/opt/Devirtualization:constructor",
        "//src/tests/JIT/opt/Devirtualization:contravariance",
        "//src/tests/JIT/opt/Devirtualization:covariance",
        "//src/tests/JIT/opt/Devirtualization:enum",
        "//src/tests/JIT/opt/Devirtualization:exact1",
        "//src/tests/JIT/opt/Devirtualization:exact2",
        "//src/tests/JIT/opt/Devirtualization:exacttype",
        "//src/tests/JIT/opt/Devirtualization:fromcollection",
        "//src/tests/JIT/opt/Devirtualization:generic",
        "//src/tests/JIT/opt/Devirtualization:generic_noinline",
        "//src/tests/JIT/opt/Devirtualization:inlinedevirt",
        "//src/tests/JIT/opt/Devirtualization:late",
        "//src/tests/JIT/opt/Devirtualization:late1",
        "//src/tests/JIT/opt/Devirtualization:overload",
        "//src/tests/JIT/opt/Devirtualization:readonlystatic",
        "//src/tests/JIT/opt/Devirtualization:sealedclass",
        "//src/tests/JIT/opt/Devirtualization:sealeddefault",
        "//src/tests/JIT/opt/Devirtualization:sealedmethod",
        "//src/tests/JIT/opt/Devirtualization:sharedoverride",
        "//src/tests/JIT/opt/Devirtualization:simple",
        "//src/tests/JIT/opt/Devirtualization:spilledreturn",
        "//src/tests/JIT/opt/Devirtualization:structreturningstruct",
        "//src/tests/JIT/opt/Divide/Regressions:Regression1_Divide",
        "//src/tests/JIT/opt/Divide/Regressions:Regression2_Divide",
        "//src/tests/JIT/opt/Divide/Regressions:Regression3_Divide",
        "//src/tests/JIT/opt/Enum:hasflag",
        "//src/tests/JIT/opt/Enum:shared_Enum",
        "//src/tests/JIT/opt/FastTailCall:FastTailCallCandidates",
        "//src/tests/JIT/opt/FastTailCall:FastTailCallInlining",
        "//src/tests/JIT/opt/FastTailCall:GitHubIssue12479",
        "//src/tests/JIT/opt/FastTailCall:StackFixup",
        "//src/tests/JIT/opt/FastTailCall:StructPassingSimple",
        "//src/tests/JIT/opt/ForwardSub:andnotcontained",
        "//src/tests/JIT/opt/ForwardSub:callArgInterference",
        "//src/tests/JIT/opt/ForwardSub:callArgInterference2",
        "//src/tests/JIT/opt/ForwardSub:callArgInterference3",
        "//src/tests/JIT/opt/ForwardSub:earlyLiveness",
        "//src/tests/JIT/opt/ForwardSub:lowerContainCheckCompare",
        "//src/tests/JIT/opt/ForwardSub:modOpt",
        "//src/tests/JIT/opt/ForwardSub:switchWithSideEffects",
        "//src/tests/JIT/opt/GuardedDevirtualization:enumerablecloning",
        "//src/tests/JIT/opt/GuardedDevirtualization:typetestcloning",
        "//src/tests/JIT/opt/HeadTailMerge:headmergeexception",
        "//src/tests/JIT/opt/Hoisting:Hoisting",
        "//src/tests/JIT/opt/Inline/regression/bug584219:inliningVars",
        "//src/tests/JIT/opt/Inline/regression/bug595776:bug595776",
        "//src/tests/JIT/opt/Inline/tests:ArrayOfStructs",
        "//src/tests/JIT/opt/Inline/tests:DelegInstanceFtn",
        "//src/tests/JIT/opt/Inline/tests:DelegStaticFtn",
        "//src/tests/JIT/opt/Inline/tests:GenericStructs",
        "//src/tests/JIT/opt/Inline/tests:Inline",
        "//src/tests/JIT/opt/Inline/tests:InlineThrow",
        "//src/tests/JIT/opt/Inline/tests:Inline_DelegateStruct",
        "//src/tests/JIT/opt/Inline/tests:Inline_DetectChanges",
        "//src/tests/JIT/opt/Inline/tests:Inline_GenericMethods",
        "//src/tests/JIT/opt/Inline/tests:Inline_Many",
        "//src/tests/JIT/opt/Inline/tests:Inline_MultipleReturn",
        "//src/tests/JIT/opt/Inline/tests:Inline_NewObj",
        "//src/tests/JIT/opt/Inline/tests:Inline_NormalizeStack",
        "//src/tests/JIT/opt/Inline/tests:Inline_Recursion",
        "//src/tests/JIT/opt/Inline/tests:Inline_RecursiveMethod",
        "//src/tests/JIT/opt/Inline/tests:Inline_RecursiveMethod21",
        "//src/tests/JIT/opt/Inline/tests:Inline_STARG",
        "//src/tests/JIT/opt/Inline/tests:Inline_SideAffects",
        "//src/tests/JIT/opt/Inline/tests:Inline_Vars",
        "//src/tests/JIT/opt/Inline/tests:Inline_handler",
        "//src/tests/JIT/opt/Inline/tests:LotsOfInlines",
        "//src/tests/JIT/opt/Inline/tests:ReturnStruct_Method",
        "//src/tests/JIT/opt/Inline/tests:StructAsParam_Method",
        "//src/tests/JIT/opt/Inline/tests:StructInClass",
        "//src/tests/JIT/opt/Inline/tests:UnsafeBlockCopy",
        "//src/tests/JIT/opt/Inline/tests:args1",
        "//src/tests/JIT/opt/Inline/tests:args2",
        "//src/tests/JIT/opt/Inline/tests:args3",
        "//src/tests/JIT/opt/Inline/tests:array",
        "//src/tests/JIT/opt/Inline/tests:debug",
        "//src/tests/JIT/opt/Inline/tests:deepcall",
        "//src/tests/JIT/opt/Inline/tests:fact",
        "//src/tests/JIT/opt/Inline/tests:ifelse",
        "//src/tests/JIT/opt/Inline/tests:indexer",
        "//src/tests/JIT/opt/Inline/tests:interfaceCall",
        "//src/tests/JIT/opt/Inline/tests:interfaceproperty",
        "//src/tests/JIT/opt/Inline/tests:mathfunc",
        "//src/tests/JIT/opt/Inline/tests:mthdimpl",
        "//src/tests/JIT/opt/Inline/tests:property",
        "//src/tests/JIT/opt/Inline/tests:size",
        "//src/tests/JIT/opt/Inline/tests:struct_opcodes",
        "//src/tests/JIT/opt/Inline/tests:throwtest",
        "//src/tests/JIT/opt/Inline/tests:trycatch",
        "//src/tests/JIT/opt/InstructionCombining:Add",
        "//src/tests/JIT/opt/InstructionCombining:And",
        "//src/tests/JIT/opt/InstructionCombining:ArrayLengthArithmetic",
        "//src/tests/JIT/opt/InstructionCombining:BitwiseClearShift",
        "//src/tests/JIT/opt/InstructionCombining:Cmn",
        "//src/tests/JIT/opt/InstructionCombining:Cmp",
        "//src/tests/JIT/opt/InstructionCombining:CompareExtend",
        "//src/tests/JIT/opt/InstructionCombining:DivToMul",
        "//src/tests/JIT/opt/InstructionCombining:Eon",
        "//src/tests/JIT/opt/InstructionCombining:Eor",
        "//src/tests/JIT/opt/InstructionCombining:MulToAdd",
        "//src/tests/JIT/opt/InstructionCombining:Mvn",
        "//src/tests/JIT/opt/InstructionCombining:Neg",
        "//src/tests/JIT/opt/InstructionCombining:NegMulOrDivToConst",
        "//src/tests/JIT/opt/InstructionCombining:Orn",
        "//src/tests/JIT/opt/InstructionCombining:Orr",
        "//src/tests/JIT/opt/InstructionCombining:Sub",
        "//src/tests/JIT/opt/InstructionCombining:UbfizSbfiz",
        "//src/tests/JIT/opt/IsKnownConstant:StringEquals_IsKnownConstant",
        "//src/tests/JIT/opt/LocAlloc:inloop",
        "//src/tests/JIT/opt/LocAlloc:localloc",
        "//src/tests/JIT/opt/Loops:DownwardsLoopMultiplyExecutedExitingBlock",
        "//src/tests/JIT/opt/Loops:LoopSideEffectsForHwiStores",
        "//src/tests/JIT/opt/Loops:SearchLoopTail",
        "//src/tests/JIT/opt/Loops:TripCountOverflow",
        "//src/tests/JIT/opt/Misc/Runtime_80086:Runtime_80086",
        "//src/tests/JIT/opt/Multiply:IntMultiply",
        "//src/tests/JIT/opt/Multiply:MultiplyLongOps",
        "//src/tests/JIT/opt/OSR:Runtime_69032",
        "//src/tests/JIT/opt/OSR:Runtime_89666",
        "//src/tests/JIT/opt/OSR:addressexposedlocal",
        "//src/tests/JIT/opt/OSR:doublestackalloc",
        "//src/tests/JIT/opt/OSR:example",
        "//src/tests/JIT/opt/OSR:exposure1",
        "//src/tests/JIT/opt/OSR:exposure2",
        "//src/tests/JIT/opt/OSR:genericmethodpatchpoint",
        "//src/tests/JIT/opt/OSR:handlerloop",
        "//src/tests/JIT/opt/OSR:innerloop",
        "//src/tests/JIT/opt/OSR:integersumloop",
        "//src/tests/JIT/opt/OSR:invalidpromotion",
        "//src/tests/JIT/opt/OSR:largefuncletframe",
        "//src/tests/JIT/opt/OSR:livelocaladdress",
        "//src/tests/JIT/opt/OSR:livelocalstackalloc",
        "//src/tests/JIT/opt/OSR:mainloop",
        "//src/tests/JIT/opt/OSR:mainloop2",
        "//src/tests/JIT/opt/OSR:mainlooptry",
        "//src/tests/JIT/opt/OSR:mainlooptry2",
        "//src/tests/JIT/opt/OSR:mainlooptry3",
        "//src/tests/JIT/opt/OSR:mainlooptry4",
        "//src/tests/JIT/opt/OSR:memoryargument",
        "//src/tests/JIT/opt/OSR:nesteddoloops",
        "//src/tests/JIT/opt/OSR:normalizeonload",
        "//src/tests/JIT/opt/OSR:originalstackalloc",
        "//src/tests/JIT/opt/OSR:osrcontainstry",
        "//src/tests/JIT/opt/OSR:pinnedlocal",
        "//src/tests/JIT/opt/OSR:promoted",
        "//src/tests/JIT/opt/OSR:shadowparam",
        "//src/tests/JIT/opt/OSR:shortenregisteredlocal",
        "//src/tests/JIT/opt/OSR:synchronized",
        "//src/tests/JIT/opt/OSR:tailpgo",
        "//src/tests/JIT/opt/OSR:tailpgo2",
        "//src/tests/JIT/opt/OSR:tailrecurse",
        "//src/tests/JIT/opt/OSR:tailrecursetry",
        "//src/tests/JIT/opt/OSR:tailrecursetry2",
        "//src/tests/JIT/opt/OSR:twoosrmethods",
        "//src/tests/JIT/opt/OSR:twoosrmethods1",
        "//src/tests/JIT/opt/ObjectStackAllocation:ConnectionCycles",
        "//src/tests/JIT/opt/ObjectStackAllocation:Delegates",
        "//src/tests/JIT/opt/ObjectStackAllocation:Fields",
        "//src/tests/JIT/opt/ObjectStackAllocation:Runtime_111922",
        "//src/tests/JIT/opt/ObjectStackAllocation:Runtime_111922v2",
        "//src/tests/JIT/opt/ObjectStackAllocation:Runtime_115831",
        "//src/tests/JIT/opt/ObjectStackAllocation:Runtime_115832",
        "//src/tests/JIT/opt/ObjectStackAllocation:Runtime_115979",
        "//src/tests/JIT/opt/ObjectStackAllocation:Runtime_116214",
        "//src/tests/JIT/opt/OptSwitchRecognition:optSwitchRecognition",
        "//src/tests/JIT/opt/OptimizeBools:optboolsreturn",
        "//src/tests/JIT/opt/Or:IntOr",
        "//src/tests/JIT/opt/RangeChecks:ModLength",
        "//src/tests/JIT/opt/RangeChecks:Overflow",
        "//src/tests/JIT/opt/RedundantBranch:RedundantBranchAnd",
        "//src/tests/JIT/opt/RedundantBranch:RedundantBranchOr",
        "//src/tests/JIT/opt/RedundantBranch:RedundantBranchUnsigned",
        "//src/tests/JIT/opt/RedundantBranch:RedundantBranchUnsigned2",
        "//src/tests/JIT/opt/Regressions:Regression1_Regressions",
        "//src/tests/JIT/opt/Regressions:Regression2_Regressions",
        "//src/tests/JIT/opt/Regressions:Regression3_Regressions",
        "//src/tests/JIT/opt/Regressions:Regression4",
        "//src/tests/JIT/opt/Regressions:Regression5",
        "//src/tests/JIT/opt/Regressions:Regression6",
        "//src/tests/JIT/opt/Regressions:Regression7",
        "//src/tests/JIT/opt/Remainder:IntRemainder",
        "//src/tests/JIT/opt/Remainder/Regressions/Regression1:Regression1",
        "//src/tests/JIT/opt/SSA:MemorySsa",
        "//src/tests/JIT/opt/SVE:ChangeMaskUse",
        "//src/tests/JIT/opt/SVE:ConditionalSelectConstants",
        "//src/tests/JIT/opt/SVE:ConstantMasks",
        "//src/tests/JIT/opt/SVE:ConstantMasksOp2Fixed",
        "//src/tests/JIT/opt/SVE:ConstantVectors",
        "//src/tests/JIT/opt/SVE:EmbeddedLoads",
        "//src/tests/JIT/opt/SVE:MaskUse",
        "//src/tests/JIT/opt/SVE:PredicateInstructions",
        "//src/tests/JIT/opt/Structs:MemsetMemcpyNullref",
        "//src/tests/JIT/opt/Structs:StructWithGC_Zeroing",
        "//src/tests/JIT/opt/Structs:structcopies",
        "//src/tests/JIT/opt/Structs:structpop",
        "//src/tests/JIT/opt/Structs:structpop2",
        "//src/tests/JIT/opt/Subtract:IntSubtract",
        "//src/tests/JIT/opt/Tailcall:EarlyFlowOptExample",
        "//src/tests/JIT/opt/Tailcall:ImplicitByrefTailCalls",
        "//src/tests/JIT/opt/Tailcall:ImplicitByrefTailCallsAliasing",
        "//src/tests/JIT/opt/ThrowHelper:NonVoidThrowHelper",
        "//src/tests/JIT/opt/ThrowHelper:ThrowHelper",
        "//src/tests/JIT/opt/ThrowHelper:ThrowHelperAtTryEntry",
        "//src/tests/JIT/opt/Types:Equality",
        "//src/tests/JIT/opt/Unsafe:Unsafe",
        "//src/tests/JIT/opt/ValueNumbering:ConstIndexRVA",
        "//src/tests/JIT/opt/ValueNumbering:ConstStringConstIndexOptimizations",
        "//src/tests/JIT/opt/ValueNumbering:ExceptionSets",
        "//src/tests/JIT/opt/ValueNumbering:ExceptionSetsPropagation_Hwi",
        "//src/tests/JIT/opt/ValueNumbering:ExposedLocalsNumbering",
        "//src/tests/JIT/opt/ValueNumbering:StaticReadonlyStructWithGC",
        "//src/tests/JIT/opt/ValueNumbering:TypeTestFolding",
        "//src/tests/JIT/opt/ValueNumbering:ZeroOffsetFieldSeqs",
        "//src/tests/JIT/opt/Vectorization:BufferMemmove",
        "//src/tests/JIT/opt/Vectorization:ReadUtf8",
        "//src/tests/JIT/opt/Vectorization:SpanHelpers_SequenceEqual",
        "//src/tests/JIT/opt/Vectorization:StackallocBlkTests",
        "//src/tests/JIT/opt/Vectorization:StringEquals_Vectorization",
        "//src/tests/JIT/opt/Vectorization:UnrollEqualsStartsWith",
        "//src/tests/JIT/opt/perf/doublealign:Locals",
        "//src/tests/JIT/opt/perf/doublenegate:GitHub_57470",
        "//src/tests/JIT/opt/perf/doublenegate:doublenegate",
        "//src/tests/JIT/opt/perf/movelim:CalculateChecksum",
        "//src/tests/JIT/opt/virtualstubdispatch/bigvtbl:bigvtbl_cs_d",
        "//src/tests/JIT/opt/virtualstubdispatch/bigvtbl:bigvtbl_cs_do",
        "//src/tests/JIT/opt/virtualstubdispatch/bigvtbl:bigvtbl_cs_r",
        "//src/tests/JIT/opt/virtualstubdispatch/bigvtbl:bigvtbl_cs_ro",
        "//src/tests/JIT/opt/virtualstubdispatch/hashcode:ctest1_cs_d",
        "//src/tests/JIT/opt/virtualstubdispatch/hashcode:ctest1_cs_do",
        "//src/tests/JIT/opt/virtualstubdispatch/hashcode:ctest1_cs_r",
        "//src/tests/JIT/opt/virtualstubdispatch/hashcode:ctest1_cs_ro",
        "//src/tests/JIT/opt/virtualstubdispatch/manyintf:ctest_cs_d",
        "//src/tests/JIT/opt/virtualstubdispatch/manyintf:ctest_cs_do",
        "//src/tests/JIT/opt/virtualstubdispatch/manyintf:ctest_cs_r",
        "//src/tests/JIT/opt/virtualstubdispatch/manyintf:ctest_cs_ro",
        "//src/tests/JIT/opt/virtualstubdispatch/mixed:mixed_cs_d",
        "//src/tests/JIT/opt/virtualstubdispatch/mixed:mixed_cs_do",
        "//src/tests/JIT/opt/virtualstubdispatch/mixed:mixed_cs_r",
        "//src/tests/JIT/opt/virtualstubdispatch/mixed:mixed_cs_ro",
    ],
)
