load("//src/libraries:defs.bzl", "COMMON_GENERATOR_ANALYZERS", "MULTITARGET_NOWARN", "netcoreapp_ref_assembly", "impl_assembly", "ref_impl_pair")

exports_files([
    "ref/Microsoft.Extensions.FileSystemGlobbing.cs",
])

netcoreapp_ref_assembly(
    name = "ref_Microsoft.Extensions.FileSystemGlobbing",
    srcs = [
        "ref/Microsoft.Extensions.FileSystemGlobbing.cs",
    ],
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Collections:ref_System.Collections",
    ],
)

impl_assembly(
    name = "impl_Microsoft.Extensions.FileSystemGlobbing",
    include_runtime_async = False,
    event_source_generator = False,
    nowarn = MULTITARGET_NOWARN + ["CP0003", "CS1591"],
    srcs = glob(["src/**/*.cs"]) + [
        "//src/libraries/System.Private.CoreLib:src/System/Numerics/Hashing/HashHelpers.cs",
    ],
    analyzers = COMMON_GENERATOR_ANALYZERS,
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Collections:ref_System.Collections",
        "//src/libraries/System.Linq:ref_System.Linq",
        "//src/libraries/System.Memory:ref_System.Memory",
    ],
    resx_file = "src/Resources/Strings.resx",
)

ref_impl_pair(
    name = "live_Microsoft.Extensions.FileSystemGlobbing",
    ref = ":ref_Microsoft.Extensions.FileSystemGlobbing",
    lib = ":impl_Microsoft.Extensions.FileSystemGlobbing",
    visibility = ["//visibility:public"],
)
