load("//src/tests:live_test.bzl", "il_coreclr_test")
load("//src/libraries:defs.bzl", "live_csharp_library")

live_csharp_library(
    name = "sinlib_cs",
    srcs = ["sinlib.cs"],
    visibility = ["//visibility:public"],
)

il_coreclr_test(
    name = "sin_il_cs_d",
    srcs = ["sin_cs_d.il", "sin_cs.il"],
    pri = 1,
    debug_type = "full",
    deps = [":sinlib_cs"],
)

il_coreclr_test(
    name = "sin_il_cs_r",
    srcs = ["sin_cs_r.il", "sin_cs.il"],
    pri = 1,
    debug_type = "pdbonly",
    optimize = True,
    deps = [":sinlib_cs"],
)
