load("//src/tests:live_test.bzl", "coreclr_test")

coreclr_test(
    name = "b425314",
    srcs = ["b425314.cs"],
    debug_type = "full",
    deps = [
        "//src/libraries/System.Threading.Thread:ref_System.Threading.Thread",
        "//src/libraries/System.Threading:ref_System.Threading",
    ],
)
