load("//src/libraries:defs.bzl", "netcoreapp_ref_assembly", "netcoreapp_impl_assembly", "ref_impl_pair")

exports_files([
    "ref/System.Linq.Expressions.cs",
])

netcoreapp_ref_assembly(
    name = "ref_System.Linq.Expressions",
    srcs = [
        "ref/System.Linq.Expressions.cs",
    ],
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.ObjectModel:ref_System.ObjectModel",
    ],
    nowarn = ["CS0618"],
)

netcoreapp_impl_assembly(
    name = "impl_System.Linq.Expressions",
    srcs = [
        # Common files
        "//src/libraries/Common:src/System/Obsoletions.cs",
        "//src/libraries/Common:src/System/Collections/Generic/ArrayBuilder.cs",

        # Dynamic Utils
        "src/System/Dynamic/Utils/CacheDict.cs",
        "src/System/Dynamic/Utils/CachedReflectionInfo.cs",
        "src/System/Dynamic/Utils/CollectionExtensions.cs",
        "src/System/Dynamic/Utils/ContractUtils.cs",
        "src/System/Dynamic/Utils/DelegateHelpers.cs",
        "src/System/Dynamic/Utils/ExpressionUtils.cs",
        "src/System/Dynamic/Utils/ExpressionVisitorUtils.cs",
        "src/System/Dynamic/Utils/Helpers.cs",
        "src/System/Dynamic/Utils/ListArgumentProvider.cs",
        "src/System/Dynamic/Utils/ListParameterProvider.cs",
        "src/System/Dynamic/Utils/TypeExtensions.cs",
        "src/System/Dynamic/Utils/TypeUtils.cs",

        # Dynamic
        "src/System/Dynamic/BinaryOperationBinder.cs",
        "src/System/Dynamic/BindingRestrictions.cs",
        "src/System/Dynamic/CallInfo.cs",
        "src/System/Dynamic/ConvertBinder.cs",
        "src/System/Dynamic/CreateInstanceBinder.cs",
        "src/System/Dynamic/DeleteIndexBinder.cs",
        "src/System/Dynamic/DeleteMemberBinder.cs",
        "src/System/Dynamic/DynamicMetaObject.cs",
        "src/System/Dynamic/DynamicMetaObjectBinder.cs",
        "src/System/Dynamic/DynamicObject.cs",
        "src/System/Dynamic/ExpandoClass.cs",
        "src/System/Dynamic/ExpandoObject.cs",
        "src/System/Dynamic/GetIndexBinder.cs",
        "src/System/Dynamic/GetMemberBinder.cs",
        "src/System/Dynamic/IDynamicMetaObjectProvider.cs",
        "src/System/Dynamic/IInvokeOnGetBinder.cs",
        "src/System/Dynamic/InvokeBinder.cs",
        "src/System/Dynamic/InvokeMemberBinder.cs",
        "src/System/Dynamic/SetIndexBinder.cs",
        "src/System/Dynamic/SetMemberBinder.cs",
        "src/System/Dynamic/UnaryOperationBinder.cs",
        "src/System/Dynamic/UpdateDelegates.Generated.cs",

        # Expressions Common
        "src/System/Linq/Expressions/Common/ArrayBuilderExtensions.cs",
        "src/System/Linq/Expressions/Common/CachedReflectionInfo.cs",
        "src/System/Linq/Expressions/Common/ConstantCheck.cs",

        # Expressions core
        "src/System/Linq/Expressions/BinaryExpression.cs",
        "src/System/Linq/Expressions/BlockExpression.cs",
        "src/System/Linq/Expressions/CatchBlock.cs",
        "src/System/Linq/Expressions/ConditionalExpression.cs",
        "src/System/Linq/Expressions/ConstantExpression.cs",
        "src/System/Linq/Expressions/DebugInfoExpression.cs",
        "src/System/Linq/Expressions/DebugViewWriter.cs",
        "src/System/Linq/Expressions/DefaultExpression.cs",
        "src/System/Linq/Expressions/DynamicExpression.cs",
        "src/System/Linq/Expressions/DynamicExpressionVisitor.cs",
        "src/System/Linq/Expressions/ElementInit.cs",
        "src/System/Linq/Expressions/Error.cs",
        "src/System/Linq/Expressions/Expression.cs",
        "src/System/Linq/Expressions/Expression.DebuggerProxy.cs",
        "src/System/Linq/Expressions/ExpressionStringBuilder.cs",
        "src/System/Linq/Expressions/ExpressionType.cs",
        "src/System/Linq/Expressions/ExpressionVisitor.cs",
        "src/System/Linq/Expressions/GotoExpression.cs",
        "src/System/Linq/Expressions/IArgumentProvider.cs",
        "src/System/Linq/Expressions/IDynamicExpression.cs",
        "src/System/Linq/Expressions/IndexExpression.cs",
        "src/System/Linq/Expressions/InvocationExpression.cs",
        "src/System/Linq/Expressions/IParameterProvider.cs",
        "src/System/Linq/Expressions/LabelExpression.cs",
        "src/System/Linq/Expressions/LabelTarget.cs",
        "src/System/Linq/Expressions/LambdaExpression.cs",
        "src/System/Linq/Expressions/ListInitExpression.cs",
        "src/System/Linq/Expressions/LoopExpression.cs",
        "src/System/Linq/Expressions/MemberAssignment.cs",
        "src/System/Linq/Expressions/MemberBinding.cs",
        "src/System/Linq/Expressions/MemberExpression.cs",
        "src/System/Linq/Expressions/MemberInitExpression.cs",
        "src/System/Linq/Expressions/MemberListBinding.cs",
        "src/System/Linq/Expressions/MemberMemberBinding.cs",
        "src/System/Linq/Expressions/MethodCallExpression.cs",
        "src/System/Linq/Expressions/NewArrayExpression.cs",
        "src/System/Linq/Expressions/NewExpression.cs",
        "src/System/Linq/Expressions/ParameterExpression.cs",
        "src/System/Linq/Expressions/RuntimeVariablesExpression.cs",
        "src/System/Linq/Expressions/StackGuard.cs",
        "src/System/Linq/Expressions/Strings.cs",
        "src/System/Linq/Expressions/SwitchCase.cs",
        "src/System/Linq/Expressions/SwitchExpression.cs",
        "src/System/Linq/Expressions/SymbolDocumentInfo.cs",
        "src/System/Linq/Expressions/TryExpression.cs",
        "src/System/Linq/Expressions/TypeBinaryExpression.cs",
        "src/System/Linq/Expressions/UnaryExpression.cs",
        "src/System/Linq/Expressions/Utils.cs",

        # Compiler
        "src/System/Linq/Expressions/Compiler/AnalyzedTree.cs",
        "src/System/Linq/Expressions/Compiler/AssemblyGen.cs",
        "src/System/Linq/Expressions/Compiler/BoundConstants.cs",
        "src/System/Linq/Expressions/Compiler/CompilerScope.cs",
        "src/System/Linq/Expressions/Compiler/CompilerScope.Storage.cs",
        "src/System/Linq/Expressions/Compiler/DelegateHelpers.cs",
        "src/System/Linq/Expressions/Compiler/DelegateHelpers.Generated.cs",
        "src/System/Linq/Expressions/Compiler/HoistedLocals.cs",
        "src/System/Linq/Expressions/Compiler/ILGen.cs",
        "src/System/Linq/Expressions/Compiler/KeyedStack.cs",
        "src/System/Linq/Expressions/Compiler/LabelInfo.cs",
        "src/System/Linq/Expressions/Compiler/LambdaCompiler.Address.cs",
        "src/System/Linq/Expressions/Compiler/LambdaCompiler.Binary.cs",
        "src/System/Linq/Expressions/Compiler/LambdaCompiler.ControlFlow.cs",
        "src/System/Linq/Expressions/Compiler/LambdaCompiler.cs",
        "src/System/Linq/Expressions/Compiler/LambdaCompiler.Expressions.cs",
        "src/System/Linq/Expressions/Compiler/LambdaCompiler.Generated.cs",
        "src/System/Linq/Expressions/Compiler/LambdaCompiler.Lambda.cs",
        "src/System/Linq/Expressions/Compiler/LambdaCompiler.Logical.cs",
        "src/System/Linq/Expressions/Compiler/LambdaCompiler.Statements.cs",
        "src/System/Linq/Expressions/Compiler/LambdaCompiler.Unary.cs",
        "src/System/Linq/Expressions/Compiler/StackSpiller.Bindings.cs",
        "src/System/Linq/Expressions/Compiler/StackSpiller.ChildRewriter.cs",
        "src/System/Linq/Expressions/Compiler/StackSpiller.cs",
        "src/System/Linq/Expressions/Compiler/StackSpiller.Generated.cs",
        "src/System/Linq/Expressions/Compiler/StackSpiller.SpilledExpressionBlock.cs",
        "src/System/Linq/Expressions/Compiler/StackSpiller.Temps.cs",
        "src/System/Linq/Expressions/Compiler/TypeInfoExtensions.cs",
        "src/System/Linq/Expressions/Compiler/VariableBinder.cs",

        # Interpreter
        "src/System/Linq/Expressions/Interpreter/AddInstruction.cs",
        "src/System/Linq/Expressions/Interpreter/AndInstruction.cs",
        "src/System/Linq/Expressions/Interpreter/ArrayOperations.cs",
        "src/System/Linq/Expressions/Interpreter/BranchLabel.cs",
        "src/System/Linq/Expressions/Interpreter/CallInstruction.cs",
        "src/System/Linq/Expressions/Interpreter/CallInstruction.Generated.cs",
        "src/System/Linq/Expressions/Interpreter/ControlFlowInstructions.cs",
        "src/System/Linq/Expressions/Interpreter/DecrementInstruction.cs",
        "src/System/Linq/Expressions/Interpreter/DefaultValueInstruction.cs",
        "src/System/Linq/Expressions/Interpreter/DivInstruction.cs",
        "src/System/Linq/Expressions/Interpreter/EqualInstruction.cs",
        "src/System/Linq/Expressions/Interpreter/ExclusiveOrInstruction.cs",
        "src/System/Linq/Expressions/Interpreter/FieldOperations.cs",
        "src/System/Linq/Expressions/Interpreter/GreaterThanInstruction.cs",
        "src/System/Linq/Expressions/Interpreter/GreaterThanOrEqualInstruction.cs",
        "src/System/Linq/Expressions/Interpreter/IncrementInstruction.cs",
        "src/System/Linq/Expressions/Interpreter/Instruction.cs",
        "src/System/Linq/Expressions/Interpreter/InstructionList.cs",
        "src/System/Linq/Expressions/Interpreter/InterpretedFrame.cs",
        "src/System/Linq/Expressions/Interpreter/Interpreter.cs",
        "src/System/Linq/Expressions/Interpreter/LabelInfo.cs",
        "src/System/Linq/Expressions/Interpreter/LeftShiftInstruction.cs",
        "src/System/Linq/Expressions/Interpreter/LessThanInstruction.cs",
        "src/System/Linq/Expressions/Interpreter/LessThanOrEqualInstruction.cs",
        "src/System/Linq/Expressions/Interpreter/LightCompiler.cs",
        "src/System/Linq/Expressions/Interpreter/LightDelegateCreator.cs",
        "src/System/Linq/Expressions/Interpreter/LightLambda.cs",
        "src/System/Linq/Expressions/Interpreter/LightLambda.Generated.cs",
        "src/System/Linq/Expressions/Interpreter/LocalAccess.cs",
        "src/System/Linq/Expressions/Interpreter/LocalVariables.cs",
        "src/System/Linq/Expressions/Interpreter/ModuloInstruction.cs",
        "src/System/Linq/Expressions/Interpreter/MulInstruction.cs",
        "src/System/Linq/Expressions/Interpreter/NegateInstruction.cs",
        "src/System/Linq/Expressions/Interpreter/NewInstruction.cs",
        "src/System/Linq/Expressions/Interpreter/NotEqualInstruction.cs",
        "src/System/Linq/Expressions/Interpreter/NotInstruction.cs",
        "src/System/Linq/Expressions/Interpreter/NullCheckInstruction.cs",
        "src/System/Linq/Expressions/Interpreter/NumericConvertInstruction.cs",
        "src/System/Linq/Expressions/Interpreter/OrInstruction.cs",
        "src/System/Linq/Expressions/Interpreter/RightShiftInstruction.cs",
        "src/System/Linq/Expressions/Interpreter/RuntimeVariables.cs",
        "src/System/Linq/Expressions/Interpreter/StackOperations.cs",
        "src/System/Linq/Expressions/Interpreter/SubInstruction.cs",
        "src/System/Linq/Expressions/Interpreter/TypeOperations.cs",
        "src/System/Linq/Expressions/Interpreter/Utilities.cs",

        # Other
        "src/System/Linq/IQueryable.cs",
        "src/System/Runtime/CompilerServices/CallSite.cs",
        "src/System/Runtime/CompilerServices/CallSiteBinder.cs",
        "src/System/Runtime/CompilerServices/CallSiteHelpers.cs",
        "src/System/Runtime/CompilerServices/CallSiteOps.cs",
        "src/System/Runtime/CompilerServices/CallSiteOpsReflectionCache.cs",
        "src/System/Runtime/CompilerServices/Closure.cs",
        "src/System/Runtime/CompilerServices/DebugInfoGenerator.cs",
        "src/System/Runtime/CompilerServices/DynamicAttribute.cs",
        "src/System/Runtime/CompilerServices/IRuntimeVariables.cs",
        "src/System/Runtime/CompilerServices/ReadOnlyCollectionBuilder.cs",
        "src/System/Runtime/CompilerServices/RuleCache.cs",
        "src/System/Runtime/CompilerServices/RuntimeOps.ExpressionQuoter.cs",
        "src/System/Runtime/CompilerServices/RuntimeOps.MergedRuntimeVariables.cs",
        "src/System/Runtime/CompilerServices/RuntimeOps.RuntimeVariableList.cs",
        "src/System/Runtime/CompilerServices/RuntimeOps.RuntimeVariables.cs",
        "src/System/Runtime/CompilerServices/TrueReadOnlyCollection.cs",
    ],
    deps = [
        "//src/libraries/System.Collections:ref_System.Collections",
        "//src/libraries/System.Linq:ref_System.Linq",
        "//src/libraries/System.Memory:ref_System.Memory",
        "//src/libraries/System.ObjectModel:ref_System.ObjectModel",
        "//src/libraries/System.Reflection.Emit:ref_System.Reflection.Emit",
        "//src/libraries/System.Reflection.Emit.ILGeneration:ref_System.Reflection.Emit.ILGeneration",
        "//src/libraries/System.Reflection.Emit.Lightweight:ref_System.Reflection.Emit.Lightweight",
        "//src/libraries/System.Reflection.Primitives:ref_System.Reflection.Primitives",
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Threading:ref_System.Threading",
    ],
    resx_file = "src/Resources/Strings.resx",
    defines = [
        "FEATURE_FAST_CREATE",
    ],
)

ref_impl_pair(
    name = "live_System.Linq.Expressions",
    ref = ":ref_System.Linq.Expressions",
    lib = ":impl_System.Linq.Expressions",
    visibility = ["//visibility:public"],
)
