load("//src/tests:live_test.bzl", "library_test")
load("//src/libraries:defs.bzl", "MULTITARGET_NOWARN")
load("//:defs.bzl", "OPEN_SNK", "gen_resx_source", "resgen")

gen_resx_source(
    name = "gen_resx",
    out = "SR.g.cs",
    assembly_name = "Microsoft.Bcl.Cryptography.Tests",
    resx_file = "//src/libraries/Microsoft.Bcl.Cryptography:src/Resources/Strings.resx",
)

resgen(
    name = "strings_resx",
    out = "FxResources.Microsoft.Bcl.Cryptography.Tests.SR.resources",
    resx_file = "//src/libraries/Microsoft.Bcl.Cryptography:src/Resources/Strings.resx",
)

library_test(
    name = "Microsoft.Bcl.Cryptography.Tests",
    resources = [":strings_resx"],
    resource_logical_names = {"FxResources.Microsoft.Bcl.Cryptography.Tests.SR.resources": "FxResources.Microsoft.Bcl.Cryptography.Tests.SR.resources"},
    additionalfiles = ["//src/libraries/Microsoft.Bcl.Cryptography:src/Resources/Strings.resx"],
    allow_unsafe_blocks = True,
    data = ["@paket.main//system.security.cryptography.x509certificates.testdata:content_files"],
    nowarn = MULTITARGET_NOWARN + ["SYSLIB5006"],
    srcs = glob(
        ["*.cs", "X509Certificates/**/*.cs"],
        exclude = [
            "PemEncodingFindTests.cs",
            "PemEncodingTests.cs",
        ],
    ) + [
        "//src/libraries/Common:src/Interop/Windows/BCrypt/Interop.Blobs.cs",
        "//src/libraries/Common:src/System/IO/MemoryMappedFiles/MemoryMappedFileMemoryManager.cs",
        "//src/libraries/Common:src/System/Memory/PointerMemoryManager.cs",
        "//src/libraries/Common:src/System/SR.cs",
        "//src/libraries/Common:src/System/Security/Cryptography/Asn1Reader/AsnValueReader.cs",
        "//src/libraries/Common:src/System/Security/Cryptography/Asn1/AlgorithmIdentifierAsn.manual.cs",
        "//src/libraries/Common:src/System/Security/Cryptography/Asn1/AlgorithmIdentifierAsn.xml.cs",
        "//src/libraries/Common:src/System/Security/Cryptography/Asn1/AttributeAsn.manual.cs",
        "//src/libraries/Common:src/System/Security/Cryptography/Asn1/AttributeAsn.xml.cs",
        "//src/libraries/Common:src/System/Security/Cryptography/Asn1/EncryptedPrivateKeyInfoAsn.xml.cs",
        "//src/libraries/Common:src/System/Security/Cryptography/Asn1/MLDsaPrivateKeyAsn.xml.cs",
        "//src/libraries/Common:src/System/Security/Cryptography/Asn1/MLDsaPrivateKeyBothAsn.xml.cs",
        "//src/libraries/Common:src/System/Security/Cryptography/Asn1/PBEParameter.xml.cs",
        "//src/libraries/Common:src/System/Security/Cryptography/Asn1/PBES2Params.xml.cs",
        "//src/libraries/Common:src/System/Security/Cryptography/Asn1/Pbkdf2Params.xml.cs",
        "//src/libraries/Common:src/System/Security/Cryptography/Asn1/Pbkdf2SaltChoice.xml.cs",
        "//src/libraries/Common:src/System/Security/Cryptography/Asn1/PrivateKeyInfoAsn.xml.cs",
        "//src/libraries/Common:src/System/Security/Cryptography/Asn1/SubjectPublicKeyInfoAsn.xml.cs",
        "//src/libraries/Common:src/System/Security/Cryptography/CryptoPool.cs",
        "//src/libraries/Common:src/System/Security/Cryptography/PqcBlobHelpers.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AsnUtils.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/ByteUtils.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/CngKeyWrapper.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/CommonAEADTests.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/HashInfo.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/PlatformSupport.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/MLKemTestData.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/MLKemAlgorithmTests.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/MLKemBaseTests.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/MLKemImplementationTests.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/MLKemKeyTests.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/MLKemNotSupportedTests.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/PbeParametersTests.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/MLKemContractTests.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/MLDsa/MLDsaTestHelpers.Cng.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/MLDsa/MLDsaTestHelpers.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/MLDsa/MLDsaTestImplementation.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/SlhDsa/SlhDsaMockImplementation.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/SlhDsa/SlhDsaTestData.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/SlhDsa/SlhDsaTestData.GeneratedCertificates.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/MLDsa/MLDsaTestsData.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/MLDsa/MLDsaTestsData.Ietf.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/X509Certificates/MLKemCertTests.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/X509Certificates/TempFileHolder.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/X509Certificates/TestData.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/X509Certificates/X509CertificateLoaderPkcs12CollectionTests.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/X509Certificates/X509CertificateLoaderPkcs12Tests.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/X509Certificates/X509CertificateLoaderTests.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/X509Certificates/CertificateCreation/PrivateKeyAssociationTests.Shared.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AesGcmTests.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/CompositeMLDsa/CompositeMLDsaContractTests.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/CompositeMLDsa/CompositeMLDsaFactoryTests.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/CompositeMLDsa/CompositeMLDsaImplementationTests.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/CompositeMLDsa/CompositeMLDsaMockImplementation.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/CompositeMLDsa/CompositeMLDsaTestData.Raw.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/CompositeMLDsa/CompositeMLDsaTestData.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/CompositeMLDsa/CompositeMLDsaTestHelpers.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/CompositeMLDsa/CompositeMLDsaTestsBase.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/EC/EccTestData.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/MLDsa/MLDsaCngTests.Windows.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/MLDsa/MLDsaCngTests.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/MLDsa/MLDsaImplementationTests.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/MLDsa/MLDsaTests.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/MLDsa/MLDsaTestsBase.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/RSA/RSATestHelpers.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/SlhDsa/SlhDsaAlgorithmTests.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/SlhDsa/SlhDsaContractTests.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/SlhDsa/SlhDsaFactoryTests.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/SlhDsa/SlhDsaImplementationTests.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/SlhDsa/SlhDsaPlatformTests.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/SlhDsa/SlhDsaTestHelpers.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/AlgorithmImplementations/SlhDsa/SlhDsaTests.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/CompositeMLDsaAlgorithmTests.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/MLDsaAlgorithmTests.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/MLKemCngTests.NotSupported.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/MLKemCngTests.Windows.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/MLKemTests.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/SP800108HmacCounterKdfTests.ArgValidation.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/SP800108HmacCounterKdfTests.Functional.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/SP800108HmacCounterKdfTests.Helpers.cs",
        "//src/libraries/Common/tests:System/Security/Cryptography/SP800108HmacCounterKdfTests.ThreadSafety.cs",

        "//src/libraries/Microsoft.Bcl.Cryptography:src/System/Security/Cryptography/CngIdentifierExtensions.cs",
        ":gen_resx",
    ],
    deps = [
        "//src/libraries/Microsoft.Bcl.Cryptography:impl_Microsoft.Bcl.Cryptography",
        "//src/libraries/System.Collections.Concurrent:ref_System.Collections.Concurrent",
        "//src/libraries/System.Collections.Immutable:ref_System.Collections.Immutable",
        "//src/libraries/System.Formats.Asn1:ref_System.Formats.Asn1",
        "//src/libraries/System.IO.MemoryMappedFiles:ref_System.IO.MemoryMappedFiles",
        "//src/libraries/System.Runtime.Numerics:ref_System.Runtime.Numerics",
        "//src/libraries/System.Security.Cryptography:ref_System.Security.Cryptography",
        "//src/libraries/System.Security.Cryptography.Pkcs:ref_System.Security.Cryptography.Pkcs",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/System.Threading.Thread:ref_System.Threading.Thread",
        "//src/libraries/Common/tests:TestUtilities",
        "@paket.main//microsoft.dotnet.remoteexecutor",
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//microsoft.dotnet.xunitextensions",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    keyfile = OPEN_SNK,
)
