load("//src/libraries:defs.bzl", "COMMON_GENERATOR_ANALYZERS", "MULTITARGET_NOWARN", "netcoreapp_ref_assembly", "impl_assembly", "ref_impl_pair")
load("//:defs.bzl", "OPEN_SNK")

exports_files([
    "ref/System.CodeDom.cs",
])

netcoreapp_ref_assembly(
    name = "ref_System.CodeDom",
    srcs = [
        "ref/System.CodeDom.cs",
    ],
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Collections.NonGeneric:ref_System.Collections.NonGeneric",
        "//src/libraries/System.Collections.Specialized:ref_System.Collections.Specialized",
        "//src/libraries/System.ComponentModel.TypeConverter:ref_System.ComponentModel.TypeConverter",
        "//src/libraries:ref_System.ComponentModel.Primitives",
    ],
)

impl_assembly(
    name = "impl_System.CodeDom",
    include_runtime_async = False,
    event_source_generator = False,
    srcs = [
        "src/Microsoft/CSharp/CSharpCodeGenerator.cs",
        "src/Microsoft/CSharp/CSharpCodeGenerator.PlatformNotSupported.cs",
        "src/Microsoft/CSharp/CSharpCodeProvider.cs",
        "src/Microsoft/CSharp/CSharpMemberAttributeConverter.cs",
        "src/Microsoft/CSharp/CSharpModifierAttributeConverter.cs",
        "src/Microsoft/CSharp/CSharpTypeAttributeConverter.cs",
        "src/Microsoft/VisualBasic/VBCodeGenerator.cs",
        "src/Microsoft/VisualBasic/VBCodeGenerator.PlatformNotSupported.cs",
        "src/Microsoft/VisualBasic/VBCodeProvider.cs",
        "src/Microsoft/VisualBasic/VBMemberAttributeConverter.cs",
        "src/Microsoft/VisualBasic/VBModifierAttributeConverter.cs",
        "src/Microsoft/VisualBasic/VBTypeAttributeConverter.cs",
        "src/System/CodeDom/CodeArgumentReferenceExpression.cs",
        "src/System/CodeDom/CodeArrayCreateExpression.cs",
        "src/System/CodeDom/CodeArrayIndexerExpression.cs",
        "src/System/CodeDom/CodeAssignStatement.cs",
        "src/System/CodeDom/CodeAttachEventStatement.cs",
        "src/System/CodeDom/CodeAttributeArgument.cs",
        "src/System/CodeDom/CodeAttributeArgumentCollection.cs",
        "src/System/CodeDom/CodeAttributeDeclaration.cs",
        "src/System/CodeDom/CodeAttributeDeclarationCollection.cs",
        "src/System/CodeDom/CodeBaseReferenceExpression.cs",
        "src/System/CodeDom/CodeBinaryOperatorExpression.cs",
        "src/System/CodeDom/CodeBinaryOperatorType.cs",
        "src/System/CodeDom/CodeCastExpression.cs",
        "src/System/CodeDom/CodeCatchClause.cs",
        "src/System/CodeDom/CodeCatchClauseCollection.cs",
        "src/System/CodeDom/CodeChecksumPragma.cs",
        "src/System/CodeDom/CodeComment.cs",
        "src/System/CodeDom/CodeCommentStatement.cs",
        "src/System/CodeDom/CodeCommentStatementCollection.cs",
        "src/System/CodeDom/CodeCompileUnit.cs",
        "src/System/CodeDom/CodeConditionStatement.cs",
        "src/System/CodeDom/CodeConstructor.cs",
        "src/System/CodeDom/CodeDefaultValueExpression.cs",
        "src/System/CodeDom/CodeDelegateCreateExpression.cs",
        "src/System/CodeDom/CodeDelegateInvokeExpression.cs",
        "src/System/CodeDom/CodeDirectionExpression.cs",
        "src/System/CodeDom/CodeDirective.cs",
        "src/System/CodeDom/CodeDirectiveCollection.cs",
        "src/System/CodeDom/CodeEntryPointMethod.cs",
        "src/System/CodeDom/CodeEventReferenceExpression.cs",
        "src/System/CodeDom/CodeExpression.cs",
        "src/System/CodeDom/CodeExpressionCollection.cs",
        "src/System/CodeDom/CodeExpressionStatement.cs",
        "src/System/CodeDom/CodeFieldReferenceExpression.cs",
        "src/System/CodeDom/CodeGotoStatement.cs",
        "src/System/CodeDom/CodeIndexerExpression.cs",
        "src/System/CodeDom/CodeIterationStatement.cs",
        "src/System/CodeDom/CodeLabeledStatement.cs",
        "src/System/CodeDom/CodeLinePragma.cs",
        "src/System/CodeDom/CodeMemberEvent.cs",
        "src/System/CodeDom/CodeMemberField.cs",
        "src/System/CodeDom/CodeMemberMethod.cs",
        "src/System/CodeDom/CodeMemberProperty.cs",
        "src/System/CodeDom/CodeMethodInvokeExpression.cs",
        "src/System/CodeDom/codemethodreferenceexpression.cs",
        "src/System/CodeDom/CodeMethodReturnStatement.cs",
        "src/System/CodeDom/CodeNamespace.cs",
        "src/System/CodeDom/CodeNamespaceCollection.cs",
        "src/System/CodeDom/CodeNamespaceImport.cs",
        "src/System/CodeDom/CodeNamespaceImportCollection.cs",
        "src/System/CodeDom/CodeObjectCreateExpression.cs",
        "src/System/CodeDom/CodeParameterDeclarationExpression.cs",
        "src/System/CodeDom/CodeParameterDeclarationExpressionCollection.cs",
        "src/System/CodeDom/CodePrimitiveExpression.cs",
        "src/System/CodeDom/CodePropertyReferenceExpression.cs",
        "src/System/CodeDom/CodePropertySetValueReferenceExpression.cs",
        "src/System/CodeDom/CodeRegionDirective.cs",
        "src/System/CodeDom/CodeRegionMode.cs",
        "src/System/CodeDom/CodeRemoveEventStatement.cs",
        "src/System/CodeDom/CodeSnippetCompileUnit.cs",
        "src/System/CodeDom/CodeSnippetExpression.cs",
        "src/System/CodeDom/CodeSnippetStatement.cs",
        "src/System/CodeDom/CodeSnippetTypeMember.cs",
        "src/System/CodeDom/CodeStatement.cs",
        "src/System/CodeDom/CodeStatementCollection.cs",
        "src/System/CodeDom/CodeThisReferenceExpression.cs",
        "src/System/CodeDom/CodeThrowExceptionStatement.cs",
        "src/System/CodeDom/CodeTryCatchFinallyStatement.cs",
        "src/System/CodeDom/CodeTypeConstructor.cs",
        "src/System/CodeDom/CodeTypeDeclaration.cs",
        "src/System/CodeDom/CodeTypeDeclarationCollection.cs",
        "src/System/CodeDom/CodeTypeDelegate.cs",
        "src/System/CodeDom/CodeTypeMember.cs",
        "src/System/CodeDom/CodeTypeMemberCollection.cs",
        "src/System/CodeDom/CodeTypeOfExpression.cs",
        "src/System/CodeDom/CodeTypeParameter.cs",
        "src/System/CodeDom/CodeTypeParameterCollection.cs",
        "src/System/CodeDom/CodeTypeReferenceExpression.cs",
        "src/System/CodeDom/CodeVariableDeclarationStatement.cs",
        "src/System/CodeDom/CodeVariableReferenceExpression.cs",
        "src/System/CodeDom/Compiler/CodeCompiler.cs",
        "src/System/CodeDom/Compiler/CodeDomProvider.cs",
        "src/System/CodeDom/Compiler/CodeGenerator.cs",
        "src/System/CodeDom/Compiler/CodeGeneratorOptions.cs",
        "src/System/CodeDom/Compiler/CodeParser.cs",
        "src/System/CodeDom/Compiler/CodeValidator.cs",
        "src/System/CodeDom/Compiler/CompilerError.cs",
        "src/System/CodeDom/Compiler/CompilerErrorCollection.cs",
        "src/System/CodeDom/Compiler/CompilerInfo.cs",
        "src/System/CodeDom/Compiler/CompilerParameters.cs",
        "src/System/CodeDom/Compiler/CompilerResults.cs",
        "src/System/CodeDom/Compiler/Executor.cs",
        "src/System/CodeDom/Compiler/GeneratorSupport.cs",
        "src/System/CodeDom/Compiler/ICodeCompiler.cs",
        "src/System/CodeDom/Compiler/ICodeGenerator.cs",
        "src/System/CodeDom/Compiler/ICodeParser.cs",
        "src/System/CodeDom/Compiler/ExposedTabStringIndentedTextWriter.cs",
        "src/System/CodeDom/Compiler/LanguageOptions.cs",
        "src/System/CodeDom/FieldDirection.cs",
        "src/System/CodeDom/MemberAttributes.cs",
        "src/System/Collections/Specialized/FixedStringLookup.cs",
        "src/StringExtensions.cs",

        "//src/libraries/Common:src/System/CodeDom/CodeObject.cs",
        "//src/libraries/Common:src/System/CodeDom/CodeTypeReference.cs",
        "//src/libraries/Common:src/System/CodeDom/CodeTypeReferenceCollection.cs",
        "//src/libraries/Common:src/System/IO/TempFileCollection.cs",
        "//src/libraries/Common:src/System/CSharpHelpers.cs",
    ],
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Collections:ref_System.Collections",
        "//src/libraries/System.Collections.NonGeneric:ref_System.Collections.NonGeneric",
        "//src/libraries/System.Collections.Specialized:ref_System.Collections.Specialized",
        "//src/libraries/System.ComponentModel.TypeConverter:ref_System.ComponentModel.TypeConverter",
        "//src/libraries:ref_System.ComponentModel.Primitives",
        "//src/libraries/System.Memory:ref_System.Memory",
        "//src/libraries:ref_System.Diagnostics.Process",
        "//src/libraries/System.Text.RegularExpressions:ref_System.Text.RegularExpressions",
        "//src/libraries/System.Threading:ref_System.Threading",
    ],
    defines = ["CODEDOM"],
    resx_file = "src/Resources/Strings.resx",
    nullable = "disable",
    analyzers = COMMON_GENERATOR_ANALYZERS,
    keyfile = OPEN_SNK,
    allow_unsafe_blocks = True,
    nowarn = MULTITARGET_NOWARN + ["nullable", "CP0003", "CS1591"],
)

ref_impl_pair(
    name = "live_System.CodeDom",
    ref = ":ref_System.CodeDom",
    lib = ":impl_System.CodeDom",
    visibility = ["//visibility:public"],
)
