load("//:defs.bzl", "csharp_library", "gen_assembly_info", "gen_resx_source", "gen_target_framework_attrs", "resgen")

gen_assembly_info(
    name = "assemblyinfo_ILCompiler.Compiler",
    out = "ILCompiler.Compiler.AssemblyInfo.cs",
    assembly_name = "ILCompiler.Compiler",
    cls_compliant = False,
    is_aot_compatible = False,
    include_serviceable = False,
    include_description = False,
    assembly_configuration = "Release",
    include_dll_safe_search_path = 0,
)

gen_target_framework_attrs(
    name = "tfmattrs_ILCompiler.Compiler",
    out = ".NETCoreApp,Version=v10.0.AssemblyAttributes.cs",
)

gen_resx_source(
    name = "SharedStringsSR",
    out = "SharedStrings.g.cs",
    assembly_name = "ILCompiler.Compiler",
    resource_name = "ILLink.Shared.SharedStrings",
    resource_class_name = "ILLink.Shared.SharedStrings",
    resx_file = "//src/tools/illink/src/ILLink.Shared:SharedStrings.resx",
)

resgen(
    name = "SharedStringsResources",
    out = "ILLink.Shared.SharedStrings.resources",
    resx_file = "//src/tools/illink/src/ILLink.Shared:SharedStrings.resx",
)

exports_files(["Compiler/JitHelper.cs"])

csharp_library(
    name = "ILCompiler.Compiler",
    interceptors_namespaces = ";Microsoft.Extensions.Validation.Generated",
    srcs = [
        ":assemblyinfo_ILCompiler.Compiler",
        ":tfmattrs_ILCompiler.Compiler",
        ":SharedStringsSR",
        "Compiler/AnalysisBasedInteropStubManager.cs",
        "Compiler/AnalysisBasedMetadataManager.cs",
        "Compiler/AssemblyExtensions.cs",
        "Compiler/BodySubstitution.cs",
        "Compiler/BodySubstitutionParser.cs",
        "Compiler/Compilation.cs",
        "Compiler/CompilationBuilder.Aot.cs",
        "Compiler/CompilationModuleGroup.Aot.cs",
        "Compiler/CompilerGeneratedInteropStubManager.cs",
        "Compiler/CompilerMetadataFieldLayoutAlgorithm.cs",
        "Compiler/CompilerTypeSystemContext.Aot.cs",
        "Compiler/CompilerTypeSystemContext.BoxedTypes.cs",
        "Compiler/CompilerTypeSystemContext.DelegateInfo.cs",
        "Compiler/CompilerTypeSystemContext.DynamicInvoke.cs",
        "Compiler/CompilerTypeSystemContext.EnumMethods.cs",
        "Compiler/CompilerTypeSystemContext.GeneratedAssembly.Sorting.cs",
        "Compiler/CompilerTypeSystemContext.GeneratedAssembly.cs",
        "Compiler/CompilerTypeSystemContext.InterfaceThunks.cs",
        "Compiler/CompilerTypeSystemContext.Mangling.cs",
        "Compiler/CompilerTypeSystemContext.Sorting.cs",
        "Compiler/CompilerTypeSystemContext.ValueTypeMethods.cs",
        "Compiler/CustomAttributeExtensions.cs",
        "Compiler/Dataflow/ArrayValue.cs",
        "Compiler/Dataflow/AttributeDataFlow.cs",
        "Compiler/Dataflow/CompilerGeneratedCallGraph.cs",
        "Compiler/Dataflow/CompilerGeneratedState.cs",
        "Compiler/Dataflow/DiagnosticContext.cs",
        "Compiler/Dataflow/DiagnosticUtilities.cs",
        "Compiler/Dataflow/FieldReferenceValue.cs",
        "Compiler/Dataflow/FieldValue.cs",
        "Compiler/Dataflow/FlowAnnotations.cs",
        "Compiler/Dataflow/GenericArgumentDataFlow.cs",
        "Compiler/Dataflow/GenericParameterValue.cs",
        "Compiler/Dataflow/HandleCallAction.cs",
        "Compiler/Dataflow/HoistedLocalKey.cs",
        "Compiler/Dataflow/InterproceduralState.cs",
        "Compiler/Dataflow/LocalVariableReferenceValue.cs",
        "Compiler/Dataflow/MethodBodyScanner.cs",
        "Compiler/Dataflow/MethodParameterValue.cs",
        "Compiler/Dataflow/MethodReturnValue.cs",
        "Compiler/Dataflow/ParameterReferenceValue.cs",
        "Compiler/Dataflow/ReferenceValue.cs",
        "Compiler/Dataflow/ReflectionMarker.cs",
        "Compiler/Dataflow/ReflectionMethodBodyScanner.cs",
        "Compiler/Dataflow/RequireDynamicallyAccessedMembersAction.cs",
        "Compiler/Dataflow/ScannerExtensions.cs",
        "Compiler/Dataflow/TrimAnalysisAssignmentPattern.cs",
        "Compiler/Dataflow/TrimAnalysisFieldAccessPattern.cs",
        "Compiler/Dataflow/TrimAnalysisGenericInstantiationAccessPattern.cs",
        "Compiler/Dataflow/TrimAnalysisMethodCallPattern.cs",
        "Compiler/Dataflow/TrimAnalysisPatternStore.cs",
        "Compiler/Dataflow/TrimAnalysisTokenAccessPattern.cs",
        "Compiler/Dataflow/ValueNode.cs",
        "Compiler/DebugInformationProvider.cs",
        "Compiler/DelegateCreationInfo.cs",
        "Compiler/DependencyAnalysis/AddressTakenMethodNode.cs",
        "Compiler/DependencyAnalysis/AnalysisCharacteristicNode.cs",
        "Compiler/DependencyAnalysis/AnalyzedExternalTypeMapNode.cs",
        "Compiler/DependencyAnalysis/AnalyzedProxyTypeMapNode.cs",
        "Compiler/DependencyAnalysis/ArrayMapNode.cs",
        "Compiler/DependencyAnalysis/ArrayOfEmbeddedDataNode.cs",
        "Compiler/DependencyAnalysis/ArrayOfEmbeddedPointersNode.cs",
        "Compiler/DependencyAnalysis/ArrayOfFrozenObjectsNode.cs",
        "Compiler/DependencyAnalysis/BlobNode.cs",
        "Compiler/DependencyAnalysis/ByRefTypeMapNode.cs",
        "Compiler/DependencyAnalysis/CallingConventionConverterKey.cs",
        "Compiler/DependencyAnalysis/CanonicalDefinitionEETypeNode.cs",
        "Compiler/DependencyAnalysis/ClassConstructorContextMap.cs",
        "Compiler/DependencyAnalysis/CodeBasedDependencyAlgorithm.cs",
        "Compiler/DependencyAnalysis/ConstructedEETypeNode.cs",
        "Compiler/DependencyAnalysis/CustomAttributeBasedDependencyAlgorithm.cs",
        "Compiler/DependencyAnalysis/CustomAttributeMetadataNode.cs",
        "Compiler/DependencyAnalysis/DataflowAnalyzedMethodNode.cs",
        "Compiler/DependencyAnalysis/DataflowAnalyzedTypeDefinitionNode.cs",
        "Compiler/DependencyAnalysis/DehydratableObjectNode.cs",
        "Compiler/DependencyAnalysis/DehydratedDataNode.cs",
        "Compiler/DependencyAnalysis/DelegateMarshallingDataNode.cs",
        "Compiler/DependencyAnalysis/DelegateMarshallingStubMapNode.cs",
        "Compiler/DependencyAnalysis/DelegateTargetVirtualMethodNode.cs",
        "Compiler/DependencyAnalysis/DictionaryLayoutNode.cs",
        "Compiler/DependencyAnalysis/DynamicDependencyAttributesOnEntityNode.cs",
        "Compiler/DependencyAnalysis/EETypeNode.cs",
        "Compiler/DependencyAnalysis/EmbeddedObjectNode.cs",
        "Compiler/DependencyAnalysis/EmbeddedPointerIndirectionNode.cs",
        "Compiler/DependencyAnalysis/EmbeddedTrimmingDescriptorNode.cs",
        "Compiler/DependencyAnalysis/ExactMethodInstantiationsEntryNode.cs",
        "Compiler/DependencyAnalysis/ExactMethodInstantiationsNode.cs",
        "Compiler/DependencyAnalysis/ExternEETypeSymbolNode.cs",
        "Compiler/DependencyAnalysis/ExternMethodSymbolNode.cs",
        "Compiler/DependencyAnalysis/ExternSymbolNode.cs",
        "Compiler/DependencyAnalysis/ExternSymbolsImportedNodeProvider.cs",
        "Compiler/DependencyAnalysis/ExternalReferencesTableNode.cs",
        "Compiler/DependencyAnalysis/ExternalTypeMapNode.cs",
        "Compiler/DependencyAnalysis/ExternalTypeMapObjectNode.cs",
        "Compiler/DependencyAnalysis/ExternalTypeMapRequestNode.cs",
        "Compiler/DependencyAnalysis/FatFunctionPointerNode.cs",
        "Compiler/DependencyAnalysis/FieldMetadataNode.cs",
        "Compiler/DependencyAnalysis/FieldRvaDataNode.cs",
        "Compiler/DependencyAnalysis/FrozenObjectNode.cs",
        "Compiler/DependencyAnalysis/FrozenRuntimeTypeNode.cs",
        "Compiler/DependencyAnalysis/FrozenStringNode.cs",
        "Compiler/DependencyAnalysis/FunctionPointerMapNode.cs",
        "Compiler/DependencyAnalysis/GCStaticEETypeNode.cs",
        "Compiler/DependencyAnalysis/GCStaticsNode.cs",
        "Compiler/DependencyAnalysis/GCStaticsPreInitDataNode.cs",
        "Compiler/DependencyAnalysis/GVMDependenciesNode.cs",
        "Compiler/DependencyAnalysis/GenericCompositionNode.cs",
        "Compiler/DependencyAnalysis/GenericDefinitionEETypeNode.cs",
        "Compiler/DependencyAnalysis/GenericDictionaryNode.cs",
        "Compiler/DependencyAnalysis/GenericLookupResult.cs",
        "Compiler/DependencyAnalysis/GenericMethodsHashtableEntryNode.cs",
        "Compiler/DependencyAnalysis/GenericMethodsHashtableNode.cs",
        "Compiler/DependencyAnalysis/GenericMethodsTemplateMap.cs",
        "Compiler/DependencyAnalysis/GenericStaticBaseInfoNode.cs",
        "Compiler/DependencyAnalysis/GenericTypesHashtableNode.cs",
        "Compiler/DependencyAnalysis/GenericTypesTemplateMap.cs",
        "Compiler/DependencyAnalysis/GenericVarianceNode.cs",
        "Compiler/DependencyAnalysis/GenericVirtualMethodImplNode.cs",
        "Compiler/DependencyAnalysis/GenericVirtualMethodTableNode.cs",
        "Compiler/DependencyAnalysis/HelperEntrypoint.cs",
        "Compiler/DependencyAnalysis/IEETypeNode.cs",
        "Compiler/DependencyAnalysis/IExternalTypeMapNode.cs",
        "Compiler/DependencyAnalysis/ILScanNodeFactory.cs",
        "Compiler/DependencyAnalysis/INodeWithCodeInfo.Aot.cs",
        "Compiler/DependencyAnalysis/INodeWithDebugInfo.cs",
        "Compiler/DependencyAnalysis/IObjectDumper.cs",
        "Compiler/DependencyAnalysis/IProxyTypeMapNode.cs",
        "Compiler/DependencyAnalysis/ISpecialUnboxThunkNode.cs",
        "Compiler/DependencyAnalysis/ImportedNodeProvider.cs",
        "Compiler/DependencyAnalysis/InlineableStringsResourceNode.cs",
        "Compiler/DependencyAnalysis/InterfaceDispatchCellNode.cs",
        "Compiler/DependencyAnalysis/InterfaceDispatchCellSectionNode.cs",
        "Compiler/DependencyAnalysis/InterfaceDispatchMapNode.cs",
        "Compiler/DependencyAnalysis/InterfaceGenericVirtualMethodTableNode.cs",
        "Compiler/DependencyAnalysis/InterfaceUseNode.cs",
        "Compiler/DependencyAnalysis/InvalidExternalTypeMapNode.cs",
        "Compiler/DependencyAnalysis/InvalidProxyTypeMapNode.cs",
        "Compiler/DependencyAnalysis/JumpStubNode.cs",
        "Compiler/DependencyAnalysis/MetadataEETypeNode.cs",
        "Compiler/DependencyAnalysis/MetadataNode.cs",
        "Compiler/DependencyAnalysis/MethodAssociatedDataNode.cs",
        "Compiler/DependencyAnalysis/MethodExceptionHandlingInfoNode.cs",
        "Compiler/DependencyAnalysis/MethodMetadataNode.cs",
        "Compiler/DependencyAnalysis/MethodParameterMetadataNode.cs",
        "Compiler/DependencyAnalysis/ModuleInitializerListNode.cs",
        "Compiler/DependencyAnalysis/ModuleMetadataNode.cs",
        "Compiler/DependencyAnalysis/ModuleUseBasedDependencyAlgorithm.cs",
        "Compiler/DependencyAnalysis/ModulesSectionNode.cs",
        "Compiler/DependencyAnalysis/NativeLayoutInfoNode.cs",
        "Compiler/DependencyAnalysis/NativeLayoutVertexNode.cs",
        "Compiler/DependencyAnalysis/NodeFactory.GenericLookups.cs",
        "Compiler/DependencyAnalysis/NodeFactory.NativeLayout.cs",
        "Compiler/DependencyAnalysis/NodeFactory.cs",
        "Compiler/DependencyAnalysis/NonGCStaticsNode.cs",
        "Compiler/DependencyAnalysis/NotReadOnlyFieldNode.cs",
        "Compiler/DependencyAnalysis/ObjectGetTypeCalledNode.cs",
        "Compiler/DependencyAnalysis/ObjectGetTypeFlowDependenciesNode.cs",
        "Compiler/DependencyAnalysis/PInvokeMethodFixupNode.cs",
        "Compiler/DependencyAnalysis/PInvokeModuleFixupNode.cs",
        "Compiler/DependencyAnalysis/PointerTypeMapNode.cs",
        "Compiler/DependencyAnalysis/ProxyTypeMapNode.cs",
        "Compiler/DependencyAnalysis/ProxyTypeMapObjectNode.cs",
        "Compiler/DependencyAnalysis/ProxyTypeMapRequestNode.cs",
        "Compiler/DependencyAnalysis/ReadyToRunGenericHelperNode.cs",
        "Compiler/DependencyAnalysis/ReadyToRunHeaderNode.cs",
        "Compiler/DependencyAnalysis/ReadyToRunHelperNode.cs",
        "Compiler/DependencyAnalysis/ReflectedDelegateNode.cs",
        "Compiler/DependencyAnalysis/ReflectedFieldNode.cs",
        "Compiler/DependencyAnalysis/ReflectedMethodNode.cs",
        "Compiler/DependencyAnalysis/ReflectedTypeNode.cs",
        "Compiler/DependencyAnalysis/ReflectionFieldMapNode.cs",
        "Compiler/DependencyAnalysis/ReflectionInvokeMapNode.cs",
        "Compiler/DependencyAnalysis/ReflectionInvokeSupportDependencyAlgorithm.cs",
        "Compiler/DependencyAnalysis/ReflectionVirtualInvokeMapNode.cs",
        "Compiler/DependencyAnalysis/ResourceDataNode.cs",
        "Compiler/DependencyAnalysis/ResourceIndexNode.cs",
        "Compiler/DependencyAnalysis/RuntimeFieldHandleNode.cs",
        "Compiler/DependencyAnalysis/RuntimeImportMethodNode.cs",
        "Compiler/DependencyAnalysis/RuntimeMethodHandleNode.cs",
        "Compiler/DependencyAnalysis/ScannedMethodNode.cs",
        "Compiler/DependencyAnalysis/SealedVTableNode.cs",
        "Compiler/DependencyAnalysis/SerializedFrozenObjectNode.cs",
        "Compiler/DependencyAnalysis/ShadowConcreteUnboxingThunkNode.cs",
        "Compiler/DependencyAnalysis/StackTraceMethodMappingNode.cs",
        "Compiler/DependencyAnalysis/StaticsInfoHashtableNode.cs",
        "Compiler/DependencyAnalysis/StringAllocatorMethodNode.cs",
        "Compiler/DependencyAnalysis/StructMarshallingDataNode.cs",
        "Compiler/DependencyAnalysis/StructMarshallingStubMapNode.cs",
        "Compiler/DependencyAnalysis/Target_ARM/ARMJumpStubNode.cs",
        "Compiler/DependencyAnalysis/Target_ARM/ARMReadyToRunGenericHelperNode.cs",
        "Compiler/DependencyAnalysis/Target_ARM/ARMReadyToRunHelperNode.cs",
        "Compiler/DependencyAnalysis/Target_ARM/ARMTentativeMethodNode.cs",
        "Compiler/DependencyAnalysis/Target_ARM/ARMUnboxingStubNode.cs",
        "Compiler/DependencyAnalysis/Target_ARM64/ARM64JumpStubNode.cs",
        "Compiler/DependencyAnalysis/Target_ARM64/ARM64ReadyToRunGenericHelperNode.cs",
        "Compiler/DependencyAnalysis/Target_ARM64/ARM64ReadyToRunHelperNode.cs",
        "Compiler/DependencyAnalysis/Target_ARM64/ARM64TentativeMethodNode.cs",
        "Compiler/DependencyAnalysis/Target_ARM64/ARM64UnboxingStubNode.cs",
        "Compiler/DependencyAnalysis/Target_LoongArch64/LoongArch64JumpStubNode.cs",
        "Compiler/DependencyAnalysis/Target_LoongArch64/LoongArch64ReadyToRunGenericHelperNode.cs",
        "Compiler/DependencyAnalysis/Target_LoongArch64/LoongArch64ReadyToRunHelperNode.cs",
        "Compiler/DependencyAnalysis/Target_LoongArch64/LoongArch64TentativeMethodNode.cs",
        "Compiler/DependencyAnalysis/Target_LoongArch64/LoongArch64UnboxingStubNode.cs",
        "Compiler/DependencyAnalysis/Target_RiscV64/RiscV64JumpStubNode.cs",
        "Compiler/DependencyAnalysis/Target_RiscV64/RiscV64ReadyToRunGenericHelperNode.cs",
        "Compiler/DependencyAnalysis/Target_RiscV64/RiscV64ReadyToRunHelperNode.cs",
        "Compiler/DependencyAnalysis/Target_RiscV64/RiscV64TentativeMethodNode.cs",
        "Compiler/DependencyAnalysis/Target_RiscV64/RiscV64UnboxingStubNode.cs",
        "Compiler/DependencyAnalysis/Target_X64/X64JumpStubNode.cs",
        "Compiler/DependencyAnalysis/Target_X64/X64ReadyToRunGenericHelperNode.cs",
        "Compiler/DependencyAnalysis/Target_X64/X64ReadyToRunHelperNode.cs",
        "Compiler/DependencyAnalysis/Target_X64/X64TentativeMethodNode.cs",
        "Compiler/DependencyAnalysis/Target_X64/X64UnboxingStubNode.cs",
        "Compiler/DependencyAnalysis/Target_X86/X86JumpStubNode.cs",
        "Compiler/DependencyAnalysis/Target_X86/X86ReadyToRunGenericHelperNode.cs",
        "Compiler/DependencyAnalysis/Target_X86/X86ReadyToRunHelperNode.cs",
        "Compiler/DependencyAnalysis/Target_X86/X86TentativeMethodNode.cs",
        "Compiler/DependencyAnalysis/Target_X86/X86UnboxingStubNode.cs",
        "Compiler/DependencyAnalysis/TentativeInstanceMethodNode.cs",
        "Compiler/DependencyAnalysis/TentativeMethodNode.cs",
        "Compiler/DependencyAnalysis/ThreadStaticsNode.cs",
        "Compiler/DependencyAnalysis/TlsRootNode.cs",
        "Compiler/DependencyAnalysis/TrimmingDescriptorNode.cs",
        "Compiler/DependencyAnalysis/TypeGVMEntriesNode.cs",
        "Compiler/DependencyAnalysis/TypeManagerIndirectionNode.cs",
        "Compiler/DependencyAnalysis/TypeMetadataMapNode.cs",
        "Compiler/DependencyAnalysis/TypeMetadataNode.cs",
        "Compiler/DependencyAnalysis/TypeThreadStaticIndexNode.cs",
        "Compiler/DependencyAnalysis/UnboxingStubNode.cs",
        "Compiler/DependencyAnalysis/VTableSliceNode.cs",
        "Compiler/DependencyAnalysis/VariantInterfaceMethodUseNode.cs",
        "Compiler/DependencyAnalysis/VirtualMethodUseNode.cs",
        "Compiler/DescriptorMarker.cs",
        "Compiler/DictionaryLayoutProvider.cs",
        "Compiler/Disassembler.cs",
        "Compiler/DynamicInvokeThunkGenerationPolicy.cs",
        "Compiler/EmptyInteropStubManager.cs",
        "Compiler/ExpectedIsaFeaturesRootProvider.cs",
        "Compiler/ExportsFileWriter.cs",
        "Compiler/ExternSymbolMappedField.cs",
        "Compiler/GenericDictionaryLookup.cs",
        "Compiler/GenericRootProvider.cs",
        "Compiler/HardwareIntrinsicHelpers.Aot.cs",
        "Compiler/HardwareIntrinsicILProvider.cs",
        "Compiler/IInliningPolicy.cs",
        "Compiler/ILAssemblyGeneratingMethodDebugInfoProvider.cs",
        "Compiler/ILScanner.cs",
        "Compiler/ILScannerBuilder.cs",
        "Compiler/ILogWriter.cs",
        "Compiler/IRootingServiceProvider.cs",
        "Compiler/InlinedThreadStatics.cs",
        "Compiler/InteropStubManager.cs",
        "Compiler/JitHelper.cs",
        "Compiler/LazyGenericsPolicy.cs",
        "Compiler/LibraryInitializers.cs",
        "Compiler/LibraryRootProvider.cs",
        "Compiler/Logger.cs",
        "Compiler/Logging/DocumentationSignatureGenerator.PartVisitor.cs",
        "Compiler/Logging/DocumentationSignatureParser.cs",
        "Compiler/Logging/MessageContainer.cs",
        "Compiler/Logging/MessageOrigin.cs",
        "Compiler/Logging/NativeAotFatalErrorException.cs",
        "Compiler/Logging/SuppressMessageInfo.cs",
        "Compiler/Logging/UnconditionalSuppressMessageAttributeState.cs",
        "Compiler/MainMethodRootProvider.cs",
        "Compiler/ManifestResourceBlockingPolicy.cs",
        "Compiler/MetadataBlockingPolicy.cs",
        "Compiler/MetadataManager.cs",
        "Compiler/MethodImportationErrorProvider.cs",
        "Compiler/MstatObjectDumper.cs",
        "Compiler/MultiFileCompilationModuleGroup.cs",
        "Compiler/NativeLibraryInitializerRootProvider.cs",
        "Compiler/NoMetadataBlockingPolicy.cs",
        "Compiler/NodeMangler.cs",
        "Compiler/ObjectDataInterner.cs",
        "Compiler/ObjectDumper.cs",
        "Compiler/ObjectWriter/CodeView/CodeViewFileTableBuilder.cs",
        "Compiler/ObjectWriter/CodeView/CodeViewNative.cs",
        "Compiler/ObjectWriter/CodeView/CodeViewSymbolsBuilder.cs",
        "Compiler/ObjectWriter/CodeView/CodeViewTypesBuilder.cs",
        "Compiler/ObjectWriter/CoffObjectWriter.cs",
        "Compiler/ObjectWriter/Dwarf/DwarfAbbrev.cs",
        "Compiler/ObjectWriter/Dwarf/DwarfBuilder.cs",
        "Compiler/ObjectWriter/Dwarf/DwarfCfiOpcode.cs",
        "Compiler/ObjectWriter/Dwarf/DwarfCie.cs",
        "Compiler/ObjectWriter/Dwarf/DwarfEhFrame.cs",
        "Compiler/ObjectWriter/Dwarf/DwarfExpressionBuilder.cs",
        "Compiler/ObjectWriter/Dwarf/DwarfFde.cs",
        "Compiler/ObjectWriter/Dwarf/DwarfFileName.cs",
        "Compiler/ObjectWriter/Dwarf/DwarfHelper.cs",
        "Compiler/ObjectWriter/Dwarf/DwarfInfo.cs",
        "Compiler/ObjectWriter/Dwarf/DwarfInfoWriter.cs",
        "Compiler/ObjectWriter/Dwarf/DwarfLineProgramTableWriter.cs",
        "Compiler/ObjectWriter/Dwarf/DwarfLineSequenceWriter.cs",
        "Compiler/ObjectWriter/Dwarf/DwarfNative.cs",
        "Compiler/ObjectWriter/Eabi/EabiAttributesBuilder.cs",
        "Compiler/ObjectWriter/Eabi/EabiNative.cs",
        "Compiler/ObjectWriter/Eabi/EabiUnwindConverter.cs",
        "Compiler/ObjectWriter/ElfNative.cs",
        "Compiler/ObjectWriter/ElfObjectWriter.cs",
        "Compiler/ObjectWriter/MachNative.cs",
        "Compiler/ObjectWriter/MachObjectWriter.cs",
        "Compiler/ObjectWriter/ObjectWriter.cs",
        "Compiler/ObjectWriter/ObjectWritingOptions.cs",
        "Compiler/ObjectWriter/SectionData.cs",
        "Compiler/ObjectWriter/SectionWriter.cs",
        "Compiler/ObjectWriter/StringTableBuilder.cs",
        "Compiler/ObjectWriter/UnixObjectWriter.cs",
        "Compiler/PreinitializationManager.cs",
        "Compiler/ReachabilityInstrumentationFilter.cs",
        "Compiler/ReachabilityInstrumentationProvider.cs",
        "Compiler/ReadOnlyFieldPolicy.cs",
        "Compiler/RootingHelpers.cs",
        "Compiler/RootingServiceProvider.cs",
        "Compiler/RuntimeConfigurationRootProvider.cs",
        "Compiler/SingleFileCompilationModuleGroup.cs",
        "Compiler/SingleMethodCompilationModuleGroup.cs",
        "Compiler/SourceLinkWriter.cs",
        "Compiler/StackTraceEmissionPolicy.cs",
        "Compiler/SubstitutedILProvider.cs",
        "Compiler/SubstitutionProvider.cs",
        "Compiler/TextLogWriter.cs",
        "Compiler/TypeMapManager.cs",
        "Compiler/TypeMapMetadata.cs",
        "Compiler/TypePreinit.cs",
        "Compiler/UnixNodeMangler.cs",
        "Compiler/UnmanagedEntryPointsRootProvider.cs",
        "Compiler/UsageBasedInteropStubManager.cs",
        "Compiler/UsageBasedMetadataManager.cs",
        "Compiler/UsageBasedTypeMapManager.cs",
        "Compiler/UserDefinedTypeDescriptor.cs",
        "Compiler/VTableSliceProvider.cs",
        "Compiler/VectorOfTFieldLayoutAlgorithm.cs",
        "Compiler/VirtualMethodCallHelper.cs",
        "Compiler/Win32ResourcesRootProvider.cs",
        "Compiler/WindowsNodeMangler.cs",
        "Compiler/XmlObjectDumper.cs",
        "IL/ILImporter.Scanner.cs",
        "IL/IsInstCheckPatternAnalyzer.cs",
        "IL/Stubs/PInvokeILProvider.cs",
        "IL/Stubs/StartupCode/NativeLibraryStartupMethod.Sorting.cs",
        "IL/Stubs/StartupCode/NativeLibraryStartupMethod.cs",
        "IL/Stubs/StartupCode/StartupCodeMainMethod.Sorting.cs",
        "IL/Stubs/StartupCode/StartupCodeMainMethod.cs",
        "IL/TypeEqualityPatternAnalyzer.cs",
    ] + [
        "//src/coreclr/tools/Common:Compiler/CodeGenerationFailedException.cs",
        "//src/coreclr/tools/Common:Compiler/CompilationBuilder.cs",
        "//src/coreclr/tools/Common:Compiler/CompilationModuleGroup.cs",
        "//src/coreclr/tools/Common:Compiler/CompilerTypeSystemContext.Validation.cs",
        "//src/coreclr/tools/Common:Compiler/CompilerTypeSystemContext.cs",
        "//src/coreclr/tools/Common:Compiler/Dataflow/DynamicallyAccessedMembersBinder.cs",
        "//src/coreclr/tools/Common:Compiler/Dataflow/EcmaExtensions.cs",
        "//src/coreclr/tools/Common:Compiler/Dataflow/GenericParameterProxy.cs",
        "//src/coreclr/tools/Common:Compiler/Dataflow/MethodProxy.cs",
        "//src/coreclr/tools/Common:Compiler/Dataflow/ParameterProxy.cs",
        "//src/coreclr/tools/Common:Compiler/Dataflow/TypeExtensions.cs",
        "//src/coreclr/tools/Common:Compiler/Dataflow/TypeProxy.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/AssemblyStubNode.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/CompilerComparer.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/EmbeddedDataContainerNode.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/IMethodBodyNode.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/IMethodNode.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/INodeWithCodeInfo.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/INodeWithRuntimeDeterminedDependencies.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/ISortableNode.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/ISymbolNode.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/MethodReadOnlyDataNode.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/ObjectDataBuilder.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/ObjectNode.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/ObjectNodeSection.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/Relocation.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/ShadowConcreteMethodNode.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/SortableDependencyNode.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/Target_ARM/ARMEmitter.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/Target_ARM/Register.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/Target_ARM/TargetRegisterMap.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/Target_ARM64/ARM64Emitter.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/Target_ARM64/AddrMode.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/Target_ARM64/Register.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/Target_ARM64/TargetRegisterMap.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/Target_LoongArch64/AddrMode.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/Target_LoongArch64/LoongArch64Emitter.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/Target_LoongArch64/Register.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/Target_LoongArch64/TargetRegisterMap.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/Target_RiscV64/AddrMode.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/Target_RiscV64/Register.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/Target_RiscV64/RiscV64Emitter.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/Target_RiscV64/TargetRegisterMap.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/Target_X64/AddrMode.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/Target_X64/Register.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/Target_X64/TargetRegisterMap.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/Target_X64/X64Emitter.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/Target_X86/AddrMode.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/Target_X86/Register.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/Target_X86/TargetRegisterMap.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyAnalysis/Target_X86/X86Emitter.cs",
        "//src/coreclr/tools/Common:Compiler/DependencyTrackingLevel.cs",
        "//src/coreclr/tools/Common:Compiler/DevirtualizationManager.cs",
        "//src/coreclr/tools/Common:Compiler/DisplayNameHelpers.cs",
        "//src/coreclr/tools/Common:Compiler/EventPseudoDesc.cs",
        "//src/coreclr/tools/Common:Compiler/FeatureSettings.cs",
        "//src/coreclr/tools/Common:Compiler/GenericCycleDetection/Graph.Cycles.cs",
        "//src/coreclr/tools/Common:Compiler/GenericCycleDetection/Graph.Vertex.cs",
        "//src/coreclr/tools/Common:Compiler/GenericCycleDetection/Graph.cs",
        "//src/coreclr/tools/Common:Compiler/GenericCycleDetection/GraphBuilder.ForEach.cs",
        "//src/coreclr/tools/Common:Compiler/GenericCycleDetection/GraphBuilder.MethodCall.cs",
        "//src/coreclr/tools/Common:Compiler/GenericCycleDetection/GraphBuilder.cs",
        "//src/coreclr/tools/Common:Compiler/GenericCycleDetection/ModuleCycleInfo.cs",
        "//src/coreclr/tools/Common:Compiler/HardwareIntrinsicHelpers.cs",
        "//src/coreclr/tools/Common:Compiler/ICompilationRootProvider.cs",
        "//src/coreclr/tools/Common:Compiler/InstructionSetSupport.cs",
        "//src/coreclr/tools/Common:Compiler/Int128FieldLayoutAlgorithm.cs",
        "//src/coreclr/tools/Common:Compiler/InternalCompilerErrorException.cs",
        "//src/coreclr/tools/Common:Compiler/MethodExtensions.cs",
        "//src/coreclr/tools/Common:Compiler/NameMangler.cs",
        "//src/coreclr/tools/Common:Compiler/NativeAotNameMangler.cs",
        "//src/coreclr/tools/Common:Compiler/ProcessLinkerXmlBase.cs",
        "//src/coreclr/tools/Common:Compiler/PropertyPseudoDesc.cs",
        "//src/coreclr/tools/Common:Compiler/PseudoDescExtensions.cs",
        "//src/coreclr/tools/Common:Compiler/SingleMethodRootProvider.cs",
        "//src/coreclr/tools/Common:Compiler/TypeExtensions.cs",
        "//src/coreclr/tools/Common:Compiler/TypePreserve.cs",
        "//src/coreclr/tools/Common:Compiler/VectorFieldLayoutAlgorithm.cs",
        "//src/coreclr/tools/Common:Compiler/Win32Resources/ResourceData.Reader.cs",
        "//src/coreclr/tools/Common:Compiler/Win32Resources/ResourceData.ResourcesDataModel.cs",
        "//src/coreclr/tools/Common:Compiler/Win32Resources/ResourceData.UpdateResourceDataModel.cs",
        "//src/coreclr/tools/Common:Compiler/Win32Resources/ResourceData.Win32Structs.cs",
        "//src/coreclr/tools/Common:Compiler/Win32Resources/ResourceData.cs",
        "//src/coreclr/tools/Common:Internal/NativeFormat/NativeFormatWriter.Primitives.cs",
        "//src/coreclr/tools/Common:Internal/Runtime/DehydratedData.cs",
        "//src/coreclr/tools/Common:Internal/Runtime/EETypeBuilderHelpers.cs",
        "//src/coreclr/tools/Common:Internal/Runtime/GCDescEncoder.cs",
        "//src/coreclr/tools/Common:Internal/Runtime/ITargetBinaryWriter.cs",
        "//src/coreclr/tools/Common:Internal/Runtime/InterfaceDispatchCellCachePointerFlags.cs",
        "//src/coreclr/tools/Common:Internal/Runtime/InteropConstants.cs",
        "//src/coreclr/tools/Common:Internal/Runtime/MappingTableFlags.cs",
        "//src/coreclr/tools/Common:Internal/Runtime/MetadataBlob.cs",
        "//src/coreclr/tools/Common:Internal/Runtime/MethodTable.Constants.cs",
        "//src/coreclr/tools/Common:Internal/Runtime/ModuleHeaders.cs",
        "//src/coreclr/tools/Common:Internal/Runtime/ReadyToRunConstants.cs",
        "//src/coreclr/tools/Common:Internal/Runtime/RuntimeConstants.cs",
        "//src/coreclr/tools/Common:Internal/Runtime/StackTraceData.cs",
        "//src/coreclr/tools/Common:Internal/Text/Utf8String.cs",
        "//src/coreclr/tools/Common:Internal/Text/Utf8StringBuilder.cs",
        "//src/coreclr/tools/Common:JitInterface/CorInfoHelpFunc.cs",
        "//src/coreclr/tools/Common:JitInterface/CorInfoInstructionSet.cs",
        "//src/coreclr/tools/Common:JitInterface/CorInfoTypes.VarInfo.cs",
        "//src/coreclr/tools/Common:JitInterface/CorInfoTypes.cs",
        "//src/coreclr/tools/Common:Microsoft/SourceLink/Tools/SourceLinkMap.cs",
        "//src/coreclr/tools/Common:Pgo/PgoFormat.cs",
        "//src/coreclr/tools/Common:System/Collections/Generic/ArrayBuilder.cs",
        "//src/coreclr/tools/Common:System/FormattingHelpers.cs",
        "//src/coreclr/tools/Common:TypeSystem/CodeGen/INonEmittableType.cs",
        "//src/coreclr/tools/Common:TypeSystem/CodeGen/NativeStructType.CodeGen.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/DelegateInfo.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/HelperExtensions.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/ILImporter.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/ILProvider.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/ILReader.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/NativeAotILProvider.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/StackValueKind.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/Stubs/ArrayMethodILEmitter.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/Stubs/AssemblyGetExecutingAssemblyMethodThunk.Sorting.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/Stubs/AssemblyGetExecutingAssemblyMethodThunk.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/Stubs/CalliMarshallingMethodThunk.Mangling.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/Stubs/CalliMarshallingMethodThunk.Sorting.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/Stubs/CalliMarshallingMethodThunk.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/Stubs/ComparerIntrinsics.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/Stubs/DebuggerSteppingHelpers.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/Stubs/DelegateMarshallingMethodThunk.Mangling.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/Stubs/DelegateMarshallingMethodThunk.Sorting.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/Stubs/DelegateMarshallingMethodThunk.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/Stubs/DelegateMethodILEmitter.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/Stubs/DelegateThunks.Sorting.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/Stubs/DelegateThunks.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/Stubs/DynamicInvokeMethodThunk.Mangling.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/Stubs/DynamicInvokeMethodThunk.Sorting.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/Stubs/DynamicInvokeMethodThunk.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/Stubs/EnumThunks.Sorting.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/Stubs/EnumThunks.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/Stubs/ForwardDelegateCreationThunk.Mangling.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/Stubs/ForwardDelegateCreationThunk.Sorting.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/Stubs/ForwardDelegateCreationThunk.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/Stubs/GetCanonTypeIntrinsic.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/Stubs/InterlockedIntrinsics.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/Stubs/MethodBaseGetCurrentMethodThunk.Mangling.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/Stubs/MethodBaseGetCurrentMethodThunk.Sorting.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/Stubs/MethodBaseGetCurrentMethodThunk.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/Stubs/PInvokeILCodeStreams.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/Stubs/PInvokeILEmitter.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/Stubs/PInvokeLazyFixupField.Sorting.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/Stubs/PInvokeLazyFixupField.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/Stubs/RuntimeHelpersIntrinsics.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/Stubs/StreamIntrinsics.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/Stubs/StructMarshallingThunk.Mangling.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/Stubs/StructMarshallingThunk.Sorting.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/Stubs/StructMarshallingThunk.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/Stubs/TypeGetTypeMethodThunk.Sorting.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/Stubs/TypeGetTypeMethodThunk.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/Stubs/TypeSystemThrowingILEmitter.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/Stubs/UnsafeIntrinsics.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/Stubs/ValueTypeGetFieldHelperMethodOverride.Sorting.cs",
        "//src/coreclr/tools/Common:TypeSystem/IL/Stubs/ValueTypeGetFieldHelperMethodOverride.cs",
        "//src/coreclr/tools/Common:TypeSystem/Interop/IL/InlineArrayType.Sorting.cs",
        "//src/coreclr/tools/Common:TypeSystem/Interop/IL/InlineArrayType.cs",
        "//src/coreclr/tools/Common:TypeSystem/Interop/IL/MarshalHelpers.Aot.cs",
        "//src/coreclr/tools/Common:TypeSystem/Interop/IL/MarshalHelpers.cs",
        "//src/coreclr/tools/Common:TypeSystem/Interop/IL/MarshalUtils.cs",
        "//src/coreclr/tools/Common:TypeSystem/Interop/IL/Marshaller.Aot.cs",
        "//src/coreclr/tools/Common:TypeSystem/Interop/IL/Marshaller.cs",
        "//src/coreclr/tools/Common:TypeSystem/Interop/IL/MarshallerKind.cs",
        "//src/coreclr/tools/Common:TypeSystem/Interop/IL/NativeStructType.Mangling.cs",
        "//src/coreclr/tools/Common:TypeSystem/Interop/IL/NativeStructType.Sorting.cs",
        "//src/coreclr/tools/Common:TypeSystem/Interop/IL/NativeStructType.cs",
        "//src/coreclr/tools/Common:TypeSystem/Interop/IL/PInvokeDelegateWrapper.Mangling.cs",
        "//src/coreclr/tools/Common:TypeSystem/Interop/IL/PInvokeDelegateWrapper.Sorting.cs",
        "//src/coreclr/tools/Common:TypeSystem/Interop/IL/PInvokeDelegateWrapper.cs",
        "//src/coreclr/tools/Common:TypeSystem/Interop/IL/PInvokeDelegateWrapperConstructor.Sorting.cs",
        "//src/coreclr/tools/Common:TypeSystem/Interop/IL/PInvokeDelegateWrapperConstructor.cs",
        "//src/coreclr/tools/Common:TypeSystem/Interop/IL/PInvokeILEmitterConfiguration.cs",
        "//src/coreclr/tools/Common:TypeSystem/Interop/InteropStateManager.cs",
        "//src/coreclr/tools/Common:TypeSystem/Interop/InteropTypes.cs",
        "//src/coreclr/tools/Common:TypeSystem/Interop/UnmanagedCallingConventions.cs",
        "//src/coreclr/tools/Common:TypeSystem/MetadataEmitter/TypeSystemMetadataEmitter.cs",
        "//src/coreclr/tools/Common:TypeSystem/TypesDebugInfoWriter/TypesDebugInfoWriter.cs",
    ] + [
        "//src/libraries/Common:src/System/Text/ValueStringBuilder.cs",
        "//src/tools/illink/src/ILLink.Shared:Annotations.cs",
        "//src/tools/illink/src/ILLink.Shared:ClosedAttribute.cs",
        "//src/tools/illink/src/ILLink.Shared:DataFlow/CompilerGeneratedNames.cs",
        "//src/tools/illink/src/ILLink.Shared:DataFlow/DefaultValueDictionary.cs",
        "//src/tools/illink/src/ILLink.Shared:DataFlow/DictionaryLattice.cs",
        "//src/tools/illink/src/ILLink.Shared:DataFlow/ForwardDataFlowAnalysis.cs",
        "//src/tools/illink/src/ILLink.Shared:DataFlow/IControlFlowGraph.cs",
        "//src/tools/illink/src/ILLink.Shared:DataFlow/IDataFlowState.cs",
        "//src/tools/illink/src/ILLink.Shared:DataFlow/IDeepCopyValue.cs",
        "//src/tools/illink/src/ILLink.Shared:DataFlow/ILattice.cs",
        "//src/tools/illink/src/ILLink.Shared:DataFlow/ITransfer.cs",
        "//src/tools/illink/src/ILLink.Shared:DataFlow/MaybeLattice.cs",
        "//src/tools/illink/src/ILLink.Shared:DataFlow/SingleValue.cs",
        "//src/tools/illink/src/ILLink.Shared:DataFlow/ValueSet.cs",
        "//src/tools/illink/src/ILLink.Shared:DataFlow/ValueSetLattice.cs",
        "//src/tools/illink/src/ILLink.Shared:DiagnosticCategory.cs",
        "//src/tools/illink/src/ILLink.Shared:DiagnosticId.cs",
        "//src/tools/illink/src/ILLink.Shared:DiagnosticString.cs",
        "//src/tools/illink/src/ILLink.Shared:DynamicallyAccessedMemberTypesEx.cs",
        "//src/tools/illink/src/ILLink.Shared:HashUtils.cs",
        "//src/tools/illink/src/ILLink.Shared:IsExternalInit.cs",
        "//src/tools/illink/src/ILLink.Shared:MessageFormat.cs",
        "//src/tools/illink/src/ILLink.Shared:MessageSubCategory.cs",
        "//src/tools/illink/src/ILLink.Shared:ParameterIndex.cs",
        "//src/tools/illink/src/ILLink.Shared:RequiresDynamicCodeAttribute.cs",
        "//src/tools/illink/src/ILLink.Shared:RequiresUnreferencedCodeAttribute.cs",
        "//src/tools/illink/src/ILLink.Shared:TrimAnalysis/ArrayOfAnnotatedSystemTypeValue.cs",
        "//src/tools/illink/src/ILLink.Shared:TrimAnalysis/ArrayValue.cs",
        "//src/tools/illink/src/ILLink.Shared:TrimAnalysis/ConstIntValue.cs",
        "//src/tools/illink/src/ILLink.Shared:TrimAnalysis/DiagnosticContext.cs",
        "//src/tools/illink/src/ILLink.Shared:TrimAnalysis/FieldValue.cs",
        "//src/tools/illink/src/ILLink.Shared:TrimAnalysis/FlowAnnotations.cs",
        "//src/tools/illink/src/ILLink.Shared:TrimAnalysis/GenericParameterValue.cs",
        "//src/tools/illink/src/ILLink.Shared:TrimAnalysis/HandleCallAction.cs",
        "//src/tools/illink/src/ILLink.Shared:TrimAnalysis/IValueWithStaticType.cs",
        "//src/tools/illink/src/ILLink.Shared:TrimAnalysis/IntrinsicId.cs",
        "//src/tools/illink/src/ILLink.Shared:TrimAnalysis/Intrinsics.cs",
        "//src/tools/illink/src/ILLink.Shared:TrimAnalysis/KnownStringValue.cs",
        "//src/tools/illink/src/ILLink.Shared:TrimAnalysis/MethodParameterValue.cs",
        "//src/tools/illink/src/ILLink.Shared:TrimAnalysis/MethodReturnValue.cs",
        "//src/tools/illink/src/ILLink.Shared:TrimAnalysis/NullValue.cs",
        "//src/tools/illink/src/ILLink.Shared:TrimAnalysis/NullableSystemTypeValue.cs",
        "//src/tools/illink/src/ILLink.Shared:TrimAnalysis/NullableValueWithDynamicallyAccessedMembers.cs",
        "//src/tools/illink/src/ILLink.Shared:TrimAnalysis/ReferenceKind.cs",
        "//src/tools/illink/src/ILLink.Shared:TrimAnalysis/RequireDynamicallyAccessedMembersAction.cs",
        "//src/tools/illink/src/ILLink.Shared:TrimAnalysis/RuntimeMethodHandleValue.cs",
        "//src/tools/illink/src/ILLink.Shared:TrimAnalysis/RuntimeTypeHandleForGenericParameterValue.cs",
        "//src/tools/illink/src/ILLink.Shared:TrimAnalysis/RuntimeTypeHandleForNullableSystemTypeValue.cs",
        "//src/tools/illink/src/ILLink.Shared:TrimAnalysis/RuntimeTypeHandleForNullableValueWithDynamicallyAccessedMembers.cs",
        "//src/tools/illink/src/ILLink.Shared:TrimAnalysis/RuntimeTypeHandleForValueWithDynamicallyAccessedMembers.cs",
        "//src/tools/illink/src/ILLink.Shared:TrimAnalysis/RuntimeTypeHandleValue.cs",
        "//src/tools/illink/src/ILLink.Shared:TrimAnalysis/SystemReflectionMethodBaseValue.cs",
        "//src/tools/illink/src/ILLink.Shared:TrimAnalysis/SystemTypeValue.cs",
        "//src/tools/illink/src/ILLink.Shared:TrimAnalysis/UnknownValue.cs",
        "//src/tools/illink/src/ILLink.Shared:TrimAnalysis/ValueExtensions.cs",
        "//src/tools/illink/src/ILLink.Shared:TrimAnalysis/ValueWithDynamicallyAccessedMembers.cs",
        "//src/tools/illink/src/ILLink.Shared:TypeSystemProxy/GenericParameterProxy.cs",
        "//src/tools/illink/src/ILLink.Shared:TypeSystemProxy/IMemberProxy.cs",
        "//src/tools/illink/src/ILLink.Shared:TypeSystemProxy/MethodProxy.cs",
        "//src/tools/illink/src/ILLink.Shared:TypeSystemProxy/ParameterCollection.cs",
        "//src/tools/illink/src/ILLink.Shared:TypeSystemProxy/ParameterProxy.cs",
        "//src/tools/illink/src/ILLink.Shared:TypeSystemProxy/TypeProxy.cs",
        "//src/tools/illink/src/ILLink.Shared:TypeSystemProxy/WellKnownType.cs",
    ],
    compiler_options = ["/unsafe", "/warnaserror+:NU1605"],
    resources = [":SharedStringsResources"],
    resource_logical_names = {
        "ILLink.Shared.SharedStrings.resources": "ILLink.Shared.SharedStrings.resources",
    },
    additionalfiles = [
        "//src/tools/illink/src/ILLink.Shared:SharedStrings.resx",
    ],
    deps = [
        "//src/coreclr/tools/aot/ILCompiler.DependencyAnalysisFramework",
        "//src/coreclr/tools/aot/ILCompiler.MetadataTransform",
        "//src/coreclr/tools/aot/ILCompiler.TypeSystem",
        "@paket.main//microsoft.diasymreader",
    ],
    target_frameworks = ["net10.0"],
    nowarn = ["1591", "CA1859", "CA1866", "CA1867"],
    extra_editorconfig_content = "\n".join([
        "dotnet_diagnostic.IDE0073.severity = none",
        "dotnet_diagnostic.SA1400.severity = none",
        "dotnet_diagnostic.SYSLIB1054.severity = none",
    ]),
    visibility = ["//visibility:public"],
    analyzers = [
        "//:source_build_analyzers",
        "//src/tools/illink/src/ILLink.RoslynAnalyzer",
        "//:staticcs_analyzers",
    ],
    msbuild_analyzer_config = "source",
)
