load("//src/libraries:defs.bzl", "netcoreapp_ref_assembly", "netcoreapp_impl_assembly", "ref_impl_pair")
load("//:defs.bzl", "OPEN_SNK", "csharp_library")

exports_files([
    "ref/System.Text.RegularExpressions.cs",
] + glob(["src/**/*.cs"]) + glob(["src/**/*.resx"]))

csharp_library(
    name = "RegexGenerator",
    keyfile = OPEN_SNK,
    out = "System.Text.RegularExpressions.Generator",
    srcs = [
        "gen/RegexGenerator.cs",
        "gen/RegexGenerator.Emitter.cs",
        "gen/RegexGenerator.Parser.cs",
        "gen/DiagnosticDescriptors.cs",
        "gen/UpgradeToGeneratedRegexAnalyzer.cs",
        "gen/UpgradeToGeneratedRegexCodeFixer.cs",
        "gen/Stubs.cs",

        # Common Roslyn helpers
        "//src/libraries/Common:src/Roslyn/DiagnosticDescriptorHelper.cs",
        "//src/libraries/Common:src/Roslyn/GetBestTypeByMetadataName.cs",
        "//src/libraries/System.Private.CoreLib:src/System/Runtime/CompilerServices/IsExternalInit.cs",
        "//src/libraries/System.Private.CoreLib:src/System/Diagnostics/CodeAnalysis/NullableAttributes.cs",
        "//src/libraries/Common:src/System/SR.cs",

        # Shared production sources
        "//src/libraries/Common:src/System/HexConverter.cs",
        "//src/libraries/Common:src/System/Obsoletions.cs",
        "//src/libraries/Common:src/System/Text/ValueStringBuilder.cs",
        "//src/libraries/Common:src/System/Collections/Generic/ValueListBuilder.cs",
        "//src/libraries/Common:src/System/Collections/Generic/ValueListBuilder.Pop.cs",
        "src/System/Threading/StackHelper.cs",
        "src/System/Text/RegularExpressions/RegexCaseEquivalences.Data.cs",
        "src/System/Text/RegularExpressions/RegexCaseEquivalences.cs",
        "src/System/Text/RegularExpressions/RegexCaseBehavior.cs",
        "src/System/Text/RegularExpressions/RegexCharClass.cs",
        "src/System/Text/RegularExpressions/RegexCharClass.Tables.cs",
        "src/System/Text/RegularExpressions/RegexFindOptimizations.cs",
        "src/System/Text/RegularExpressions/RegexNode.cs",
        "src/System/Text/RegularExpressions/RegexNodeKind.cs",
        "src/System/Text/RegularExpressions/RegexOpcode.cs",
        "src/System/Text/RegularExpressions/RegexOptions.cs",
        "src/System/Text/RegularExpressions/RegexParseError.cs",
        "src/System/Text/RegularExpressions/RegexParseException.cs",
        "src/System/Text/RegularExpressions/RegexParser.cs",
        "src/System/Text/RegularExpressions/RegexPrefixAnalyzer.cs",
        "src/System/Text/RegularExpressions/RegexTree.cs",
        "src/System/Text/RegularExpressions/RegexTreeAnalyzer.cs",
        "src/System/Collections/HashtableExtensions.cs",

        # Span polyfills for netstandard2.0
        "//src/libraries/Common:src/System/MemoryExtensionsPolyfills.cs",
        "//src/libraries/Common:src/System/StringPolyfills.cs",
        "//src/libraries/Common:src/System/Buffers/SearchValuesPolyfills.cs",
        "//src/libraries/Common:src/System/Text/AsciiPolyfills.cs",
        "//src/libraries/Common:src/Polyfills/EncodingPolyfills.cs",
    ],
    resx_file = "gen/Resources/Strings.resx",
    target_frameworks = ["netstandard2.0"],
    langversion = "preview",
    cls_compliant = False,
    nullable = "annotations",
    allow_unsafe_blocks = True,
    deps = [
        "@paket.main//microsoft.codeanalysis.common",
        "@paket.main//microsoft.codeanalysis.csharp",
        "@paket.main//microsoft.codeanalysis.workspaces.common",
        "@paket.main//microsoft.codeanalysis.csharp.workspaces",
        "@paket.main//system.composition.attributedmodel",
        "@paket.main//system.collections.immutable",
        "@paket.main//system.memory",
        "@paket.main//system.buffers",
        "@paket.main//system.runtime.compilerservices.unsafe",
    ],
    nowarn = [
        "CS0436",
        "CS0649",
        "CA1872",
    ],
    visibility = ["//visibility:public"],
)

netcoreapp_ref_assembly(
    name = "ref_System.Text.RegularExpressions",
    srcs = [
        "ref/System.Text.RegularExpressions.cs",
    ],
    deps = [
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Reflection.Emit.ILGeneration:ref_System.Reflection.Emit.ILGeneration",
    ],
)

netcoreapp_impl_assembly(
    name = "impl_System.Text.RegularExpressions",
    com_interface_generator = True,
    nowarn = [],
    srcs = [
        # Core types
        "src/System/Collections/HashtableExtensions.cs",
        "src/System/Text/RegularExpressions/ValueMatch.cs",
        "src/System/Text/StructListBuilder.cs",
        "src/System/Threading/StackHelper.cs",
        "src/System/Text/RegularExpressions/Capture.cs",
        "src/System/Text/RegularExpressions/CaptureCollection.cs",
        "src/System/Text/RegularExpressions/CollectionDebuggerProxy.cs",
        "src/System/Text/RegularExpressions/Group.cs",
        "src/System/Text/RegularExpressions/GroupCollection.cs",
        "src/System/Text/RegularExpressions/Match.cs",
        "src/System/Text/RegularExpressions/MatchCollection.cs",
        "src/System/Text/RegularExpressions/Regex.cs",
        "src/System/Text/RegularExpressions/Regex.Cache.cs",
        "src/System/Text/RegularExpressions/Regex.Count.cs",
        "src/System/Text/RegularExpressions/Regex.Debug.cs",
        "src/System/Text/RegularExpressions/Regex.Match.cs",
        "src/System/Text/RegularExpressions/Regex.Replace.cs",
        "src/System/Text/RegularExpressions/Regex.Split.cs",
        "src/System/Text/RegularExpressions/Regex.EnumerateMatches.cs",
        "src/System/Text/RegularExpressions/Regex.EnumerateSplits.cs",
        "src/System/Text/RegularExpressions/Regex.Timeout.cs",
        "src/System/Text/RegularExpressions/RegexAssemblyCompiler.cs",
        "src/System/Text/RegularExpressions/RegexCaseBehavior.cs",
        "src/System/Text/RegularExpressions/RegexCaseEquivalences.Data.cs",
        "src/System/Text/RegularExpressions/RegexCaseEquivalences.cs",
        "src/System/Text/RegularExpressions/RegexCharClass.cs",
        "src/System/Text/RegularExpressions/RegexCharClass.Tables.cs",
        "src/System/Text/RegularExpressions/RegexCompilationInfo.cs",
        "src/System/Text/RegularExpressions/RegexFindOptimizations.cs",
        "src/System/Text/RegularExpressions/GeneratedRegexAttribute.cs",
        "src/System/Text/RegularExpressions/RegexInterpreter.cs",
        "src/System/Text/RegularExpressions/RegexInterpreterCode.cs",
        "src/System/Text/RegularExpressions/RegexMatchTimeoutException.cs",
        "src/System/Text/RegularExpressions/RegexNode.cs",
        "src/System/Text/RegularExpressions/RegexNodeKind.cs",
        "src/System/Text/RegularExpressions/RegexOpcode.cs",
        "src/System/Text/RegularExpressions/RegexOptions.cs",
        "src/System/Text/RegularExpressions/RegexParseError.cs",
        "src/System/Text/RegularExpressions/RegexParseException.cs",
        "src/System/Text/RegularExpressions/RegexParser.cs",
        "src/System/Text/RegularExpressions/RegexPrefixAnalyzer.cs",
        "src/System/Text/RegularExpressions/RegexReplacement.cs",
        "src/System/Text/RegularExpressions/RegexRunner.cs",
        "src/System/Text/RegularExpressions/RegexRunnerFactory.cs",
        "src/System/Text/RegularExpressions/RegexRunnerMode.cs",
        "src/System/Text/RegularExpressions/RegexTree.cs",
        "src/System/Text/RegularExpressions/RegexTreeAnalyzer.cs",
        "src/System/Text/RegularExpressions/RegexWriter.cs",
        "src/System/Text/RegularExpressions/ThrowHelper.cs",

        # RegexOptions.Compiled
        "src/System/Text/RegularExpressions/CompiledRegexRunnerFactory.cs",
        "src/System/Text/RegularExpressions/CompiledRegexRunner.cs",
        "src/System/Text/RegularExpressions/RegexCompiler.cs",
        "src/System/Text/RegularExpressions/RegexLWCGCompiler.cs",

        # RegexOptions.NonBacktracking (Symbolic engine)
        "src/System/Text/RegularExpressions/Symbolic/BDD.cs",
        "src/System/Text/RegularExpressions/Symbolic/BDDRangeConverter.cs",
        "src/System/Text/RegularExpressions/Symbolic/BitVector.cs",
        "src/System/Text/RegularExpressions/Symbolic/BitVectorSolver.cs",
        "src/System/Text/RegularExpressions/Symbolic/CharKind.cs",
        "src/System/Text/RegularExpressions/Symbolic/CharSetSolver.cs",
        "src/System/Text/RegularExpressions/Symbolic/DerivativeEffect.cs",
        "src/System/Text/RegularExpressions/Symbolic/MatchingState.cs",
        "src/System/Text/RegularExpressions/Symbolic/DoublyLinkedList.cs",
        "src/System/Text/RegularExpressions/Symbolic/ISolver.cs",
        "src/System/Text/RegularExpressions/Symbolic/MatchReversalKind.cs",
        "src/System/Text/RegularExpressions/Symbolic/MatchReversal.cs",
        "src/System/Text/RegularExpressions/Symbolic/MintermClassifier.cs",
        "src/System/Text/RegularExpressions/Symbolic/MintermGenerator.cs",
        "src/System/Text/RegularExpressions/Symbolic/RegexNodeConverter.cs",
        "src/System/Text/RegularExpressions/Symbolic/SparseIntMap.cs",
        "src/System/Text/RegularExpressions/Symbolic/StateFlags.cs",
        "src/System/Text/RegularExpressions/Symbolic/SymbolicMatch.cs",
        "src/System/Text/RegularExpressions/Symbolic/SymbolicRegexBuilder.cs",
        "src/System/Text/RegularExpressions/Symbolic/SymbolicRegexNode.cs",
        "src/System/Text/RegularExpressions/Symbolic/SymbolicRegexKind.cs",
        "src/System/Text/RegularExpressions/Symbolic/SymbolicRegexInfo.cs",
        "src/System/Text/RegularExpressions/Symbolic/SymbolicRegexMatcher.Automata.cs",
        "src/System/Text/RegularExpressions/Symbolic/SymbolicRegexMatcher.cs",
        "src/System/Text/RegularExpressions/Symbolic/SymbolicRegexMatcher.Dgml.cs",
        "src/System/Text/RegularExpressions/Symbolic/SymbolicRegexMatcher.Explore.cs",
        "src/System/Text/RegularExpressions/Symbolic/SymbolicRegexMatcher.Sample.cs",
        "src/System/Text/RegularExpressions/Symbolic/SymbolicRegexRunnerFactory.cs",
        "src/System/Text/RegularExpressions/Symbolic/SymbolicRegexThresholds.cs",
        "src/System/Text/RegularExpressions/Symbolic/UInt64Solver.cs",
        "src/System/Text/RegularExpressions/Symbolic/UnicodeCategoryConditions.cs",
        "src/System/Text/RegularExpressions/Symbolic/UnicodeCategoryRanges.cs",
        "src/System/Text/RegularExpressions/Symbolic/UnicodeCategoryRangesGenerator.cs",

        # Common source files
        "//src/libraries/Common:src/System/HexConverter.cs",
        "//src/libraries/Common:src/System/Obsoletions.cs",
        "//src/libraries/Common:src/System/Text/ValueStringBuilder.cs",

        # CoreLib shared source files
        "//src/libraries/Common:src/System/Collections/Generic/ValueListBuilder.cs",
        "//src/libraries/Common:src/System/Collections/Generic/ValueListBuilder.Pop.cs",
    ],
    deps = [
        "//src/libraries/System.Collections:ref_System.Collections",
        "//src/libraries/System.Collections.Concurrent:ref_System.Collections.Concurrent",
        "//src/libraries/System.Memory:ref_System.Memory",
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Runtime.InteropServices:ref_System.Runtime.InteropServices",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/System.Reflection.Emit:ref_System.Reflection.Emit",
        "//src/libraries/System.Reflection.Emit.ILGeneration:ref_System.Reflection.Emit.ILGeneration",
        "//src/libraries/System.Reflection.Emit.Lightweight:ref_System.Reflection.Emit.Lightweight",
        "//src/libraries/System.Reflection.Primitives:ref_System.Reflection.Primitives",
    ],
    resx_file = "src/Resources/Strings.resx",
    defines = [
        "SYSTEM_TEXT_REGULAREXPRESSIONS",
    ],
)

ref_impl_pair(
    name = "live_System.Text.RegularExpressions",
    ref = ":ref_System.Text.RegularExpressions",
    lib = ":impl_System.Text.RegularExpressions",
    visibility = ["//visibility:public"],
)
