load("//src/tests:live_test.bzl", "library_test")
load("//:defs.bzl", "OPEN_SNK")

library_test(
    name = "System.Net.Ping.Functional.Tests",
    defines = select({"@platforms//os:linux": ["UNIX", "UNIX1_0"], "@platforms//os:macos": ["UNIX", "UNIX1_0"], "//conditions:default": []}),
    srcs = glob(["**/*.cs"]) + [
        "//src/libraries/Common/tests:System/Net/RemoteExecutorExtensions.cs",
        "//src/libraries/Common/tests:System/Net/Configuration.cs",
        "//src/libraries/Common/tests:System/Net/Configuration.Ping.cs",
        "//src/libraries/Common/tests:System/Net/Capability.RawSocketPermissions.cs",
        "//src/libraries/Common:src/DisableRuntimeMarshalling.cs",
        "//src/libraries/Common:src/Interop/Unix/Interop.DefaultPathBufferSize.cs",
        "//src/libraries/Common:src/System/Net/RawSocketPermissions.cs",
        "//src/libraries/Common:src/Interop/Unix/Interop.Libraries.cs",
        "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.ReadLink.cs",
        "//src/libraries/Common:src/System/Net/NetworkInformation/UnixCommandLinePing.cs",
        "//src/libraries/Common:src/System/Text/ValueUtf8Converter.cs",
    ],
    deps = [
        "//src/libraries/System.Net.Ping:ref_System.Net.Ping",
        "//src/libraries/System.Net.Primitives:ref_System.Net.Primitives",
        "//src/libraries/System.Net.Sockets:ref_System.Net.Sockets",
        "//src/libraries/System.Net.NameResolution:ref_System.Net.NameResolution",
        "//src/libraries/System.Net.NetworkInformation:ref_System.Net.NetworkInformation",
        "//src/libraries/System.ComponentModel.EventBasedAsync:ref_System.ComponentModel.EventBasedAsync",
        "//src/libraries:ref_Microsoft.Win32.Primitives",
        "//src/libraries:ref_System.Threading.Tasks",
        "//src/libraries/System.Collections.Concurrent:ref_System.Collections.Concurrent",
        "//src/libraries/System.Collections.Immutable:ref_System.Collections.Immutable",
        "//src/libraries/System.Diagnostics.Tracing:ref_System.Diagnostics.Tracing",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/Common/tests:TestUtilities",
        "@paket.main//microsoft.dotnet.remoteexecutor",
        "@paket.main//microsoft.dotnet.xunitassert",
        "@paket.main//microsoft.dotnet.xunitextensions",
        "@paket.main//xunit.abstractions",
        "@paket.main//xunit.extensibility.core",
    ],
    allow_unsafe_blocks = True,
    tags = ["no-sandbox"],
    size = "large",
    keyfile = OPEN_SNK,
)
