load("//src/tests:live_test.bzl", "coreclr_test")

coreclr_test(
    name = "Runtime_52864",
    srcs = ["Runtime_52864.cs"],
    pri = 1,
    optimize = True,
    deps = [
        "//src/libraries/System.Threading.Thread:ref_System.Threading.Thread",
        "//src/libraries/System.Threading:ref_System.Threading",
    ],
)
