load("//src/tests:live_test.bzl", "coreclr_test")

coreclr_test(
    name = "box-unbox-generics001",
    srcs = [
        "box-unbox-generics001.cs",
        "//src/tests/JIT/jit64/valuetypes/nullable/box-unbox:structdef.cs",
    ],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "box-unbox-generics002",
    srcs = [
        "box-unbox-generics002.cs",
        "//src/tests/JIT/jit64/valuetypes/nullable/box-unbox:structdef.cs",
    ],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "box-unbox-generics003",
    srcs = [
        "box-unbox-generics003.cs",
        "//src/tests/JIT/jit64/valuetypes/nullable/box-unbox:structdef.cs",
    ],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "box-unbox-generics004",
    srcs = [
        "box-unbox-generics004.cs",
        "//src/tests/JIT/jit64/valuetypes/nullable/box-unbox:structdef.cs",
    ],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "box-unbox-generics005",
    srcs = [
        "box-unbox-generics005.cs",
        "//src/tests/JIT/jit64/valuetypes/nullable/box-unbox:structdef.cs",
    ],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "box-unbox-generics006",
    srcs = [
        "box-unbox-generics006.cs",
        "//src/tests/JIT/jit64/valuetypes/nullable/box-unbox:structdef.cs",
    ],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "box-unbox-generics007",
    srcs = [
        "box-unbox-generics007.cs",
        "//src/tests/JIT/jit64/valuetypes/nullable/box-unbox:structdef.cs",
    ],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "box-unbox-generics008",
    srcs = [
        "box-unbox-generics008.cs",
        "//src/tests/JIT/jit64/valuetypes/nullable/box-unbox:structdef.cs",
    ],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "box-unbox-generics009",
    srcs = [
        "box-unbox-generics009.cs",
        "//src/tests/JIT/jit64/valuetypes/nullable/box-unbox:structdef.cs",
    ],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "box-unbox-generics010",
    srcs = [
        "box-unbox-generics010.cs",
        "//src/tests/JIT/jit64/valuetypes/nullable/box-unbox:structdef.cs",
    ],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "box-unbox-generics011",
    srcs = [
        "box-unbox-generics011.cs",
        "//src/tests/JIT/jit64/valuetypes/nullable/box-unbox:structdef.cs",
    ],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "box-unbox-generics012",
    srcs = [
        "box-unbox-generics012.cs",
        "//src/tests/JIT/jit64/valuetypes/nullable/box-unbox:structdef.cs",
    ],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "box-unbox-generics013",
    srcs = [
        "box-unbox-generics013.cs",
        "//src/tests/JIT/jit64/valuetypes/nullable/box-unbox:structdef.cs",
    ],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "box-unbox-generics014",
    srcs = [
        "box-unbox-generics014.cs",
        "//src/tests/JIT/jit64/valuetypes/nullable/box-unbox:structdef.cs",
    ],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "box-unbox-generics015",
    srcs = [
        "box-unbox-generics015.cs",
        "//src/tests/JIT/jit64/valuetypes/nullable/box-unbox:structdef.cs",
    ],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "box-unbox-generics016",
    srcs = [
        "box-unbox-generics016.cs",
        "//src/tests/JIT/jit64/valuetypes/nullable/box-unbox:structdef.cs",
    ],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "box-unbox-generics017",
    srcs = [
        "box-unbox-generics017.cs",
        "//src/tests/JIT/jit64/valuetypes/nullable/box-unbox:structdef.cs",
    ],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "box-unbox-generics018",
    srcs = [
        "box-unbox-generics018.cs",
        "//src/tests/JIT/jit64/valuetypes/nullable/box-unbox:structdef.cs",
    ],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "box-unbox-generics019",
    srcs = [
        "box-unbox-generics019.cs",
        "//src/tests/JIT/jit64/valuetypes/nullable/box-unbox:structdef.cs",
    ],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "box-unbox-generics020",
    srcs = [
        "box-unbox-generics020.cs",
        "//src/tests/JIT/jit64/valuetypes/nullable/box-unbox:structdef.cs",
    ],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "box-unbox-generics021",
    srcs = [
        "box-unbox-generics021.cs",
        "//src/tests/JIT/jit64/valuetypes/nullable/box-unbox:structdef.cs",
    ],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "box-unbox-generics022",
    srcs = [
        "box-unbox-generics022.cs",
        "//src/tests/JIT/jit64/valuetypes/nullable/box-unbox:structdef.cs",
    ],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "box-unbox-generics023",
    srcs = [
        "box-unbox-generics023.cs",
        "//src/tests/JIT/jit64/valuetypes/nullable/box-unbox:structdef.cs",
    ],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "box-unbox-generics024",
    srcs = [
        "box-unbox-generics024.cs",
        "//src/tests/JIT/jit64/valuetypes/nullable/box-unbox:structdef.cs",
    ],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "box-unbox-generics025",
    srcs = [
        "box-unbox-generics025.cs",
        "//src/tests/JIT/jit64/valuetypes/nullable/box-unbox:structdef.cs",
    ],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "box-unbox-generics026",
    srcs = [
        "box-unbox-generics026.cs",
        "//src/tests/JIT/jit64/valuetypes/nullable/box-unbox:structdef.cs",
    ],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "box-unbox-generics027",
    srcs = [
        "box-unbox-generics027.cs",
        "//src/tests/JIT/jit64/valuetypes/nullable/box-unbox:structdef.cs",
    ],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "box-unbox-generics028",
    srcs = [
        "box-unbox-generics028.cs",
        "//src/tests/JIT/jit64/valuetypes/nullable/box-unbox:structdef.cs",
    ],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "box-unbox-generics029",
    srcs = [
        "box-unbox-generics029.cs",
        "//src/tests/JIT/jit64/valuetypes/nullable/box-unbox:structdef.cs",
    ],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "box-unbox-generics030",
    srcs = [
        "box-unbox-generics030.cs",
        "//src/tests/JIT/jit64/valuetypes/nullable/box-unbox:structdef.cs",
    ],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "box-unbox-generics031",
    srcs = [
        "box-unbox-generics031.cs",
        "//src/tests/JIT/jit64/valuetypes/nullable/box-unbox:structdef.cs",
    ],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "box-unbox-generics032",
    srcs = [
        "box-unbox-generics032.cs",
        "//src/tests/JIT/jit64/valuetypes/nullable/box-unbox:structdef.cs",
    ],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "box-unbox-generics033",
    srcs = [
        "box-unbox-generics033.cs",
        "//src/tests/JIT/jit64/valuetypes/nullable/box-unbox:structdef.cs",
    ],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "box-unbox-generics034",
    srcs = [
        "box-unbox-generics034.cs",
        "//src/tests/JIT/jit64/valuetypes/nullable/box-unbox:structdef.cs",
    ],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "box-unbox-generics037",
    srcs = [
        "box-unbox-generics037.cs",
        "//src/tests/JIT/jit64/valuetypes/nullable/box-unbox:structdef.cs",
    ],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "box-unbox-generics038",
    srcs = [
        "box-unbox-generics038.cs",
        "//src/tests/JIT/jit64/valuetypes/nullable/box-unbox:structdef.cs",
    ],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "box-unbox-generics039",
    srcs = [
        "box-unbox-generics039.cs",
        "//src/tests/JIT/jit64/valuetypes/nullable/box-unbox:structdef.cs",
    ],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "box-unbox-generics040",
    srcs = [
        "box-unbox-generics040.cs",
        "//src/tests/JIT/jit64/valuetypes/nullable/box-unbox:structdef.cs",
    ],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "box-unbox-generics041",
    srcs = [
        "box-unbox-generics041.cs",
        "//src/tests/JIT/jit64/valuetypes/nullable/box-unbox:structdef.cs",
    ],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "box-unbox-generics042",
    srcs = [
        "box-unbox-generics042.cs",
        "//src/tests/JIT/jit64/valuetypes/nullable/box-unbox:structdef.cs",
    ],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "box-unbox-generics043",
    srcs = [
        "box-unbox-generics043.cs",
        "//src/tests/JIT/jit64/valuetypes/nullable/box-unbox:structdef.cs",
    ],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "box-unbox-generics044",
    srcs = [
        "box-unbox-generics044.cs",
        "//src/tests/JIT/jit64/valuetypes/nullable/box-unbox:structdef.cs",
    ],
    pri = 1,
    size = "medium",
)

coreclr_test(
    name = "box-unbox-generics045",
    srcs = [
        "box-unbox-generics045.cs",
        "//src/tests/JIT/jit64/valuetypes/nullable/box-unbox:structdef.cs",
    ],
    pri = 1,
    size = "medium",
)
