load("//src/libraries:defs.bzl", "netcoreapp_impl_assembly")

netcoreapp_impl_assembly(
    name = "impl_System.Data",
    skip_cs1591 = True,
    srcs = [
        "src/System.Data.cs",
        "ref/System.Data.cs",
    ],
    deps = [
        "//src/libraries/System.Data.Common:ref_System.Data.Common",
        "//src/libraries:ref_System.Private.CoreLib",
        "//src/libraries:impl_System.Runtime",
        "//src/libraries/shims/stubs:ref_System.Data.Odbc",
        "//src/libraries/shims/stubs:ref_System.Data.OleDb",
        "//src/libraries/shims/stubs:ref_System.Data.SqlClient",
        "//src/libraries/shims/stubs:ref_System.Security.Permissions",
    ],
    os_targeted = True,
    exclude_sr = True,
    assembly_version = "4.0.0.0",
)
