load("//src/libraries:defs.bzl", "netcoreapp_ref_assembly", "netcoreapp_impl_assembly")

netcoreapp_ref_assembly(
    name = "ref_System.Net.Ping",
    srcs = [
        "ref/System.Net.Ping.cs",
    ],
    deps = [
        "//src/libraries:ref_System.ComponentModel.Primitives",
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.ComponentModel.EventBasedAsync:ref_System.ComponentModel.EventBasedAsync",
        "//src/libraries/System.Net.Primitives:ref_System.Net.Primitives",
    ],
)

netcoreapp_impl_assembly(
    name = "impl_System.Net.Ping",
    analyzers = [
        "//src/libraries/System.Runtime.InteropServices:LibraryImportGenerator",
        "//src/libraries/System.Runtime.InteropServices:Microsoft.Interop.SourceGeneration",
    ],
    srcs = glob(
        ["src/System/**/*.cs"],
        exclude = [
            "src/System/Net/NetworkInformation/Ping.OSX.cs",
            "src/System/Net/NetworkInformation/Ping.Windows.cs",
            "src/System/Net/NetworkInformation/Ping.Unix.cs",
            "src/System/Net/NetworkInformation/Ping.PingUtility.cs",
        ],
    ) + [
        # Common sources
        "//src/libraries/Common:src/DisableRuntimeMarshalling.cs",
        "//src/libraries/Common:src/System/Obsoletions.cs",
        "//src/libraries/Common:src/System/Net/SocketProtocolSupportPal.cs",
    ] + select({
        "@platforms//os:linux": [
            # Linux-specific Ping impl
            "src/System/Net/NetworkInformation/Ping.Unix.cs",
            "src/System/Net/NetworkInformation/Ping.PingUtility.cs",
            # Unix src Common files
            "//src/libraries/Common:src/System/Net/RawSocketPermissions.cs",
            "//src/libraries/Common:src/System/Net/SocketProtocolSupportPal.Unix.cs",
            "//src/libraries/Common:src/System/Net/NetworkInformation/UnixCommandLinePing.cs",
            "//src/libraries/Common:src/System/Net/IPEndPointExtensions.cs",
            "//src/libraries/Common:src/System/Net/SocketAddressPal.Unix.cs",
            "//src/libraries/Common:src/System/Net/IPAddressParserStatics.cs",
            "//src/libraries/Common:src/System/Net/Sockets/SocketErrorPal.Unix.cs",
            "//src/libraries/Common:src/System/Text/ValueUtf8Converter.cs",
            # Interop Unix
            "//src/libraries/Common:src/Interop/Unix/Interop.DefaultPathBufferSize.cs",
            "//src/libraries/Common:src/Interop/Unix/Interop.Errors.cs",
            "//src/libraries/Common:src/Interop/Unix/Interop.Libraries.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.IOVector.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.ReceiveSocketError.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Close.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.MessageHeader.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Socket.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.SocketAddress.cs",
        ],
        "@platforms//os:macos": [
            # macOS-specific Ping impl
            "src/System/Net/NetworkInformation/Ping.OSX.cs",
            # Unix src Common files (shared with Linux)
            "//src/libraries/Common:src/System/Net/RawSocketPermissions.cs",
            "//src/libraries/Common:src/System/Net/SocketProtocolSupportPal.Unix.cs",
            "//src/libraries/Common:src/System/Net/NetworkInformation/UnixCommandLinePing.cs",
            "//src/libraries/Common:src/System/Net/IPEndPointExtensions.cs",
            "//src/libraries/Common:src/System/Net/SocketAddressPal.Unix.cs",
            "//src/libraries/Common:src/System/Net/IPAddressParserStatics.cs",
            "//src/libraries/Common:src/System/Net/Sockets/SocketErrorPal.Unix.cs",
            "//src/libraries/Common:src/System/Text/ValueUtf8Converter.cs",
            # Interop Unix
            "//src/libraries/Common:src/Interop/Unix/Interop.DefaultPathBufferSize.cs",
            "//src/libraries/Common:src/Interop/Unix/Interop.Errors.cs",
            "//src/libraries/Common:src/Interop/Unix/Interop.Libraries.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.IOVector.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.ReceiveSocketError.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Close.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.MessageHeader.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.Socket.cs",
            "//src/libraries/Common:src/Interop/Unix/System.Native/Interop.SocketAddress.cs",
        ],
    }),
    resx_file = "src/Resources/Strings.resx",
    allow_unsafe_blocks = True,
    deps = [
        "//src/libraries:ref_Microsoft.Win32.Primitives",
        "//src/libraries:ref_System.ComponentModel.Primitives",
        "//src/libraries:ref_System.Diagnostics.Process",
        "//src/libraries:ref_System.Runtime",
        "//src/libraries/System.Collections:ref_System.Collections",
        "//src/libraries/System.Collections.Specialized:ref_System.Collections.Specialized",
        "//src/libraries/System.ComponentModel.EventBasedAsync:ref_System.ComponentModel.EventBasedAsync",
        "//src/libraries/System.Diagnostics.Tracing:ref_System.Diagnostics.Tracing",
        "//src/libraries/System.Memory:ref_System.Memory",
        "//src/libraries/System.Net.NameResolution:ref_System.Net.NameResolution",
        "//src/libraries/System.Net.Primitives:ref_System.Net.Primitives",
        "//src/libraries/System.Net.Sockets:ref_System.Net.Sockets",
        "//src/libraries/System.Runtime.InteropServices:ref_System.Runtime.InteropServices",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/System.Threading.ThreadPool:ref_System.Threading.ThreadPool",
    ],
)
