load("//src/tests:live_test.bzl", "coreclr_test")

coreclr_test(
    name = "mixed1_cs_r",
    srcs = ["mixed1.cs"],
    pri = 1,
    allow_unsafe_blocks = True,
    size = "medium",
)

coreclr_test(
    name = "mixed1_cs_ro",
    srcs = ["mixed1.cs"],
    optimize = True,
    allow_unsafe_blocks = True,
)

coreclr_test(
    name = "mixed2_cs_r",
    srcs = ["mixed2.cs"],
    pri = 1,
    allow_unsafe_blocks = True,
    size = "medium",
)

coreclr_test(
    name = "mixed2_cs_do",
    srcs = ["mixed2.cs"],
    pri = 1,
    debug_type = "full",
    optimize = True,
    allow_unsafe_blocks = True,
    size = "medium",
)

coreclr_test(
    name = "mixed1_cs_d",
    srcs = ["mixed1.cs"],
    pri = 1,
    debug_type = "full",
    optimize = False,
    allow_unsafe_blocks = True,
    size = "medium",
)

coreclr_test(
    name = "mixed2_cs_d",
    srcs = ["mixed2.cs"],
    pri = 1,
    debug_type = "full",
    optimize = False,
    allow_unsafe_blocks = True,
    size = "medium",
)

coreclr_test(
    name = "mixed2_cs_ro",
    srcs = ["mixed2.cs"],
    pri = 1,
    optimize = True,
    allow_unsafe_blocks = True,
    size = "medium",
)

coreclr_test(
    name = "mixed1_cs_do",
    srcs = ["mixed1.cs"],
    debug_type = "full",
    optimize = True,
    allow_unsafe_blocks = True,
)
