#ifndef EP_SHARED_CONFIG_H_INCLUDED
#define EP_SHARED_CONFIG_H_INCLUDED

// Hardcoded for darwin-arm64 (matching CMake configure results).

#define HAVE_ERRNO_H 1
#define HAVE_LINUX_USER_EVENTS_H 0
#define HAVE_SYS_IOCTL_H 1
#define HAVE_SYS_SOCKET_H 1
#define HAVE_SYS_UIO_H 1
#define HAVE_UNISTD_H 1
#define HAVE_ACCEPT4 0

/* #undef FEATURE_PERFTRACING_PAL_TCP */
/* #undef FEATURE_PERFTRACING_PAL_WS */
/* #undef FEATURE_PERFTRACING_DISABLE_THREADS */
/* #undef FEATURE_PERFTRACING_DISABLE_PERFTRACING_LISTEN_PORTS */
/* #undef FEATURE_PERFTRACING_DISABLE_DEFAULT_LISTEN_PORT */
/* #undef FEATURE_PERFTRACING_DISABLE_CONNECT_PORTS */

#define CMAKE_C_BYTE_ORDER_LITTLE_ENDIAN 0
#define CMAKE_C_BYTE_ORDER_BIG_ENDIAN 1
#define CMAKE_C_BYTE_ORDER CMAKE_C_BYTE_ORDER_LITTLE_ENDIAN
#if CMAKE_C_BYTE_ORDER == CMAKE_C_BYTE_ORDER_BIG_ENDIAN
#define BIGENDIAN 1
#endif

#endif //EP_SHARED_CONFIG_H_INCLUDED
