load("//src/tests:live_test.bzl", "il_coreclr_test")

il_coreclr_test(
    name = "RefX1",
    srcs = ["RefX1.il"],
    tags = ["manual"],  # Needs additional deps not yet available
)

il_coreclr_test(
    name = "ValX1",
    srcs = ["ValX1.il"],
    tags = ["manual"],  # Needs additional deps not yet available
)
